### ISSUE TITLE
Can't scroll up

### ISSUE THREAD

**Issue by YellowApple** [scoute-dich/browser#1]
Wants to refresh instead.  Tested on latest available from F-Droid on Android 7.0 (CopperheadOS, Nexus 6P).

**Comment by scoute-dich** [comment]
Does this happen on all websites?

**Comment by YellowApple** [comment]
I've narrowed it down to sites with most of the content contained in an element with `overflow: auto` set.  Browser seems to think it's at the top of the page, so it wants to refresh.  So, more specifically, I can't scroll up on elements with their own scrolling.

**Comment by scoute-dich** [comment]
Can you give me a link to such a site?

**Comment by YellowApple** [comment]
The one with which I noticed the issue is one that I'm developing myself (and ain't published yet).  I'll see about putting up a test case somewhere publicly-accessible.

**Comment by rjk40** [comment]
![ic_left](https://cloud.githubusercontent.com/assets/24350954/21380476/e83babf0-c72b-11e6-98a4-dfbd41fbf629.png)
![ic_right](https://cloud.githubusercontent.com/assets/24350954/21380490/f74cd84e-c72b-11e6-9801-64813548950b.png)
![ic_up](https://cloud.githubusercontent.com/assets/24350954/21380505/10d96dcc-c72c-11e6-9446-93528e7abbc3.png)
![qc_later](https://cloud.githubusercontent.com/assets/24350954/21380511/216b304e-c72c-11e6-831d-a4e6f28665c3.png)
This might be of help if its compares

**Comment by scoute-dich** [comment]
@rjk40: I don't understand...

**Comment by scoute-dich** [comment]
Any news here?

**Comment by YellowApple** [comment]
Hi.  Sorry for the silence.

Test case can be found at https://yellowapple.us/layout-test.

**Comment by scoute-dich** [comment]
I can't load this page (not on phone and not on desktop PC).

**Comment by YellowApple** [comment]
Whoops, sorry.  Try https://www.yellowapple.us/layout-test

**Comment by scoute-dich** [comment]
Ok. I see.

**Comment by KevinMX** [comment]
Well this happened to me as well when I'm visiting baidu news. Hope u can fix this:)

**Comment by scoute-dich** [comment]
I will remove swipe to refresh with next update. To reload use the menu -> other -> reload. If there are further problems after next update, please reopen this issue.
