### ISSUE TITLE
Add "Open as URL" to the search engine menu

### ISSUE THREAD

**Issue by dkavlakov** [scoute-dich/browser#10]
Having to prepend "http:"/"https:" to each URL that does not start with "www" is extremely annoying. If making the browser recognize valid domain names is problematic please at least add option to force-open urlbar contents as url instead of searching them (btw: not all valid url's are searchable). A possible place for such override can be the search engine selection menu.

**Comment by scoute-dich** [comment]
I attached an apk in #7 
Perhaps you can test it also.

**Comment by scoute-dich** [comment]
Opening urls should now work without typing "www.", "http" or something similar.
