### ISSUE TITLE
Active button colors on OLED theme

### ISSUE THREAD

**Issue by thermosflasche** [scoute-dich/browser#1006]
I noticed that the active/checked buttons on the OLED theme can't be read, probably due to having both white background and foreground.

![Attached example capture](https://i.postimg.cc/zDHtRHrc/Screenshot-20221026-122650-Navegador-FOSS.png)

**Comment by Stilgarrr** [comment]
+1

**Comment by scoute-dich** [comment]
Will be fixed with next update.
![Screenshot_20221114-150459](https://user-images.githubusercontent.com/3949944/201680106-39c70af6-1c7b-453a-a421-ab1018f3e69a.png)
