### ISSUE TITLE
[Bug] Javascript enabled for websites on first launch

### ISSUE THREAD

**Issue by qube-03** [scoute-dich/browser#1008]
hi! i really like this browser but one bug is annoying me quite a bit. that is, if you load a webpage for the first time, then javascript - even if you disabled it in your chosen mode - is turned on. if you reload the website the issue is fixed.

**Comment by qube-03** [comment]
oh, i forgot, this only happens on first launch, i.e. when you load up your homepage (also i use trackercontrol to block certain connections if that matters)

**Comment by scoute-dich** [comment]
I do not understand how to reproduce that issue. Can please explain step by step, what to do?

**Comment by scoute-dich** [comment]
I changed the code. If this issue is still there after the next update, please reopen a new one.
