### ISSUE TITLE
Entries in trusted sites list that include protocol are no longer recognised

### ISSUE THREAD

**Issue by danielhatton** [scoute-dich/browser#1009]
I have a bunch of entries in my trusted sites list in the form of URLs including a protocol, e.g.

https://twitter.com

Until a couple of months ago, this worked fine.  However, at some point (?upgrade to v9.4), these entries started being ignored, and the relevant sites started being opened with the standard profile.  Now, entries in the trusted sites list only work if they're in the form of a domain name without protocol, e.g.

twitter.com

**Comment by scoute-dich** [comment]
The lists only checks domains. So this is the intended behavior.

**Comment by danielhatton** [comment]
On Wed, 21 Dec 2022, Gaukler Faun wrote:

> The lists only checks domains. So this is the intended behavior.

OK, thanks.
