### ISSUE TITLE
[Bug] Cannot Clear Cache and Unregister Service Worker

### ISSUE THREAD

**Issue by Allium-altaicum** [scoute-dich/browser#1013]
# Description
Cannot clear cache and unregister service worker
# Environment
- Device: [Huawei - SEA-AL10]
- OS: [Android 10]
- Version: 9.5
# To reproduce
1. Go to https://mdn.github.io/pwa-examples/js13kpwa/
2. Refresh
3. Quit
4. Open '"Settings"
5. Click "Delete", then enable "Clear on device stored data" and "Clear Cookies".
6. Click "DELETE"
7. Restart browser
8. Turn off mobile data and WiFi
9. Go to https://mdn.github.io/pwa-examples/js13kpwa/
10. See loaded page
# Expected behaviour
Display 'Web page not available'

**Comment by scoute-dich** [comment]
For me, there are no problems. But since the last update, I changed a lot of code. So I'll close this issue. If the issue also exists after the update in Version 9.6, please open a new issue.
