### ISSUE TITLE
`[enhancement]` expand toolbar button area

### ISSUE THREAD

**Issue by asklow** [scoute-dich/browser#1014]
There's lot of unresponsive dead UI around the toolbar buttons, which often cause hit & miss on regular usage.

![Screenshot_20221201](https://user-images.githubusercontent.com/117489882/205116208-305b5e2d-6f3d-40da-87ed-cf08a0850622.png)

Expanding the clickable area margins would fix this simple issue.

**Comment by scoute-dich** [comment]
I changed the layout a bit.
