### ISSUE TITLE
Youtube videos in full screen mode cropped

### ISSUE THREAD

**Issue by heubergen** [scoute-dich/browser#1015]
As seen in this video the full screen mode in Youtube cropped the video making it unusable.

Device: Fairphone 3+
Android version: 11
WebView: Up to date from PlayStore

https://user-images.githubusercontent.com/5529410/205450523-a59b6183-f07b-4d10-b08d-90ba2c5548ef.mp4

**Comment by scoute-dich** [comment]
I found the issue and think it is solved. If the issue also exists after the update in Version 9.6, please open a new issue.
