### ISSUE TITLE
URL-Redirects are part of history

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#1017]
If you use the non-javascript version of duckduckgo or any other site that uses URL redirects one needs to press back in a very quick sequence, making it very difficult to return to the linking page

Steps to reproduce the behaviour:

Go to https://html.duckduckgo.com/html/?q=test
Click on first link
Press back/use guesture
The page just reloads

Expected behaviour
One should return to https://html.duckduckgo.com/html/?q=test

**Comment by scoute-dich** [comment]
For me, there are no problems. Everything works as expected. But since the last update, I changed a lot of code. So I'll close this issue. If the issue also exists after the update in Version 9.6, please open a new issue.
