### ISSUE TITLE
Browser app does not seem to match domains on the 'Trusted websites' list.

### ISSUE THREAD

**Issue by maratbn** [scoute-dich/browser#1018]
Seeing this with version 9.5

Browser app does not seem to match domains on the 'Trusted websites' list.  This can be demonstrated if the app is configured to reject cookies for 'Standard websites' but accept cookies for 'Trusted websites'. 

To reproduce:

(1) Tilt phone horizontally while on app home screen.
(2) Tap the 3 vertical dots in bottom right corner of the app. Overlay with menu options will appear.
(3) Tap the 3 vertical dots in bottom right corner of the menu options overlay.  Menu options overlay will now display the "Setti..." option.
(4) Tap the "Setti..." option to enter the 'Settings' screen.
(5) Under 'Browser Settings" heading tap 'Privacy'.  'Privacy' settings screen will appear.
(6) Scroll down to get to 'Edit profiles'.
(7) Tap on 'Edit profiles'.  Overlay with profile names will appear.
(8) Tap on 'Standard'.  Profile options for the 'Standard' profile will appear.
(9) Scroll down to the 'Cookies' checkbox.
(10) Uncheck the 'Cookies' checkbox.
(11) Open a cookie checking website 'https://www.whatismybrowser.com/detect/are-cookies-enabled' with the app.  Website will inform that cookies are not enabled.
(12) Repeat steps (1) to (7) to return to the overlay with profile names.  
(13) Now tap on 'Trusted'.  Profile options for the 'Trusted' profile will appear.
(14) Scroll down to the 'Cookies' checkbox.
(15) Check the 'Cookies' checkbox.
(16) Repeat steps (1) to (5) to return the to 'Privacy' settings screen.
(17) Tap 'Trusted websites'.  'Trusted websites' screen will appear.
(18) Add the cookie testing site domain 'whatismybrowser.com' to the trusted websites list.
(19) Repeat step (11) to see if cookies are now working for the cookie testing site as they should be.  However, website will continue to inform that cookies are not enabled, despite the website being on the 'Trusted websites' list.  This suggests that the app is not matching the cookie testing site as present on the 'Trusted websites' list.  This is the nature of the bug reported in this bug report.
(20) Repeat steps (1) to (9) to return to the 'Cookies' checkbox for the 'Standard' profile.
(21) Now check the 'Cookies' checkbox.
(22) Repeat step (11) to see if cookies are now working for the cookie test site.  Website will now inform that indeed cookies are now enabled.  This further confirms that the app did not match the cookie testing site as present on the 'Trusted websites' list, and demonstrates that the app is processing this 'Trusted' site as a regular 'Standard' site.  This is the nature of the bug reported in this bug report.

**Comment by scoute-dich** [comment]
Since opening this issue, I changed a lot of code. Especially concerning the profiles. So I'll close this issue. If the issue also exists after the update in Version 9.6, please open a new issue.
