### ISSUE TITLE
After sharing link on any app and then when we share to clipboard, the app crashes. 

### ISSUE THREAD

**Issue by syedubair** [scoute-dich/browser#102]
#### Expected behavior
After sharing a link from Browser app to any app like whatsapp, Instagram, or any app and then when we share to clipboard it is expected to copy the link. 

#### Actual behavior
When a link is first shared on any platform and then when we try to share to clipboard the app crashes. It does not crash when we directly choose the second option i.e., share to clipboard. But it always crashes when the above mentioned steps are followed. 

#### How to reproduce
Launch the browser and search anything. 

Click on the options menu at the bottom right corner. 

Now click on the share icon. 

Press the share link button and share through any of the platforms available to you(whatsapp, Instagram, etc) 

Go back and now press the options button and then the share icon again. 

This time press the share to clipboard button. 
The app will crash. 

* Browser: Browser v5.3.1
* Operating system: Android Nought 7 - Moto g5 plus 

#### Recording Of The Bug
https://youtu.be/e3H1XVwfBuY
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedubair/after-sharing-link-on-any-app-and-then-when-we-share-to-clipboard-the-app-crashes">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by scoute-dich** [comment]
This is fixed already and will be ok with next update. If not please reopen. Thanks for submitting.
