### ISSUE TITLE
Android TV Optimisations

### ISSUE THREAD

**Issue by SecularSteve** [scoute-dich/browser#1020]
I've noticed that there's a severe lack of legit non-invasive Internet Browsers optimised for Android TV set-ups. Like Android Boxes, Fire Sticks, or even the new Chromecast.

This is a good chance to take advantage of this eco-system in the FOSS-world. That includes Remote Control Configurations, and even speed optimisations. Could this browser have the potential for that?

**Comment by scoute-dich** [comment]
I don't know. But I will not care for it, since lag of time and own using scenarios.
