### ISSUE TITLE
Running external applications

### ISSUE THREAD

**Issue by Ni4ellas** [scoute-dich/browser#1021]
Hi, add the ability to launch an external application when clicking on links, if possible

**Comment by scoute-dich** [comment]
This feature is already implemented. In the context menu of a link (long pressing the link) is an entry “Open with”.

**Comment by urmomseksy** [comment]
@scoute-dich I don't think this feature is working. Version 9.11 and Samsung for A53.
Android 13

- I have redreader set to open by default reddit.com, etc
- I have LibreTube set to open YouTube and Piped instances

When I press "open with" these only attempt to load in FOSS browser. FOSS browser is not set to open these links by default (I don't have an option in app settings to choose default URLs for FOSS, anyway).

Thank you.
