### ISSUE TITLE
Logging into sites

### ISSUE THREAD

**Issue by ElizabethWega** [scoute-dich/browser#1034]
Greetings!
As a student, it is not uncommon that I have to log into particular sites throughout the day, especially those connected to my school. Whenever I try to log into one, upon pressing the "log in" button, the browser refreshes the page and I have to insert the login information again, which turns out to be an action done in vain, for the afore mentioned event occurs again, making a never-ending loop. Is it possible to tweak the settings to make the logging in work? Is this a bug? A feature? I thank you in advance for your answer.

**Comment by Bnyro** [comment]
Did you try long pressing the shield icon inside the search bar and in the menu that's then popping up, selecting the first one of the three shields in the top row?
This should allow the website to save cookies and other stuff and thus the website should work as on every browser then.

**Comment by ElizabethWega** [comment]
> Did you try long pressing the shield icon inside the search bar and in the menu that's then popping up, selecting the first one of the three shields in the top row? This should allow the website to save cookies and other stuff and thus the website should work as on every browser then.

Oh my, it works!! Thank you so much!! Now I can finally use the browser to its fullest!
