### ISSUE TITLE
upgraded to 9.6 everything is purple?

### ISSUE THREAD

**Issue by luke-2136** [scoute-dich/browser#1045]
Hello - like title says i just upgraded to 9.6 now everything is purple colored. Tried all the themes (system, day, night, oled) no difference. Have to say not liking this color at all. The original look/color is so much better. Is this a bug of some sort or has it been changed purposely. If so, how about an option for original colors? If not probably have to go back to 9.5 and stay there - light pastel purple not for me. For the record been very much enjoying FOSS browser though. 

sample:
![foss](https://user-images.githubusercontent.com/96635125/222645151-34ab22a4-c949-4179-a11f-30375b757348.png)

[os Android 11]

**Comment by scoute-dich** [comment]
Just check the settings. There are two theme related options:

- theme: there you can choose between dark/light/system
- the second option "wallpaper based" is for the color. If you disable it, the default color (green) of FOSS Browser will be used. If you enable it, Material You will be used and the colors should match to your wallpaper. If your device doesn't support this, the default Android colors will be used.
