### ISSUE TITLE
Feature requests: changes to URL display

### ISSUE THREAD

**Issue by quartertone** [scoute-dich/browser#1050]
- Location bar: please add an option to display URL (without https://) instead of page title

- Tab list / bookmark list / history: please add option to display URL (in smaller print) along with the bookmark name. {Web designers don't always make proper use of page titles, and they are often unhelpful in distinguishing deep pages from the main index.}

- When long-pressing a link, the popup should display the entire link (or abbreviated beginning and end if it's too long)

**Comment by scoute-dich** [comment]
At the moment, no new features. For the next months I have less time. Your suggestion seems useful. If I have time in the summer (or earlier) I'll implement it. Until then, you must click in the toolbar to get the url, or share it (to clipboard, …).

**Comment by scoute-dich** [comment]
I implemented, that the url will be shown, when you click the title of context or normal menu. I hope that helps.

**Comment by scoute-dich** [comment]
Also, in lists urls will be shown.
