### ISSUE TITLE
Feature request: Location bar gestures

### ISSUE THREAD

**Issue by quartertone** [scoute-dich/browser#1051]
Please allow gestures on the location bar. Useful scenarios would be swiping left/right to switch tabs, or long press to copy the link. The shield is a very small target to swipe on.

**Comment by scoute-dich** [comment]
There are already gestures implemented in the settings. There are more than enough options (also switching the tabs). Additional gestures on the toolbar interfere with the textinput field. That was implemented in earlier releases, but there were too many problems.
