### ISSUE TITLE
"Opened Tabs" string doesn't fit

### ISSUE THREAD

**Issue by E0697** [scoute-dich/browser#1067]
The "opened tabs" string is cut off (attached screenshot).

Could it be renamed or maybe displayed over 2 lines?

![Screenshot_2023-03-11-23-24-48-01_62aaca7cac4d42d85991331f18db19b5.jpg](https://user-images.githubusercontent.com/66939100/224510367-20fd065a-888c-4405-8591-491ca3ebb169.jpg)

**Comment by scoute-dich** [comment]
"Opened Tabs" and the other menu entries will be moved on top of the entries in the next release, and there will be only icons. This is needed for better support of landscape mode and smaller devices, and will therefore not be returned.

**Comment by E0697** [comment]
I think it's going to be much better like that. Thank you!
