### ISSUE TITLE
Sharing the link to other apps doea not work properly 

### ISSUE THREAD

**Issue by umair1209** [scoute-dich/browser#107]
#### Expected behavior
Sharing  webpages on different applications through browser should paste the link of the web page on the application we are sharing the link. 
#### Actual behavior

When I tried to share a link of the webpage on browser to other applications, the link was not pasted there, instead I saw **null**. 

#### How to reproduce
- Open browser and search something 
- Click on share link
- Share the link to any application
- You will see *null* instead of the link. 
- This does not happen all the time so you might have to try multiple times. 
- Also I was able to reproduce bug mainly when I tried to share google and Wikipedia links. 

* Browser: Browser v5. 3.1
* Operating system: Android 6.0.1

#### Recording Of The Bug

https://youtu.be/xVAuCfKQ4aA    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/sharing-the-link-to-other-apps-doea-not-work-properly">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by scoute-dich** [comment]
This is fixed already and will be ok with next update. If not please reopen. Thanks for submitting.
