### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by element54** [scoute-dich/browser#108]
Hello,

how about using Continuous Integration via travis for this project? It would automatically test and build the app. Furthermore, when using tags it could release new versions automatically to github.
I would be willing to help enabling CI.
Good resources are:
https://docs.travis-ci.com/user/languages/android/
https://docs.travis-ci.com/user/deployment/releases/

**Comment by scoute-dich** [comment]
I won't implement this. I don't see the advantages and don't have the time to figure it out.
