### ISSUE TITLE
Create Google Search URL in the Home and Link in Bookmarks

### ISSUE THREAD

**Issue by ston75** [scoute-dich/browser#109]
When opening the browser is it possible to insert the Google.com page on the Home page and on the Bookmarks?

**Comment by scoute-dich** [comment]
When you opened googl.com just hit the menu button -> save. There you can save every website on the startpage or in your bookmarks.

**Comment by scoute-dich** [comment]
When you just want to search, set Google as your default search engine. Then you can search from everywhere, using the toolbar.

**Comment by ston75** [comment]
If I want to start Google when I open my app fork, how should I do?

**Comment by scoute-dich** [comment]
In the `private void dispatchIntent(Intent intent)` just change at the bottom:

`} else {
            pinAlbums(null);
        }`

to

`} else {
            pinAlbums("https://www.google.com");
        }`
