### ISSUE TITLE
[BUG] Pin Protection doesn't protect it at all

### ISSUE THREAD

**Issue by skinzor** [scoute-dich/browser#11]
Hello!
I've just installed this browser. My purpose was to try it, but then I've seen that it doesn't have tabs xD
Anyway, you've done a great job.

I don't know if it's a known issue, but I thought I should tell you.
So, let's say that I enable PIN Protection.
Next time I open the browser, it'll ask for PIN, but if I press back button or press home button (when it asks for PIN) and then I open the browser, it will not ask for PIN.

Good luck with your project!

**Comment by scoute-dich** [comment]
Hi,

thanks for testing the app and reporting the bug. I've fixed it.
