### ISSUE TITLE
Using the tab switcher on the browser doesn't work

### ISSUE THREAD

**Issue by kingdidi** [scoute-dich/browser#114]
#### Expected behavior
I expected that I'll be able to swtich to the next tab using the recently included tabs swticher function on the browser 
#### Actual behavior
Using the tab switcher to move to the next tab gives me the message "can't load next site"
#### How to reproduce
- launch the app
- open websites on two different tabs
- stay on the frst tab 
- access the the tab switcher option by clicking the 3 dots button
- click the forward arrow on the tab switcher 

* Browser: htc m7
* Operating system: android 6.0.1
* software version: 5.4

#### Recording Of The Bug
https://youtu.be/oWnm5qY7nSY
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kingdidi/using-the-tab-switcher-on-the-browser-doesn-t-work">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ildar** [comment]
This isn't for navigation among tabs, it's for the (current) tab history:
back and forward.

**Comment by kingdidi** [comment]
Oh okay. I was unaware of that.
Now I'm aware.
Also the update didn't fix the crash when I open the file manager

On Mar 3, 2018 16:42, "ildar" <notifications@github.com> wrote:

This isn't for navigation among tabs, it's for the (current) tab history:
back and forward.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scoute-dich/browser/issues/114#issuecomment-370156793>,
or mute the thread

**Comment by scoute-dich** [comment]
Please test the apk in #110 
It should solve the app crash. Thanks for clearing.
