### ISSUE TITLE
App may crashes when all tabs are swiped out (hard to reproduce)

### ISSUE THREAD

**Issue by smallg0at** [scoute-dich/browser#119]
log:
java.Iang.IndexOutOfBoundsException  at java.util. Lin ked List.get(Lin ked List.java:51 9)  at de.baumann.browser.Browser.BrowserContainer.get(Brow serContainer.java:12)  at de.baumann.browser.Activity.BrowserActivity $68.onClick(BrowserActivity.java:2810)  at android.view.View.performClick(View.java:5275)  at android.view.View$PerformClick.run(View.java:21556)  at android.os.Handler.handleCallback(Handler.java:815)  at android.os.Handler.dispatchMessage(Handler.java:  104)   at android.os.Looper.Ioop(Looper.java:207)  atandroid.app.ActivityThread.main(ActivityThread.java: I 5795)  at java.Iang.reflect.Method.invoke(Native Method)  at com.and roid.internal.os.Zygotelnit $MethodAndArgsCaller.run(2ygotelnit.java:907)  at com.android.internal.os.Zygotelnit.main(Zygotelnit.java:  768)

**Comment by scoute-dich** [comment]
If this is still from relevance, please reopen it.
