### ISSUE TITLE
please do not release a version so frequently

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#121]
I think the recent releases are too frequent. 
give user more time to use,to report issues.
give translator more time to translate.

**Comment by scoute-dich** [comment]
Ok. I will make a commit today with a few new strings. Then I will upload an apk in the xda forum for testing. Then of there are no more critical issues I will release the next official update a few days later.

**Comment by ildar** [comment]
no-no-nonono!
Release Early, Release Often! (c)
<http://catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s04.html>
Please don't slow down! Those who can't update often can update slower.
Nobody's actually forced to.
I think finding bugs and reporting isn't bad even if for an older version
(in case the issue tracker been checked for this issue).
Translators should be cared and that's a different issue. I'm not sure
which but an online translation service that pulls the most recent
`strings.xml` should be found and used.
