### ISSUE TITLE
App Crashes When we try to save images. 

### ISSUE THREAD

**Issue by wanizubair** [scoute-dich/browser#123]
#### Expected behavior
+ The App should be able to save images. 

#### Actual behavior
App Crashes when we try to save images and we are not able to save images. 

#### How to reproduce

+ Launch the app. 

+ search image. 

+ Tap long press on image you see different options there. 

+ Click on Save option, App Crashes and you are not able to save images. 

* Browser: F|L|OSS BROWSER, Version 5.4
* Operating system: Android Nought (7.0)

#### Recording Of The Bug

https://youtu.be/8dNcf1csusU    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wanizubair/app-crashes-when-we-try-to-save-images">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ildar** [comment]
can provide the logcat?

**Comment by scoute-dich** [comment]
This happens when permission "write on störage is not granted". It will be fixed with next update. Thanks for reporting.
