### ISSUE TITLE
link open problem not open click to url to not open play store , etc.

### ISSUE THREAD

**Issue by niksooo7** [scoute-dich/browser#125]

**Comment by scoute-dich** [comment]
Can you provide such a link?

**Comment by niksooo7** [comment]
https://skrilo.app.link/YrYuZcfQfl

this link to add whatsapp msg and click to open this browser after show problem

**Comment by niksooo7** [comment]
this is my whatsapp no 9724406104 send nikul hi msg i 
Explanation this problem

**Comment by scoute-dich** [comment]
I don't use WhatApp (privacy concerns).

**Comment by niksooo7** [comment]
open this video and show problem url = https://drive.google.com/file/d/1zv_mjy-T_AcKXMGTDJzBEsHWg5qvldFD/view?usp=drivesdk
show video

**Comment by scoute-dich** [comment]
This has a solution in the next version v5.6:

There will be an entry in the menu to open websites (or links by long pressing) with any compatible app. The last entry ("Öffnen mit").

![](https://i.imgur.com/bobcIL6.png)
