### ISSUE TITLE
bug  dictated in F|L|OSS Browser setting 

### ISSUE THREAD

**Issue by djavalord** [scoute-dich/browser#126]
#### Expected behavior
click on the setting, then the setting menu will load

#### Actual behavior
when setting is selected, the app returned to the home page instead of loading the setting

#### How to reproduce
download  F|L|OSS Browser from F-droid, install and launch, from the home page, click on the 3 dots at the down right hand side, then click again the 3 dots at the middle of the popup page, then select setting.

* Browser: F|L|OSS Browser Version 5.5.1
* Operating system: Android 5.1.1 Lollipop. Infinix hot 3LTE

#### Recording Of The Bug
https://youtu.be/9VwVG6YAVkw
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@javalord/bug-dictated-in-f-or-l-or-oss-browser-setting">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by scoute-dich** [comment]
This should be fixed with next update. If not please reopen the issue.
