### ISSUE TITLE
FC When search from com.orekie.search

### ISSUE THREAD

**Issue by smallg0at** [scoute-dich/browser#128]
## log:
`java.lang.RuntimeException: Unable to start service de.baumann.browser.Service.HolderService@550ae4c with Intent { cmp=de.baumann.browser/.Service.HolderService }: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3208) 	at android.app.ActivityThread.access$2300(ActivityThread.java:180) 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1594) 	at android.os.Handler.dispatchMessage(Handler.java:111) 	at android.os.Looper.loop(Looper.java:207) 	at android.app.ActivityThread.main(ActivityThread.java:5795) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? 	at android.app.ContextImpl.startActivity(ContextImpl.java:687) 	at android.app.ContextImpl.startActivity(ContextImpl.java:674) 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:341) 	at de.baumann.browser.Service.HolderService.onStartCommand(HolderService.java:85) 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3191) 	... 8 more` 
Settings: open page in foreground

**Comment by scoute-dich** [comment]
Is "com.orekie.search" an app?

**Comment by SC1040-TS2** [comment]
I found a link for it on the Asian site CoolAPK.com, and it seems to be a lightweight search app of some kind, @scoute-dich .

https://www.coolapk.com/apk/com.orekie.search
