### ISSUE TITLE
Cannot open links from Gmail app (Android) 

### ISSUE THREAD

**Issue by Embridioum** [scoute-dich/browser#132]
Every link I open ends up as a search in my chosen engine (DuckDuckGo).

**Comment by Embridioum** [comment]
Android version 8.0.0
FLOSS Browser version 5.5 (F-Droid)
Gmail 8.3.12.190852125

Confirmed again in Gmail. 

Working with ProtonMail 1.8.3.

**Comment by scoute-dich** [comment]
Thanks for the fast feedback. So it seems primary a Gmail issue. As I noticed this behavior also from an other app on my side, I leave the issue open, although I can't reproduce it at the moment.

A workaround could be to copy the link and share it to F|L|OSS Browser...
