### ISSUE TITLE
Fast Toggle Says "JavaScript" instead of "Cookies"

### ISSUE THREAD

**Issue by esmoak** [scoute-dich/browser#140]
F(L)OSS version 5.6 installed from F-Droid.

Android: 6.0.1

When I long press the "menu" or the "Navigation button" to access Fast Toggle, my options show from top to bottom: AdBlock, Javascript, Javascript, History, etc.

The cookies icon is correct, it is just labeled as Javascript instead.

**Comment by scoute-dich** [comment]
Is fixed with next release. Thanks for reporting.
