### ISSUE TITLE
Distinct secure connections

### ISSUE THREAD

**Issue by Madis0** [scoute-dich/browser#142]
I just tried this browser and overall it looks well designed, but what really disappointed me was the lack of distinction between HTTP and HTTPS sites. You don't really need green locks for all HTTPS, but some kind of broken lock or alert symbol for HTTP would be great.

**Comment by scoute-dich** [comment]
This will be implemented in next version:

If there is no https connection, the reload button will show an "unlocked" icon. Clicking it will give you the opportunity to reload the site with a https connection.
