### ISSUE TITLE
Certain un-encoded URLs yield search results

### ISSUE THREAD

**Issue by mcstafford-git** [scoute-dich/browser#144]
When clicking an [archive.org link](http://web.archive.org/web/20180414130639/https://m.theepochtimes.com/uplift/this-is-one-of-the-largest-moving-crabs-in-the-world-when-it-gets-put-into-water-its-mesmerizing_2478350.html) I wind up viewing [search engine results](https://duckduckgo.com/?q=http%3A%2F%2Fweb.archive.org%2Fweb%2F20180414130639%2Fhttps%3A%2F%2Fm.theepochtimes.com%2Fuplift%2Fthis-is-one-of-the-largest-moving-crabs-in-the-world-when-it-gets-put-into-water-its-mesmerizing_2478350.html&ia=web).

**Comment by mcstafford-git** [comment]
Better phrasing would have been entering in address bar, as opposed to clicking.

**Comment by scoute-dich** [comment]
This will be fixed in next version.
