### ISSUE TITLE
Consider adding Searx as a default search engine option.

### ISSUE THREAD

**Issue by SC1040-TS2** [scoute-dich/browser#145]
Searx.me is a powerful and versatile search engine, mostly because it is a meta-search engine; an engine which parses other selected search engines for results. It also has its own settings, where you can customize which engines are used by Searx and how search requests are processed, for instance.

This engine is both for simple users and power users alike, but mostly leans towards power users in the customizabiliy it offers. I would consider adding it as a viable alternative to Startpage, Google, Bing, DuckDuckGo, and others, as it already supports the use of them and engines such as Qwant, Ixquick, Wikipedia, Reddit, and so on in its Preference settings.

(I hate to sound like an informative commercial in this, but Searx really is powerful in my experience. To have it in this browser would certainly be a nice touch, if nothing else, and I would appreciate any further insight on this prospect.)

**Comment by scoute-dich** [comment]
Will be added in next release. Thanks for the tip.

**Comment by SC1040-TS2** [comment]
You're welcome. On another note, I've been trying to convert Ninja (the browser's base) to the Gradle format through Android Studio's automated processes, with some success.
