### ISSUE TITLE
Sites do not respect whitelists unless opened in a new tab

### ISSUE THREAD

**Issue by esmoak** [scoute-dich/browser#146]
F(L)OSS version 5.6 installed from F-Droid. Android: 6.0.1

Background: I have F(L)OSS setup to default with JavaScript OFF, Cookies OFF, Images ON, History ON, for all sites unless whitelisted.

I have whitelisted cookies for a vBulletin based internet forum so I can stay logged in--I'll call this "Forum." 

**Steps to replicate the issue:**

1) Forum loads: JavaScript OFF and everything else ON. (Cookies on because whitelist)

2) I will click on an Imgur link from Forum. (Mobile Imgur needs JavaScript to work correctly so I whitelist it.) Imgur loads: JavaScript ON (whitelisted), and the rest defaulted to Cookies Off, etc. 

     A) If I open the Imgur link in the same window as Forum, the JavaScript will not work unless I click the "Fast Toggle" button and hit OK at the bottom.

     B) If I open Imgur in a new foreground or background tab, it works correctly--image loads.

3) Finally, when I am done with Imgur, the Forum site seems to inherit the "Cookies OFF" status of Imgur, and it logs me out. This happens whether I swipe the Imgur tab to close or if I hit the back button to close.

     A) I can hit OK at the bottom of the Fast Toggle menu on the Forum site and it will remember that I have the cookie and re-log me in. 

This issue appears to involve sites with different settings inheriting settings based on opened tabs. I don't think this is site specific, but I don't have a lot of options to test this out in other ways. 

**1) A simple way of looking at this is: Site A (cookie but no javascript) opens Site B (javascript but no cookie).**

**2) Site B will not javascript correctly as if it inherits the settings of Site A, unless it is opened in a separate tab, or if I hit OK at the bottom of quick toggle menu again.**

**3) When I back out of Site B, Site A thinks I have no cookies again unless I hit OK at the bottom of quick toggle menu.**

**Comment by scoute-dich** [comment]
The cookie problem will be solved with next update. With JavaScript I found no solution until now...

**Comment by esmoak** [comment]
@scoute-dich Thanks for all your hard work.

Maybe look into how this app sandboxes websites?

https://github.com/tobykurien/WebApps

I know the goals of your app and this other app are different, but possibly the solution is similar.

Thanks again.

**Comment by scoute-dich** [comment]
Should be ok now.
