### ISSUE TITLE
Please consider new name for browser (feature request)

### ISSUE THREAD

**Issue by esmoak** [scoute-dich/browser#147]
I like to recommend F|L|OSS to other people on Reddit.

1) The name F|L|OSS is cumbersome to type, and sometimes gets typed as F(L)OSS.

2) When searching Reddit or other forums, you would have to try searching for F|L|OSS, F(L)OSS, and sometimes FLOSS just to find all relevant threads regarding the browser. Consistency is important for people researching a new browser.

3) F(L)OSS just sounds somewhat generic. 

Perhaps consider calling it something like: 
 - Flick Browser (since tabs can be flicked to close them).
 - Dich Browser
 - Scoute Browser
 - FLOSS without the ( ) or | |

Just a suggestion. I love the browser and will continue using it regardless. Thanks for your work, time, and effort. If I could code I would help you.

**Comment by scoute-dich** [comment]
I'll change it to FOSS Browser with next update.
