### ISSUE TITLE
bookmark ordering

### ISSUE THREAD

**Issue by gothmog123** [scoute-dich/browser#148]
This is the best browser ever on android!

Just a minor hiccup, could you change the way bookmarks are ordered from alphabetical to date of creation? Maybe implement folders? Any way organizing them could be more logical.

**Comment by junior012** [comment]
spanish please

**Comment by pejakm** [comment]
+1 for the bookmark folders! I cannot switch from Lightning Browser completely without this feature. Perhaps even to add ability to import bookmarks from the Lightning Browser?

**Comment by scoute-dich** [comment]
In the next release a more advanced bookmark management will be implemented.
