### ISSUE TITLE
Recent apps shows tabs of browser

### ISSUE THREAD

**Issue by ErikK194** [scoute-dich/browser#15]
Its not really an issue, more a feature request.

How about if u can switch tabs in Recent apps?
[https://www.howtogeek.com/wp-content/uploads/2014/08/02_switching_using_recent_apps.png](url)

It would be like in LineageOS's new browser Jelly. U know it?

**Comment by scoute-dich** [comment]
Picture is offline ...

**Comment by ErikK194** [comment]
https://imgur.com/gallery/AicvQ
last picture

**Comment by scoute-dich** [comment]
Are the tabs shown when pressing the default recents button together with all other apps or is it native implemented in Jelly?

**Comment by ErikK194** [comment]
Default recents button together with all other apps.
Would be more material and use parts of android like your browser webview, or?

**Comment by scoute-dich** [comment]
I will not implement this, due to my personal design and handling guidelines. I just implemented a scroll view (over the toolbar) to fast switch between tabs.

Regards
Gaukler Faun
