### ISSUE TITLE
Settings menu don't works (#126 reopened)

### ISSUE THREAD

**Issue by edgato** [scoute-dich/browser#151]
Expected behavior
click on the setting, then the setting menu will load

Actual behavior
when setting is selected, the app returned to the home page instead of loading the setting

How to reproduce
download F|L|OSS Browser from F-droid, install and launch, from the home page, click on the 3 dots at the down right hand side, then click again the 3 dots at the middle of the popup page, then select setting.

Browser: F|L|OSS Browser Version 5.7
Android V5.1

**Comment by scoute-dich** [comment]
I closed #188.
I also reverted an older change. Can you (or anyone running Lollipop) please test attached apk (rename zip to apk)?
[Uploading app-debug.zip…]()

**Comment by edgato** [comment]
I tested the apk on the link and now I can see the settings menu correctly, both on ligth and normal theme. also tested the version 5.9 from F-droid and worked as well, so I will say it is solved

Thanks
