### ISSUE TITLE
[FR] Custom search engine? 

### ISSUE THREAD

**Issue by UksusoFF** [scoute-dich/browser#154]
It's will be very helpful add support for OpenSearch or just "search string" such as 
```
https://yandex.ru/search/?text=
https://en.wikipedia.org/w/index.php?search=
```

**Comment by ildar** [comment]
JFYI, may this be helpful: I use duckduckgo bangs:
https://duckduckgo.com/bang which has all you asked + many more.

**Comment by BO41** [comment]
@UksusoFF isn't this already possible?
If you click on "Search Engine" and then on the bottom right, there is a button "custom" where you can enter an URL. I assume it does exactly what you ask for, but I didn't test it.

Otherwise it would be a nice feature to add

**Comment by UksusoFF** [comment]
@BO41 That's right.

**Comment by scoute-dich** [comment]
Yes. There you can add a custom search engine. A planned feature for the future is to implement search engine on the fly, without open the settings... But I don't have much time in the next weeks, since I go on vacations.
