### ISSUE TITLE
Some hopefully easily-fixed Java issues were detected by Android Lint, but I do not know if they conflict to where the browser is unusable.

### ISSUE THREAD

**Issue by SC1040-TS2** [scoute-dich/browser#157]
Right now I'm currently working on implementing a few QuickFix-suggested changes, among them being:

-Updating the Gradle Dependency in build.gradle from 3.1.2 to 3.1.3.(Android Lint:Correctness issue)
-Making **public synchronized void addAlbum(int flag) {** 's declaration access weaker by setting the method to Private.(Declaration redundancy warning)
-Replacing 10 'if' statements with 'switch', and replacing two 'if' statements with 'Integer:Compare' statements where appropriate.(Java level migration aids warnings)

I cannot test these changes due to my CPU, but I would appreciate if you looked into them yourself.

Regards from a complete newbie.

**Comment by scoute-dich** [comment]
I'm aware of this. There are much more things to correct. I'll do that in the next days. Thanks for reporting.

**Comment by scoute-dich** [comment]
All lint issues fixed.
