### ISSUE TITLE
Send the DNT (Do Not Track) header

### ISSUE THREAD

**Issue by flocke** [scoute-dich/browser#158]
Could you include an option to send the [DNT header](https://de.wikipedia.org/wiki/Do_Not_Track_(Software)) for all HTTP(S) requests?
While most website mostly likely don't honor it it can't hurt to send the header anyways, especially if it's hidden behind a opt-in settings option.

I might look into it and try to implement this myself, but I can't promise anything since I don't have a lot of time on my hand currently.

**Comment by scoute-dich** [comment]
Will be in next update.
