### ISSUE TITLE
Show URL after link is long-pressed

### ISSUE THREAD

**Issue by n-o-o-b** [scoute-dich/browser#159]
Currently, the browser does not show the URL of the hyperlink you have selected, only options for opening new tabs and sharing and so on. It would be very useful to be able to see the URL before following the link. Most other browsers have this feature.

**Comment by ildar** [comment]
related or dup? https://github.com/scoute-dich/browser/issues/139

**Comment by scoute-dich** [comment]
Link will be shown with next update.
