### ISSUE TITLE
Cant download attachment

### ISSUE THREAD

**Issue by ErikK194** [scoute-dich/browser#16]
I cant download attachments on xda-developers forum

**Comment by scoute-dich** [comment]
I don't know why, but now it seems to work. Do you want to try with a test apk?

**Comment by ErikK194** [comment]
Sure, thx

**Comment by scoute-dich** [comment]
Here it is. Rename zip to apk. You can also test the new implementation of the five tabs. -> Click the toolbar.

Thanks in advance
Gaukler F
[app-debug.zip](https://github.com/scoute-dich/browser/files/1014970/app-debug.zip)
aun

**Comment by scoute-dich** [comment]
When there are any problems after next update, please reopen the issue.
