### ISSUE TITLE
Backup export/import did not work

### ISSUE THREAD

**Issue by rancidfrog** [scoute-dich/browser#160]
5.8 requires uninstall of previous versions:
![](https://i.imgur.com/UQRSybp.png)

So, I exported database:
![](https://i.imgur.com/p9pj6Kq.png)

Uninstalled app, and then installed latest 5.8 version.
When I imported db:
![](https://i.imgur.com/6K6lKy2.png)

It deletes dbs and not import, see toast:
![](https://i.imgur.com/VtQZ7Am.png)
Selecting import shows the above dialog.
And, settings, bookmarks ... were all lost:
![](https://i.imgur.com/7TgftRp.png)

**Comment by scoute-dich** [comment]
That's because I changed the database model. Of toy have a backup of the old version, you can try to export the white lists and your bookmarks separately. Then you can try to import them with the updated version.

**Comment by scoute-dich** [comment]
Backup and restore works fine for me now. If this isn't the caase for you feel free to reopen the issue. Sorry for your discomfort.
