### ISSUE TITLE
Issues with login to certain sites

### ISSUE THREAD

**Issue by rancidfrog** [scoute-dich/browser#161]
Has browser signature changed, or the name sent to sites?
Because latest version 5.8 has login issues trying to log on to some sites

**Comment by rancidfrog** [comment]
It might be an issue with user agent.
Is it possible to add the option for choosing user-agent:
![](https://i.imgur.com/npDVi7U.png)

**Comment by scoute-dich** [comment]
There's no option to change the user agent. It was a time so, but since it was very buggy, I removed it. So I don't think, that I can do here something.

**Comment by scoute-dich** [comment]
You must enable JavaScript and Cookies for login sites.

**Comment by scoute-dich** [comment]
Since, I'm cleaning up issues, I'll close this. There were updates since opening this issue, so open a new issue, if this one still is there.
