### ISSUE TITLE
2-column menu

### ISSUE THREAD

**Issue by rancidfrog** [scoute-dich/browser#167]
All entries could fit in 2-column for most devices, instead of having 2 sections:
![](https://s33.postimg.cc/443svika7/AFFIX_20180720_211033_01_01.png)

**Comment by scoute-dich** [comment]
I will not impotent this. It's a good idea, but I don't have the time.

**Comment by BO41** [comment]
@scoute-dich you could leave the issue open and tag it, so if anyone else wants to implement it, they would have an issue for it

_feature_ and _needs_help_ or _PRs_welcome_

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to say that, but I will concentrate on the important things.

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to say that, but I will concentrate on the important things.
