### ISSUE TITLE
Some feature suggestions

### ISSUE THREAD

**Issue by kakolisgay** [scoute-dich/browser#169]
I recently found FOSS Browser on F-Droid and decided to try it out, It's really well put together and works nicely, however I feel like some things are missing and should be included. Such as:
- A way to change the User-agent. Maybe something like how Lightning Handles it?
- A preview of the next and previous tab when dragging the Omnibar left or right like Chrome Canary
- An option to toggle the `dnt` header as it can be used for fingerprinting

None of these features are essential however I do feel that FOSS Browser could benefit from having them

**Comment by scoute-dich** [comment]
I can think of an option for the dnt header, the rest will not be implemented.

**Comment by scoute-dich** [comment]
DNT is implemented.
Custom user agent will probably implemented in future. I#ll close this issue. For custom user agent please follw #269 .
