### ISSUE TITLE
Image format extension ignored & svg-format not downloadable

### ISSUE THREAD

**Issue by mygithubusrname** [scoute-dich/browser#17]
Hi,

Is there a possibility to preserve the filename extension of images? Saving imagefiles leads to renaming with the following pattern: yyyy-mm-dd_hh-mm-ss.jpg. The suffix jpg is always replacing the original extension.

How to reproduce:
Step 1: Open link: https://upload.wikimedia.org/wikipedia/commons/e/e6/Walking_baby_tux.gif
Step 2: Long press loaded image.
Step 3: Press "Save image" in pop-up menu.
Step 4: Image will be saved with wrong extension.

I see this issue with png-, gif-, bmp- and webp-files.

I also noticed a possible issue with svg-imagefiles. It seems not possible to save those images. 

How to reproduce:
Step 1: Open link: https://upload.wikimedia.org/wikipedia/commons/b/b0/NewTux.svg
Step 2. Long press loaded image. No pop-up menu appears with "Save image".

Additional Infos:
- Device model: GT-I9505
- Android version: 7.1.1
- Browser version: 3.5

Best regards.

**Comment by scoute-dich** [comment]
Hi thanks for reporting.

1. I think I will find a solution.
2. It seems that svg-files are not recognized as picture files. A workaround would be to set a "save link as" entry in the context menu for links. Than it would be possible to save any linked file. I think that would be possible for me to do... Would that be ok for you?

**Comment by mygithubusrname** [comment]
Hi, both solutions sound great - many thanks. Keep up the good work. Best regards.

**Comment by scoute-dich** [comment]
Both already implemented. Just want to test a few days and then I will release the update.

**Comment by scoute-dich** [comment]
When there are any problems after next update, please reopen the issue.
