### ISSUE TITLE
Request: Copy Link option

### ISSUE THREAD

**Issue by Ascrod** [scoute-dich/browser#170]
It looks like the "Copy Link" option was removed from the long-press menu for URLs in v5.8. Was there a reason for this? It would be nice if it could be either re-added to that menu, or added as an extra option in the share menu.

**Comment by scoute-dich** [comment]
I removed it, because there is only place for four items in the menus. I for my use have installed "Share to clipboard" from F-Droid. Then you can share the link to clipboard. Sorry, but I won#T bring that feature back.

**Comment by Ascrod** [comment]
Understandable... I've started using Share to Clipboard and it does what I need. Thanks for the tip.
