### ISSUE TITLE
[Feature suggestion] Hold and drag to rearrange tabs.

### ISSUE THREAD

**Issue by n-o-o-b** [scoute-dich/browser#172]
Would be cool to be able to rearrange the tabs in the tab preview.

**Comment by scoute-dich** [comment]
Since a lag of time, I'll not implement this. Sorry.

**Comment by BO41** [comment]
@scoute-dich you could leave the issue open and tag it, so if anyone else wants to implement it, they would have an issue for it.
Maybe someone else got time :)

Possible tags:

-  feature
- needs_help
- PRs_welcome

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to day that, but I will concentrate on the important things.
