### ISSUE TITLE
Document creation.

### ISSUE THREAD

**Issue by HarryHeights** [scoute-dich/browser#180]
Hello, I'm Harry. I'm not a developer, however, I'm a writer and a content creator. I'm also a contributor to open source projects. I contribute in the aspect of documentation or copywriting. Copywriting is simply a way to advertise a project in written form or creating documents for projects. It could drafting a privacy policy, About, FAQs or even proof reading already existing document.
So I came across your project which I must commend is pretty cool and noticed it doesn't have a privacy policy and for an app that deals with internet connectivity while being used, it'll be good to state and let users know whats and whats not about information collection and use which is the essential constituent of a privacy policy.  Then there's no FAQs document, which would be very helpful to noobs as it'll be a self service guide. Then About is a descriptive summary of your project which is mostly written in a way to create influence and spur people to try out the software.

I'll be creating these if you are interested. 
I'll love to hear from you.

**Comment by scoute-dich** [comment]
It would be nice, if you could do that. Ask me, if you need further information.

**Comment by HarryHeights** [comment]
Alright. I'll work on those and send pull requests. Sorry for late reply.

**Comment by HarryHeights** [comment]
sorry for the delay in getting the proposed work done. I was at a place with no access to my laptop. I'll be up to speed with the document creation. Thanks for understanding.

**Comment by scoute-dich** [comment]
Thanks for your work until now. I'll close this. If you have more pull requests in future, you're welcome.
