### ISSUE TITLE
add ad-blocking lists

### ISSUE THREAD

**Issue by BO41** [scoute-dich/browser#184]
If I see this rigth, you are using `browser/app/src/main/assets/hosts.txt` as the file for ad blocking.

1. should we update it?

2. should we add some more host files?
uMatrix for example has some more lists, for example [malwaredomains](http://www.malwaredomains.com/) and some other adblocking lists.

I think the current list should be updated (if there is an update, but the current version is 8 months old.
And I think it would be great to add some more lists and an option for the user to select them.

tell me what you think, then I would look what I can do :)

**Comment by scoute-dich** [comment]
That would be a nice idea. I was on vacation. And I see it's a lot to do... I will look first into real issues, and then into feature requests. But of you have the time, feel free to contribute.

**Comment by BO41** [comment]
@scoute-dich yeah sure. of course. This is not important.

I could see if there is an updated list. I also could find some other lists.
But I don't think I am able to add an option to select the lists

**Comment by scoute-dich** [comment]
When there's more time some day, I could look into the code of AdBlock or something like that..

**Comment by scoute-dich** [comment]
I updated the list with
https://github.com/AdAway/AdAway/wiki/HostsSources

Used lists:
- https://adaway.org/hosts.txt
- https://hosts-file.net/ad_servers.txt
- https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
- http://www.malwaredomainlist.com/hostslist/hosts.txt
- https://github.com/StevenBlack/hosts/raw/master/hosts

I think that might be enough. I can update the list one a month or something like that.

**Comment by BO41** [comment]
nice, awesome :tada: 
I think once every few months would be enough.
