### ISSUE TITLE
Blank target href do not open a new tab

### ISSUE THREAD

**Issue by jza34** [scoute-dich/browser#185]
Click on a click with target=_blank should open a new tab by default.
Or could it be an option?
Thanks for the good work!

**Comment by BO41** [comment]
you are right, the `target` attribute seems to be ignored.
I think it should be. Making it an option is even a better variant :+1: 

@scoute-dich do you have a reason for this behavior?
and where in the code would this needed to be changed?

**Comment by scoute-dich** [comment]
Can you provide me such a link? I don't understand the question...

**Comment by BO41** [comment]
I assume this issue is still present.

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_a_target

in this example, you should see, that clicking the link opens a new tab, since the `target` is set to `_blank`.
While a link with `target="_self"` should open the link in the same tab.

**Comment by fe60** [comment]
For me the current implementation is the preferred behaviour.

If it gets implemented, I would like to have an option to switch it off, as mentioned by @BO41 in the first comment. Or just keep it as is.

**Comment by scoute-dich** [comment]
Will be implemented in next update. Without any new settings, since I don't want to have new strings to translate and this should be indeed the default behavior for users.
