### ISSUE TITLE
Variety of things that would make this the perfect browser

### ISSUE THREAD

**Issue by Carbuzzer** [scoute-dich/browser#19]
Just wanted to start off by saying that this is probably the smoothest mobile browser I've ever used. I'd love to use this as my main browser, but there's a couple issues I have that is preventing me from doing so. 

**Issue 1**: Lack of search suggestions when typing in URL's. Most browsers I've used have Google search suggestions enabled which makes it a lot easier to navigate to the websites you want. Also, most browsers learn the websites you go on most and display a few right before you start typing, which is extremely convenient. 

**Issue 2**: The search box is weirdly laid out. For example, I've been constantly hitting the URL at the bottom of the browser thinking it's the URL search, when it's actually the tabs manager. I find it really weird to have to press the small magnified glass in order to search. In my opinion, the search bar should be where the URL is and the tabs manager should be where the magnified glass is.

**Issue 3**: The cookies setting should be more clear. There are 4 options for cookies, but it doesn't make any sense. The first option is accept cookies, when it should say accept first-party cookies only. There should only be three options here; accept cookies, accept cookies except 3rd party, and block cookies. I mean, why would someone want to accept third party cookies only? Makes no sense.

**Issue 4**: The notification shade when browsing stays green, when it should be black. It's not a big issue, but it would look nicer if it was consistent with the norm.

**Issue 5**: I noticed the browser keeps reloading and going back to the homepage (which is this Github). Even when I'm on a website (Reddit, for example) then go into the browser settings and go back to the browser itself, it reloads back to the homepage. Also, does this browser have history? Because I can't find it anywhere and it just reloads everytime I close the browser.

Again, this is a super smooth browser that I'd LOVE to use provided these things are sorted out. I know it's a relatively new browser, and I'm sure it'll only get better with time. Having said that, I will gladly donate if these issues are sorted out.

**Comment by scoute-dich** [comment]
Sorry for late response, but I was on vacation. Here are my thoughts:

**Issue 1:** Sorry, but I don't know how to implement this feature.

**Issue 2:** I will think about it and test it. If it's more comfortable I will switch it.

**Issue 3:** That's a good idea. I will implement it.

**Issue 4:** The green color is from the toolbar. The black color is the background of the snackbar, which displays the notifications. If you have suggestions... I will also take a look in possible solutions.

**Issue 5:** After opening the main settings screen has been opened and you go back to the browser, the browser gets recreated, to apply the settings. This behavior is intented. If you have an other idea just tell me. I will also search for a better solution...  If you want to change settings on the fly without reloading, you must use the popup dialog. The browser has a history (icon beneath the magnifier  icon). Btw. you can change your homepage by clicking the "star" in your bookmarks list.

So let me know your thoughts. I will start working on it in the next days... Thanks for your interest in my app.

Regards
Gaukler Faun

**Comment by scoute-dich** [comment]
Most of the things are done. I will let the issue opened, until I decide, what to do with the two remaining issues.

**Issue 1:** Sorry, but I don't know how to implement this feature.

**Issue 2:** Done.

**Issue 3:** Done.

**Issue 4:** The green color is from the toolbar. The black color is the background of the snackbar, which displays the notifications. If you have suggestions... I will also take a look in possible solutions.

**Issue 5:** Done.

Regards
Gaukler Faun

**Comment by mkodekar** [comment]
@scoute-dich you can add array adapter which implements filterable and and see in history and bookmarks and also from a custom web services from where you can connect and load data

**Comment by tclaybor** [comment]
@mkodekar you can still get suggestions from the search page. The Dev is trying to keep this app very light and very privacy friendly. Connecting to a Web service just to navigate somewhere is more trouble and weight than it's worth when you could just use the search engine home page.

@scoute-dich if you do not plan to implement the two outstanding points (notification shade and search suggestions), then you have completed all changes requested and this could be closed. 

Not trying to step on your toes, just trying to help :)

**Comment by scoute-dich** [comment]
As suggested by @tclaybor search suggestions will not be implemented.

The last issue (matching colors of the snackbar) also. With the next update the snackbar will show above the toolbar, so the "shading" of it will not disturb the consistence anymore.

**Comment by cavemandaveman** [comment]
I agree, search suggestions seem too heavyweight for this browser. But what about @mkodekar's points about suggesting history and bookmark options? That would improve usability a little.

**Comment by agboom** [comment]
Sorry for digging up an old issue, but I'd like to weigh in to this. This browser is one of the fastest  I've used that is also open source. As @cavemandaveman mentioned suggesting history and bookmarks in the omnibar would improve usability, imho significantly.

As an example, I often use history to quickly open a page by typing a few letters that match. To open the page for this project, I would type "git<space>browser" and usually it already shows a short list. Sometimes a few letters even suffice. This really speeds up browsing for me. 

If you're not up to it, I'd be happy to contribute. I've never created an Android app before, however, so I'll need some pointers.
