### ISSUE TITLE
screenshots missing in f-droid

### ISSUE THREAD

**Issue by BO41** [scoute-dich/browser#191]
there are no screenshots of the app on the [f-droid page](https://f-droid.org/packages/de.baumann.browser/).

I think you should add some (more = better) up-to-date ones.
People should see what it looks like and what the features are.

**Comment by scoute-dich** [comment]
Do you know, what I must do? Or is there a documentation?

**Comment by BO41** [comment]
never worked with f-droid or added an app.

but the docs provide this explanation  https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

- graphics and screenshots as PNG or JPEG files
-  dangerous and unneeded metadata is stripped from image files
-  images are recompressed

**Comment by BO41** [comment]
you could at least link your [screenshots](https://github.com/scoute-dich/browser/blob/master/SCREENSHOTS.md)
