### ISSUE TITLE
Toolbar shaking bug

### ISSUE THREAD

**Issue by poilynx** [scoute-dich/browser#194]
click https://poilynx.github.io/ in Browser

**Comment by BO41** [comment]
you mean when you are trying to scroll, the toolbar keeps appearing an disappearing?

**Comment by scoute-dich** [comment]
[app-debug.zip](https://github.com/scoute-dich/browser/files/2331722/app-debug.zip)
That happens sometimes, when at the end of a website there are only some (<= 56) pixels left to scroll. I think the attached version (rename zip to apk) is a compromise. Just tell me your thoughts.

**Comment by poilynx** [comment]
@scoute-dich When i run the APK file attached, the problem is not resolved. Tool bar appears and disappears quickly, just like electric bell by electromagnetic oscillation driving. (I set the toolbar hide automatic when scroll down). poor english :joy:

**Comment by scoute-dich** [comment]
Will finally be solved with next release. The price will be, that you must scroll more than the toolbar high to the top to show the toolbar again, once it is hidden. But in my tests it's the best solution.

**Comment by scoute-dich** [comment]
@poilynx Can you test please the following apk. Because we have different screens, I can't test.
[app-debug.zip](https://github.com/scoute-dich/browser/files/3122544/app-debug.zip)
