### ISSUE TITLE
[Feature Request]Allowing Changes to Locations of Addressbar and Tab List.

### ISSUE THREAD

**Issue by moriel5** [scoute-dich/browser#195]
Hello, it's great seeing you again @scoute-dich, I'm still using your modded K-9 Mail, despite the fact that it is slightly outdated, due to it being much more comfortable for me.

As a Lightning Browser user, I was wondering whether it would be possible to implement additional (seperate) locations for the addressbar and tab list, since I am used to having the addressbar on the top, and the tab bar on the left.

Other than that, I think that FOSS Browser is pretty awesome, plus it is both light in size and system resources (Lightning Browser is starting to show it's age).

**Comment by BO41** [comment]
It should not be that hard to make an option whether to have the addressbar on top or bottom.
I think some users might like this as not everyone is used to having it on the bottom.

**Comment by moriel5** [comment]
This sounds great to me.
By the way, despite the fact that I am used to having the tabs in a sidebar (on my phone), I really like your tabbar implementation.

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to day that, but I will concentrate on the important things.
