### ISSUE TITLE
Swiping between images in Duckduckgo causes visual glitch

### ISSUE THREAD

**Issue by 1RaE** [scoute-dich/browser#196]
When you open a image in duckduckgo, then swipe to the side to the next picture, half the image is invsisible then it takes a second or two to return to normal. Scrolling is also laggy, through that seems limited to DDG and Qwant. Also, when you drag an image which is too large for the display downwards, it is impossible to view the hidden part of the image while looking in portrait mode as it just bounces up and down in infinity until you release the image. These problems are not major but I feel this browser should be able to handle what other webview-based browsers are capable off.

**Comment by scoute-dich** [comment]
Since, I'm cleaning up issues, I'll close this. There were updates since opening this issue, so open a new issue, if this one still is there.
