### ISSUE TITLE
This browser doesnt support "app redirection"

### ISSUE THREAD

**Issue by 1RaE** [scoute-dich/browser#197]
When you open certain apps, you are required to authenticate your login via the browser. But this browser doesn't support, or at least it doesn't do that, so the login fails. I don't know code but would support of this kind of feature be hard to implement?

**Comment by scoute-dich** [comment]
Can you give me an example link?

**Comment by 1RaE** [comment]
Tusky, open source mastodon client, is the specific app this caused problems for. I would hazard a guess it tries to open a webview instance within the app itself but that fails so it opens it in the browser instead but something is a miss at this point. I would say easiest way to replicate is to download tusky, try to sign in and see if it still fails. This always resulted in a blank screen for me.

**Comment by scoute-dich** [comment]
Is this still from relevance? Have you enabled JavaScript and Cookies for the login site?

**Comment by scoute-dich** [comment]
Since, I'm cleaning up issues, I'll close this. There were updates since opening this issue, so open a new issue, if this one still is there.
