### ISSUE TITLE
URL copying?

### ISSUE THREAD

**Issue by 1RaE** [scoute-dich/browser#198]
Copying URL within a search engine is not possible, and only brings up a screen to open a new tab. When searching images this gets annoying as it leads me to sites without HTTPS when trying to get the image url to search for the image on a HTTPS enabled site.

**Comment by scoute-dich** [comment]
Please use a third party app like "Share to clipboard" from F-Droid. Than you can share the link to the clipboard. I don't want more menu entries or submenus.
