### ISSUE TITLE
Questions about Browser

### ISSUE THREAD

**Issue by reno-a** [scoute-dich/browser#2]
Hello,
Thank-you for this open source web browser.
I have two questions :
- how return to home page ?
- if Browser use WebView, the version is different about original web browser (gello). Do you included a WebView gear?
Thanx for your answers.
PS : sorry for my english

**Comment by scoute-dich** [comment]
First question:
You don't need to go back. Just swipe to the left on the toolbar and your bookmarks will open (read the help dialog).

Second question:
I don't understand what you mean...

Regards
Gaukler Faun

**Comment by reno-a** [comment]
Thanx for your responses.

I see the arrows and I use it.
Effectively it's OK.

For WebView, it's my mistake .
Just the engine is different to Chromium (Gello).

Have a nice day.

**Comment by scoute-dich** [comment]
;-)

**Comment by kskarthik** [comment]
In browser 😀 Will you support tabs in future ?

**Comment by scoute-dich** [comment]
I don't know how to implement it. So I think no. There are actually two "tabs". For me that's enough...

Sorry
Gaukler Faun
