### ISSUE TITLE
strange notification behavior

### ISSUE THREAD

**Issue by amo13** [scoute-dich/browser#20]
Thanks for your great work on this app! It's pretty hard to find a decent web browser on f-droid but yours is already pretty amazing. It's also nice that you keep maintaining it!
However, I noticed a strange notification behavior when opening a website from another app through your browser: A notification shows up on top of the status bar but there is no text in it and there is no way to tap on it. You have to wait for it to disappear, swipe down the notifications and tap on it after it disappeared. You can see what it looks like for me on the picture attached. I also noticed that the notification draws over the status bar for different amounts of time depending on the device I use.
Do you think there is a way to fix this or at least have some meaningful text in the notification? ;)

![img_20170619_110211](https://user-images.githubusercontent.com/6617661/27278869-f4220dc0-54e2-11e7-81de-425930b48519.jpg)

**Comment by scoute-dich** [comment]
![](http://i.imgur.com/VUqnkic.png)
No issues here running Android nougat. As you can see, here the notification is working like intended. It shows the touched link and gives you the possibility to as the link to the readLater list or open that list. By clicking the notification, the link should open immediately.

Are you using any themes or apps which manipulate the notification behavior?

_Gesendet von meinem OnePlus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by amo13** [comment]
I see. Have you tested it on Android 6? I run different devices on mostly Cyanogenmod 13. I don't install weird exposed modules or stuff like that. The system is clean on my devices.
Is it possible that the notification requires gapps to works correctly? I don't use any gapps on my devices...
If you need a logcat, I can provide one, you just need to tell me how to get it, if "take a bug report" in dev options is not what you would need.
Cheers and thanks a lot for investigating!

**Comment by Dvaderfun** [comment]
Yes, Notifications not optimized for Android 5 -6

**Comment by amo13** [comment]
Sometimes it looks somewhat more buggy than on the photo: I haven't figured out under what circumstances exactly, but instead of showing the empty notification shown above, it would display the notification of another app in that same way, also not clickable...

**Comment by scoute-dich** [comment]
Thanks for the comments. I will look at it at the weekend. The problem is that I only have one device running Android Nougat. But let's see...

_Gesendet von meinem OnePlus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
Have here a test apk. Perhaps can one of you try it. Just rename "zip" to "apk". Thanks.
[app-debug.zip](https://github.com/scoute-dich/browser/files/1100304/app-debug.zip)

**Comment by amo13** [comment]
Yes that works much better!!! The notification looks nice now :)
Only thing is that the notification just adds to the list of notifications but does not appear for a short time for me to tap it directly without having to swipe down the notifications. I don't know how it behaves on nougat, but it seemed to be meant like that on the previous versions. Like when you get a call while using the phone: the phone app does not open, but a call notification draws over the statusbar. This does not work yet on marshmallow.
Thanks a lot for the fix!

**Comment by scoute-dich** [comment]
When you click the notification on the "top area" it doesn't open the link?

_Gesendet von meinem OnePlus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
"Heads up" notifications should work with next update. Please reopen this issue, if there are further problems.

**Comment by amo13** [comment]
will do!
Thanks a lot, bro! Sorry for not answering the last message, been super busy lately...
