### ISSUE TITLE
Feature request: Add website shortcut to homescreen

### ISSUE THREAD

**Issue by skygate2012** [scoute-dich/browser#200]

**Comment by BO41** [comment]
what do you mean?
could you elaborate and describe your feature a bit more, please?

do you mean this https://github.com/scoute-dich/browser/blob/master/SCREENSHOTS.md (first image)?

**Comment by skygate2012** [comment]
@BO41 Sorry for my briefness. I mean the homescreen of the Android system launcher, like the `Page > Add Page Shortcut` feature in Firefox. Not the home of the browser itself.

**Comment by scoute-dich** [comment]
I'll try to implement this. But with Android O and P it seems that the way shortcuts are added to home screen has changed. I experimented a little bit. But found no solution until now.

**Comment by scoute-dich** [comment]
Yeah, found a solution, which is working through all supported android versions. If someone will test:
[app-debug.zip](https://github.com/scoute-dich/browser/files/3114087/app-debug.zip)

**Comment by scoute-dich** [comment]
Will be added with next update. If you have problems with the apk provided above, please reopen the issue.
