### ISSUE TITLE
[Feature Request] Desktop Mode

### ISSUE THREAD

**Issue by jerryn70** [scoute-dich/browser#202]

**Comment by JonnyTech** [comment]
Most other mobile browsers have the option to request the desktop version of a page. This seems to depend on changing the user agent string of the browser. May need `webView.getSettings().setUseWideViewPort(true)` too. Is this feature planned or available as a bookmarklet?

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to say that, but I will concentrate on the important things.
