### ISSUE TITLE
[Feature Request] force zoom

### ISSUE THREAD

**Issue by tomasz1986** [scoute-dich/browser#204]
Would it be possible to add a "force zoom" feature to the browser? Without it, it is impossible to zoom on sites that block zoom on mobile (and thus make themselves impossible to use for many people, e.g. with poor eyesight).

This is how the setting looks like in Chromium:

![image](https://user-images.githubusercontent.com/5626656/45392563-df0cac00-b662-11e8-8ff9-cd158e69f6c4.png)

Increasing just the text size is not enough, as you still cannot enlarge images or other non-textual content.

**Comment by scoute-dich** [comment]
Chromium uses his own rendering engine. I don't know a method in the system webview.

**Comment by scoute-dich** [comment]
Some websites have a special tag in there website code, which disables zooming. I know no method to overwrite this.
