### ISSUE TITLE
[feature request] Android TTS integration

### ISSUE THREAD

**Issue by kuanyui** [scoute-dich/browser#209]
TTS ( https://developer.android.com/reference/android/speech/tts/TextToSpeech ) is the only function that I wish a mobile web browser has, but I never seem this function is implemented on any trusty browser.

(Firefox for Android seems has some addons can do this, but none of them actually workable...)

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to say that, but I will concentrate on the important things.

**Comment by kuanyui** [comment]
That's OK because I also have exactly the same thought on my projects.
