### ISSUE TITLE
[Privacy] WebView: Phoning home to Google?

### ISSUE THREAD

**Issue by shellshocker** [scoute-dich/browser#210]
[Here](https://android-developers.googleblog.com/2018/04/protecting-webview-with-safe-browsing.html) Google says:

> Since 2007, Google Safe Browsing has been protecting users across the web from phishing and malware attacks. It protects over three billion devices from an increasing number of threats, now also including unwanted software across desktop and mobile platforms. Today, we’re announcing that Google Play Protect is bringing Safe Browsing to WebView by default, starting in April 2018 with the release of WebView 66.

Since FLOSS Browser is using Android WebView is this also active in the browser? I'm using LineageOS without any GAPPs - so I'm wondering if it's possible to use FLOSS Browser without "phoning home" to Google via WebView.

Thanks!

**Comment by dimqua** [comment]
You can use e.g. [Bromite WebView](https://www.bromite.org/system_web_view) for now or just wait when [this project](https://gitlab.com/thermatk/Unobtainium) will be added to F-Droid (WIP).

**Comment by scoute-dich** [comment]
I don't think that this is a problem, when you don't use any GoogleApps on your phone.

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to say that, but I will concentrate on the important things.
