### ISSUE TITLE
[Feature request] Refresh screenshot for links on startpage

### ISSUE THREAD

**Issue by engelhro** [scoute-dich/browser#211]
**Request**

It would be great to be able to refresh the screenshot (maybe via long click) which is set the first time a link resp. open tab gets added to the start page. Alternatively it would be nice to be able to set a solid background color (selected by the user from the usual Android Material color palette) instead.

**Reasoning**

Especially for news sites the look of the start page changes often, and the screenshot taken initially will be outdated soon. It should be possible to set a new picture from time to time, or to represent such dynamic sites by a solid color instead.

Thanks for considering this idea!

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to say that, but I will concentrate on the important things.
