### ISSUE TITLE
Download manager not download file only pop up download complete specially bank sites download bank statement as a pdf format but havent work for this browser while external chrome browser work fine

### ISSUE THREAD

**Issue by neerajsinghvr** [scoute-dich/browser#212]
Download manager not download file only show pop-up download complete but file doesn't save at download folder I have accept write permission as well run time. **This issue specially on bank sites when want to download bank statement as a PDF format or other but haven't work for this browser while external chrome,Firefox browser work fine**

**Comment by scoute-dich** [comment]
Foss Browser uses the native Android download manager. I never had this problem. The downloads are working with an other browser, which uses the build in download manager?

**Comment by neerajsinghvr** [comment]
Correct as per my observation issue on api nougat and above till
marshmallow work fine

**Comment by neerajsinghvr** [comment]
[https://drive.google.com/file/d/131nsXnVEWPL8Lt7h6eOQRHp70YfytKuM/view?usp=sharing](url)
