### ISSUE TITLE
Edit bookmark URL

### ISSUE THREAD

**Issue by JonnyTech** [scoute-dich/browser#213]
When editing a bookmark, is there an option to edit the URL as only the title is visible in the dialog?

**Comment by scoute-dich** [comment]
Yes only dialog. In the next version you can set also login data for a bookmark and you can assign colors as "tags" to any bookmark. The you can filter by color.

**Comment by scoute-dich** [comment]
Ok. I misunderstood. I think it should be no problem to make an additional field for editing the url. I'll make that. But at the moment I don't have much time.

**Comment by scoute-dich** [comment]
Done.
