### ISSUE TITLE
[Feature] Show Source Code

### ISSUE THREAD

**Issue by c0dev0id** [scoute-dich/browser#215]
Hi,
Foss-Browser is my favorite mobile browser. The only functionality I'm missing is a way to look at the source code of websites. I'm not sure if this is a hard to implement task, because no other browser seems to be able to do this...

**Comment by scoute-dich** [comment]
You can long press on link to an webpage, and "save as..." html. Then the link will be downloaded as HTML file. This works of course only of the link belongs to a html document.

**Comment by scoute-dich** [comment]
Since I don't have much time, I'm closing all feature requests, which I will not implement in the near future. Sorry to say that, but I will concentrate on the important things.
