### ISSUE TITLE
Open YouTube links with YouTube app

### ISSUE THREAD

**Issue by n-o-o-b** [scoute-dich/browser#216]
This shouldn't be a priority, but it would be nice if the browser could open YT links in the app rather than taking me to the webpage. The webpage is kinda inconvenient and limited compared to the app.

**Comment by gh-pmjm** [comment]
You can always long-tap the link or a playback window and select the 'Open link with...' at pop-up menu. It gives you an direct option to open it in other app (in this case the YouTube app).
