### ISSUE TITLE
Scrolling to bottom of page causes flickering

### ISSUE THREAD

**Issue by 1d10** [scoute-dich/browser#218]
Hello. I recently installed FOSS Browser on my Galaxy Express Prime phone running stock Android Nougat (7.1.1). I really like FOSS Browser and want to continue using it, but I've been experiencing the issue listed in the title. Every time I scroll to the bottom of a page with a fast swipe, the page will start flickering up and down. Not only is this irritating to my eyes, but it often forces me to restart the browser. Please address this issue and continue to improve the FOSS Browser app as I believe it has a LOT of potential. In the mean time, I'll stick with using Ninja.

**Comment by scoute-dich** [comment]
Can you test please the apk provided in #194 ?
