### ISSUE TITLE
[Feature Request] Toolbar URL

### ISSUE THREAD

**Issue by cavemandaveman** [scoute-dich/browser#22]
This is a great browser, I love that you only have the necessary features. There are a few things I would suggest, however.

Currently, the toolbar shows the page title, but it would be nice to have the option of showing the full url. And when clicking the toolbar, it would be nice if it went into edit mode for the url so that you can manipulate/copy the current url. If the full url was highlighted as soon as you click, you could just start typing and therefore keep the current search functionality (think omnibar).

Also, a verification icon or lock icon for https sites would be a nice bonus.

**Comment by scoute-dich** [comment]
Good idea. I'll try to implement this in next update! Sorry for late response. ;-)

_Gesendet von meinem OnePlus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madline7** [comment]
GERMAN

**Comment by scoute-dich** [comment]
I've implemented your suggestion.

For the second: I don't think that there is enough space for an additional icon on the toolbar to show https status...

If you have an idea just tell me. In the next weeks I've a bit more of time.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JM480** [comment]
This feature seems to be missing in current versions. Can this feature be added back?

**Comment by scoute-dich** [comment]
For me, everything still works as expected. What do you mean is missing?

**Comment by JM480** [comment]
There's no option to always show the full URL in the toolbar.
