### ISSUE TITLE
Add support for the javascript: URI scheme

### ISSUE THREAD

**Issue by Zer0Division** [scoute-dich/browser#223]
If I send javascript code (like javascript:alert('hello world')) through the address bar it get treated as a search query and the browser redirect me to google(my default search engine), instead of running it (with the code above I should get a popup which says "hello world"). 

This would allow users to add some bookmarklets to the browser. Thanks in Advance.

**Comment by scoute-dich** [comment]
I've a lot to do at work at the moment. Since I'm doing this in my free time, there's no time for implementing new features.
