### ISSUE TITLE
Toggle for JavaScript Whitelist

### ISSUE THREAD

**Issue by FlexW** [scoute-dich/browser#227]
I would be really nice if there were an option (maybe in Fast toggle) to add the current open page to the JavaScript whitelist.

**Comment by scoute-dich** [comment]
This is already implemented in the FastToggle dialog. There are supported whitelists for javascript, cookies and adblocker.

**Comment by FlexW** [comment]
Yes, but with the JavaScript Button in Fasttoggle, the domain is not added to the whitelist and JavaScript gets enabled globally. It would be nice if the toggle would just add the domain to the whitelist.

**Comment by FlexW** [comment]
Okay thanks. I haven't seen it. Sorry.
