### ISSUE TITLE
That update is awful

### ISSUE THREAD

**Issue by Zer0Division** [scoute-dich/browser#229]
I'm sorry guys but the old design was way better.

Setting startpage.com as a default homepage is just dumb, people who are interested can just set it as a default search engine, on the other side people who are not, are stuck with an useless homepage and must press that burger icon at every startup.

The gestures of the navigation button and the toolbar are now linked, so we can no longer switch tabs with the toolbar and navigate the history with the button, because they both do the same thing.

In addition to that,  swiping up from the toolbar isn't  allowed anymore, and the little animation we were getting while swiping left and right is gone, these were indeed really convenient features.

This feels almost like a downgrade, I'm switching back to the older version.

**Comment by ildar** [comment]
I agree.
Also in Settings -> Behavior -> Overview I set History but all I get is startpage.com ?

**Comment by scoute-dich** [comment]
See here:
https://forum.xda-developers.com/showpost.php?p=78563392&postcount=287

@ildar History should open, when you open the overview. In the next version there will be an option to open the overview on start of FOSS Browser instead of favorite website.

**Comment by Zer0Division** [comment]
Just seen the mockup for the gesture implementation, this looks great (don't forget the scroll to top functionality by swiping up in the navigation button), as soon as you add it I would switch to the update version. 👍
