### ISSUE TITLE
Tab questions

### ISSUE THREAD

**Issue by cavemandaveman** [scoute-dich/browser#23]
Is there a way to close a tab? I usually like to close/clear the tab when I'm done browsing the page.

Also, is it possible to set a blank/empty page instead of one of the bookmarks when you open a new tab?

**Comment by scoute-dich** [comment]
To clear long press a tab in the overview. But that will open the bookmark favorite. But when I add the option, to set a blank page as bookmark, this could be done. I'll implement this also. Thanks for your suggestions.

_Gesendet von meinem OnePlus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
Will be in next update. To set an empty page as bookmark open the bookmark list and click the overflow button to open the menu.
