### ISSUE TITLE
Bookmarks on startup

### ISSUE THREAD

**Issue by bernique** [scoute-dich/browser#231]
Since last major update v6, I cannot get any more my bookmarks on startup. I only get home, ie my search engine. I can't any way to get back my bookmarks.
FYI, I didn't succeed in saving my bookmarks, I lost all of them....
Thank you for your development.
Loïc

**Comment by puppykickr** [comment]
I have the same problem.
Absolutely hate the new version.

The only solution is to uninstall and then install version 6.0

This is the last version that stores bookmarks and allows the homescreen to be set up as desired.

Thank God I use two devices and tried the new version where I had nothing important stored, because it would all have been lost.

**Comment by bernique** [comment]
Thanks for the advice. I'm back on 6.0 and it is back the best Android browser!

**Comment by bernique** [comment]
Another point with the new version: I could not get research by tapping words in the address bar.

**Comment by puppykickr** [comment]
Same here.

The new versions were a total dissappointment.

To make so many changes for the worse, it would have been better if the new
versions were a different app all together.

FOSS is a decent browser, so because the new versions are not they could be
called F**K instead.

Because that's what everyone said as soon as they updated.

Grant Ryan Swan
(puppykicker)

**Comment by theBubbly** [comment]
@puppykickr Jeez Louise, man. Take a chill pill. It seems that as if yet no one has, so allow me to be the first to let you in on a little secret: this code is Free as in, "If you don't like it, Fix it." Alternatively, FLOSS can be interpreted as, "F*** Off, Selfish Sh*t."
You see, most grownups have jobs, families, and countless other responsibilities taking precedence over free, tailor-made software for Grant Ryan Swan.
I will assume that you are either a child who has had everything handed to them, or that you are an unemployed adult who has had everything handed to them. In either scenario, you cannot be blamed for being a complete asshat — you just don't know any better, and your parents should have been more responsible.
However, if indeed you are a working adult human being, then shame on you, sir. Shame on you for being a complete asshat.

You're better than this.

Shape up, Mr. Swan.

**Comment by theBubbly** [comment]
P.S. — Everybody makes mistakes. For example, your English could probably benefit from the old once-over.

**Comment by puppykickr** [comment]
@theBubbly
It is not my fault that plain, normal English is beyond your understanding, any more than it is my job to repair someone else's mistakes.

**Comment by fe60** [comment]
@puppykickr 
I lost my bookmarks too. At the first moment I was angry. But then I decided to not simply complain about a software provided for free, but try to help at least a bit. Reporting the issue as @bernique did, is a good starting point.

@scoute-dich 
Would it help to get the build of the software running locally and act as a software tester for new features/releases?

And I learned two things:
I have to set-up a backup for my smartphone (incl. browser bookmarks).
F-Droid can offer more than one version of a software (didn't know this before).

**Comment by scoute-dich** [comment]
Here you can find a short explanation for the last update: https://forum.xda-developers.com/android/apps-games/app-browser-t3500091/page29

With today's release out will be possible again to open the overview on start. Also take a look in the new gesture settings.

@fe60 Of course you could help. Just fork this project and send pull requests or issues. Any help is appreciated, since I'm not a learned developer.

**Comment by scoute-dich** [comment]
Btw. there was hint to show the old bookmarks. And the advice to save them again. I knew that this update would make trouble, but I gave every user the possibility to maintain his old bookmarks. I would be glad, of you give "FOSS Browser" a second chance.

Thanks you all for using my app.

**Comment by puppykickr** [comment]
Yes, we all are aware of the hint to save the bookmarks.

The thing of it is, it did not work, and no matter what was done all
bookmarks were erased.

Not to mention the complete deletion of whatever someone had set up as a
homepage.

This may not be such an issue for some, but for those on a time schedule it
is undesireable to have to completely reconfigure an entire browser, not to
mention the loss of any important information.

It is simple to tell someone that they should back up all there apps and
info all the time, but is is even easier for the user to just check off the
'ignore all updates' box.

Grant Ryan Swan
(puppykicker)

**Comment by puppykickr** [comment]
I feel that, although the last two updates have caused much stress and
strife, that I still owe you an apology if I sound arguementive,
unthankful, or disrespectful.

Your FOSS is a great browser.

I appreciate it, and all the hard work you must have put into it.

That being said, version 6.0 is the last version that is useable for me.

Grant Ryan Swan
(puppykicker)

**Comment by sibrat** [comment]
> I lost my bookmarks too.

i've managed to restore my bookmarks by backup app with data, removing new version and reinstalling 6.0 then restoring data only. But i never hit that "OK" in startup, so it may not work

**Comment by ildar** [comment]
xcuse me, why didn't you just write a little code to migrate bookmarks to
the new table? All devs do that if db layout changes...

**Comment by Ascrod** [comment]
After updating, I too have noticed that my bookmarks list is now empty. However, those bookmarks still appear in my suggestions list when typing into the URL bar.

I can eventually recover all my old bookmarks in this way, if I wish. But if there is an old one that I want to remove, there is no apparent way to do so.

**Comment by scoute-dich** [comment]
Again: sorry for the trouble. Here's a short explanation:

https://forum.xda-developers.com/android/apps-games/app-browser-t3500091/page29

As said, I'm not a learned developer. I just share what I'm doing.
