### ISSUE TITLE
Add Cookies support for download function

### ISSUE THREAD

**Issue by KennyLeung** [scoute-dich/browser#232]
Some download need login status, so hope to add cookies support in download function, In BrowserUtil.java donload method, add some code like below:

        DownloadManager.Request request = new DownloadManager.Request(Uri.parse(url));
        String filename = URLUtil.guessFileName(url, contentDisposition, mimeType); // Maybe unexpected filename.
+        CookieManager cookieManager = CookieManager.getInstance();
+        String cookie = cookieManager.getCookie(url);  
+        request.addRequestHeader("Cookie", cookie);

        request.allowScanningByMediaScanner();
        request.setVisibleInDownloadsUi(true);

**Comment by scoute-dich** [comment]
Ok. I'll do that. Thanks for reporting.
