### ISSUE TITLE
change startup page

### ISSUE THREAD

**Issue by himpierre** [scoute-dich/browser#233]
Hi Devs.

Thanks for making this browser. One question though. Where do i change the page the browser opens at startup? Can't find this setting. Using version 6.1.1.

thanks and cheers

**Comment by fe60** [comment]
Just set a bookmark and define it as favorite (hold the bookmark to get the entry related menu and use "Set as favorite".

https://github.com/scoute-dich/browser/issues/230#issuecomment-450858041

**Comment by scoute-dich** [comment]
With today's release you'll also be able to open the bookmark on start up. With the next update it will be also possible to set a blank page as favorite.

**Comment by QiangF** [comment]
This should be in the readme.

**Comment by scoute-dich** [comment]
I implemented it in the help dialog. Will be there with next update.
