### ISSUE TITLE
New interface 6.1 / 6.2 - if home page is set to list of bookmarks don't show preview thumbnails

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#239]
Reason for request:
I have a list of > 100 bookmarks which I sort with an unicode symbol as first letter (☆, ≣, ⓘ, €, ⚒ ...) for easy access. Since the list is sorted for displaying I have access to a lot of pages with fast scrolling through the list. Worked great up to version 6.0

Since (6.1, 6.1.1) 6.2:
On top of this list are only 2 images of 2 links, but they take up a third of my (small) screen in portrait mode. Huge waste of space! Please provide an option to deactivate the images on top of the list, both for the chronic and the bookmarks.
I just need the lines with text for access.

Just because every other stupid browser shows preview images, it doesn't mean they are always helpful. 

In addition: It's great to save the bookmarks in the database and to have the new ability to edit the links. But: please allow in the settings to export the bookmarks in addition to the database to the file as it was before (and maybe sort the links at the same time according to the name of the link). Can you please use the document api for saving? I would like to choose the folder. At the moment I copy the browser_backup directory manully to the new destination. It's only a minor annoyance, but it would speed things up :-)

I need this to synchronize my bookmarks over nextcloud / floccus addon with my windows pc.

Thanks

**Comment by tusch001** [comment]
Hi scoute-dich!

I'm also only a user, with even less (zero) experience in programming. I wish I would know more so I could help you with the browser. 

„I don't now how to export bookmarks“. 

Can you just use the way it was done in the previous versions up to version 6.0?
In the settings there was an option to export bookmarks as a text file (I don't know the English entry, in German it was under Einstellungen - Sicherung). The second last entry let you save your bookmarks. This entry is now gone since the bookmarks are saved in the database. It would for the moment be sufficient to have this entry back as an additional option for saving bookmarks. Just as it was done previously, only link name and address. No passwords. Maybe sorted alphabetically with the link name (My personal preference). 
I don't know if this sorting is done easily, the Via Browser (mark.via.gp) does it this way. Perhaps copy + paste the code?

Again: Thanks for doing the work. I couldn't do it myself.

**Comment by scoute-dich** [comment]
I can't use three old method, since I changed the database model for bookmarks, when I implemented bookmark filtering. I'll close this issue, since the original issue is solved. With next update you'll get even more space, when opening history, bookmarks, ...
