### ISSUE TITLE
Cant open URL

### ISSUE THREAD

**Issue by mhdev90** [scoute-dich/browser#246]
I cant open any URL

1. Open the Browser.
2. Tap the address bar
3. Type a URL e.g. github.com
4. Tap Enter

Result: The addres bar jump back to previous page.

**Comment by scoute-dich** [comment]
Works like a charm here. Do you have more informations?

**Comment by scoute-dich** [comment]
Feel free to reopen, if problem still exists on latest version.

**Comment by HJarausch** [comment]
I do have this problem since the last update (from Google Play)

**Comment by jr-darkblue** [comment]
This happens to me as well.
Installed from FDroid ver 7.2 on Android 7.1.1 with miui 11.0.2
I tried different different keyboards all produce the same result. 
Could you re open the issue?
