### ISSUE TITLE
On pages with long, scrolling collections of images, the UI will glitch. 

### ISSUE THREAD

**Issue by brainard52** [scoute-dich/browser#248]
I use this browser to read manga on mangadex.org because I can hide the URL bar. Some comics are vertical with many image segments. These behave as expected in Firefox and Chrome, but on this browser, the browser will frequently scroll unexpectedly quickly or jump up and down. The images flicker when this occurs. An example page can be found here: https://mangadex.org/chapter/527117 

Unusually, some are worse than others. I suspect it may have to do with the height of the image, but I do not have any evidence of this.

**Comment by scoute-dich** [comment]
I added hardware acceleration support and set rendering priority to high with the next update. I think that's nothing more I can do. If you have an additional clue fell free to reopen the issue or open a new one.
