### ISSUE TITLE
Use correct search text for Android Autofill API

### ISSUE THREAD

**Issue by 4e6963** [scoute-dich/browser#253]
Foss Browser seems to support the Android Autofill Framework. The Autofill pop-up shows up correctly but it does not pass the correct website url to the Autofill Framework. Instead it just sends the app package name: androidapp://de.baumann.browser.

It would be a great feature to support Autofill for Password managers like KeePass2Android or Bitwarden.

**Comment by scoute-dich** [comment]
Autofill works for me now. I use keepassDX from F-Droid as autofill app.

**Comment by 2zqa** [comment]
Not working for me either. Using Bitwarden version 2.11.3 (3653). It says that there are no items for de.baumann.browser". It does work in Firefox and Chrome.
