### ISSUE TITLE
Upgrade webview version ?

### ISSUE THREAD

**Issue by jpfox** [scoute-dich/browser#254]
FOSS Browser uses built-in webview to render page. Is there a solution to use a more recent version of renderer ?

I've tried to install ChromiumPublic.apk and ContentShell.apk published by Woolyss but FOSS Browser does not use them.
https://chromium.woolyss.com/download/#android

Do you think it would be possible ?

Thank you for your great job !

**Comment by scoute-dich** [comment]
You can upate your webview within the playstore. You can change the webview in the Android settings, if you have enabled "Developer options". In these options you can set the system webview to use. This will be the webview "FOSS Browser" uses.

**Comment by jpfox** [comment]
Thanks for your answer.
I know that is is possible with PlayStore but my phone has no google stuff (neither Chrome, nor Google Apps). So I can't upgrade webview this way.

**Comment by scoute-dich** [comment]
I also have no Google stuff. In on LineAgeOS Pie. The build in webview works like a charm. In F-Droid you can download YalpStore. With this app you can install default Google webview, of you want.

**Comment by jpfox** [comment]
Ok, I didn't know it was possible with Yalp without installing Google Chrome. Thanks !
