### ISSUE TITLE
Some favicons not shown in DuckDuckGo

### ISSUE THREAD

**Issue by Tobiplayer3** [scoute-dich/browser#262]
I've noticed that some favicons can't be displayed next to the search results when using DuckDuckGo. Every other browser seems to work except for this one. I can't really figure out what causes this but I'd say it has to do with compression.
Would be great if you can have a look at it even though it's just a minor problem.

**Comment by scoute-dich** [comment]
It seems to work on my side, except the advertisings on top and bottom of the search results.

**Comment by Tobiplayer3** [comment]
I just tested it again and it does seem to work now. Not sure what's going on but I'll just close this issue for now.
