### ISSUE TITLE
(how) Does backup/restore really work?

### ISSUE THREAD

**Issue by HJarausch** [scoute-dich/browser#263]
I have Fossbrowser installed on my smartphone as well as on my tablet.
Since I've lost my booksmark on my smartphone, I made a backup on my tablet via
Settings -> Backup -> backup database
I even checked Documents/browser_backup/databases/browser_bookmarks.db with an Sqlite browser - and it contained all my bookmarks.
Then, I've copied this file to my smartphone and tried to 
Settings -> Backup -> backup restore

But I couldn't see my booksmarks.
What am I missing?
I'm using version 6.3.2 on both devices.

Many thanks for a hint,
Helmut

**Comment by Tobiplayer3** [comment]
Never had an issue with backup/restore but I never used this feature across mulitple devices. Are you sure you copied the files in the exact same folder structure?

**Comment by HJarausch** [comment]
Yes! I even generated a new backup and copied the files of the other device into that folder.
It's sad, but without Export/Import of bookmarks, this browser cannot be my primary browser.
Helmut.

**Comment by scoute-dich** [comment]
I assume, that you give the write on storage permission? Perhaps first make a backup on the second device (without the bookmarks), and replace the backup of the backup of the first device.

**Comment by scoute-dich** [comment]
Since, I'm cleaning up issues, I'll close this. There were updates since opening this issue, so open a new issue, if this one still is there.
