### ISSUE TITLE
french

### ISSUE THREAD

**Issue by franco27** [scoute-dich/browser#264]
on Github I don't know how to translate your application into French. 
 
Can you explain how to do the translation? 

Which file should be translated? 
 
On Windows I have already done French translations for software. and some Android applications too, but never through Github. 
 
Until now I have been sent a file for translation, or asked to go to a translation platform. 
 
Thank you for your answer. 

I went through the project files and saw at app/src/main/res that there are translations in several languages.  I saw a French translation started but far from finished. 
 
I would like to start from scratch the French translation and not continue it.  I'm waiting for your message.

**Comment by scoute-dich** [comment]
Sorry for the late response. You can simply translate the following files from the "values directory" (they are in English):

- values/strings
- values/strings_dialogs

Then you can zip them and attach it here. Then I'll copy them into the "values-fr-rfR" directory. If there are further questions, fell free to ask.

**Comment by franco27** [comment]
thank you for your answer even late. 
 
A few days ago, I started the French translation, and I will soon finish it. 
 
I would attach, here with a new message, these files translated into French.

**Comment by franco27** [comment]
the French translation is finished. 
[french.zip](https://github.com/scoute-dich/browser/files/3138394/french.zip)

**Comment by scoute-dich** [comment]
Many thanks! I'll merge out before the next update.

**Comment by scoute-dich** [comment]
I have some new strings to translate. I just added them today. If you have the time please translate them. Just make a commet here. Thanks in advance.



    <string name="setting_title_themeColor">Color UI</string>
    <string name="setting_summary_themeColor">Tint some elements from the UI to match the website colors,</string>
    <string name="setting_title_theme">Theme</string>

    <string name="setting_summary_toolbarShow">Pressing back will make the toolbar visible, before going back in history.</string>
    <string name="setting_title_toolbarShow">First toolbar</string>

**Comment by franco27** [comment]
hello , here is the French translation

> <string name="setting_title_themeColor">Couleur de l'interface</string>
> <string name="setting_summary_themeColor">Faire correspondre l'interface avec les couleurs du site Web,</string>
> <string name="setting_title_theme">Thème</string>
> 
> <string name="setting_summary_toolbarShow">Cliquer sur Retour pour rendre la barre d'outils visible, avant de revenir en arrière dans l'historique.</string>
> <string name="setting_title_toolbarShow">Première barre d'outils</string>
