### ISSUE TITLE
Problems with long, scrolling lists inside the bottom drawer

### ISSUE THREAD

**Issue by uli-on** [scoute-dich/browser#265]
FOSS Browser v6.2
Android 6.0.1
Moto G4

When the list of bookmarks is long enough to cause scrolling I have difficulties to tap the topmost ones of the list, they're hidden below the section for preview icons and that way I can have only six bookmarks at my disposal. When I draw the list down, trying to make it scroll, the whole drawer is moved downward, no scrolling inside the bookmarks list.

The same behaviour I have inside the list of colours for  bookmarks. Here, though, I've found a workaround to make it scroll: Tap and hold a colour until it becomes highlighted, then move the finger off of that item: The scrollbar becomes visible and I can scroll to the topmost, the red one. That workaround is hardly to apply to the list of bookmarks as there another dialog pops up whenever I tap+hold a bookmark.

**Comment by uli-on** [comment]
Steps to reproduce:

Open the bookmarks drawer with enough of them to have a scrolling list.
Tap the bottom-most bookmark. (Website opens)
Tap the Back button.
Open the bottom drawer with its list of bookmarks coming up.
Leave FOSS Browser by tapping the Home button, with the drawer still open.
(Do something else on your phone.)
Open FOSS Browser up again.
In case you see a scroll bar (not always): wait until it's vanished.
Try to scroll: No scrolling here, drawer closes instead.

These are the circumstances it happens *most of the time*, unfortunately *not always*, so you'll have to do these steps some times again in order to reproduce.

**Comment by scoute-dich** [comment]
Will be improved with next update. See #277.
