### ISSUE TITLE
Browser doesnt want to go back one page when opened after an app switch

### ISSUE THREAD

**Issue by cyagon** [scoute-dich/browser#266]
App Version: 6.3.2/GooglePlay 
Phone: Oneplus 3
OS: LineageOS 16 (Android Pie) / 20.03.19

Video: https://streamable.com/cj9c3

Logcat: [logcat.txt](https://github.com/scoute-dich/browser/files/2999371/logcat.txt)

**Comment by scoute-dich** [comment]
Thanks for reporting. I can reproduce it and I'll look into it.

**Comment by scoute-dich** [comment]
Seems to be solved with next update. If not please reopen this issue or create a new one.
