### ISSUE TITLE
Feedback after latest F-Droid Update

### ISSUE THREAD

**Issue by tonisnark** [scoute-dich/browser#267]
Latest upgrade makes it impossible, or, at the least, very unclear, to get rid of StartPage on new tabs. Also, those who upgraded from previous versions saw all their data get wiped unexpectedly (including bookmarks). And that's unacceptable even for a free app. Thankfully I found IceCat.

**Comment by scoute-dich** [comment]
Yes that was my mistake. I'm sorry for that. I'm doing all this in my spare free time and I'm not a learned developer. Perhaps you can give FOSS Browser a second chance?
