### ISSUE TITLE
Pinch in/out to zoom in/out

### ISSUE THREAD

**Issue by HarryHeights** [scoute-dich/browser#271]
I tried pinching out to zoom a webpage. It didn't work. I don't think it is a bug related issue. Probably the feature isn't implemented. It would be great if I'm able to pinch in or out to zoom a page. Thanks.

**Comment by alexspurling** [comment]
Zooming is not always possible on all websites. Can you give the name of the sites that you tried to zoom on so we can see if this is an issue that affects all sites or just some?

**Comment by scoute-dich** [comment]
Zooming is enabled by default for all websites. Some websites don't allow zooming. Specially if they are optimized for mobile view. So I can't do anything.
