### ISSUE TITLE
[Feature Request] Sessions

### ISSUE THREAD

**Issue by baltitenger** [scoute-dich/browser#274]
In my mind, sessions would be like anything else added to the home, except if you open the session and go somewhere else on the site, the home entry would get updated automatically (maybe only while you're still on the same domain). This would be really useful for forums and such. In other browsers, this could only be achieved by leaving that tab open.

**Comment by ildar** [comment]
Looks dup of https://github.com/scoute-dich/browser/issues/75

**Comment by scoute-dich** [comment]
Still on my big todo list. Still no idea how to implement. Perhaps dynamic shortcuts (only Android 7+) or just set the history as the default content of the overview. Then you could open every last visited websites very fast... Discussion please on #75 .
