### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by Flashwalker** [scoute-dich/browser#275]
This is really inconvenient now, when the list of tabs is on top over overview or bookmarks, and it starts from the bottom panel. Dude, this is an uncomfortable stretch with a finger from the bottom up each time.

And it was convenient to close tabs by swipe up/down. why you removed it?

And changing url for new tab has a little bit tricky way.

And how to wipe search history?

And how can I disable media autoplay?

**Comment by scoute-dich** [comment]
- Will be improved with next update
- With next update you can close tabs by long pressing.
- I don't understand.
- In the history menu (the three dots).
- You can't disable. I don't know a method to implement.

And overall you can ask in a more friendly way. I'm doing this for free in my free time. I also have a real job and family.

**Comment by Flashwalker** [comment]
Okay. I understand all these social moments, so, very friendly mode ON: 😇
Thank’s very much for your answers, i‘m very appreciate your efforts. Your app is so cool.
Have a nice day. Greetings to wife an kids.
