### ISSUE TITLE
[Improvement] Larger button for closing tabs

### ISSUE THREAD

**Issue by dkmgfk** [scoute-dich/browser#278]
The browser is really dependable, however it would be nicer if the tab closing buttons are a little bit larger, or even better, incorporate some sort of gesture to close them.

**Comment by scoute-dich** [comment]
With today's release, you van close a tab by long pressing the preview. Swept gestures aren't possible, because they interrupt with the scroll view and the bootomsheet dialog. Please read also the new help dialog (after the update) to get more information. Thanks for contributing!

**Comment by dkmgfk** [comment]
> With today's release, you can close a tab by long pressing the preview. Swipe gestures aren't possible, because they interrupt with the scroll view and the bootomsheet dialog. Please read also the new help dialog (after the update) to get more information. Thanks for contributing!

Thank you so much for the speedy reply! Never expect for a reply in a few weeks since this is a hobby project. And of course the app itself is simple and reliable.

However I downloaded it from F-droid, haven't received an update as of now. Maybe wait a few days can help.

Regards

**Comment by dkmgfk** [comment]
![Screenshot_20190608-113138](https://user-images.githubusercontent.com/47562939/59141560-c6f36e80-89e1-11e9-97d5-386403ad7841.png)
Hi!
In my opinion the bottomsheet dialog duplicates the buttons located below the thumbnails. Long-pressing to close a tab is still too slow for someone like me who opens numerous tabs at once. It would be great if one can simply swipe up the thumbnail to close the tab.

**Comment by dkmgfk** [comment]
![Screenshot_20190616-234253_1](https://user-images.githubusercontent.com/47562939/59566288-a174fd80-9090-11e9-99e5-c3a4fca675d7.png)
Maybe this could be a good idea, without conflicting with tab moving function.

**Comment by scoute-dich** [comment]
Long pressing to close a tab is now working. I'll close this issue. If there are further suggestions please reopen or create a new issue. Thanks for contributing.
