### ISSUE TITLE
Crashes when editing address

### ISSUE THREAD

**Issue by dkmgfk** [scoute-dich/browser#279]
Procedure to reproduce
When you are visiting a site like https://en.wikipedia.org/wiki/User:xxx and having the browsing history of numerous other pages on the same site stored in memory, eg. https://en.wikipedia.org/wiki/Berlin https://en.wikipedia.org/wiki/London etc

Directly editing the address in the tool bar will result in, first the browser attempts to show relevant histories, then after deleting a few characters at the end of the address, the browser crashes.

There are a lot of other circumstances can cause it crash, but I've forgot them at the moment.

Also it would be nice to have the option of custom User Agent string settings.

**Comment by scoute-dich** [comment]
I can't reproduce this. Since I made a lot of changes since the last update, it's possible, that the issue doesn't exist anymore. I released an update today. Can you please report back (in a few days), of the issue is still there?

**Comment by tusch001** [comment]
I can add some other information to it:

I use multiling keyboard and have behind some keys some webaddresses (something like "kasserver.com" when long pressing (touching) the k-key). 
Not always but more than 50% of the time, especially when I put that address in after having changed the focus of the app or I start the app fresh the browser crashes. I think it has something to do with the search in chronic / or my long list of bookmarks. I have a "feeling" that the input is to fast for the search. 

Also I can report that the behaviour described by dkmgfk is not new and has been around for a while. I just thought it was me using the keyboard app. This keyboard app has never shown any problems in any other application with putting in long words with one key.

**Comment by scoute-dich** [comment]
I made some changes concerning the keyboard handling. Is this solved?

**Comment by tusch001** [comment]
At the moment I can't say. For me that happened when I had all those bookmarks in versions ≤ 6.0. With the update to 6.1 / 6.2 they weren't transfered. Is there a way to get them into the database of 6.6? I still have the plain html list.
In version 6.4 (without all the bookmarks) I very very rarely had a sudden closure most times when switching apps and coming back and only when using the input described as above.

**Comment by scoute-dich** [comment]
You can test attached apk file and report back, if the issue still persists. Just rename the file.
[app-debug.zip](https://github.com/scoute-dich/browser/files/3827187/app-debug.zip)

**Comment by Sooyca** [comment]
On my phone I can reproduce this issue (so far with 100% effectivness) by opening the browser and typing "www" then deleting it for four times sufficiently fast.

**Comment by tusch001** [comment]
kasserver.com

**Comment by tusch001** [comment]
Follow up on my two previous posts: Now my list of bookmarks and history has grown again, the behaviour is still present in the debug app. Some inputs end in the browser crashing. Especially when the input contains words / letters that are part of previous inputs or bookmarks. What is different (since I guess version 6.6) that sometimes the field would not accept the new input after Enter and just display the last input and show the old page. These I repeat 1 or 2 times until the browser predictably crashes.

This behaviour is not very often and I can't say what's triggers it. But it's often enough that it is noticable.

**Comment by scoute-dich** [comment]
Can this issue be closed?
