### ISSUE TITLE
[feature request] optionally choose download manager in settings and / or storage location of downloaded files

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#282]
Hi scoute-dich!

I don't know if it's easily implemented. I hate androids download manager. Not only because of the crappy interface but also because it won't let you open some file types (apks for example). Since the user has no possibility to change the default download manager in the OS maybe the browser could change the default app with which to open the download links. Via browser does that (mark.via.gp). At least it lets you switch to ADM Downloader if it is installed. I personally would love to have ES Downloader as well as an option. I still use a very old version of ES file explorer for all my file operations anyway (version 3.2.5.5, before the app was sold to spying china). But ES downloader works only in some apps - don't know why.

Or as an alternative: 
Ask the user in settings where to store the downloaded files. Maybe use android SAF for choosing the location so that external SD is supported. And then let the download manager save the file there. When it's done ask the user if he want's to open that location with his default file manager.

I know this great browser is just a hobby project, so no pressure. Just a humble suggestion.

Thanks

**Comment by scoute-dich** [comment]
As I've no time to think about this in the near future I'll close this issue. It would be a nice feature, but at the moment there are other things more important.
