### ISSUE TITLE
Belongs to issue #280 - don't know how to reopen it

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#288]
Hi
I found another menu where the ok button is hidden:

The menu which is roughly translated "The certificate of this page is not safe, do you want to continue anyway?" (I put in a wrong webaddress - theguardian.de)

**Comment by scoute-dich** [comment]
Thanks. The problem is that the used method is used in different files. Seems that I've to search for it in all java files. If you find more dialogs, just report.

**Comment by tusch001** [comment]
Hi scoute-dich!
Here is another dialog with hidden buttons:
When reloading a page that has reviously transmitted data (e.g. in a form).:
Question: Do you want to resend your data?
--> Buttons are below the screen.

Thanks Patricia

**Comment by scoute-dich** [comment]
Thanks. Fixed both.
