### ISSUE TITLE
Backup/Restore Fails

### ISSUE THREAD

**Issue by tclaybor** [scoute-dich/browser#29]
GENERAL INFO
————————————————————————————
Galaxy Note 4 SM-N910A Android 6.0.1 API 23
Browser v3.8.1 DL'ed @ XDA, README (master)
————————————————————————————
TROUBLESHOOTING/EXTRA INFO
————————————————————————————
Storage & Location permissions both ALLOWED
App is not password protected
Cache preserved on exit, offline pages enabled
ReadList has items
Bookmarks List has items
No home screen shortcuts
No PassStorage items, but option enabled
————————————————————————————
Hi,

Love this app, but I had an issue backing up my lists. I get an error after clicking that says "Backup failed" or "Restore failed". I'm not sure if this is a new bug introduced with v3.8.x, as it worked fine in earlier versions. Let me know if you need any other info, or want help in testing. I'm happy to assist you in any way I can. Us FOSS Devs have to stick together, right? :-)

P.S. I have verified that the bug is not related to the information I'm about to share, but I have "Disabled" the "Android System Webview" app on my OS. The app still seems to work fine though. Can you comment on how this is possible? And if this might affect the app's performance or not?

Thanks again for being awesome!

- Tom

**Comment by tclaybor** [comment]
Also, issue #27, Crash, by @shailandraRajput

Was closed prematurely. If you could re-open it (assuming the OP doesn't) or just take a look, I have verified the bug is replicable.

**Comment by tclaybor** [comment]
@scoute-dich Fixed this issue by removing this app from the "Optimize battery usage" list. Not sure why it was affected, but everything works fine now. Closing issue.

**Comment by scoute-dich** [comment]
That's strange. I'll have an eye on it. When this will happen again, please reopen the issue.
