### ISSUE TITLE
Crash while taking screenshot with storage permission disabled

### ISSUE THREAD

**Issue by Ascrod** [scoute-dich/browser#290]
Steps to reproduce:
1) Disable the "Storage" permission for the app
1) Navigate to https://www.example.com
2) Open the save menu and select Screenshot

Expected behavior:
A toast appears, explaining that the app does not have "storage" permission.

Actual behavior:
App crashes to home screen. The issue appears to be related to trying to show the toast on a separate thread.

**Comment by scoute-dich** [comment]
This should be fixed with last updates. If not, please reopen the issue.
