### ISSUE TITLE
Bug: Address Bar not updated after clicking link

### ISSUE THREAD

**Issue by orwell96** [scoute-dich/browser#292]
System: Samsung, Android 7.7.1

Sometimes when a site is opened by means of clicking a link, the address bar does not show the new page title. Clicking on the address bar does display the URL, but it disappears once you close the keyboard. The address bar is always black when this happens.

When this happens, clicking the "back" button asks whether to close the tab/the browser, as if there was no previous page.

The effects disappear once you open the tab selector and click on the current tab again.
![20190712_135233](https://user-images.githubusercontent.com/13201701/61126300-5e9a2000-a4ac-11e9-88ad-8635725a202f.jpg)
![20190712_135250](https://user-images.githubusercontent.com/13201701/61126313-64900100-a4ac-11e9-9316-1d36f27cece2.jpg)

This appears to be particularily related to submitting HTML forms. So far, it occured every time I created a new issue or edited an issue on GitHub.

**Comment by scoute-dich** [comment]
You can test attached apk file and report back, if the issue still persists. Just rename the file.
[app-debug.zip](https://github.com/scoute-dich/browser/files/3827188/app-debug.zip)

**Comment by orwell96** [comment]
The problem did not reappear so far. Thanks for fixing!
