### ISSUE TITLE
Feature Request: allow to download images

### ISSUE THREAD

**Issue by orwell96** [scoute-dich/browser#294]
Currently, it is impossible to download an image and save it to local storage once it is opened in the browser

**Comment by scoute-dich** [comment]
Long press on the image, choose "save as" and if the extension of the image isn't recognized change it to what you want.

**Comment by orwell96** [comment]
Oh, my fault. The long-press menu is clipped in landscape mode, I have to swipe up to view the full menu...
Thanks anyway

**Comment by scoute-dich** [comment]
@orwell96 Thirs will also be solved with the next update. All dialogs will be expanded, when opened in landscape mode.
