### ISSUE TITLE
Bug: Webview fails to display entire page.

### ISSUE THREAD

**Issue by jjcyr55** [scoute-dich/browser#295]
While browsing code on github the browser fails to display the entire page. Maybe after line 150-200 the screen blanks out. This is a new device.  Not sure if this is a webview bug or a foss bug. Note: So far I have only encountered this problem on github. Very nice browser otherwise. This is my first ever bug report, I hope I did it correctly.

**Comment by scoute-dich** [comment]
Have you a link to the corresponding Github site? Have you tried it with other browsers?

**Comment by Ascrod** [comment]
I think this may be a WebView issue. It manifests in other WebView-based browsers such as Privacy Browser, but not in browsers that use their own engines such as Fennec.

Here's an example where the page goes blank after about 80 LOC:
https://github.com/scoute-dich/browser/blob/master/app/src/main/java/de/baumann/browser/Activity/BrowserActivity.java

**Comment by jjcyr55** [comment]
I have tried several different github sites on foss browser, all with the
same result. I have been experimenting with several different browsers, as
I'm creating one myself, and most of them work fine on github. However,
many other browsers that utilize the same style tabs, or cardviews as tabs,
as foss browser does have the same effect; it cuts off at around 130 lines
or so, but it then allows you to scroll down to the bottom of the page
showing only a blank/white code container. Then when the bottom of the page
is reached and the container ends, for some strange reason it shows all the
standard privacy policy links and that sort of stuff at the bottom. Its
very strange.

**Comment by scoute-dich** [comment]
I'm going on vacation for two weeks (Rügen, Germany). No. Laptop, no coding. You'll here from me, when I'm back.

**Comment by scoute-dich** [comment]
Is this issue still from relevance. Try also to update your webview (via playstore). With latest webview installed it seems to work now.
