### ISSUE TITLE
Can't open site using ip address

### ISSUE THREAD

**Issue by QiangF** [scoute-dich/browser#296]
Browser seems by default add https to all site user typed in the url bar. I have a website that opens with http://ip_adress correctly in other browsers, but I can't open with this browser. Can it be configured not to change the user input, just use the url of what user typed?

**Comment by tusch001** [comment]
@developer
I can understand the need for connections with http and ip address, e.g. in local networks. For me personally one of the great features of this browser is the default secure setting with https for all inputs. If you make changes please give the user in settings the option to choose this as default (as it is now). Or maybe use https if http is not typed in explicitly.
Thanks for consideration.

**Comment by scoute-dich** [comment]
If you type "http://ip_adress" correctly with "http://" it should work. Have you tested it?

**Comment by tusch001** [comment]
@scoute-dich
I tried to test it in a clean setup (stock android 6, browser version 6.4 from fdroid, on my running android there were too many security measures active):

Local http:// works when typing "http://" directly in the field. Also when loading address from a bookmark:
![lokal_network](https://user-images.githubusercontent.com/46721195/62114665-6ed93a00-b2b7-11e9-8912-6184bd9d81cb.png)

I tried to test it with sites in the www, but this is very difficult. Most sites nowadays redirect you (correctly) to https.
In my list of bookmarks I found two very old ones that don't use a secure connection. I can grep their ip in the terminal with
ping -c 1 -W 1 palaeos.com | grep PING|cut -d "(" -f 2|cut -d ")" -f 1
(site palaeos.com/index.html delivered at time of testing 66.33.208.47).
But as soon as you type http://66.33.208.47/index.html I get an error from the server (Site Not Found). Other unsecure http sites are protected by cloudflare when asked for by ip address. This behaviour is also seen on my windows desktop with firefox.

So I don't think it's a webview related issue.

As far as I got with testing I would say the browser works as intended.

@QiangF:
Can you provide an ip address for further testing (if reachable over www)?
If you have javascript turned off please test again with enabled javascript. Other browsers often have javascript turned on by default. Maybe the site redirects you to https internally?Or maybe (if installed) your firewall / VPN blocks port 80 (needed for http) for unknown apps?

That are possible reasons I can think of why you can't display a page.
