### ISSUE TITLE
version 6.5 shows only blank page

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#299]
Hi scoute-dich,

there seems to be a problem with webview / displaying pages in the new release. I just upgraded from version 6.4 to 6.5. I thought that I could see the github page (still in cache somewhere? Not sure anymore) but couldn't open any other page. Just a white page. First I thought it was my firewall but after deinstalling orbot + firewall + reboot the problem still exists. 
Deinstalling app + reinstalling version 6.4 --> everything works as intended.
Deinstalling version 6.4 + reinstalling 6.5 --> same blank page. Even github startpage is white.

Not good :-(

Android 6.0.1 (Stock) + Android System Webview 75.0.3770.143

At the moment I don't have my other android devices with me. Will test tomorrow. 

Nevertheless I wish you a Good Night

Version 6.5
![version_6 5](https://user-images.githubusercontent.com/46721195/62334697-019cf300-b4c9-11e9-9d40-9a3ba08d4b63.png)

Version 6.4:
![version_6 4](https://user-images.githubusercontent.com/46721195/62334723-19747700-b4c9-11e9-9ba8-e10a3dae44c2.png)

**Comment by tusch001** [comment]
more information - problem is more related to address bar:
I installed 6.5 again (without reboot). I get the github page that was last open in 6.4 (still in cache?). I can click on the links and open pages all over github this way. Even oned that I haven't visited before. They are displayed correctly.

But:
If I tap in the address field and replace the github link with any other domain and type enter - nothing happens. The browser closes the keyboard and shows the old address highlighted in the bar. The displayed page is the same.

**Comment by scoute-dich** [comment]
Thanks for reporting this critical issue. I Already found a solution for the text input problem. The second thing (website not loading on start) is still not solved. But I'll yet to find a solution later today.

**Comment by scoute-dich** [comment]
I fixed it hopefully. If you want you can test the apk on [release site](https://github.com/scoute-dich/browser/releases/tag/v6.6). If there are still problems open, please report it again. I only have device running Android P, so I can't often test on older devices.

**Comment by scoute-dich** [comment]
Feel free to reopen, if there are further problems.

**Comment by tusch001** [comment]
While you closed the issue I was testing:
Confirm working on Stock Android 6.0.1 and Android 5.1.1 (CyanogenMod).

Tomorrow I have access to some of my family's other phones / tablets. But I think you found the error.
Thanks
