### ISSUE TITLE
Horizontal scrolling interpreted as gestures

### ISSUE THREAD

**Issue by rjc** [scoute-dich/browser#3]
Hi,
I prefer to use gestures for navigation but currently sideways scrolling (for pages wider than the screen) is interpreted as back/forward move as soon as I release the finger. This makes the horizontal scrolling unusable on pages with fixed width.

Regards,

rjc

**Comment by scoute-dich** [comment]
Yes, I know that. That is why I implemented navigation with the arrows. I think I can't do anything. But I will do some research on the weekend...

Thanks for using my app.

**Comment by scoute-dich** [comment]
Would it be a solution for you to disable the swipe navigation function in the "session settings"? I think that could be possible...

**Comment by rjc** [comment]
But I **do** want to use swipe navigation rather than arrows - that's why I reported the issue in the first place :^)

The problem is that both navigation **and** horizontal scrolling do not work together.

**Comment by scoute-dich** [comment]
On most sites with mobile layout it works. So perhaps I thought it would be a workaround to implement a "disable swipe" setting in the "session settings". Perhaps with a whitelist. The same way I did with JavaScript. 

Normally I don't use JavaScript, but some websites need or enabled...

**Comment by scoute-dich** [comment]
Since navigation and horizontal scrolling do not work together, I removed this option. Now navigating with arrows is default and can't be changed.

Sorry.
