### ISSUE TITLE
[Bug] Gitlab issue pages do not display properly

### ISSUE THREAD

**Issue by PapistPenguin** [scoute-dich/browser#308]
When I view issue pages on Gitlab, a sidebar is shown over the content and the comments do not show. This happens for a time on IceCatMobile. However, on that browser, it resolves in a few seconds. On FOSS Browser, however, it does not.

**Comment by scoute-dich** [comment]
Hi,
I found a solution that works for me: you must enable javascript and "Remote Content" for Gitlab. It seems that some of the content must be loaded from other servers, so enabling this options solves the problem for me. Please reopen this issue, if there are further problems.
