### ISSUE TITLE
App Icon (Question)

### ISSUE THREAD

**Issue by puppykickr** [scoute-dich/browser#309]
Not an issue, just a question.

I use two OS right now, 7.1.1 and 8.1.0

When I run the current version from F-Droid the app icon for the 8.1.0 is a green square with rounded corners with an earth in the center.

Using the same version of the app on my 7.1.1 the icon is the old grey square with sharp corners an an earth in the center.

I see that the app is available on the PlayStore, and the icon appears to be a green circle with an earth in the center.

I am just wondering why the icon is different when using the same version on two different OS, and if the new(?) green circle background icon will be added to the F-Droid version.

I do like the look of the green circle background.

**Comment by scoute-dich** [comment]
With Android 8, adaptive icons were introduced. They can change their shape, according to system or launcher settings. For Android versions < 8 their are fallback icons, which can't change the shape.
