### ISSUE TITLE
Refreshing Page after Removal of Pull-to-Refresh

### ISSUE THREAD

**Issue by tclaybor** [scoute-dich/browser#31]
This is not app-breaking, just a rough edge.

In v3.8.1 you removed the pull-down-to-reload gesture in order to fix a bug that resulted in the inability to scroll back up.

I fully support that fix and believe it should never be re-implemented. However, since the removal of that, there is no browser function to reload a page except for 

1. Changing session settings
2. Clicking the URL bar and then hitting enter/go (basically re-navigating to the same URL)
3. Using the history list

Is it possible to do one of the following to restore the refresh/reload functionality?
- Move the history button to the "Open" menu and place the reload button where it is currently
- Add a button or icon to the action menu
- Add a refresh action that becomes visible when the omnibar is in text entry mode (perhaps to the left of the text input field)

If the third option is preferred, perhaps you could have the reload button always be visible on the left of the omnibar. Just a thought.

**Comment by tclaybor** [comment]
OOPS! Just realized the "More" menu has an option! Sorry!

I'll leave it open just in case you like the above ideas, since having to tap 3 times is somewhat unusual for such a common action.

Sorry again for missing the ability in "More".

**Comment by scoute-dich** [comment]
I'll think about that also.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
I've thought about about it. Option one is implemented now.
