### ISSUE TITLE
Get previous versions

### ISSUE THREAD

**Issue by Flashwalker** [scoute-dich/browser#310]
There can i get previous versions .apk files? 
Current version functionality is broken some how. I want to downgrade.
But F-droid gives me broken packeges

**Comment by tusch001** [comment]
Here on github :-)
https://github.com/scoute-dich/browser/releases
Choose version (called app-debug.apk). They are the same as those on f-droid but are signed with different keys. You need to deinstall previous versions first.

**Comment by puppykickr** [comment]
@Flashwalker
Be sure to uninstall the new version before trying to install older versions.

**Comment by Flashwalker** [comment]
Okay
