### ISSUE TITLE
Cannot download APK file

### ISSUE THREAD

**Issue by PapistPenguin** [scoute-dich/browser#312]
I was sent a link to an APK file (example.com/app.apk). However, when I download it, it downloads as a txt file. Even after renaming it to app.apk, it does not work.

OnePlus 6
LineageOS 16
Android 9

**Comment by tusch001** [comment]
I have the same problem on two of my lineage 14 (android 7.1.2 - close to official lineage builds) devices with (only) apk files. 
(file e.g. https://eu.dl.twrp.me/twrpapp/me.twrp.twrpapk-26.apk)
On one of the two devices the download managers renames this file to me.txt. I can change the ending to apk and the file can be installed.

But: 
The same happens with the Jelly browser that comes with lineageOS. 
And: After installing the latest Android system webview and changing webview implementation in developers settings the download manager renames the file instead to me.zip.
Just tested it: This behaviour is seen in FOSS Browser versions 5.5, 6.2 and 6.6.1

When I install a lineage 7.1.2 resurrection remix build on this device the download works fine. 


The second lineage 14 device names the download file correctly but won't let me open the file. I have to move it to some other folder first.

On lineage16 (another device) I also have to move the file to another folder to open it.

On all other older non lineage devices I don't have any problem (stock android 5, 6 and 8).


So I think this behaviour might be a security restriction in lineage OS?
At least for me moving and renaming the apk file works.

**Comment by scoute-dich** [comment]
This should already work. If not, please provide a link to an apk-file to test. F-Droid website downloading and installing apks is working on my side.
