### ISSUE TITLE
'Set As Startpage' not working

### ISSUE THREAD

**Issue by puppykickr** [scoute-dich/browser#313]
As the newest version seems completely disfunctional, I downgraded to the previous one.

Although I can force the browser to work, the ability to set the desired start page is broken.

The pop up that says 'start page successfully set' gives me hope, that is quickly dashed to the ground and stomped on when I close the app and reopen it.

Android OS 7.1.1

**Comment by Avispa** [comment]
Had similar issue. I'm not related to the project but I guess it would help if you mention the version of *FOSS Browser* you use.

**Comment by scoute-dich** [comment]
This should already be solved. If not, or for any other issue not related to this, please open a new one.
