### ISSUE TITLE
Data is transferred, but settings are not

### ISSUE THREAD

**Issue by puppykickr** [scoute-dich/browser#314]
When going to other versions of the app and doing a data transfer, certain data is indeed transferred-  such as the homepage.

(I don't know about bookmarks, as I don't bother with them on this browser any longer.)

However, the actual settings of the browser are not transferred-  forcing the user to go through all of them again.

Android OS 7.1.1

**Comment by scoute-dich** [comment]
Settings can now be backed up and restored. If there are further problems concerning backups, please open a new issue.
