### ISSUE TITLE
Too Many Settings Require App Restart

### ISSUE THREAD

**Issue by puppykickr** [scoute-dich/browser#315]
It seems that the majority of the settings that I wish to vary from default require an app restart.

This is understandable, except the app asks for these restarts after.  Every.  Single.  One.

It would seem to be better if all of these could be concentrated into a single restart upon the closure of the settings if it is required.

I do realize that I can cancel each popup as it is asked and continue on with my settings until finished, and then do a single restart.

But to constantly be interrupted with repeated popups while resetting the settings is a bother.

Android OS 7.1.1

**Comment by scoute-dich** [comment]
This should be also solved in actual version.
