### ISSUE TITLE
Browser complains about its own "about:blank" page not using SSL

### ISSUE THREAD

**Issue by Avispa** [scoute-dich/browser#316]
*FOSS Browser* v6.6.1 installed from *F-Droid* running on *Android* 8.0.0 complains about no SSL connection on own `about:blank` when set as start page:
```
This website uses an unsecured connection ("http"). Do you want to try a secure connection ("https")?
```

**Comment by scoute-dich** [comment]
Because this is no secure connection. So I think this is ok.
