### ISSUE TITLE
6.7: not able to import settings from 6.6.1

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#318]
Hi scoute-dich,

I couldn't import my previous saved settings from version 6.6.1 in 6.7. I went back to 6.6.1 --> no problem.
(no overview entries, no bookmarks)
OS: Lineage 16, browser 6.7

Logcat says: java.io.FileNotFoundException: /storage/emulated/0/Documents/browser_backup/data (No such file or directory) - which was never created with export:
![Screenshot_Documents_browser_backup](https://user-images.githubusercontent.com/46721195/64950533-e10fd900-d87b-11e9-8b1b-6f6de14f7d8b.png)

Full Logcat:

09-16 11:59:14.436   402   402 I chatty  : uid=1000(system) /vendor/bin/hw/android.hardware.power@1.1-service-qti identical 4 lines
09-16 11:59:14.680   313  2308 D SurfaceFlinger: duplicate layer name: changing de.baumann.browser/de.baumann.browser.Activity.Settings_DataActivity to de.baumann.browser/de.baumann.browser.Activity.Settings_DataActivity#1
09-16 11:59:14.692  9146  9237 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
09-16 11:59:14.693  9146  9237 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
09-16 11:59:15.774   402   402 I chatty  : uid=1000(system) /vendor/bin/hw/android.hardware.power@1.1-service-qti identical 2 lines
09-16 11:59:15.867  9146  9237 D OpenGLRenderer: endAllActiveAnimators on 0x90f62500 (RippleDrawable) with handle 0x89fbabe0
09-16 11:59:15.930  9146  9146 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Documents/browser_backup/data (No such file or directory)
09-16 11:59:15.930  9146  9146 W System.err: 	at java.io.FileInputStream.open0(Native Method)
09-16 11:59:15.930  9146  9146 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:231)
09-16 11:59:15.931  9146  9146 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:165)
09-16 11:59:15.931  9146  9146 W System.err: 	at de.baumann.browser.Fragment.Fragment_settings_data.copyDirectory(Fragment_settings_data.java:539)
09-16 11:59:15.931  9146  9146 W System.err: 	at de.baumann.browser.Fragment.Fragment_settings_data.access$200(Fragment_settings_data.java:53)
09-16 11:59:15.931  9146  9146 W System.err: 	at de.baumann.browser.Fragment.Fragment_settings_data$15.onClick(Fragment_settings_data.java:451)
09-16 11:59:15.931  9146  9146 W System.err: 	at android.view.View.performClick(View.java:6597)
09-16 11:59:15.931  9146  9146 W System.err: 	at android.view.View.performClickInternal(View.java:6574)
09-16 11:59:15.931  9146  9146 W System.err: 	at android.view.View.access$3100(View.java:778)
09-16 11:59:15.931  9146  9146 W System.err: 	at android.view.View$PerformClick.run(View.java:25885)
09-16 11:59:15.931  9146  9146 W System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
09-16 11:59:15.931  9146  9146 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-16 11:59:15.932  9146  9146 W System.err: 	at android.os.Looper.loop(Looper.java:193)
09-16 11:59:15.932  9146  9146 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
09-16 11:59:15.932  9146  9146 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 11:59:15.932  9146  9146 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-16 11:59:15.932  9146  9146 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-16 11:59:16.052   313  2308 W SurfaceFlinger: Attempting to set client state on removed layer: de.baumann.browser/de.baumann.browser.Activity.Settings_DataActivity#1
09-16 11:59:16.052   313  2308 W SurfaceFlinger: Attempting to destroy on removed layer: de.baumann.browser/de.baumann.browser.Activity.Settings_DataActivity#1
09-16 11:59:16.077   313  9549 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=1758#0
09-16 11:59:16.077   313  9549 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=1758#0

**Comment by scoute-dich** [comment]
Is it possible to upgrade to 6.7 (without loosing data) and then making a backup, changing some settings or bookmarks and then restore the backup?

**Comment by J44B** [comment]
After backing up data and reinstalling this browser (because of new ROM) I couldn't import anything either. Initially I had no "Documents" folder on my storage. So I created one, copied the data there, but importing just returned something like "import count: 0".

I then deleted the "Documents" folder, since it contained nothing but my copied data. I did an export of just the bookmarks of this virgin installation. It created a new "Documents" folder with the "browser data" folder in it. I deleted this subfolder, copied my previous one there instead and voilà - the import was successful.

**Comment by tusch001** [comment]
@scoute-dich
Yes it is (now). At the time of writing I was on f-droid version 6.6.1 with no update available there. So I deinstalled it for github-version 6.7. This should not be relevant for most users since they just update from whatever source they are using. I can confirm that direct updates are working.

Since you changed quite a lot with the backups in the future there should not be such a problem any more.

Thanks for all the work.

@J44B:
Now I know to keep install app version 6.6.1 with my then backup of bookmarks for my other devices and upgrade from there I think this has resolved. But thanks for the tipp. (I was playing around with an SQlite editor to get my bookmarks and was not yet there :-)

**Comment by scoute-dich** [comment]
Settings can now be backed up and restored. If there are further problems concerning backups, please open a new issue.
