### ISSUE TITLE
Opening Links in Browser from Other Apps

### ISSUE THREAD

**Issue by tclaybor** [scoute-dich/browser#32]
Currently in v3.8.1, clicking a link in another app creates a notification to open list, add to read later, or open in browser (via clicking notification).

Could you change the default behaviour or add an option in settings to let us open the link without going through the notification? Not sure if this is a limitation in WebView or something, but sometimes I click a link 3-4 times because I don't realize the notification appeared. I always expect my default browser to open when clicking a link.

If you don't want to do this, that's cool. It won't keep me from using Browser as my default :)

**Comment by scoute-dich** [comment]
I'll think about it.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
So productive today. This is also implemented now. ;-)
