### ISSUE TITLE
after file download navigation bar doesn't accept input, restarts download

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#320]
This has been around for a while, still in 6.7.

Steps to reproduce:
- open a page where you can download files, eg apkmirror.com
- download file (I downloaded an apk) & confirm
- I always cancel when I'm asked to open download manager
- type something into navigation bar to search (eg "google playstore app" + Enter)

--> instead of opening search page the browser asks if you want to download the file (again)

OS: independent (Android 6 Stock, Lineage 14 + 16)

**Comment by scoute-dich** [comment]
please test attached apk (just rename) and report if issue still persists.
[app-debug.zip](https://github.com/scoute-dich/browser/files/3827162/app-debug.zip)

**Comment by tusch001** [comment]
Sorry, was offline for several days. 
At the moment I could just test it with my mobile on Stock Android 6.01. Odd behaviour is still present.

I later have access to my other devices and test there.

Does it relate to the sometimes incongruent reaction of the input of the navigation bar?

**Comment by scoute-dich** [comment]
I can proof the navigation bar. Indeed I'm on Android 10 in the meantime and using gestures instead.

**Comment by tusch001** [comment]
gone in version 7.1
