### ISSUE TITLE
Remove device model and build number from user agent string

### ISSUE THREAD

**Issue by articlecat** [scoute-dich/browser#321]
FOSS Browser currently includes the device model and build number after the Android version in the user agent string. This information does not help sites serve web pages, and reveals an unnecessary amount of detail that could be used to track the user.

It would be great if FOSS Browser removed the device model and build number from its user agent string.

**Comment by scoute-dich** [comment]
Any hint, what the useragent string should look like?

**Comment by scoute-dich** [comment]
Will be removed in next update.

**Comment by articlecat** [comment]
Thank you!

Here is what the user agent string for the current version (6.7) of FOSS Browser looks like:
```
Mozilla/[Mozilla version] (Linux; Android [Android version]; [device name] Build/[build number]; wv) AppleWebKit/[Webkit version] (KHTML, like Gecko) Version/[version] Chrome/[Chrome version] Mobile Safari/[Safari version]
```

A simplified user agent string could look like this:
```
Mozilla/[Mozilla version] (Linux; Android [Android version]) AppleWebKit/[WebKit version] (KHTML; like Gecko) Chrome/[Chrome version] Mobile Safari/[Safari version]
```

**Comment by scoute-dich** [comment]
Since there are problems changing the useragent, I'll revert the custom useragent again for next update. But I'm thinking of setting a custom useragent in the settings. Perhaps I'll implement this "between the years".

**Comment by scoute-dich** [comment]
So I implemented custom user agent in the settings. It will be available with next update.
