### ISSUE TITLE
belongs to issue #280

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#322]
Hi scoute-dich,

I found another confirmation dialog with hidden buttons in landscape mode:

settings - search engines - add your own - the buttons below the input field are hidden.

When you are at it: 
The German translation for the field label of the input field for the search engine is "Titel" which suggest a name eg "Google" but the app needs a link eg "google.com". Maybe it's just in German but you might want to check the English template just in case.

Thanks.

ps: Although the fdroid description says that the browser is intended for one handed use on mobile phones I want to let you know that a 10 inch tablet in landscape mode is also very suitable for this app!

**Comment by scoute-dich** [comment]
Thanks for reporting. Will be solved with next update.
