### ISSUE TITLE
GitHub today start show "unsupported browser" notification

### ISSUE THREAD

**Issue by Symbian9** [scoute-dich/browser#324]
![pic.1](https://i.imgur.com/b1MLOq9.png)

FOSS Brovser: `6.7` (F-Droid)

JavaScript: Enabled

Cookies: Enabled

> **NOTE:** In same time I has no such notification with *Privacy Browser* `3.2` (F-Droid)

**Comment by scoute-dich** [comment]
Be sure to use the latest system webview. Which OS are you running?

**Comment by Symbian9** [comment]
> Which OS are you running?

Android 5.1 (***Ido***)

**Comment by scoute-dich** [comment]
Since FOSS Browser is the system webview, I think it's a problem of outdated webview. I don't have this problems using webview version Version 74.0.3729.186.

**Comment by Symbian9** [comment]
Is it possible add into *FOSS Browser* built-in webview that would be independent from system webview?

Or make two builds of *FOSS Browser*:

1. without built-in webview (depend on system webview as it work now);
2. with built-in webview (independent of system webview).

**Comment by scoute-dich** [comment]
No. I want to keep FOSS Browser as small as possible. Whenever possible I'm trying to use system components (webview, download manager, print service, ...).

**Comment by scoute-dich** [comment]
You can try to update webview (via PlayStore).

**Comment by Symbian9** [comment]
> You can try to update webview (via PlayStore).

It's impossible, because I keep Play Store disabled (I'm aware of any auto-updates from Google) & my *device is un-rooted*.

How could I update it manually?

**Comment by scoute-dich** [comment]
You can try to download webview from apk-mirror or similar sites.

**Comment by Symbian9** [comment]
Okay, temporary solved by installing latest webview from APKMirror

- https://www.apkmirror.com/apk/google-inc/android-system-webview/
