### ISSUE TITLE
Can't set homepage. 

### ISSUE THREAD

**Issue by Fatcakes** [scoute-dich/browser#331]
Opens to the github.com page always. Why?

**Comment by scoute-dich** [comment]
Long pressing on a bookmark and save it as favorite doesn't work?

**Comment by Fatcakes** [comment]
Still opens the to the github page everytime.

**Comment by yuthstyle88** [comment]
Can I join yours project? I can help you .

**Comment by scoute-dich** [comment]
@yuthstyle88 You can fork my project and make pull requests. You're welcome to help.

**Comment by scoute-dich** [comment]
@yuthstyle88 You can test attached apk file and report back, if the issue still persists. Just rename the file.
[app-debug.zip](https://github.com/scoute-dich/browser/files/3825686/app-debug.zip)
