### ISSUE TITLE
Page loading hangs when requesting site with invalid(expired) SSL certificate

### ISSUE THREAD

**Issue by orwell96** [scoute-dich/browser#348]
Hi again,

I noticed that if you try to access a website via https that has an expired certificate, the following happens:
- when accessed by clicking a link, a progress bar appears for a split second, then disappears. Tab behaves as of the link was not clicked at all
- when accessed by input to address bar, the progress bar stops at ~1/10 the screen width, as if page is loading forever
- Upon doing any action (switching tabs, opening menu) the progress bar disappears again

What should happen instead:
- the user is presented with some sort of information that the secure connection failed, maybe with the option to use HTTP or add an exception

To reproduce:
use https://advtrains.de
Edit: cert is now updated

**Comment by scoute-dich** [comment]
Is this still relevant in the current version?

**Comment by scoute-dich** [comment]
Certificate issues are now handled with a prompt. If there are any problems feel free to open a new issue.
