### ISSUE TITLE
*not a bug* for our thumbs, a scroll down button would be a great addition

### ISSUE THREAD

**Issue by teacherphiljp** [scoute-dich/browser#35]
Its up to you if it should be two buttons which are permanent with perhaps a toggle in settings or if the button should only appear when the browser is looking at the top of the page, should you decide to adopt this suggestion. This is my first issue. I hope im posting my suggestion in the right place. great browser imho btw! Thanks. Repetitive motions are taking a toll on my thumb.

**Comment by teacherphiljp** [comment]
Just to clarify, when I say "Its up to you if it should be two buttons which are permanent with perhaps a toggle in settings or..." I am talking about the existing scroll up button plus adding a scroll down button

**Comment by teacherphiljp** [comment]
It just occured to me that there is already a back button in the best place for a scroll down button when the browser is viewing the top of a page, and it would probably be best if the scroll down button only appears after scrolling down a small amount (small distance) from the top. Thanks again.

**Comment by teacherphiljp** [comment]
It just occured to me that there is a Forward button in the best place for a scroll down button when the browser is viewing the top of a page, and it would probably be best if the scroll down button only appears after scrolling down a small amount (small distance) from the top. In that case, two scroll buttons (up and down) would probably be most useful. Thanks again.

**Comment by scoute-dich** [comment]
> This is my first issue. I hope im posting my suggestion in the right place.

Yes that's the right place. And thanks for suggesting. I also thought about a scroll-down-button sometimes. So if I'm not the only one, it will be implemented.

Or should I say: it's already implemented and will be there with next update. Thanks. We independed developers need the help (and making such suggestions is also a kind of help) of the community. That's the spirit of open source!

Regards
Gaukler Faun
![screenshot_20170809-092645](https://user-images.githubusercontent.com/3949944/29109867-eab02d6a-7ce4-11e7-9864-f0cf1ddd8853.png)
