### ISSUE TITLE
Open Blob URL Problem

### ISSUE THREAD

**Issue by wahono77** [scoute-dich/browser#350]
I try open website and click a url to open blob, but I got error message in debugging console:

W/cr_AwAutofillManager: WebView autofill is disabled because WebView isn't created with activity context.
I/ContentValues: Uri =blob:https://wahonobasic.acosyscloud.com/9320d2f4-760e-4e84-8184-e26548264ded

Any solution for this?

Thanks in advance

**Comment by scoute-dich** [comment]
I don't understand the problem. What do you mean with "blob"?
