### ISSUE TITLE
Cannot render http://map.project-osrm.org

### ISSUE THREAD

**Issue by HJarausch** [scoute-dich/browser#351]
The browser cannot render http://map.project-osrm.org.
It displays only some rubbish at the top of the screen. 
There is no problem with other browsers like Monument Browser or Opera on my PC. 
Thanks for looking into it, 
Helmut

**Comment by scoute-dich** [comment]
Hi,

is this issue still relevant? Because on my side there's no problem rendering the website. If yes, please reopen this issue.
