### ISSUE TITLE
Resuming app sometimes resets browsing session to homepage

### ISSUE THREAD

**Issue by wesinator** [scoute-dich/browser#353]
Android 9
Nokia TA-1044 (2GB RAM)

Sometimes when I leave switch out the app and back (without closing/clearing it), it doesn't re-open the page I had open, but instead resets the session to the homepage. This was with only two apps open, including FOSS browser.

**Expected:** always resume the page where left off.

**Comment by contrapunctus-1** [comment]
I have the same issue on a Nokia 6.1 (TA-1089), also running Android 9.

**Comment by scoute-dich** [comment]
I've released an update. The Play Store version is online. The F-Droid version not yet. You can also download the debug-apk on the release site. Can you please check if the issue is still there? I made a lot of changes.

**Comment by wesinator** [comment]
still experiencing in 6.8 

**p.s.** was the open links in background with notification feature removed ?

**Comment by scoute-dich** [comment]
@wesinator Yes, as it has a lot of bugs.

This is Android related. Android closes apps, if they are not used for a longer time. You can only exclude FOSS Browser from battery optimizations in the system settings.
