### ISSUE TITLE
Option to disable WebRTC

### ISSUE THREAD

**Issue by jvandenbroek** [scoute-dich/browser#361]
Would be nice if an option could be added to disable WebRTC for improved privacy. Great fast browser btw!

**Comment by scoute-dich** [comment]
Can you please test, if the attached apk (rename it) will solve the problem?
[app-debug.zip](https://github.com/scoute-dich/browser/files/4255104/app-debug.zip)

**Comment by jvandenbroek** [comment]
Unfortunately it doesn't, my local LAN IP and global IPv6 addresses (while using VPN) are still being leaked. You can test it here: https://browserleaks.com/webrtc

**Comment by scoute-dich** [comment]
I've a lot to do at work at the moment. Since I'm doing this in my free time, there's no time for implementing new features.

Also I found no solution for implementing this.
