### ISSUE TITLE
Traffic not going through proxy

### ISSUE THREAD

**Issue by domaci-duch** [scoute-dich/browser#362]
First of all thanks for your great app!
I noticed that FOSS browser ignores the proxy option in my mobile's WiFi setup.
Could it be made to (optionally?) follow that, please?

**Comment by brakcoinnn** [comment]
`
[LICENSE-GPL3.txt](https://github.com/scoute-dich/browser/files/4108476/LICENSE-GPL3.txt)

`

**Comment by scoute-dich** [comment]
Perhaps this happens because FOSS Browser uses the system webview. I'm developing this browser mainly for my own purposes and just sharing it to give something back to the FOSS community. Also I don't have much time (Work and family) and also not the knowledge to implement any proxy settings. So sorry.

**Comment by scoute-dich** [comment]
At the moment I'm looking into an other issue #361 . Perhaps disabling webRTC solves also your problem. But I can't guarantee.

**Comment by scoute-dich** [comment]
Can you please test, if the attached apk (rename it) will solve the problem?
[app-debug.zip](https://github.com/scoute-dich/browser/files/4255107/app-debug.zip)

**Comment by domaci-duch** [comment]
Thank you very much for your interest, much appreciated.
I did a couple of tests by trying to divert IP traffic to my PC; here are my results:
- www.whatismyipaddress.com (or equivalent) on FOSS Browser returns the VPN server's IP address my PC is connected to, so this shows that redirection is actually working
- however, my local privoxy page at http://p.p is not recognised, so it is passed to the search engine as a query. By comparison, Google Chrome can open this address.
Please let me know if have any other suggestions.
