### ISSUE TITLE
StartPage is still default search engine regardless of user setting

### ISSUE THREAD

**Issue by puppykickr** [scoute-dich/browser#363]
I gave the new version a try once again.

As expected, my personal settings were all erased and set to default when the app was updated.

No worries, this was expected, as it has always been this way.

But now I find that when the browser is opened via another app, Black Player for instance-  to do a lyrics search for a song (my main reason for having this app) I find that the results are given from StartPage.

I have Duck Duck Go specifically chosen as the default search engine in the settings.

As it is, I actually have 'Custom Search Engine' selected, and in the section for the custom search engine I have placed the https address for DuckDuckGo that will include all of my settings for that search engine (theme, post vs. get, suggestions, etc.)

This is how I always set up my custom search engines on any browser, and it works on all of them-  including Lightning, BeHe Explorer, Ume (the stock junk browser on my device), etc.

The custom DuckDuckGo address with my settings is:

https://duckduckgo.com/?k5=1&kg=p&kae=t&kau=-1&kao=-1&kap=-1&kaq=-1&kax=-1&kak=-1&kv=-1&kay=b&kam=osm&kaj=u&kk=-1&k1=-1&kn=1&kac=-1&kav=1&kp=-2

**Comment by sachafroment** [comment]
- ANDROID: 9.0
- VERSION: 6.8

I'm having this issue as well.
I set my custom search engine value to : https://search.disroot.org/?q= but when i try to search for something, it forces me to use startpage.

**Comment by scoute-dich** [comment]
Hi, I found the problem. This will be fixed in the next release (perhaps at the weekend). Please stay patient.
