### ISSUE TITLE
Dark Reader, NoScript, and friends

### ISSUE THREAD

**Issue by contrapunctus-1** [scoute-dich/browser#364]
I really like FOSS Browser - the bottom-bar-oriented UI is comfortable (unlike Fennec - and indeed most FOSS apps), it allows users to set custom search engines (unlike Firefox Lite), and I can place greater trust in it because it's available on F-Droid. (unlike Fenix/Firefox Preview)

Unfortunately, there are a few features I miss from Firefox, which affect everyday use for me -
1. Reader mode
2. [Dark Reader](https://darkreader.org/)
3. [NoScript](https://noscript.net/)
4. [I Don't Care About Cookies](https://www.i-dont-care-about-cookies.eu/)

Instead of implementing all of these in FOSS Browser, could it be possible to implement the WebExtension API so that these extensions can be installed in FOSS Browser?

**Comment by scoute-dich** [comment]
I don't want to add more features and I don't want to add any external libraries or apis. Also I don't have the abilities or resources to do that. So: no. Sorry.
