### ISSUE TITLE
Background Links Enhancements

### ISSUE THREAD

**Issue by cavemandaveman** [scoute-dich/browser#37]
Sometimes, when you're in another app and opening multiple links in the background, it's hard to tell if you actually clicked a link (after the first one), since there is only one notification in the status bar. A toast notification would ease my mind in knowing that I clicked the link and Browser registered it.

Also, since Marshmallow combines these notifications into one, if I click the notification when there are multiple background links, Browser will only open the last one. I'm not sure what the best approach here would be. Maybe if you click the notification, Browser can open each link in a different tab? But then you risk the chance of losing a link if you have more than 5. Or maybe remove the 5 tab restriction? Or maybe not group the notifications? I'm not sure, what do you think?

**Comment by tclaybor** [comment]
Just for more input on the matter, I would really like it to stay at 5 tab maximum. I honestly liked it most when it was only 2 tabs, but I won't complain about adding functionality to an app, period.

For now if I were you, I would click "Add to ReadList" after each link, but perhaps you could just have Browser open the link in the foreground (v4.0+).

@cavemandaveman Perform the steps you described above, and then long press the omnibar. Is the last link (the one that it opens) in the 4th tab or the 1st?

Just a friendly fan of this app, I say all of the above with a kind demeanour :-)

**Comment by tclaybor** [comment]
Are you on Stock MM? Also, is it a Samsung, Moto, Nexus, etc? Question is relevant due to OEM notification settings via SystemUI.

**Comment by scoute-dich** [comment]
"Add to read later" is dropped in latest release, because it was to buggy. The first received link gets overwritten by the second.

But you can expand the bundled notification, then you have all notifications sperated and can click one after the other. Of you click on the content of a bundled notification, only the last saved link will open and the notification will disappear. That's a Android "feature" and I can do nothing to prevent it.

But I will think about the toast.
![](http://i.imgur.com/pGTabr5.png)

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
And now I'm going to sleep. ;-)

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cavemandaveman** [comment]
@tclaybor I'm on a LineageOS based MM ROM and long clicking the omnibar shows the link on the 1st tab.

@scoute-dich True, I can expand the bundled notification, it's just that sometimes I forget and click the bundle and lose all my links haha. I guess I just need to get used to expanding.

Is there a way for an app to tell Android not to bundle notifications? For instance in K9, there are different notifications per email address, but each of those bundle mail notifications for that address. (I'm using K9 Material by the way, and it's awesome, so thank you for that as well!)

A toast would definitely help user experience though!

**Comment by scoute-dich** [comment]
I don't know of there is such an app. But you can search on PlayStore. Btw. K9 bundles all notifications for me (but I'm on Nougat). I will look at the notifications today.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
So, I implemented the toast and will close this issue. If there are new problems after the update, feel free to reopen this issue. Thanks also to you for your contribution.
