### ISSUE TITLE
Crashing when sharing or saving screenshot from the app

### ISSUE THREAD

**Issue by vanhamiel** [scoute-dich/browser#372]
The app crashes when trying to save or share a screenshot of the current page, even the blank homepage, using the app feature.
I'm running FOSS on a xperia x compact with Android 8.0, stock rom.
Thank you for your time.

**Comment by scoute-dich** [comment]
Permission to write on storage is granted?

**Comment by scoute-dich** [comment]
Since this is s buggy feature and the option to save websites as PDF for sharing and offline use, I'll remove this feature with next update.
