### ISSUE TITLE
how to change start page

### ISSUE THREAD

**Issue by MeAppDeveloper** [scoute-dich/browser#374]
how to remove github url on start, i want to use google.com on start...please solve this issue

**Comment by scoute-dich** [comment]
You can save every site you want. Just click the three dots in the menu and then "Save as favorite" (the one with the star).
![](https://i.imgur.com/3ZhH9bS.jpg)

**Comment by MeAppDeveloper** [comment]
I want to change from its source code...when it run webpage shows Google
search page... Thanks
