### ISSUE TITLE
(Feature request) add report bug button

### ISSUE THREAD

**Issue by vinhcomputer** [scoute-dich/browser#375]
Hi,
Firstly, thank you for the great browser.
Secondly, I wonder if you could add a button or something to make reporting problems when browsing websites easier. I was walking through websites and some of them have display problem on the browser. It's hard and cumbersome to report lots of small problems like that with full context information. 
If you could capture all debug information you want with that feature then I think lots of trivial problems will be reported easier and get fixed faster.

Thank you

**Comment by scoute-dich** [comment]
I've a lot to do at work at the moment. Since I'm doing this in my free time, there's no time for implementing new features.
