### ISSUE TITLE
Tabs are closed when app is swiped away.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [scoute-dich/browser#377]
If you swipe the app away, all tabs are deleted too (just the homepage open now)

- Expected behaviour:
To be able to resume browsing with tabs saved.

THANK YOU for this amazing app! The navigation is perfect design for a phone! Looking forward to 7.0!!

**Comment by eroldru** [comment]
I'd also love to have this feature. It's the only thing keeping me from using it as my main browser app. Other than that, the browser is perfect!

**Comment by 5c0tt-b0t** [comment]
> I'd also love to have this feature. It's the only thing keeping me from using it as my main browser app. Other than that, the browser is perfect!

Same here! Totally agree!!!

**Comment by scoute-dich** [comment]
At the moment I don't have much time, since I work as teacher in a school in Germany. Since we reopened schools since two months, there's a lot to organize. But perhaps later in the year.

**Comment by eroldru** [comment]
Absolutely no problem. Please take care and stay healthy. Thank you for such an amazing product.

**Comment by 5c0tt1** [comment]
Couldnt have said it better! Thank you for the app, navigation & design/ui is incredible, i really look forward to the day i can finally get rid of fennec f-droid! :grin:

**Comment by 5c0tt-b0t** [comment]
Hi, re-downloaded the app to check if this was fixed inbthe last 4 months since writing this, seems it hasnt, just here to check if this is something that will be implemented soon? As I see it, this browser only has one problem, and it is a major one, that stops me and hundreds of others, making this amazing app our default browser... `it is unable keep tabs open once swiped away` this basic feature has been available to browsers since Android 1.0 and is a major piece of basic functionality, without it, this app will never be a fully functional browser. I really hope this feature is a high priority, I think it should be.
Once again, I thank you for making this beautiful app! it has the potential to be the best Android browser ever, but this one small feature is stopping that from happening, everything else us amazing!

**Comment by scoute-dich** [comment]
I've a lot to do at work at the moment. Since I'm doing this in my free time, there's no time for implementing new features.
Also I think this is default behaviour of Android. If you swipe an app away, it'll get closed. If you don't swipe the app FOSS Browser resumes where you left it.
