### ISSUE TITLE
back/forward navigation in the main menu

### ISSUE THREAD

**Issue by DrSensor** [scoute-dich/browser#378]
implement back/forward navigation in the main menu (mainly for guys who disable the navigation button #366)

_Originally posted by @scoute-dich in https://github.com/scoute-dich/browser/issues/84#issuecomment-367827036_

**Comment by scoute-dich** [comment]
You can assign gestures to the toolbar to move back/forward. I don't want to integrate more features in future.

**Comment by cbiere** [comment]
I disabled the swipe gestures after noticing that it interferes with editing the address bar. So unless back/forward navigation is disabled when the address bar is active, I would appreciate some extra forward button in the popup menu. The space is certainly there.
