### ISSUE TITLE
Crash when set to open bookmark tab on startup

### ISSUE THREAD

**Issue by firecat53** [scoute-dich/browser#38]
- Install app
- Visit one site, save to bookmarks
- Change settings to show bookmark tab on startup

App will now immediately crash on startup until you clear app data from Android app info menu.

Thanks!

Edit: Version 4.1 installed from F-Droid 

Edit 2: same crash occurs when any of the tabs other than the default selected from the on-startup setting.

**Comment by scoute-dich** [comment]
Yes, I can confirm that. I will take a look today. I don't think that's a big thing. Thanks for reporting.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
This is fixed with next update (only a few lines of code).
