### ISSUE TITLE
Unable to use http basic authentication

### ISSUE THREAD

**Issue by firecat53** [scoute-dich/browser#39]
When going to a site using https basic/digest authentication, no method (pop-up) is provided for entering username or password.

Thanks!

**Comment by scoute-dich** [comment]
Can you provide me link where I can test it?

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by firecat53** [comment]
Emailed you privately.

**Comment by firecat53** [comment]
Also looks like it doesn't work with form-based basic authentication either.

**Comment by scoute-dich** [comment]
[app-debug.zip](https://github.com/scoute-dich/browser/files/1243303/app-debug.zip)

You can test attached apk file (Just rename to zip to apk). For me it works. When it doesn't I will look tomorrow. ;-)

**Comment by firecat53** [comment]
It worked! Nice job :)
