### ISSUE TITLE
History does not get cleared on exit

### ISSUE THREAD

**Issue by cao-** [scoute-dich/browser#4]
The "clear history on exit" option does not work.  In fact, if I reopen the browser after having exited it, the history is still present.  I exit the browser by clicking the back button and answering "ok" to the question "Do you want to exit?".

**Comment by scoute-dich** [comment]
Ok. I switched the database model and forgot to change the database name in the exit method. I will fix it.
Thanks for reporting.

**Comment by scoute-dich** [comment]
fixed.
