### ISSUE TITLE
how to change homepage 

### ISSUE THREAD

**Issue by MeAppDeveloper** [scoute-dich/browser#409]
how to change homepage github to google in source code, please help

**Comment by tusch001** [comment]
go to settings - first entry is favorite (or similiar translation) - enter https://www.google.com or your localized google version

**Comment by MeAppDeveloper** [comment]
> go to settings - first entry is favorite (or similiar translation) - enter https://www.google.com or your localized google version

i requested to you please provide your email, i want to contact you.

**Comment by tusch001** [comment]
> i requested to you please provide your email, i want to contact you.

I'm not the developer nor willing to provide an email address. This is github and issues are discussed openly. 
As far as I can see you are more a developer than I am playing with the source code. So I suggest use the search engine built into your developer platform. I'm pretty sure the term github isn't very prevalent in the source code and therefore should be easy located in the files. Replace it and build the code. Although I don't see why that is necessary considering you can change it in settings. And there already have been copycats of this app on google. So sorry I am not willing to help further.
