### ISSUE TITLE
Exiting bug and behavior

### ISSUE THREAD

**Issue by firecat53** [scoute-dich/browser#41]
Pushing the phone back button several times in a row when trying to exit breaks the 'ok' prompt to exit. 

Another issue is that there's no way to force an exit without either switching tabs or going back to the beginning of your history in the current tab.

Perhaps an alternate means to force an exit is to allow long press on the back button to pop up a menu of the current tab history that also includes an exit now button. Similar to how Firefox handles long press of the back button, but including the exit option (no further prompts if that option is chosen).

Hopefully that makes sense!

**Comment by scoute-dich** [comment]
Sorry for the late response. Work started again, so at the moment I don't have much time, but I will think about it, when I have (more) time again.

Regards
Gaukler Faun

**Comment by scoute-dich** [comment]
Hi,

I'm back again. You can always exit the browser by swiping up on the toolbar. This works also in all lists.

**Comment by firecat53** [comment]
Nifty! I missed that.
