### ISSUE TITLE
button names

### ISSUE THREAD

**Issue by femifrak** [scoute-dich/browser#419]
Nice browser!
However, I am lost because I don't know and cannot find out which buttons have which name:
What is the navigation button, what the fab button, ...
Is the navigation button the grey circle with the three dots on the right bottom? I tried to wipe it right and left but I cannot navigate with these gestures ...
(version 7.0)
Thanks!

**Comment by tusch001** [comment]
I try to help as far as I know:
The button with 3 dots is the (additional) floating navigation button/icon when you scroll down on a page. Depending on your settings it may be overlaid with the 3 button settings icon of the toolbar (the input area) when constantly visible. Guestures need to be activated in settings to work. There you can adjust the behaviour. 
Although I have to admit that I had my navigation button on the lower right corner and could not make right swipes successfully work on the three dots (not enough space to swipe?). I don't use it anymore.

The tab 'button' (?) I guess is the bar you get when you swipe up on the toolbar to see a horizontal list of small screenshots of open tabs. This might be deactivated in settings. A further swipe up or tap on the left icon on the toolbar reveals the icons to open a new tab, an overview of saved pages, bookmarks and history.

I hope that helps a bit.

**Comment by scoute-dich** [comment]
I don't want to change the original strings. FOSS Browser is translated in over ten languages. There would be much trouble with renaming buttons. So I'll do nothing concerning this.
