### ISSUE TITLE
Location prompted when set to allow

### ISSUE THREAD

**Issue by firecat53** [scoute-dich/browser#42]
I'm not sure if it's a universal issue or just with Google news (news.google.com) but every time I visit the site I'm prompted for location access permission when I have it set in the startup settings to allow. 

(Also happens at fredmeyer.com)

**Comment by scoute-dich** [comment]
Sorry for the late response. Work started again, so at the moment I don't have much time, but I will think about it, when I have (more) time again.

Regards
Gaukler Faun

**Comment by scoute-dich** [comment]
Sorry, but I can't reproduce this issue.. Can you give me some more details (and perhaps some screenshots)?

**Comment by scoute-dich** [comment]
Update is on his way. Since I switched to Ninja as new base of Browser please test the new implementations and open a new issue if there are further problems. Thanks for your patience.
