### ISSUE TITLE
(Request) Please include .apk file with releases

### ISSUE THREAD

**Issue by 5c0tt-b0t** [scoute-dich/browser#422]
Hello, I love this app (alot! Thank you!) I am unable to build apks due to an ancient PC! :'(
The last couple releases only include the source, no .apk files. Could you possibly include one within releases like you used to? Its just F-Droid is a little slow at getting apps into the store, and I am sure there are people, like me, that watch this project on Github and cannot build for themselves, thank you for considering and a HUGE thank you for this app!

**Comment by scoute-dich** [comment]
In future you can download latest apks from.
https://github.com/scoute-dich/browser/tree/master/app

There is a "debug" (latest development build) and a "release" directory.
