### ISSUE TITLE
[Feature Request] Close "Search on site" with Android Back-Button when Keyboard is closed/hidden

### ISSUE THREAD

**Issue by nabemono** [scoute-dich/browser#423]
Hi,

thank you for creating this great app! 

Currently when "Search on site" is active, it is needed to close it by pressing the Close-Button. The Android Back-Button only hides/closes the Keyboard.

Maybe "Search on site" can be closed with the Android Back-Button after the Keyboard has already been already closed/hidden?

(I am currently using FOSS Browser 7.1)

Best regards + have a nice day
nabemono

**Comment by scoute-dich** [comment]
Good idea. will be default behaviour in with next update.
