### ISSUE TITLE
[Feature Request] Allow actions "Search on site", "Save as bookmark" and "Share link" as gestures

### ISSUE THREAD

**Issue by nabemono** [scoute-dich/browser#424]
Hi,

I often use "Search on site", "Save as bookmark" and "Share link".
May I suggest these actions to be allowed for the gestures of the toolbar and the "Navigation button"?

Best regards + have a nice day
nabemono

**Comment by Tonus1** [comment]
I was thinking to assign a gesture to switch dark mode on and off

**Comment by scoute-dich** [comment]
Will be implemented with next update. ;-)
