### ISSUE TITLE
[Feature Request ] Please Add  "Desktop Mode", "Indigo Tab" Option In It.

### ISSUE THREAD

**Issue by MeAppDeveloper** [scoute-dich/browser#429]
Best Browser, But Please Add " History", "Desktop Mode", "Indigo Tab" Option In It. Thanks

**Comment by scoute-dich** [comment]
1. Desktop mode will never be implemented. I tried it several times. But it's unreliable. You can set a custom desktop-user-agent in settings.
2. Inkognito-tab isn't needed. Long pressing the menu or navigation button will bring up the fast settings. There you can toggle whatever you want (per website).
