### ISSUE TITLE
Tie together passStorage and bookmarks

### ISSUE THREAD

**Issue by firecat53** [scoute-dich/browser#43]
Suggestions:

1. When adding a domain to passStorage automatically add a bookmark to that domain at the same time.

2. When you visit that domain, whether by clicking from the passStorage tab or from the bookmarks tab, open the copy username prompt.

3. Add a cancel option ( x or 'cancel') to the username prompt to dismiss it if not needed (for example on sites that usually keep you logged in).

4. Auto-dismiss the prompt if you leave that domain.

**Comment by scoute-dich** [comment]
Sorry for the late response. Work started again, so at the moment I don't have much time, but I will think about it, when I have (more) time again.

Regards
Gaukler Faun

**Comment by scoute-dich** [comment]
3 & 4: You can dismiss the prompt by swiping it away. About 1 & 2: I must think about it ...

**Comment by scoute-dich** [comment]
I tried a little bit. But it seems not possible. Bookmarks and passStorage are two independant databases. Also the passStorage is encrypted. So it would be a lot of work, and I don't think that I have the time and developer skills to implement this, since I'm doing this in my freetime ...

Sorry.
