### ISSUE TITLE
Navigation Button Gestures Almost Entirely Useless

### ISSUE THREAD

**Issue by allora** [scoute-dich/browser#431]
Depending on the location of the navigation button, you can have 1 or 2 gesture directions inaccessible. It is impossible to position the button in such a way for all 4 gestures to be usable. The down gesture is always almost impossible to use no matter where you place the button.

Can the button be given more padding near the borders of the screen? Or better yet, can we customize its location exactly? Considering its already possible to move the button between 3 preset positions, it would be nice to be able to place it wherever we find most convenient.

Or better yet, maybe its better to define a "gesture area" rather than relying on the precise location of some button. Especially one that doesnt get overlapped by the address bar.

**Comment by scoute-dich** [comment]
I'll close this issue, since I made a lot of changes concerning styles, themes and the behavior of the toolbar. If there are still problems concerning this, please open a new issue after next update. The fab-navigation-button is removed with the next update.
