### ISSUE TITLE
Trojan Alert from Lookout

### ISSUE THREAD

**Issue by krbjmpr** [scoute-dich/browser#432]
FOSS Browser 7.1 src Fdroid
Lookout 10.32.4-5a02b33 src Playstore
LGv20 US996 Oreo 8.0.0 Kernel 3.18.71 US99620f
Images attached.

![Capture+_2020-07-07-19-41-46](https://user-images.githubusercontent.com/67986727/86860777-1d225d80-c08b-11ea-81dd-9def9fd918d2.png)

![Capture+_2020-07-07-19-41-35](https://user-images.githubusercontent.com/67986727/86860790-24496b80-c08b-11ea-8a3a-a2e0e3784333.png)

**Comment by scoute-dich** [comment]
That's strange. But I think, there is nothing I can do.
