### ISSUE TITLE
Google search history (localstorage) not cleared

### ISSUE THREAD

**Issue by rsnitsch** [scoute-dich/browser#435]
Clearing the browser history does not clear my Google search history. This is weird and very disappointing. I guess the localstorage is not cleared properly.

Note: I'm using FOSS browser from Google PlayStore. (Is there any reason why I should prefer installing it via F-Droid?)

**Comment by scoute-dich** [comment]
I think your Google search history is synchronized (with many other data about you) with the Google-servers. There is nothing I can do. You can try to disable cookies and javascript, to prevent Google from saving data. Or perhaps in your Google-Accountsettings you can disable it.

FOSS Browser on PlayStore is the same as on F-Droid. Except the signatures. F-Droid collects no data. That's the advantage.

**Comment by rsnitsch** [comment]
No. In fact, I can reproduce the issue on a fresh LineageOS system without any Google Apps.

It seems it has been observed in other browser apps. For example: https://github.com/mozilla-mobile/focus-android/issues/1306


Am 13. Juli 2020 20:51:09 MESZ schrieb Gaukler Faun <notifications@github.com>:

**Comment by scoute-dich** [comment]
Ok.

You can try if it works with attached apk file. You must enable "Clesr indexed databases" in the settings, and optional "Clear on exit".
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/4919929/app-debug.apk.zip)

**Comment by rsnitsch** [comment]
I cannot install your APK file. I have removed the ".zip" extension and tried to install it, but I only get an error message saying "Die App wurde nicht installiert" (english: The app was not installed). No details are given.

I have tried to uninstall FOSS browser completely and then install your debug APK, but the same error message is shown...

**Comment by rsnitsch** [comment]
I tried to install the app using adb with `adb install app-debug.apk`. That resulted in a failure, too. Error code: `INSTALL_FAILED_TEST_ONLY`

I found out that this is due to `android:testOnly="true"` in `AndroidManifest.xml`. It can be ignored with the -t switch, i.e. `adb install -t app-debug.apk` did the trick.

Now it's installed, but I can't start/open it. It crashes immediately. This is the logcat output:

```
07-15 16:15:37.483  8006  8006 D AndroidRuntime: Shutting down VM
07-15 16:15:37.489  8006  8006 E AndroidRuntime: FATAL EXCEPTION: main
07-15 16:15:37.489  8006  8006 E AndroidRuntime: Process: de.baumann.browser, PID: 8006
07-15 16:15:37.489  8006  8006 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{de.baumann.browser/de.baumann.browser.activity.BrowserActivity}: java.lang.ClassNotFoundException: Didn't find class "de.baumann.browser.activity.BrowserActivity" on path: DexPathList[[zip file "/data/app/de.baumann.browser-l9SmpJFsXLg4YJcZofWJlA==/base.apk"],nativeLibraryDirectories=[/data/app/de.baumann.browser-l9SmpJFsXLg4YJcZofWJlA==/lib/arm64, /system/lib64, /vendor/lib64]]
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "de.baumann.browser.activity.BrowserActivity" on path: DexPathList[[zip file "/data/app/de.baumann.browser-l9SmpJFsXLg4YJcZofWJlA==/base.apk"],nativeLibraryDirectories=[/data/app/de.baumann.browser-l9SmpJFsXLg4YJcZofWJlA==/lib/arm64, /system/lib64, /vendor/lib64]]
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	... 9 more
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 	Suppressed: java.io.IOException: Failed to open dex files from /data/app/de.baumann.browser-l9SmpJFsXLg4YJcZofWJlA==/base.apk because: Unrecognized version number in /data/app/de.baumann.browser-l9SmpJFsXLg4YJcZofWJlA==/base.apk: 0 3 9 
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:100)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:74)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:954)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:2270)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5639)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
07-15 16:15:37.489  8006  8006 E AndroidRuntime: 		... 6 more
07-15 16:15:37.497  3540  6062 W ActivityManager:   Force finishing activity de.baumann.browser/.activity.BrowserActivity
07-15 16:15:37.504  3540  3787 I ActivityManager: Showing crash dialog for package de.baumann.browser u0
```

**Comment by scoute-dich** [comment]
Try to uninstall the app and install it again. This helped for me the first time I installed adebug-apk.

**Comment by rsnitsch** [comment]
> Try to uninstall the app and install it again. This helped for me the first time I installed adebug-apk.

Tried that, same error.

**Comment by scoute-dich** [comment]
I got a hint from #430 
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/4938592/app-debug.apk.zip)

**Comment by rsnitsch** [comment]
> I got a hint from #430
> [app-debug.apk.zip](https://github.com/scoute-dich/browser/files/4938592/app-debug.apk.zip)

This APK worked!

First, the bad news: Navigating to Google.com was not possible via the URL field for some reason (input seems to be ignored). I had to set google.com as startpage in order to test the localstorage issue.

Here comes the good news: The localstorage is now properly cleared, it seems. The Google search history is erased as it should be.

**Comment by scoute-dich** [comment]
> First, the bad news: Navigating to Google.com was not possible via the URL field for some reason (input seems to be ignored). I had to set google.com as startpage in order to test the localstorage issue.

Works for me. At the moment I don't know what to do. No input is working?

**Comment by rsnitsch** [comment]
> > First, the bad news: Navigating to Google.com was not possible via the URL field for some reason (input seems to be ignored). I had to set google.com as startpage in order to test the localstorage issue.
> 
> Works for me. At the moment I don't know what to do. No input is working?

I can enter a URL. But when I hit "submit/enter", nothing happens. The browser just stays at the current location.

**Comment by scoute-dich** [comment]
You can test attached apk-file and report back.
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/5059422/app-debug.apk.zip)

**Comment by scoute-dich** [comment]
Since the original issue is closed.
