### ISSUE TITLE
Reopening the app always opens new tab in foreground

### ISSUE THREAD

**Issue by rsnitsch** [scoute-dich/browser#436]
Since the last version the behavior of FOSS browser has changed... when I open the app from the home screen, a new tab will always be opened and put to foreground - even if the app was already running before. Even if the last active tab is showing nothing but the start page, a new tab with the start page will be opened. This can easily lead to many parallel tabs that show nothing but the startpage.

Is that a change that was made on purpose or is it a bug? If it's not a bug, is there a possibility to restore the old behavior (just bring the app back to foreground without creating a new tab)?

And if it's not a bug, maybe you should reconsider opening a new tab when there is already a tab showing the startpage. There is no need to open the startpage multiple times.

**Comment by scoute-dich** [comment]
It is a bug and will be solved with next update. Thanks for reporting.
