### ISSUE TITLE
Update status bar title when tab is closed

### ISSUE THREAD

**Issue by firecat53** [scoute-dich/browser#44]
Right now if you hit x to close a tab and the default page is about: blank, the status bar still shows the previous website title. It should update to empty.

Also, is there a way to make the default page when a tab is closed be the bookmarks page?

**Comment by scoute-dich** [comment]
Sorry for the late response. Work started again, so at the moment I don't have much time, but I will think about it, when I have (more) time again.

Regards
Gaukler Faun

**Comment by scoute-dich** [comment]
This issue I also can't reproduce. Is this a problem when you close the current tab or an other tab (which isn't the current?

**Comment by scoute-dich** [comment]
Tabs ae totaly new implemented. Update is on his way. Since I switched to Ninja as new base of Browser please test the new implementations and open a new issue if there are further problems. Thanks for your patience.
