### ISSUE TITLE
URLs with custom port are always opened in search.

### ISSUE THREAD

**Issue by phamhongviet** [scoute-dich/browser#442]
URLs with custom port, e.g https://this.url.port:12345/ are always treated as a search string. The only way to open those URLs are to tap on them in other websites. After the browser open them correctly by follow a link on other websites, bookmarking those URL doesn't work. Open a bookmarked URL still open the search page with the URL as a string.

**Comment by scoute-dich** [comment]
You can test attached apk-file and report back. Problem should be solved.
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/5059554/app-debug.apk.zip)

**Comment by phamhongviet** [comment]
This problem is  fixed. Thank you for your work.
