### ISSUE TITLE
Is there a way to stop loading a page?

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#444]
Hi  
   

I prefer your browser because of the features it offers. Generally I'm browsing without Javascript and deactivated cookies. Which helps not only with privacy but also lets pages load much faster (I often have very bad network connection at work).  

Because of GDPR a lot of European webpages display a cookie consent box. The code is often placed at the bottom of the page which is shown at the end of the loading process and the box is then absolutely positioned with css at the top / bottom of the screen to overlay the text. On a small mobile screen this consumes half of the display. With deactivated JS most boxes can't be discarded (sites usually don't use css for this and - even worse - don't check beforehand if cookies are enabled at all).  

This cookie consent box is shown on every page of the domain (because cookies are deactivated and settings can't be set / retrieved).

Having a button to stop loading the page would make a lot of pages better readible. This button could take the same place as the reload button above the js / cookie settings menu since the stop button is only useful when the reload button is not needed.  

Or better: put it in the input bar on the left side only while the page is loading and the user hasn't activated the input to type in a new page.

Otherwise Javascript and cookies need to be activated which contradicts a bit the purpose of your browser :-) At the moment I have a dozen sites for which I have JS activated only for the above mentioned reasons.

A humble suggestion.
  

Thanks for all the work you put in your browser.

**Comment by scoute-dich** [comment]
This is implemented with next update. Thanks for still using my browser. ;-)
