### ISSUE TITLE
[Question] Toggle third party content loading

### ISSUE THREAD

**Issue by VR-25** [scoute-dich/browser#448]
What kind of third party content does that refer to?
With third party content blocking enabled, it seems sites are still loading resources from third party domains.
I must be missing something.

**Comment by scoute-dich** [comment]
Enabling third party content enables:

- setAllowFileAccessFromFileURLs(true);
- setAllowUniversalAccessFromFileURLs(true);
- setDomStorageEnabled(true);

There are not many, but a few sites (for me: nextcloud, sourceforge), which do not load all content, when disabled. Often these are small things, like icons, special fonts and so on.
