### ISSUE TITLE
passStorage not functional with http basic authentication popups

### ISSUE THREAD

**Issue by firecat53** [scoute-dich/browser#45]
Sorry to drop another issue on you, but there's no way to use the passStorage feature with authentication popups. Any swipe or tap away from the page with the pop-up clears the pop-up and fails authentication.

**Comment by scoute-dich** [comment]
I think this could be solved with an option to build a notification from where it would be possible to copy the login data to the clipboard. Perhaps when long pressing an entry in the passStorage...

But as said, it could take a while till I've the time to work on it. Anyway, thanks for reporting the issues. Every reported (and solved) issue makes the app better...

**Comment by scoute-dich** [comment]
This is also solved. There will be a new entry in the passStorage context menu (Autofill authentication dialog) with the next update. I will upload the update in the next days after testing it...
