### ISSUE TITLE
Can't save any file

### ISSUE THREAD

**Issue by Kanten** [scoute-dich/browser#450]
Hi there,
I'm using the browser in version 7.2 under Android 11 on my Pixel 3.
In the app settings, there's no option to allow the access to write or read the memory. So every download i make turns after some time into an error.

![Screenshot_20201002-215143](https://user-images.githubusercontent.com/1925977/94964383-08266080-04fa-11eb-9496-00eacaec0197.png)

**Comment by scoute-dich** [comment]
Since FOSS Browser uses the Android-Downloadmanager, since Android 10 there is no permission needed to save Downloads in the default public download-folder.

I do not have this problem, using Android 11.

**Comment by scoute-dich** [comment]
Please reopen when problem still perstits after next update.
