### ISSUE TITLE
Using a self signed certificate?

### ISSUE THREAD

**Issue by vladns** [scoute-dich/browser#451]
Actually the question.

**Comment by scoute-dich** [comment]
Using a self signed certificate for what?

**Comment by vladns** [comment]
It's not what it's for. For example, the firefox browser can add your own certificates or use the system certificates from the operating system store. Specifically, in my case, this is needed to filter http traffic, otherwise the browser constantly reports an incorrect certificate, well, this is the way it should be, but in this case I don't need it. All my checks are happening above, on the proxy server.

**Comment by scoute-dich** [comment]
I understand. The sad thing is, that I haven't the knowledge, the time or the skills to solve this problem. I'm developing in my freetime, and all I know Ilerned by myself. So if you want so "advanced features" you should probably change the browser. I will not implement new features anytime soon.
