### ISSUE TITLE
Great browser! - Pinch and zoom not working after 7.0

### ISSUE THREAD

**Issue by erlanger** [scoute-dich/browser#453]
Hi,
   First, thank you for this browser! It is the best one for android!  
   Pinch and zoom is not working after version 7.0 so I have not been able to upgrade since my eyesight is not good.

  Hopefully you can get it to work again. It is on Android 9.

**Comment by scoute-dich** [comment]
Zooming should be working again. At least with the next update.

**Comment by erlanger** [comment]
Thanks! appreciate you keeping this in mind!
