### ISSUE TITLE
Direct links on adress bar not working

### ISSUE THREAD

**Issue by overtube** [scoute-dich/browser#454]
Imposible going to another site, will type exact adress on adress bar. Only possible to do this - open new tab and search needed site from search engine. 
This feature working on version 7.1.

**Comment by hasifantasy** [comment]
Same to me

**Comment by scoute-dich** [comment]
I'll close this issue, since I made a lot of changes concerning styles, themes and the behavior of the toolbar. If there are still problems concerning this, please open a new issue after next update.
