### ISSUE TITLE
What site is this and is it secure?

### ISSUE THREAD

**Issue by cbiere** [scoute-dich/browser#456]
When I'm on a site on which I enter credentials, I want to be sure I'm on the right site and it's using HTTPS. The only way to verify this at the moment, is tapping on the address bar and scrolling to the most left — which can easily trigger the default back gesture. Also, if I tapped on OK during a HTTPS warning, I can't tell the difference between a secured website and one with an invalid certificate. The warning might be dismissed by accident or intentionally but in any case, whether the site uses a valid certificate should still be obvious afterwards.

I would like to suggest the following:
- Show the good ol' lock symbol in the address bar.
- Show a full page warning like other browsers if a certificate is invalid, requiring two tabs so that it's not easily dismissed by accident.
- When switching from title to URL in the navigation bar, show the beginning of the URL instead of the end, so that it's easy to identify the domain and protocol.

**Comment by scoute-dich** [comment]
If you open the menu, the reload button will be replaced by an alert-icon, if there is no https-connection. Clicking it will try to reconnect via https. I do not want more icons on the toolbar. I hope this is ok for you.
