### ISSUE TITLE
improve dark mode

### ISSUE THREAD

**Issue by francescosoave** [scoute-dich/browser#457]
Hi! I'm almost ready to fully switch to this browser! There's only 1 thing that I'd like to suggest. When I setup the dark mode I'd also like the search page/result (duckduckgo in my case) to be dark. See the examples below. The dark one is what happens in Bromite browser, the white one is what happens in FOSS. Thanks!

![Screenshot_20201031-084113](https://user-images.githubusercontent.com/26126452/97774165-f5816480-1b55-11eb-82ef-ac32da2696c7.jpg)
![Screenshot_20201031-084058](https://user-images.githubusercontent.com/26126452/97774169-f74b2800-1b55-11eb-9a77-989f0d8a563c.jpg)

**Comment by cbiere** [comment]
Did you enable "Inverted colors" in the settings under Behavior/UI? The name of this setting is slightly misleading and it seems to depend on Android with respect to its actual effect. On Android 7 it really just inverts colors but on newer versions like Android 9+ it results in a near pefect dark mode i.e. photos are not inversed. Actually, it might not depend on Android itself but the Webview implementation which you can check and possibly change in the Android developer settings.

Aside from that, Duckduckgo has some ingenious feature: You can modify its options at will and then copy a link that includes these options as switches. If you configure this as your custom default search engine, you can enforce the dark theme among many other options even without storing cookies. Also the link is not personalized, it's completely transparent and the switches are all documented.

**Comment by francescosoave** [comment]
thanks! I didn't know about the features you mentioned..I think I'll stick with the duckduckgo solution for now..the inverted colors looks weird sometimes..thanks!
