### ISSUE TITLE
[Enhancement]Consider making the navigation button self-adjusting with the toolbar.

### ISSUE THREAD

**Issue by divan19** [scoute-dich/browser#458]
If the toolbar is not hidden while scrolling, the **nav button** is covered by the toolbar, rendering the button unusable.

I love using gestures on the toolbar and the **nav button**. I like the toolbar hidden while scrolling. It'd be great if the app could adjust position of the **nav button** relative to the toolbar. I mean, with hidden toolbar, the button can hold its position at bottom, but when the toolbar is shown it should be just above the toolbar. I also feel that a larger square button will enhance the overall experience. 

When I visited [Shafaet's Planet](https://www.shafaetsplanet.com) in this browser, a button labeled 'top' behaved exactly like I'd love the **nav button** to behave.
![toolbar-hidden](https://user-images.githubusercontent.com/47885840/99599820-0bb36f80-29f4-11eb-912b-d5487e2e4d44.jpg)
![toolbar-not-hidden](https://user-images.githubusercontent.com/47885840/99599831-10782380-29f4-11eb-9833-74e7b7fb6266.jpg)

Anyway, thank you for this unique browser.

**Comment by scoute-dich** [comment]
Hi,

you can also use the gestures you assigned to the nav-button on the regular overflow button on the toolbar (when toolbar is shown). At the moment I'm spare of time, so I will not add any new features.
