### ISSUE TITLE
Google Drive download issued .bin instead .img

### ISSUE THREAD

**Issue by daywalk3r666** [scoute-dich/browser#459]
when i try to download a file from gdrive foss browser downloading "51b65fd4h654f6.bin" instead of twrp 3.4.0-1.img

![photo_2020-11-25_14-49-09](https://user-images.githubusercontent.com/15938117/100245680-9df9cd00-2f38-11eb-9d9a-c8934dd0c29b.jpg)

**Comment by tusch001** [comment]
I had this issue too on some third-party sites with zip files that were linked to google drive. I just renamed the downloaded file and gave it the correct file type ending. Maybe that helps for you.

**Comment by scoute-dich** [comment]
Yes, I can confirm this. I also rename the files afterwards. Alternatively you can long click on the download link and then choose "Save as".
