### ISSUE TITLE
Storage use builds up over time

### ISSUE THREAD

**Issue by JartThrower** [scoute-dich/browser#462]
The app uses more and more storage the longer it's used. This persists even after clearing all data and selecting the "delete database" option. Setting the browser to clear all data on exit also doesn't help.

![Screenshot_20201214-191511_Settings](https://user-images.githubusercontent.com/68966968/102292025-5f8d7780-3f12-11eb-91b8-bedb6854b73f.png)

**Comment by daywalk3r666** [comment]
this caused by your webview. chrome or aosp webview collect anonymous diagnostic data. it needs a commit to opt out.

meanwhile you can use bromite webview

the log files are in /data/data/de.baumann.browser/app_webview/BrowserMetrics

**Comment by scoute-dich** [comment]
In next release it is opt out. Thanks for reporting.
