### ISSUE TITLE
[Suggestion] Number of open tabs shown on icon / option to always keep tabs icon in bar

### ISSUE THREAD

**Issue by th23x** [scoute-dich/browser#464]
Hey,

thanks for the great and light-weight browser :-)

I so far came across two improvement ideas for the handling with open tabs:

1) Show the **number of open tabs in the tabs icon** in the status/browser bar

2) Allow an **option to always keep the tabs icon in the bar** (instead of showing there the last used one eg homepage etc) as the tabs is the one by far most often used one - even after once switching to eg history

Thanks for consideration and kind regards
Thorsten

**Comment by scoute-dich** [comment]
This will be implemented with next update.
