### ISSUE TITLE
Light Mode & Full Screen Immersive Mode

### ISSUE THREAD

**Issue by ioconfig** [scoute-dich/browser#465]
Status notification bar does not reflect Light Mode. The status notification bar is dark grey in Light Mode. Please make white status bar to reflect light mode. 

Full Screen Immersive Mode does not hide the Status Notification bar. Please hide status bar in full screen Immersive mode.

**Comment by scoute-dich** [comment]
Can you please attach a screenshot? I can not confirm this issue.

**Comment by scoute-dich** [comment]
I implemented the new Material Components. Full Screen issue will be fixed with next update. But statusbar will have dark color.
