### ISSUE TITLE
please add WebRTC support

### ISSUE THREAD

**Issue by BrunoKatz** [scoute-dich/browser#466]
It would be great to be able to use foss browser to join BBB-Meetings (not wanting to use chrome....)

When I try to access a **[bigbluebutton](https://github.com/bigbluebutton/bigbluebutton)** meeting,
for instance on [senfcall.de](https://public.senfcall.de/)
I get a message, that the browser is not supported (actually the message says, that the browser is supported, but that the version is too old -> Neither do I know which useragent **foss browser** uses generally, nor, what is exactly needed to support BBB)

(screenshot of the message in german)

![Screenshot_20210316-160003_FOSS_Browser](https://user-images.githubusercontent.com/38205938/111332243-e79a2f00-8671-11eb-8a91-0474158ac364.png)

I also opened an [issue](https://github.com/bigbluebutton/bigbluebutton/issues/11657) with BBB

**Comment by lonesomewalker** [comment]
The correct issue title would be:
please add WebRTC support

**Comment by scoute-dich** [comment]
Hi,

at the moment there is no possibility for me to implement webRTC. I do not have the skills or time. Sorry to say.

**Comment by BrunoKatz** [comment]
@scoute-dich thank you for looking in to this!
