### ISSUE TITLE
Crashes when resize in split-screen mode/multi-window mode

### ISSUE THREAD

**Issue by Nabokov86** [scoute-dich/browser#469]
If you initially open it in multi-window mode, the application does not crash. But if you try to switch to split screen mode or back to full screen mode, a crash occurs.

Tested on android 9 and 7. Other browsers don't have this problem

**Comment by scoute-dich** [comment]
Hi,

I think, this is caused by the implementation of webview in my browser. I disabled multiwindow-support. With next release FOSS Browser will only start in full-screen mode.
