### ISSUE TITLE
Change tot blank page on new tab

### ISSUE THREAD

**Issue by lil5** [scoute-dich/browser#48]
At the moment new tab will bring you to the Github page.

It would be easier on possible data charges; for instance.

Please consider changing to a blank page on new tab.

The `start tab` option only specifies the first tab loaded on application start.

**Comment by 3damned** [comment]
@lil5 , to make blank page appear on new tabs: go to Bookmarks page, then open 3dot menu and select "Blank page as favorite"

**Comment by scoute-dich** [comment]
@lil5 answerd the question. If there are further questions concerning this issue, please reopen.

**Comment by lil5** [comment]
Thanks
