### ISSUE TITLE
App stop working after changeing the overview

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#486]
Steps: 
Seteing > behavior/ui > overview 
Check it and choose bookmarks

Restart the browser

And it will not start again

V. : 7.3

**Comment by scoute-dich** [comment]
Happens this with start, bookmarks and history?

**Comment by scoute-dich** [comment]
This is solved with the next update.

**Comment by islam2hamy** [comment]
Not fixed

**Comment by scoute-dich** [comment]
New test:
[app-debug.zip](https://github.com/scoute-dich/browser/files/6466783/app-debug.zip)

**Comment by islam2hamy** [comment]
Fixed
