### ISSUE TITLE
Dark mode in v. : 7.3

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#487]
My phone doesn't have built in dark mode
So i cant use it in the app

please add it back to the app , so i can change to dark mode

**Comment by scoute-dich** [comment]
At the moment I don't have much time. Perhaps I'll bring it back later. I just changed all libraries and switched to the "Material Components". So it would take a while for me to figure out how to implement miter than one theme.

**Comment by scoute-dich** [comment]
I'll close this also. I want to have a very stable release, before implementing new features.
