### ISSUE TITLE
Can't search using toolbar

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#491]
Open the browser v. 7.2
Write in the toolbar "adidas"
Or paste a site url
Hit enter from the keyboard

It will remove your input

<a href="https://ibb.co/6XQM2HM"><img src="https://i.ibb.co/rd9jgxj/IMG.jpg" alt="IMG" border="0"></a>

**Comment by scoute-dich** [comment]
This is solved in v7.3 ;-)
