### ISSUE TITLE
Feature (re)proposal: Desktop View

### ISSUE THREAD

**Issue by alabre** [scoute-dich/browser#493]
Hi and thank you for that quick and lean browser which is my daily driver through the internet.
I would like to address the following Feature Request of a feature that seems to be available from versions 3.5 to 5.7.

Desktop View of pages
1. To be able to edit excel sheets on my mobile device, as a User I want to be able to switch to the desktop view of a page on demand. (Background: Editing is not possible in mobile view, but in desktop view).

If you like that feature a next improvement on this could be:
2. To avoid reloads of a page, as a User I want to tag pages "open in desktop view" to load them in desktop view always.

So, having the feature "on demand" would help, the second proposal is already the golden edge on that feature and far less important for me. If you have questions I would love to discuss them with you.

All the best and thank you again for your work
Achim

**Comment by scoute-dich** [comment]
I tried that several times but never had success. It was always buggy. So I will never implement this. It costs too much time and effort. I'm doing this in my free time. Sorry.

**Comment by alabre** [comment]
Can understand you totally. Thank you for your quick response and your great work. :-)

**Comment by scoute-dich** [comment]
Btw.: You can set a custom user agent in the settings.
