### ISSUE TITLE
Browser crashes on start-up

### ISSUE THREAD

**Issue by Lee245** [scoute-dich/browser#494]
I have updated from 7.3 to 7.4 and was able to use the browser (nice UI improvements btw!). Then I changed some settings. As far as I remember, I changed the default new tab from blank to showing the bookmarks. Then the browser prompted that I had to restart it due to the changes and after closing it keeps crashing and I cannot open it. Clearing user-data would probably help, but hopefully there is a better fix. Cache is already cleared. 

If you need more information, like a logcat or something, let me know.

**Comment by scoute-dich** [comment]
Hi, I just released a update (7.4.2), which fixes this. Sorry for the problems. You can wait until the update is released or roll back to v7.3.

**Comment by scoute-dich** [comment]
Btw. bookmarks can't be opened in a new tab...

**Comment by Lee245** [comment]
> Thanks.
> 
> Hi, I just released a update (7.4.3), which fixes this. Sorry for the problems. You can wait until the update is released or roll back to v7.3.
> 
> Do you update from F-Droid or PlayStore?
> 
> You can also test the attached apk file on the latest release.

Thanks for the quick response and fix. No worries :). I update from F-Droid. I guess it will take a while before the update is released there. In the meanwhile I'll use the apk from here.

**Comment by x5731** [comment]
Thanks for the browser.
I started using it today, when the overview is home in behavior/UI, and I choose show on start, the app continues working but on next opening it crashes.

I don't know if the fix is in 7.4.3 as u said above.

**Comment by islam2hamy** [comment]
> Thanks for the browser.
> I started using it today, when the overview is home in behavior/UI, and I choose show on start, the app continues working but on next opening it crashes.
> 
> I don't know if the fix is in 7.4.3 as u said above.

Fixed in v. 7.4.1
