### ISSUE TITLE
App shortcuts doesn't work

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#495]
<a href="https://ibb.co/HLccgYv"><img src="https://i.ibb.co/ymzzs5T/IMG.jpg" alt="IMG" border="0"></a>

**Comment by scoute-dich** [comment]
Perhaps I'll remove app shortcuts. It seems to buggy. And opening the overview and choosing a tab takes not much longer than opening the appshortcut via longpressing ...

**Comment by scoute-dich** [comment]
I removed it with the latest changes. It is also a problem, since I must use different package names in Play Store and F-Droid. :-(
