### ISSUE TITLE
after file download browser doesn't open new websitr + repeats download

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#497]
more or less same as issue #320:

Steps to reproduce:

I used [Evozi Downloader](https://apps.evozi.com/apk-downloader/) to download an apk file from google, eg de.baumann.browser1 (you need JS activated, click to generate the download link then on the green button to download the app).

After saving the file I didn't open Android File Manager (no to the question) but swiched to another app.

Coming back to Foss browser type in the same (still open tab) a new domain into the navigation bar (eg google.com) and hit enter.

Result:  
The browser asks again if it should save the previous downloaded file instead of opening the link.

Remark:
This doesn't happen if I open a new tab only if I use the already open page.

Browser:
latest version (7.4.3) from github  

OS:

- Android 6.01 minus google (Cat S 60)
- Stock 8.0.0 (Cat S 41)
- Lineage 14 / Android 7.1.2 (Samsung Galaxy Note 10.1)

This is only a minor issue. Thanks for this great browser. With the update many of the minor problems on my old Android phone seem to be gone.

**Comment by scoute-dich** [comment]
Is this an issue for the current version 7.4.3?

**Comment by tusch001** [comment]
yes

**Comment by scoute-dich** [comment]
I can not reproduce this. Does this only happen on the mentioned website, or with any download?

**Comment by tusch001** [comment]
It's not that often, that I download files. I think this so far has only happened with apk-files, So only two sites (apkmirror.com and the above mentioned). Maybe it is not the file itself but the fact that I switch to another app to install the apk. Don't worry. This minor issue is probably not even worth your time since I all my phones are Android 6 - 8. Not the newest phones.

Thanks anyway for your time.

**Comment by scoute-dich** [comment]
I just released a new version (7.5) if this bug still is not solved, please report it here. Otherwise, please close this issue (Or I'll do that in the near future).

**Comment by tusch001** [comment]
Still there. 

I think it is related to the other now closed issue with the input bar not loading some pages sometimes.
This behavior is in Version 7.5 much better. Once in a while still present. Maybe when links or pages are opened with JavaScript?
The only other reproducable misbehaviour is at my webhoster kasserver.com / all-inkl.com. As German you might know them. Kasserver.com is one of the few Domains where I accept all Cookies / Javascript, even third-parties. When I want to open within kasserver.com a link into my email web access which goes to all-inkl.com the same page from kasserver.con is loaded again.

So: I'm happy how the Browser is behaving at the moment compared to older versions. As I've written previously it really is a minor issue. But I wanted to let you know there is still something not 100 % ok with the input bar.

Nevertheless feel free to close the issue.

Thanks
