### ISSUE TITLE
Keyboard not showing when selecting adress bar

### ISSUE THREAD

**Issue by Tonus1** [scoute-dich/browser#498]
As in title :  when I select the adress bar I cannot input any text. No new search nor new site.

**Comment by scoute-dich** [comment]
Which version you are using?

**Comment by Tonus1** [comment]
Hi
It was 7.4.1, at that time latest on F-Droid...
While checking I saw 1.4.3 that solved the problem ! 

Thanks for this awesome (new version of your) browser !
