### ISSUE TITLE
Feature proposal : Search shortcuts

### ISSUE THREAD

**Issue by Zickfky** [scoute-dich/browser#499]
Hello !
Thank you for your great browser.
I would like to suggest two features.

1. When you launch the application and you have selected "about:blank" by default, it will be very useful if the keyboard automatically opens instead of selecting "about:blank", and sometimes have to manually delete it before type.

2. Is it possible to implement search shortcuts like in the desktop version of Firefox ? For instance, you enter _'thesau'_ --> https://www.thesaurus.com/browse/%s
And when you type _'thesau example'_, it returns https://www.thesaurus.com/browse/example 

Thank you in advance

**Comment by scoute-dich** [comment]
I think the first thing I can implement in near future. 
====
The second thing I won't implement in the near future. I don't have the time. Normally I don't add any new features. New features are meaning new bugs ...

**Comment by scoute-dich** [comment]
First point will be implemented in next version.

**Comment by scoute-dich** [comment]
As said, the first point is solved with next update.

Search shurtcuts I'll not implement. At the moment I only solve all functionial issues. Until then I'll not implement new features.
