### ISSUE TITLE
one tab browser

### ISSUE THREAD

**Issue by AKprisonER** [scoute-dich/browser#50]
how to make it to one only one tab?
Mean currently there are five tabs for browsing, but there should be only one tab should be there.
How to restrict other tabs?

**Comment by 3damned** [comment]
@AKprisonER, The maintainer is kinda busy now so I will take the liberty of answering this simple question: the number of tabs is **static** for now. There are five tabs - no more no less.

**Comment by AKprisonER** [comment]
U didn't get my question. But anyway i took a old commit with one tab and merged new features with current stable version.

**Comment by scoute-dich** [comment]
@AKprisonER answered the right way. Thanks for that.

I don't plan to add an option to set the number of tabs. I think five tabs are enough. And if you don't need them, then just ignore them. Until you switch to an other tab there will no data be loaded.

If there are more questions concerning the number of tabs please comment or reopen this issue.

**Comment by rancidfrog** [comment]
A question: Why not have normal tabs management: I.E. only open when asked and  without limits?
The UI design of your tabs looks great.
There should be a design pattern which handles that. Currently it is a little weird as if you open page in tabs 1, 2, and 3. Then close tab 2. Navigating between 1 and 3 you will have to keep jumping over 2.
Also, remembering last tabs would be nice; for example, if you have a page open and you exit, next time you open it comes back to it, maybe a switch setting.
Personally, I usually have many tabs open. And when browsing I keep opening new background tabs.
At the moment I use both naked browser and lightning browser, which both handle tabs well.
Would love to see tab management in this app. Design is sweet.

**Comment by scoute-dich** [comment]
The problem is, that I don't know how to implement tabs. I've never learned developing in a "professional" way...

**Comment by rancidfrog** [comment]
Not sure if helpful or if interested,
But.
Ninja browser, which used similar omnibar uses a linked list:
- https://github.com/mthli/Ninja/blob/master/Ninja/src/io/github/mthli/Ninja/Browser/BrowserContainer.java

Lightning has more detailed approach, even though he converted to kotlin which is basically java++
https://github.com/anthonycr/Lightning-Browser/tree/dev/app/src/main/java/acr/browser/lightning/browser

- https://github.com/anthonycr/Lightning-Browser/blob/dev/app/src/main/java/acr/browser/lightning/browser/TabsManager.kt
- https://github.com/anthonycr/Lightning-Browser/blob/dev/app/src/main/java/acr/browser/lightning/browser/TabsView.kt
- https://github.com/anthonycr/Lightning-Browser/blob/dev/app/src/main/java/acr/browser/lightning/browser/fragment/TabViewState.kt
- https://github.com/anthonycr/Lightning-Browser/blob/dev/app/src/main/java/acr/browser/lightning/browser/fragment/TabsFragment.kt

**Comment by scoute-dich** [comment]
TAbs are totaly new implemented. Update is on his way. Since I switched to Ninja as new base of Browser please test the new implementations and open a new issue if there are further problems. Thanks for your patience.
