### ISSUE TITLE
"Save as bookmark" says "added to Home"

### ISSUE THREAD

**Issue by riveravaldez** [scoute-dich/browser#501]
Hi, minor detail, it seems.

When in a page, the action "Save as bookmark" works fine, but the message says "Successfully added to Home", which I suppose is misleading for the user.

Just that. Kind regards, and thanks for the lovely FOSS Browser.

**Comment by scoute-dich** [comment]
Thanks. Is fixed with next update.

**Comment by riveravaldez** [comment]
Great! Thanks a lot.
