### ISSUE TITLE
Is it possible to preserve opened tabs after Exit and Restart?

### ISSUE THREAD

**Issue by riveravaldez** [scoute-dich/browser#502]
Hi,

is there a way to preserve the opened tabs after exiting the browser and then starting it again?

Thanks a lot, kind regards.

**Comment by scoute-dich** [comment]
No. I don't see a possibility at the moment. I don't have the skills  and time.

**Comment by dessalines** [comment]
This should be reopened. Restoring saved tabs is one of the most important features of any browser.
