### ISSUE TITLE
Content obstructed by navigation bar

### ISSUE THREAD

**Issue by cbiere** [scoute-dich/browser#503]
App version: 7.4.1

Example URL: https://duckduckgo.com/?q=example&ia=images

Tab on a picture and you'll get a near fullscreen overlay with the picture and some link and information below which is near hidden and possibly inaccessible behind the navigation bar on the bottom. As there is nothing to scroll, there doesn't seem to be anyway to hide the bar and get to the content. Depending on display resolution and font sizes, actual examples might differ. See screenshot below.

![7020](https://user-images.githubusercontent.com/8558711/118778474-6a19b780-b88a-11eb-9834-b16cd74c34a3.jpg)

Suggestion: Hide the navigation bar if the user makes a scroll gesture even if there is nothing to scroll. No idea if that's possible.

**Comment by UksusoFF** [comment]
Try to disable hidding bottom panel feature.

**Comment by cbiere** [comment]
No. Thank you.



________________________________
Von: Kirill Uksusov ***@***.***>
Gesendet: Montag, 31. Mai 2021 08:45
An: scoute-dich/browser
Cc: Christian Biere; Author
Betreff: Re: [scoute-dich/browser] Content obstructed by navigation bar (#503) 

Try to disable hidding bottom panel feature.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/scoute-dich/browser/issues/503#issuecomment-851234512", "url": "https://github.com/scoute-dich/browser/issues/503#issuecomment-851234512", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by woheller69** [comment]
![Screenshot_20210630-064826_FOSS Browser](https://user-images.githubusercontent.com/68678880/123903801-af440580-d96f-11eb-8303-c54b709fae0e.jpg)
I have the same problem, e.g on marketwatch.com.

With disable hiding bottom panel it is better, but still not 100%
![Screenshot_20210630-065032_FOSS Browser](https://user-images.githubusercontent.com/68678880/123903974-f5996480-d96f-11eb-881a-9188c7b4916c.jpg)

**Comment by woheller69** [comment]
can we hide/show the navigation bar with a swipe gesture on the 3 lines at the bottom left?

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6742507/app-debug.apk.zip)
For me, the issue is solved, with attached apk. If anyone wants to test.

**Comment by woheller69** [comment]
For me that seems to work :-)

**Comment by woheller69** [comment]
![Screenshot_20210707-113841_FOSS Browser](https://user-images.githubusercontent.com/68678880/124737463-441ea400-df18-11eb-9114-41958fee19ae.jpg)

Problem is again there on www.xing.com 
I cannot press the button at the bottom

**Comment by woheller69** [comment]
Seems to work when swiping up, so nothing to do
