### ISSUE TITLE
Browser crashes when opening a new tab

### ISSUE THREAD

**Issue by Cwpute** [scoute-dich/browser#506]
As the title says, new blank tabs opened from the menu make the browser crash.

It happens whether i have several tabs open or if i've just opened FOSS Browser. New tabs opened from links in other apps don't make the browser crash, although i have to manually reload the tab for it to actually load at all - the two issuses might be linked.
As far as i know, this behavior only occured since last update (currently using FOSS Browser v7.4.3) but it might have to do with the new design update that rolled out recently.
I should also probably point out that i'm using Android Webview Version 89.0.4389.105, because  later versions made any webview based apps on my phone crash.
I'm on a Huawei Honor BLN-L21, running Android 7.0.

I'll be switching to the last version prior to the design update until this issue is fixed.

Thanks for your time !

**Comment by scoute-dich** [comment]
Hi,

thanks for reporting. Can you please test attaches apk file (just rename it)? Concerning both reported issues?
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6523660/app-debug.apk.zip)

**Comment by scoute-dich** [comment]
Hi. Thanks for reporting both issues. I left a test-apk in issue #507 If you have the time, you can test it.

This issue could Also be solved by latest changes. If not, can you please make a logcat, when the browser crashes.

**Comment by tusch001** [comment]
I have the same problem and downloaded the apk-debug.apk above to test. Unfortunately I get a parsing error when installing on Android 6.0.1

**Comment by Cwpute** [comment]
> Hi,
> 
> thanks for reporting. If you have the time, can you please test attached apk file (just rename it)?
> 
> If this does not solve the issue, can you please make a logcat, when the browser crashes?
> 
> [app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6523660/app-debug.apk.zip)

I'm not sure what to do. What do i rename it to ? How do i activate the logcat if i don't have any computer to plug my smartphone into ?

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6527753/app-debug.apk.zip)

Perhaps the attached apk was corrupt. Above there is a new one. You must remove ".zip" from the filename and save the apk file on your phone. Then open it with the internal file manager of your phone.

**_This test apk will be installed as a separate app. So no data will get lost. You can use it to test and then uninstall it._**

To take a logcat you do not need PC. There are several apps to that for you. Just search for "logcat" in F-Droid or PlayStore. Once you've installed such an app you can start a record. Then try to reproduce the issue. Then stop the recording. Then you can share it here.

**Comment by Cwpute** [comment]
It seems like the test-apk doesn't crash when i open a new blank tab !

**Comment by scoute-dich** [comment]
Ok, then it semms to be fixed with the next update.
