### ISSUE TITLE
(v7.4.3) need to add dark / black mode theme option

### ISSUE THREAD

**Issue by Ananas-Kuchen** [scoute-dich/browser#508]
The last time I installed an old version it had a dark / black theme mode (maybe 7.2 or something below it)

and in version 7.4.3 (f-droid) I can't find the option to activate the dark / black theme anymore

Can you add a dark / black theme to the application?

Thanks

**Comment by scoute-dich** [comment]
At the moment I only solve all functionial issues. Until then I'll not implement new features.

**Comment by scoute-dich** [comment]
But it is on the todo list ...

**Comment by Ananas-Kuchen** [comment]
> But it is on the todo list ...

It feels weird. you removed that feature but will bring it back

**Comment by scoute-dich** [comment]
That's because I changed the theme libraries from AppCombatX to Material Components. 

The new libraries must be implemented in an other way. That is something I must figure out first. But at the moment bug hunting is the first thing I want to do.
