### ISSUE TITLE
(request) the save website feature to "mht" format

### ISSUE THREAD

**Issue by Ananas-Kuchen** [scoute-dich/browser#509]
Can you add the option to save website as "mht" format?

I don't like to save as pdf. no different from firefox. the thing that I don't like is the image-based snippet of screenshots

Although "mht" is archive based. but the website that is saved still has the original element

Thanks

**Comment by Ananas-Kuchen** [comment]
and it's great if the save website can be in a custom location by default

**Comment by scoute-dich** [comment]
At the moment I only solve all functionial issues. Until then I'll not implement new features.

**Comment by Ananas-Kuchen** [comment]
> At the moment I only solve all functionial issues. Until then I'll not implement new features.

How sad. I really don't like saving web to pdf because it's no different from screenshots in image format 😔
