### ISSUE TITLE
New bookmarks are not shown in red-filtered bookmark view

### ISSUE THREAD

**Issue by snoopymat** [scoute-dich/browser#513]
If I had created a new bookmark, then it looks as if the app had tagged it with a red color point.
But if I apply the bookmark filter "Red" to the bookmarks, then this new bookmark is not shown. But it should be shown, because I expect to see the bookmarks with a red color point in the bookmark view filtered with option "Red".
Only if I edit this bookmark and assign to it the red color point (though it seems to be already there), then the bookmark will be shown afterwards in filtered with Red bookmark view. 

Occurs under Android 8.1.0 and under Android 10 (EMUI) with FOSS Browser 7.4.3 installed today from F-Droid via F-Droid app.

**Comment by scoute-dich** [comment]
This will be fixed with next update. Thanks for reporting.
