### ISSUE TITLE
Multiple Tabs all link to single page after...

### ISSUE THREAD

**Issue by Zehra** [scoute-dich/browser#514]
**Bug description:**
Tabs colored green as in indication of being selected/current will all link to a single page, regardless of content or title.

**Steps to reproduce:**
1. Open browser and open new tab. (Tests done with opening from bookmarks.)
2. When tabs number is 2 or greater, the section which lists the page title? (It's between the tabs and home/bookmarks section.) is moved to the side to select another of the opened tabs.
3. Open tabs section and select from the tabs one of the links.
4. Bug should appear when attempting to select another link which will incorrectly link to another page/tab.

FOSS Browser version: **7.4.3**

**Minor footnotes:**
- Tabs cycled change color to green as in **selected** tab when bug occurs.
- New tabs opened after bug trigger are not affected.
- Bug can be triggered again however.

**Comment by scoute-dich** [comment]
Is this still happening in Version 7.4.4?

**Comment by scoute-dich** [comment]
It will be solved with next update (v 7.5). If it will not be solved for you, please open a new issue for the new version. Thanks in advance.
