### ISSUE TITLE
Can't interact with url in address line

### ISSUE THREAD

**Issue by UksusoFF** [scoute-dich/browser#516]
In latest release version 7.4 can't do nothing with url in address line: select/edit/copy url.

After click on address line shows only page title. Page title also can't any text actions.

**Comment by UksusoFF** [comment]
Some cases:
Go to some url with mistake and got 404. Otherwise edit url it's needed to type it again.

Go to domain without https support. Also 404 and  again typing.

**Comment by UksusoFF** [comment]
Also when typed long text search it's truncated with dots. And can't see whats writing.

**Comment by UksusoFF** [comment]
Also can't paste any text from clipboard....

**Comment by tusch001** [comment]
I just wanted to open the same issue. Two additional use cases why I is important to have access to the navigation:

- With all the phishing emails out there people need a way to verify that they are also signing in with their own credentials in the right website. 
- When I have to make small changes on my own homepage (eg correcting a typo) I often go directly to the path, eg mywebsite.com/path/where/I/change/the/content. I do have a bookmark to the top domain which I open but at the moment there is no way to put the path in the navigation field.

Thanks

**Comment by Zehra** [comment]
Being unable to interact with the URL increases difficulty with navigation and creates security issues.

**Examples:**
* Search queries which specify number of return results.
Often it is quicker to modify the the query value, as bookmarking them would not make sense or be practical.
* Quicker navigation of specific sites
Site mentions they have docs and APIs on docs.example.com and api.example.com, and no previous bookmarks or links in site.
* General requirements to be able to view, copy, modify and paste links.
With various sites, manual modification of links provides easier navigation.
If redirects occur, it's easy to see where one is.
Apps may not open and require manual copy and paste of links.
* Page title provides little data at times and is relatively useless.
This may happen on various sites with titles like: _**example.com - my website**_
* Website URL changes, but links to website are not updated.
The links are all 404s and there is no relatively easy way of accessing them.

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6587684/app-debug.apk.zip)
Hi, perhaps anyone can test if this solves the issue. For me, using Android 11 it works.

**Comment by scoute-dich** [comment]
It will be solved with next update (v 7.5). If it will not be solved for you, please open a new issue for the new version. Thanks in advance.
