### ISSUE TITLE
URL/Address bar is behaving incorrectly

### ISSUE THREAD

**Issue by StOrmCatz** [scoute-dich/browser#519]
On my tablet running Android 7.1.2,  the URL bar is exhibiting three issues:
1. When typing in the URL bar,  it's not being recognized as a URL field so my keyboard (SwiftKey) is automatically adding a space after a period. This makes the address invalid and instead it performs a search.
2. After loading a page, when I select the URL bar it doesn't show me the actual address but remains as the Title of the page. This makes it impossible to adjust the address without typing it all over again.
3. Sometimes after inputting a value in the URL bar,  it occasionally doesn't do anything. This is probably related to issue #449, but here it's not a case where it's completely broken or no reaction

**Comment by scoute-dich** [comment]
Which version of FOSS Browser are you using?

**Comment by StOrmCatz** [comment]
> 
> 
> Which version of FOSS Browser are you using?

This is with the current latest version 7.4.4

**Comment by UksusoFF** [comment]
Seems it's duplicate: https://github.com/scoute-dich/browser/issues/516

**Comment by scoute-dich** [comment]
Thanks for reporting. I will release the update soon. This should be fixed.

**Comment by scoute-dich** [comment]
This will be fixed in 7.5. If not feel free to open a new issue. Thanks for contributing.
