### ISSUE TITLE
Bookmarks menu missing from long press

### ISSUE THREAD

**Issue by AL-Ghub** [scoute-dich/browser#520]
Since 7.4.4 a long press on Android icon no longer displays Bookmarks, instead I see "App Info".  I do not see an option to re-instate this useful feature.

I either was on 7.4.3 or 7.4.1 previously.  I get an error if I attempt to Downgrade.

Android Version 9

**Comment by scoute-dich** [comment]
There were some bugs concerning the shortcuts, when I changed android libraries. In the next time I'll not reimplement this. At the moment, I'm still resolving bugs and issues. Perhaps in the future (if there is more time) I'll reimplement. Sorry to say.
