### ISSUE TITLE
Go to HTTP protocol and internationalised domain not work

### ISSUE THREAD

**Issue by UksusoFF** [scoute-dich/browser#522]
Try go to:
* http://link.2gis.ru/EB8D3591/v4-android/20210601/samara/70000001048213541?http://app.adjust.com/c3oz9gh
* https://яндекс.рф

This not opened, but search.

7.4.4 version

**Comment by UksusoFF** [comment]
I'm try go to this link from github and it's work. But from android applications it's going to search :/

**Comment by scoute-dich** [comment]
This will be fixed in 7.5. If not feel free to open a new issue. Thanks for contributing.
