### ISSUE TITLE
Trackers blocking and prevent IP leaking options

### ISSUE THREAD

**Issue by amir28** [scoute-dich/browser#524]
Hello, at first I appreciate you for your great work but some features are still unavailable to use FOSS browser as my main browser.

It's worth to see options for disabling WebGL, WebRTC ,protecting the fingerprint and change timezone in this browser.
Thank you

**Comment by scoute-dich** [comment]
Hello.

WebRTC is not supported by FOSS Browser, since it uses the native Android webView to show content. So it's not necessary to disable it. To disable WebGL, it should be enough to disable JavaScript (I think).

Anyway, at the moment I'll not implement new features for several reasons.

**Comment by amir28** [comment]
WebRTC is supported by android WebView(lolipop and above) and is enable by default and also in FOSS Browser(you can just test it). And disable javascript just for WebGL is a little inappropriate because breaks many websites to even load.
I agree on which this works may should be on low priority but it should not be rejected
(Sorry if i've English mistakes)

**Comment by scoute-dich** [comment]
Ok, then I will disable WebRTC in next update, if I find a way. The thing about disabling WebGL is, that I have no idea how to do that. I even haven't learned developing in a course or school. I've learned this all in my free time on my own. So even if I would like, I do not have the knowledge and not the time to learn such things. I hope you understand.

If you are a developer, feel free to fork and make a pull request.

**Comment by amir28** [comment]
Now after some research and looking for webview settings in documents It seems google just allows developers to change a limited options of WebView and also if we had access to just something like chrome://flags of WebView, disabling WebGL, WebRTC, fingerprint and etc was not possible because it's not even possible even in a desktop Chrome(I thought it's possible but seems it only works by installing extentions) :///
Privacy seems a joke for google.

Thank you for your attention.
If someone thinks i'm wrong please correct me
