### ISSUE TITLE
Theme not completely applies

### ISSUE THREAD

**Issue by rancidfrog** [scoute-dich/browser#53]
Theming does not really apply at the moment.
I selected dark theme, grey|grey, but still theme is quite white:
Dialogs
![](https://i.imgur.com/qDwHxYA.png)
Tabs and Menu
![](https://i.imgur.com/2e0tMxJ.png)
Settings pop-up
![](https://i.imgur.com/2eCUjQg.png)
Settings
![](https://i.imgur.com/tcj2eTT.png)
Search pop-up
![](https://i.imgur.com/FyesEvk.png)
About page
![](https://i.imgur.com/ZNZs80A.png)

Having theme apply across all areas would be amazing

**Comment by scoute-dich** [comment]
Here it works with no problems...    But I will look, perhaps a problem with the strings translations...

**Comment by rancidfrog** [comment]
Also, styling suggestion for menu:
Add line separator between title and options
For example take the app GitPoint, 
![](https://i.imgur.com/RWhBG8L.png)
It has clean design and separators

Some places where can be added
![](https://i.imgur.com/as1Gu3w.png)

![](https://i.imgur.com/HCrp2nS.png)

![](https://i.imgur.com/EkfC2Oj.png)

![](https://i.imgur.com/bzs0MwP.png)

Maybe center titles?

**Comment by scoute-dich** [comment]
Menu with the submenus will be as they are now in the next release. Themes are the next I'll implement in the new version which will be based on Ninja browser.

**Comment by scoute-dich** [comment]
This should be fixed. Update is on his way. Since I switched to Ninja as new base of Browser please test the new implementations and open a new issue if there are further problems. Thanks for your patience.
