### ISSUE TITLE
Problem with history

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#534]
I think there is a problem with history. Even though I have deactivated it, sometimes a history seems to be created.
When I am searching something, results of this history are displayed. And when I click on one of these items a completely different site is loaded... Any ideas? I noticed that several times, but do not yet know, how to reproduce...

**Comment by woheller69** [comment]
Have not seen this anymore. Will reopen if needed

**Comment by woheller69** [comment]
Something is wrong there. Yesterday when I was testing the Favicon feature I switched on history.
Sometimes an entry does not match the URL behind.
So you see e.g. BR24 in history an when clicked it e.g. opens www.welt.de.
Maybe somewhere a notifydatasetchanged is missing?

**Comment by scoute-dich** [comment]
As I have less time at the moment, I will not merge the "favicon commit". I have not merged until now, and there are no problems. Sorry to say. I do not want more and more open issues.

**Comment by woheller69** [comment]
The favicon commit is not the reason for the problem with history...

**Comment by woheller69** [comment]
I just saw it there again because usually I have history off.

**Comment by woheller69** [comment]
I think it is related to this:
https://stackoverflow.com/questions/11407599/getting-web-page-title-from-setwebviewclient
"Sometimes it doesn't show the title. sometimes it shows title of previous page."

That is what I noticed. The url is there but the title is wrong
