### ISSUE TITLE
Not responsive address bar after multiple link copy&past actions (also browser doesn't reopen previous session)

### ISSUE THREAD

**Issue by IllusiveMan196** [scoute-dich/browser#535]
After opening couple videos on YouTube (to test browser) I've run in a couple issues:

- browser doesn't collapse "navbar" in full screen video view, as a result anything that's on screen edges, like video quality for example, can't be activated. To reproduce just open any YT video in full-screen view.
- after quite some fiddling with links and copypasting them back and forth browser managed to do whatever it did on the screenshot and became completely unresponsive ("black rectangle of nothingness" on screenshot is supposed to be either keyboard which disappeared or clipboard which didn't appear). Have no idea how to reproduce...
- it also doesn't renew previous session and new page opened by default is "about:blank" if "favorite page" setting is left clear. Just relaunch browser to reproduce this behaviour.

Android 10, WebView 91.0.4472.77

![ScreenshotFOSS](https://user-images.githubusercontent.com/29149835/123151419-1a6f7280-d46c-11eb-83e2-fada505c9a54.jpg)

**Comment by scoute-dich** [comment]
Please make for each issue a separate issue. And try to make it reproducible. Describe the steps to reproduce the issue. If the browser crashes, try to make a logcat.

> it also doesn't renew previous session and new page opened by default is "about:blank" if "favorite page" setting is left clear. Just relaunch browser to reproduce this behaviour.

This is the expected behavior. A "favorite page", means no startpage. Also FOSS Browser doesn't restore last opened tabs.
