### ISSUE TITLE
Restart app to apply changes appears even when nothing changes

### ISSUE THREAD

**Issue by rancidfrog** [scoute-dich/browser#54]
In settings,
The pop-slide-up "Restart app to apply changes" occurs on click instead of on setting changed.

![](https://i.imgur.com/tXDOrCL.png)

For example as soon as you click on Theme option the pop-up appears, before you select anything.
So, even if you click back button,  the pop-up is there

Also, another example - if you click a checkbox, i.e. App settings | Swipe, and then click again to uncheck it, pop up appears even though technically it shouldn't because nothing changed.

**Comment by scoute-dich** [comment]
Thanks for reporting all the issues and sorry for the late responses. At the moment I'm working on some big changes. I'm trying to use Ninja Browser as base and then implementing all of the functionality from my own work. If you want to test it, I can upload an apk file. But it's still a lot of work...

**Comment by scoute-dich** [comment]
This should be fixed. Update is on his way. Since I switched to Ninja as new base of Browser please test the new implementations and open a new issue if there are further problems. Thanks for your patience.
