### ISSUE TITLE
Request about forms data

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#546]
Can you please add ability not to save forms data

Thank you

https://developer.android.com/guide/topics/text/autofill

https://support.mozilla.org/bm/questions/813403

https://developer.android.com/reference/android/webkit/WebSettings#setSaveFormData(boolean)

**Comment by scoute-dich** [comment]
Saving form data is depreciated since API-level 26. So I will not use it. WebView supports autofill by default. I use KeePassX as autofill-service.

If you want to save login-data for websites, you can try to use JavaScript and cookies. On most sites this works.

**Comment by islam2hamy** [comment]
I need not to save forms data , it is saved now

**Comment by islam2hamy** [comment]
I need not to save forms data , it is saved now

**Comment by woheller69** [comment]
At the moment the browser is setting:

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            this.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_YES);         }

This would probably need to be set to NO, for older VERSION_CODES setSaveFormData(false) would be needed.

Would require a new setting in SharedPreferences

**Comment by islam2hamy** [comment]
So ,
You will do it as option ?

**Comment by scoute-dich** [comment]
Yes.

**Comment by islam2hamy** [comment]
It is not working in v.8

**Comment by islam2hamy** [comment]
android 7.1.2

**Comment by cauerego** [comment]
i need the exact opposite...

i find saving form data as nearly essential!

not only across sessions, but specially when going to another app and back, or rebooting phone.

love the fact you use KeePassx. we should definitely promote it more.

granted, saving form data might be a work better done by the keyboard... but i think 2 levels of data redundancy to be fair enough.

it's terrible to fill a single form, such as a github big report, filled with data, only to lose it for whatever stupid reason.

but at least here it's easy to manually backup with copy and paste... the main problem with manual backup is: it's not a real backup and you will always lose data to chaos.
