### ISSUE TITLE
Tab switching when swipe disabled

### ISSUE THREAD

**Issue by rancidfrog** [scoute-dich/browser#55]
There seems to be an issue regarding applying settings.
As if I enable Swipe in settings and click restart to apply, sometimes I need to do it twice for it to work.

Also, when Swipe is disabled the arrows, which I saw previously do not appear:
![](https://i.imgur.com/5QpfJLV.png)

I believe I saw earlier a left and right arrow, which appeared and all of sudden do not appear anymore.

Temporary hide arrows?
![](https://i.imgur.com/HF7GSk5.png)

I am currently testing latest release, and I saw them in this release, but now they do not come up.

Also, I do not see anymore the tab switcher at the bottom, is it disabled?

**Comment by scoute-dich** [comment]
At the moment I'm working on some big changes. I'm trying to use Ninja Browser as base and then implementing all of the functionality from my own work. Tab handling will be completely new. It'll be possible to open unlimited number of tabs. The arrow buttons will be replaced with one navigation button. If you want to test it, I can upload an apk file.

**Comment by scoute-dich** [comment]
Update is on his way. Since I switched to Ninja as new base of Browser please test the new implementations and open a new issue if there are further problems. Thanks for your patience.
