### ISSUE TITLE
Skip Redirects during Back/Forward Navigation

### ISSUE THREAD

**Issue by BrendonIrwan** [scoute-dich/browser#551]
For some reason, I can not reproduce this on Fennec/Firefox.

If you proceed with this redirection link (with caution):

`https://duckduckgo.com/l/?uddg=https%3A%2F%2Ff%2Ddroid.org%2Fen%2Fpackages%2Fde.baumann.browser%2F&rut=524540ebb098821456130e5ca886fe0efc353365795c35bbde28d364e4fa8aa7`

You should be brought to F-Droid's page of your application, which is good.
Now try going back, just to be brought back to the same page again, which is bad. Its difficult to navigate back further the history.

If the link doesn't work then try searching anything with [[html.duckduckgo.com/html](https://html.duckduckgo.com/html)], and each result should have a similar looking link.

This can happen on other browsers. But redirects can be skipped there by the following:
1. Tap and hold the Back button to pull up the navigation history, then
2. Select the appropriate entry.

**Comment by scoute-dich** [comment]
You can bring up history by opening the overview. In the settings, you can also set the history tab to open by default, when showing the overview the first time.

At the moment, I'm looking for a solution. But until now without success.

**Comment by BrendonIrwan** [comment]
A temporary solution: double-tapping the back button quickly works, as long as your tap rate defeats every infrastructure that connects you to the web.

**Comment by olifoss** [comment]
Recognized the same behaviour with Google News (since a couple of foss versions):

[Google News](https://news.google.com/topstories?hl=de&gl=DE&ceid=DE:de) 

When opening news links I can't get back by simple tapping once the back button.

The mentioned workaround "double-tapping the back button quickly" is my solution or I open the links in a new tab.

**Comment by scoute-dich** [comment]
This should work, when pressing back two times. Sometimes at the first time.

https://github.com/scoute-dich/browser/tree/master/app/build/outputs/apk/debug

Please can anyone test?

**Comment by olifoss** [comment]
Hi,

I'm sorry, can't install the apk. Paket installer error "can't install this app".

Best regards
Oliver

21.08.2021 23:32:52 Gaukler Faun ***@***.***>:

**Comment by scoute-dich** [comment]
I'll upload a new apk today here.

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/7031057/app-debug.apk.zip)

**Comment by BrendonIrwan** [comment]
Hello. I haven't been on my phone for weeks.

I've installed this build (uninstall stable first) and imported my settings over.

So far so good, I'll let you know if there's any abnormality.
