### ISSUE TITLE
Question about sp_remote

### ISSUE THREAD

**Issue by scoute-dich** [scoute-dich/browser#555]
Question about sp_remote:

The description says: Enable remote content, which is not directly from the website you are visiting.

But is this really true?
With that preference we are switching setDomStorageEnabled and this, as far as I understand allows the application to store page elements that could include user sensitive information. Setting the DOM Storage value to false will prevents local storage from being used. So it is not about "content" but about storage.

https://www.sevenforums.com/tutorials/106540-dom-storage-cookies-enable-disable.html
DOM Storage is often compared to HTTP cookies. Like cookies, Web developers can store per-session or domain-specific data as name/value pairs on the client using DOM Storage. However, unlike cookies, DOM Storage makes it easier to control how information stored by one browser window is visible to another.

In my view the description needs to be changed...

**Comment by BrendonIrwan** [comment]
I'm not sure how DOM storage has much to do with remote content in the first place? It's basically just a per-origin persistent storage I think?
