### ISSUE TITLE
Sorting of history ...

### ISSUE THREAD

**Issue by scoute-dich** [scoute-dich/browser#556]
... must be reversed.

**Comment by scoute-dich** [comment]
Start Site also.

**Comment by woheller69** [comment]
I reversed it already together with bookmarks, do you want to have it like before?

**Comment by woheller69** [comment]
Start site should be sorted by name. Default seems to be date. But date is always zero, that is what I used to distinguish between Start Site (Time 0), Bookmark (Time 1..123), History (Time >> 123)
Start Site sorting by date should therfore be removed

**Comment by woheller69** [comment]
Probably I am wrong, you are using ordinal not time for sorting start page by date, right? Time is 0.

if (action.addGridItem(new Record(title, url, 0, counter)))

Maybe addGridItem should be renamed addStartSite to be more consistent.

**Comment by scoute-dich** [comment]
I managed it. In StartTab the newest entry is now at the bottom (when sorting by date). Also in history the newest entry is now at the bottom.
