### ISSUE TITLE
After on screen keyboard is closed, half the screen is black

### ISSUE THREAD

**Issue by ksapp-dell** [scoute-dich/browser#558]
Hi,

When you type something in the address bar at the bottom, the keyboard pops up and the adressbar in now at about half the screen height.
That is normal as the keyboard covers the bottom part if the screen.
After typing is done we want to close the on screen keyboard with the ,back' button at bottom right.
By doing this, the keyboard will be closed, but the address bar stays in the middle of the screen and the keyboard just leaves a black area on the screen behind.
This seems to happen only when typing in the address bar of the browser and not on the website itself.
This issue happens not every time but quite often and I was not able to figure out exactly why. 
May be somebody has an idea about this.

**Comment by woheller69** [comment]
just had this as well. Needed to restart the app. New tab did not work either.

**Comment by scoute-dich** [comment]
Sorry, but I can't reproduce that. Which Android versions are you using?

**Comment by woheller69** [comment]
Android 10. I only had it once so far...

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6775702/app-debug.apk.zip)
I changed the screen configuration in the manifest. Perhaps, that helps.

**Comment by cbiere** [comment]
Maybe it's related, maybe it isn't: Since 8.0 the keyboard randomly doesn't come up at all when I click on an input field.

**Comment by scoute-dich** [comment]
I simplified the code concerning showing/hiding keyboard. Please test attached apk-file and report back.
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6790215/app-debug.apk.zip)

**Comment by ksapp-dell** [comment]
Hi, i will do that, but it may need some time as the issue didn't ocour regularly..

**Comment by scoute-dich** [comment]
You must rename it, and delete ".zip" from the filename. I can not upload apk-files here.

**Comment by ksapp-dell** [comment]
Hi, sorry that does not work I can't install the renamed file. It says ,App not installed when I try to install it.

**Comment by scoute-dich** [comment]
So here is a new one. Perhaps you must uninstall FOSS Browser before testing.
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6803749/app-debug.apk.zip)

**Comment by ksapp-dell** [comment]
Hi, sorry for coming back late - I was very busy with other things. I could install this one after removing the original app. I will test it now and come back. 
Thanks

**Comment by scoute-dich** [comment]
Just update to the current version.

**Comment by ksapp-dell** [comment]
For me this issue is closed now.
