### ISSUE TITLE
Clicking physical menu button does not always work

### ISSUE THREAD

**Issue by rancidfrog** [scoute-dich/browser#56]
Sometimes clicking physical menu button works like below for example,
![](https://i.imgur.com/fHoQzyG.png)

But, after a moments later clicking menu button does nothing for a while. Then, it works again.

Otherwise clicking menu in toolbar is needed,
![](https://i.imgur.com/bbJUT4l.png)

**Comment by scoute-dich** [comment]
At the moment I'm working on some big changes. I'm trying to use Ninja Browser as base and then implementing all of the functionality from my own work. In this version clicking the physical menu button should work. If you want to test it, I can upload an apk file.

**Comment by scoute-dich** [comment]
This should be fixed. Update is on his way. Since I switched to Ninja as new base of Browser please test the new implementations and open a new issue if there are further problems. Thanks for your patience.
