### ISSUE TITLE
App crash when opening pdf

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#563]
App offers to open pdf (probably it should not...)
When selected to open pdf the app crashes. Same with .docx

![Screenshot_20210704-134348_Android System](https://user-images.githubusercontent.com/68678880/124383675-ff9fc800-dccd-11eb-9aa5-0772e9694107.jpg)

**Comment by scoute-dich** [comment]
Can you provide the link?

**Comment by woheller69** [comment]
https://www.bmjv.de/SharedDocs/Publikationen/DE/Patientenverfuegung.html

**Comment by woheller69** [comment]
Here download of .docx leads to crash

https://www.bmjv.de/SharedDocs/Downloads/DE/Service/Formulare/Patientenverfuegung_Textbausteine_word.html

**Comment by woheller69** [comment]
Cannot reproduce it anymore. Maybe it was due to another change I had made in my own version.
