### ISSUE TITLE
Disable option for swipe up on toolbar to exit

### ISSUE THREAD

**Issue by rancidfrog** [scoute-dich/browser#57]
I keep exiting app due to the gesture swiping up.
Is there a way to disable it, as personally I prefer back button to exit?

Note: It seems like when you do the swipe up gesture, a new tab opens then app exits.
Just a weird observation

**Comment by scoute-dich** [comment]
Yeah, that's right. At the moment I'm working on some big changes. I'm trying to use Ninja Browser as base and then implementing all of the functionality from my own work. In the next version leaving the app will be handled in a better way. If you want to test it, I can upload an apk file.

**Comment by scoute-dich** [comment]
Update is on his way. Since I switched to Ninja as new base of Browser please test the new implementations and open a new issue if there are further problems. Thanks for your patience.
