### ISSUE TITLE
Privacy Enhancement

### ISSUE THREAD

**Issue by NSTAdventure** [scoute-dich/browser#573]
Feature:
1. Add community host:
- host to block all tracker
- host to block all annoying ads
(included invisible one)

2. Block all third party request
(Toggleable on and off)

Enhancement:
1. Java script toggle Enhancement allow you to toggle that from toolbar instead of setting
2. Java script noscript like feature allow user to block certain or specific js

@scoute-dich

**Comment by scoute-dich** [comment]
I do not want to add new features at the moment. I also do not want more icons on the toolbar. Even on small displays should be enough place to show the title of the website. You can almost toggle JavaScript from the "Fast Toogle Dialog". You can open it, by long pressing the overflow button on the toolbar.
