### ISSUE TITLE
[Request] Redesign of tab count that doesn't look like a notification

### ISSUE THREAD

**Issue by Hund** [scoute-dich/browser#578]
Currently, the tab count looks like a notification dot that show you the total unread messages you have. It's rather distracting and confusing.

![Screenshot_20210708-042337~2](https://user-images.githubusercontent.com/320498/124852404-8c83a380-dfa4-11eb-8962-dddc762e4ffe.png)

I would like to suggest the same appearance as Firefox.

![Screenshot_20210708-042351~2](https://user-images.githubusercontent.com/320498/124852422-93aab180-dfa4-11eb-81da-8973cfe12598.png)

Thanks!

**Comment by scoute-dich** [comment]
At the moment I will not do this. I don't have the time to figure out, how to do that, and I don't want more icons on the toolbar (I think three are enough). Also, I should do more for work, than for a  "freetime-project" ...

**Comment by Hund** [comment]
> […] I don't want more icons on the toolbar (I think three are enough).

I'm not sure how changing an icon is adding more icons.

> Also, I should do more for work, than for a "freetime-project" ...

I see. Thank you for your reply and your time! I guess this project is dead then.

**Comment by scoute-dich** [comment]
> I see. Thank you for your reply and your time! I guess this project is dead then.

That's not the truth. The project is not dead. I just have family and a job. As I use the browser daily, I'll of course working on issues and of course I'll update in future.

I just don't want to add new features at the moment.
