### ISSUE TITLE
Desktop view is set as default

### ISSUE THREAD

**Issue by olifoss** [scoute-dich/browser#583]
When I start foss, the desktop view is active.I've to manually switch to mobile view. When I then quit foss and start again, desktop view is active again

It only happens with my Android 9 phone. On my Android 10 phone is everything fine, opens with mobile view.

Would it be useful to have a option for the standard view?

Thanks.

Oliver from Germany. ♥️foss

**Comment by scoute-dich** [comment]
Are you loading a saved bookmark on start?

**Comment by olifoss** [comment]
No. On start I've choosen the bookmark-view in the options. See Screenshot.
![IMG_20210709_115205](https://user-images.githubusercontent.com/87170889/125059967-2eda7e80-e0ac-11eb-9e31-78b97cb4a859.jpg)


I use Version 8.0 from F-Droid.

**Comment by scoute-dich** [comment]
You can test following akp-file. 
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6791847/app-debug.apk.zip)

**Comment by olifoss** [comment]
Sorry, I'm not an android developer. I extracted the zip, don't know how to install it. Paket installer shows an error.

**Comment by islam2hamy** [comment]
Rename the file , remove .zip

**Comment by islam2hamy** [comment]
Mmm , it is show install error

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6803729/app-debug.apk.zip)
Here is a new one.

**Comment by islam2hamy** [comment]
App dosn't open after install

**Comment by olifoss** [comment]
I'm sorry, paket installer doesn't install the apk.

**Comment by olifoss** [comment]
I've deinstalled FOSS Browser (previously created backup). Then I can Install the test-apk. But it crashes when opening.

I installed again from F-Droid. Everything is fine, when I open "n-tv.de" I get the mobile Version. Then I imported the bookmarks from the backup. When I open "n-tv.de" from the bookmarks, I get the desktop version. 

Seems to be a bookmark related problem. Deleted the bookmark and saved it again. Then I get the mobile view.

**Comment by scoute-dich** [comment]
Ok. If that happens again with an other bookmark, just long press the bookmark and edit it. There you can save if desktop mode is enabled or not for that bookmark.

This is a new feature and some old bookmarks are saved with desktop mode enabled.

Sorry for the trouble.

**Comment by olifoss** [comment]
Thanks for your tip and the great feature "desktop mode". Missed it for a long time.

A further feature that I miss, could you place it?: browse forward. I have sometimes the situation that I browse back and realize that it was a mistake. Than I have no easy way to navigate to the previous page.

**Comment by scoute-dich** [comment]
Just check the gesture settings. You can assign a lot of gestures for the toolbar.
