### ISSUE TITLE
Keyboard doesn't show up when tapping on website fields

### ISSUE THREAD

**Issue by olifoss** [scoute-dich/browser#586]
Sometimes the keyboard doesn't show up when tapping on website fields (like search fields). Just happened now by writing this issue.

When I tap the URL bar the keyboard shows. Then tapping a field, doesn't get keyboard inputs, still the text in the URL bar is highlighted.

As a workaround I've to open a new tab and start typing a URL. When I switch back to the previous tab, the keyboard shows when tapping a website field.

I recognize this behaviour since Version 8.0.
My Keyboard: FlorisBoard from F-Droid.

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6803740/app-debug.apk.zip)
Does this solve the issue?

**Comment by olifoss** [comment]
I'm sorry, paket installer doesn't install the apk.

**Comment by cbiere** [comment]
olifoss: You have to uninstall the app before you can install the APK. However, be sure to backup your bookmarks and settings AND copy it to a location that won't be deleted on uninstall.

scoute-dich: I can still reproduce the issue with this APK as soon as I import my backupped data. So some setting seems to trigger this.

**Comment by cbiere** [comment]
The setting that triggers it is the Favorite (Homepage). As soon as I set it to about:blank or clear the setting, the keyboard doesn't show up. When I set Favorite to any HTTP or HTTPS URL, the keyboard issue is gone.

**Comment by scoute-dich** [comment]
That was the missing hint. Will be fixed with next update.

**Comment by ksapp-dell** [comment]
OK thanks for finding out. (-;

**Comment by olifoss** [comment]
Thank you. I've "about:blank" as homepage.
