### ISSUE TITLE
Can't open link externally

### ISSUE THREAD

**Issue by pritkr** [scoute-dich/browser#588]
I can't open zoom links in the  zoom app neither I can open YouTube links in YouTube app.

**Comment by scoute-dich** [comment]
Even long pressing the link → open with does not work? Or in the share menu → open link with?

**Comment by cbiere** [comment]
Share menu - Open link with... works for me but I'd really prefer if this happened automatically or if a dialog popped up as with other browsers and apps. Who would want to use YT in a browser when you have NewPipe?

**Comment by scoute-dich** [comment]
Ok. Will be fixed with next update.
