### ISSUE TITLE
[Bug] Apk files don't recognized as installation files after downloading

### ISSUE THREAD

**Issue by Kristinita** [scoute-dich/browser#59]
### 1. Briefly

If I download `apk` file in «Browser» and open it:

+ In «Browser» I can't install file without using file manager,
+ In another browsers I successful install app.

### 2. Steps to reproduce

I download Yappy `apk` file from **<http://apk-dl.com/com.mariussoft.endlessjabber>** via «Browser».

![Yappy](https://i.imgur.com/uTxVF1K.png)

I press do `Download complete` → file incorrect open for me in Osmand+ app, not in Apk Installer.

I open «Downloads» app → file, downloaded via «Browser», have icon as in text files; exactly the same file, downloaded from another browser, have an «Android» icon.

![Text Icon](https://i.imgur.com/skZCWvL.png)

### 3. Expected behavior

Successful installing `apk` file after downloading as in another browsers.

### 4. Not helped

1. I can't find external open source downloader, compatible with «Browser». GigaGet [**not compatible**](https://github.com/PaperAirplane-Dev-Team/GigaGet/issues/30) and [**discontinued**](https://github.com/PaperAirplane-Dev-Team/GigaGet). [**I can't find alternative**](https://forum.f-droid.org/t/alternative-for-gigaget-downloader/480).
1. I can't find open source alternative of default «Downloads» app. Yes, I can install `apk`, use any file manager, but it takes a time.

### 5. Hardware and software

+ ARK Benefit S401,
+ Android 5.1.1,
+ [**VERTEX**](https://4pda.ru/forum/index.php?showtopic=788444&st=80#entry56079362) ROM,
+ Browser 4.4 (latest F-Droid version at the moment).

Thanks.

**Comment by Kristinita** [comment]
Don't reproduce in [**Cyanogen 12.1**](http://4pda.ru/forum/index.php?showtopic=788444&st=60#entry55887596). Most likely, the problem in bad VERTEX ROM.

Thanks.

**Comment by scoute-dich** [comment]
I had this problem to with some ROMs. So indeed it seems to be rom related. Sorry for the late answer.
