### ISSUE TITLE
Shopping with eBay-app: No suitable browser found

### ISSUE THREAD

**Issue by olifoss** [scoute-dich/browser#591]
The eBay-app opens the Android standard browser when paying with PayPal. I've set FOSS Browser as default. Get an error: "no suitable browser found" from the PayPal Website.

When I switch to Bromite browser as default browser, then Bromite opens when checking out with PayPal. With Bromite there's no error.

**Comment by scoute-dich** [comment]
Can you give me such a link to test?

**Comment by olifoss** [comment]
Sorry, can't cppy the link. It is a PayPal-Button. By long pressing the button it is not possible to copy the link. The eBay-App shows by checkout this message (translated it to english: no browser found to open the link.

Seems to be dependend on the Android version. On my Android 9 phone everything works correct, foss browser opens. I just updated my second Xiaomi phone (Redmi Note 9) to Android 11, there exists the problem. Before on Android 10 it worked.

**Comment by scoute-dich** [comment]
Perhaps the ebay-App does send an intent, which can't be opened with FOSS Browser. It should open all intents starting with "http/https".

`<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="http" />
                <data android:scheme="https" />
            </intent-filter>`

I will do some research, but I can't promise anything. You could also try to use the mobile site of ebay with the browser. Less apps, less collected data.
