### ISSUE TITLE
Loading website interferes with typing in omnibox

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#594]
Open new tab and immediately start typing a search or url.
Even though webview should stop loading its startpage it does not. 
When it is finished with loading it overwrites the input you just started...

**Comment by woheller69** [comment]
I have a solution for this. Will add this, when you are done with the database stuff

**Comment by scoute-dich** [comment]
I won't revert the test commit. Perhaps on summer holidays I can going on to clean up this.
