### ISSUE TITLE
Better contrast for icons

### ISSUE THREAD

**Issue by gokulraam** [scoute-dich/browser#604]
Better contrast for icons on/off state in dark mode. Attached screenshot.
![Screenshot_20210722-183714](https://user-images.githubusercontent.com/40225391/126644508-34986428-8cbf-4a19-9414-4ddcfc457481.png)

**Comment by scoute-dich** [comment]
![Screenshot_20210723-221136](https://user-images.githubusercontent.com/3949944/126836210-598afa50-5b1e-449e-9fdd-e69e61d8ba0d.png)
Would this be ok?

**Comment by gokulraam** [comment]
Seems better.

**Comment by scoute-dich** [comment]
I know, there are troubles with the contrast. This is the way Android handles the new material themes.

I want to add different themes in the next version. Perhaps I can implement a high contrast theme.
