### ISSUE TITLE
Add MetaGer as search engine

### ISSUE THREAD

**Issue by EchedeyLR** [scoute-dich/browser#608]
MetaGer, mostly speaking in the English instance https://metager.org/, is a FLOSS search engine.

The main instances supported by the same project only acts as metasearch engine in this case.

Having it as an option would be great to promote FLOSS instead of having to edit manually the custom option which could prevent normal users from doing it.

**Comment by scoute-dich** [comment]
Since I worked on search machines yesterday, I implemented MetaGer as a option in the settings.

**Comment by scoute-dich** [comment]
Wait until next update.

**Comment by EchedeyLR** [comment]
Thank you :3
