### ISSUE TITLE
Download function error

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#614]
Describe the bug
Failed to download from https://nationsglory.fr/download

**Comment by scoute-dich** [comment]
Works for me, but , tries to download the file as "bin-file". In that case, just rename the downloaded file.

Which Android version are you using? Is out possible, that you must grant storage permission?

**Comment by Kita2345** [comment]
Android 5
downloads sometimes it doesn't work and sometimes it downloads

**Comment by scoute-dich** [comment]
On some sites JavaScript and/or cookies must be enabled to download. Have you tested this? Google drive for example is horrible to download...

Is there a specific url, which never works? Then you can provide it here.

**Comment by scoute-dich** [comment]
I need some hints to reproduce the issue.

**Comment by scoute-dich** [comment]
Another question: does the download dialog appear? Or is any other toast shown?

**Comment by Kita2345** [comment]
Download dialog appears but the download is not running it shows up as a
queue. On android 11 I downloaded the file as "bin file" but the download
didn't run, it showed up as try again later

Pada tanggal Jum, 30 Jul 2021 23.00, Gaukler Faun ***@***.***>
menulis:

**Comment by woheller69** [comment]
I think that is a problem on the download site:
DownloadManager: [314] Stop requested with status 503: Service Temporarily Unavailable
The server has a problem

**Comment by scoute-dich** [comment]
If there are further problems with downloading after the next update, please reopen a new issue.
