### ISSUE TITLE
Please put version 5 to f-droid

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#62]
Hi, The apk on f-droid is old version,would you please update it.
Thanks !

**Comment by scoute-dich** [comment]
There was an build error on the F-Droid side. I don't know the reason... Perhaps some missing resource files. I will try to push a new version code to Github. Perhaps it will work.

**Comment by scoute-dich** [comment]
I'll try to solve the opened issues before publishing the next update.

**Comment by scoute-dich** [comment]
I found the problem:
https://f-droid.org/wiki/page/de.baumann.browser/lastbuild_67

But I don't know how to solve. Any clues?

**Comment by flocke** [comment]
I am waiting for version 5 on F-Droid as well. Let me try and figure out what is going on. I use Gradle 3.0.1 in andOTP as well and it works somehow.

**Comment by flocke** [comment]
Nvm, just tried to build v5.0.1 locally and got the same error as F-Droid but it seems to be fixed in v5.1.

**Comment by scoute-dich** [comment]
Why do you think it is fixed?

**Comment by flocke** [comment]
Because I got the same error F-Droid had when trying to build v5.0.1 but I could build v5.1 without problems. We will have to see if F-Droid builds fine as well ...

**Comment by lishoujun** [comment]
https://f-droid.org/wiki/page/de.baumann.browser/lastbuild_68
`INFO: Creating log directory
INFO: Creating temporary directory
INFO: Creating output directory
INFO: Using git version 2.11.0
INFO: Building version 5.1 (68) of de.baumann.browser
INFO: Getting source for revision v5.1
INFO: Creating local.properties file at build/de.baumann.browser/local.properties
INFO: Creating local.properties file at build/de.baumann.browser/app/local.properties
INFO: Running 'prebuild' commands in build/de.baumann.browser/app
INFO: Cleaning Gradle project...
INFO: Scanning source for common problems...
ERROR: Found unknown maven repo 'https://jitpack.de' at build.gradle
INFO: Removing gradle-wrapper.jar at gradle/wrapper/gradle-wrapper.jar
ERROR: Could not build app de.baumann.browser: Can't build due to 1 error while scanning`

**Comment by flocke** [comment]
That should be easily fixed by removing the jitpack.io repo (which doesn't exist) from build.gradle.

**Comment by Bubu** [comment]
See #69

**Comment by lishoujun** [comment]
@scoute-dich   please release a minor version  ，let's check the fdroid build.
I think this time it well be all just fine 😄.

**Comment by scoute-dich** [comment]
@Bubu I'll look at it.

I released a miner version 5.1.1 yesterday... Let's wait and see what happens.

**Comment by lishoujun** [comment]
@scoute-dich  last release was not detected by f-droid.
i check they docs but don't know why.(english is my second language) so ... is they have a bug or we don't fit the rule?
https://f-droid.org/docs/Build_Metadata_Reference/#Update-Check-Mode

**Comment by scoute-dich** [comment]
Normally when a update is released, they detect it automatically. I don't know what went wrong this time. I will release a version 5.1.2.

F-Droid sometimes sucks. I often have trouble with my apps. But that's their policy. And all in all it's good. It gives the users more security when they build the apps on their own. In PlayStore everybody can upload an apk file. Even of the source code is public the user had no guaranty that thy the uploaded apk is build from source.

**Comment by Bubu** [comment]
https://gitlab.com/fdroid/fdroiddata/commit/3f0944acd0e96227777d73bea765d159186aaa10

Will hopefully be released in a day.

**Comment by lishoujun** [comment]
@Bubu  a wow thanks！

**Comment by scoute-dich** [comment]
Build was successful.

![](https://i.imgur.com/8SfOajH.png)
