### ISSUE TITLE
Option to stop auto play video

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#625]
Can you pleas add this option?

**Comment by woheller69** [comment]
is already implemented in current code. Should come with next release. It is active if you set "save data"

**Comment by woheller69** [comment]
should even work in published relese 8.1.2

**Comment by islam2hamy** [comment]
While browsing a site like facebook
Videos autoplayed
while "save data" is checked or unchecked

Android 7.1.2

**Comment by woheller69** [comment]
Videos should be stopped when loading page is finished, tested  e.g. on finance.yahoo.com

Maybe they are starting videos again and agein via javascript. 

In next version the implementation will be a bit different. Maybe it works then

**Comment by woheller69** [comment]
can you send a link where it happens

**Comment by islam2hamy** [comment]
https://m.facebook.com/NBE1898/

**Comment by woheller69** [comment]
for me all videos are stopped there even without save data...

**Comment by islam2hamy** [comment]
Mmm

**Comment by woheller69** [comment]
I think this can be closed. Webview does not allow preventing video autoplay in all cases.
We are stopping all videos when the page is loaded by injecting some Javascript code (requires Javascript on) in save_data mode.
But the webpage can start them again. And then we would need to distinguish if this was based on user action or not...
