### ISSUE TITLE
Bookmark filter list not shown on long click

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#629]
bottom_navigation.findViewById(R.id.page_2).setOnLongClickListener(v -> {
            show_dialogFilter();
            return true;
        });

does not work on Android 6.0.1.
When long pressing on the bookmark icon the dialogFilter is not shown.

**Comment by scoute-dich** [comment]
Can you find the cause? I only have a phone, running Android 11.

**Comment by woheller69** [comment]
I already tried and did not find the cause. I only have the idea that
setOnLongClickListener and setOnNavigationItemSelectedListener do not like each other:
 
       bottom_navigation.setOnNavigationItemSelectedListener(navListener);
        bottom_navigation.findViewById(R.id.page_2).setOnLongClickListener

For me it is not important I use the Android 6 phone only for testing

**Comment by woheller69** [comment]
I do not have an idea why, but it is working now...
