### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#632]
![Screenshot_2021-08-04-18-07-52_2](https://user-images.githubusercontent.com/87817690/128171746-714b7e50-3f01-4fe1-ae60-a2d909aa4f8d.jpg)

**Comment by scoute-dich** [comment]
Can you reproduce this? Here is an apk-file to test.
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6945878/app-debug.apk.zip)

**Comment by scoute-dich** [comment]
Duplicate of #642
