### ISSUE TITLE
gestures and text-edit-scrolling collide

### ISSUE THREAD

**Issue by marcusatiliusregulus** [scoute-dich/browser#633]
## setup:
i have the nav-bar on the bottom and swiping left/right on the nav-bar navigates through the history.

## problem:
when i edit the url and want to move the url eg. to the right (to get to the beginning of the url) it is interpreted as a gesture.

## expected behaviour:
do not interpret (at least not the left/right swipe on nav-bar) gesture while editing urls

## version:
8.1.2

**Comment by scoute-dich** [comment]
Should be fixed with next update.
