### ISSUE TITLE
Force close 

### ISSUE THREAD

**Issue by ksapp-dell** [scoute-dich/browser#639]
![Screenshot_20210805-222749_Lawnchair](https://user-images.githubusercontent.com/62463497/128416951-80d804a1-7da9-4152-bb1f-a853f2b1636e.jpg)
Hi,

the app crashes when I click in the address bar during a site is loading.
I have the debug version that was provided for testing (#558)
Regards
Samsung S7 Android 8.0

**Comment by woheller69** [comment]
should be different now. Loading is stopped when you click in the address bar

**Comment by ksapp-dell** [comment]
Yes  - I didn't see the update as I was using the debug app and F-droid didn't show any update due to that.
Everything s ok now.
Thanks for this nice browser).
