### ISSUE TITLE
Is that a bug or a feature?

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#646]
![Screenshot_20210807-221726_FOSS Browser](https://user-images.githubusercontent.com/68678880/128612915-8341497e-a573-4a73-b030-3613a7a3302a.jpg)

Startpage/Bookmarks use to be full width before...

**Comment by woheller69** [comment]
if it is a feature I would suggest to make the tab button with counter invisible. Now it is shown twice

**Comment by scoute-dich** [comment]
This does not happen on my phone. Not even in landscape. I changed nothing in the bottomSheetDialog.🤔

**Comment by woheller69** [comment]
Strange. I deleted all app data, but it comes back...
It shows bookmarks full width for the fraction of a second and then shrinks it.

**Comment by woheller69** [comment]
It seems to me they added an edgeToEdgeEnabled attribute to bottomSheetDialog ( 'com.google.android.material:material:1.4.0') which does not work properly and is always read as false. 

https://github.com/material-components/material-components-android/commits/master/lib/java/com/google/android/material/bottomsheet/BottomSheetDialog.java

So we should stay with 1.3.0 and wait for 1.5.0
