### ISSUE TITLE
Restoring bookmarks does not work properly

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#653]
In BackupUnit.java we have:

                if (!action.checkUrl(url, RecordUnit.TABLE_BOOKMARK)) {
                    list.add(record);
                }

So bookmarks which are currently existing (maybe with other settings for iconColor, or desktopMode) are not replaced with data from backup.
Is that intended? Otherwise we should delete all bookmarks first and then restore them.

**Comment by scoute-dich** [comment]
That is from the original project (Ninja Webbrowser). You are right. If the toast says "Current data will be deleted.", it should happen. I'll change this also for restoring the other stuff ...
