### ISSUE TITLE
Swipe to reload not working sometimes

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#654]
e.g here ( https://www.heise.de/newsticker/ ) if I use my tablet in landscape mode. This page obviously loads with a bit of zoom. When I make it small, swipe to reload works again. When rotating to portrait and back to landscape it also works.

I saw this in the new code:

     (!ninjaWebView.canScrollHorizontally(0))

Does this mean swipe to reload is not availabe if horizontal scrolling is possible, and if so, why?

**Comment by scoute-dich** [comment]
That happened while I improved the code to hide toolbar, when itmes on  a website were covered by the toolbar. Was my mistake. I'll change it.

**Comment by scoute-dich** [comment]
You can test it also. I do not use this feature (that's why you can change it in settings now).
