### ISSUE TITLE
content-autofill.googleapis.com

### ISSUE THREAD

**Issue by schoolprivacy** [scoute-dich/browser#657]
Hello

Everytime i start Foss Browser, i get connection attempts (a lot of attempts) to content-autofill.googleapis.com

I have Form Data unticked, but still getting spammed.

Am i missing something? or ?

Thanks

**Comment by scoute-dich** [comment]
Are you opening a website with auto-completion at start? Such as a search machine? Perhaps, the website itself opens such a connection.

**Comment by scoute-dich** [comment]
Please reopen if still actual.
