### ISSUE TITLE
Toolbar hides, but reappears if page is refreshed.

### ISSUE THREAD

**Issue by Zehra** [scoute-dich/browser#660]
In `Behavior/UI` the `Hide toolbar` option is not selected/checked.
The options in `Behavior` which are enabled are `Confirm browser exit` and `Swipe down to reload`.

The issue is the toolbar will disappear, while not being selected as an option.
I'm not sure of which conditions do cause the error, as it is seemingly random to an extent, but perhaps the above allows others to perhaps replicate it and possibly fill in the details regarding this bug.

**FOSS browser** version: `8.2`

**Comment by scoute-dich** [comment]
I think, I know how to solve this. Thanks for reporting.

**Comment by scoute-dich** [comment]
Will be solved with next update.
