### ISSUE TITLE
Be able to search through the history

### ISSUE THREAD

**Issue by KeronCyst** [scoute-dich/browser#668]
8.2 on LG G6 running Android 8.0.0:

I don't see any way to run a search through the app's history. This would be super-helpful.

**Comment by woheller69** [comment]
this is implemented, if history is active

**Comment by KeronCyst** [comment]
Oh, where is the button? My history is turned on but I can't find any magnifying glass or search text.

**Comment by woheller69** [comment]
there is no button. As you type in the normal search field entries from history will be shown when they match the search

**Comment by KeronCyst** [comment]
Ohhhhhh, got it! Cleverly minimalistic.
