### ISSUE TITLE
'open links in background' doesn't work

### ISSUE THREAD

**Issue by iynere** [scoute-dich/browser#67]
expected behavior is, I select a blank tab for my link to open in, the new tab popup closes, and I'm back to my original page. however, even with 'open links in background' checked, I'm immediately sent to new tabs when I open one. running a custom Android 7 rom on an LG G3. love yr app. thanks !!

**Comment by scoute-dich** [comment]
I think you're at version 4.+. The current version is 5.1. Since version 5 I use Ninja Browser as the base for Browser. This is also fixed in latest version. If not open a new issue after you tested this with latest version.
