### ISSUE TITLE
Copy link icon is malfunctioning

### ISSUE THREAD

**Issue by KeronCyst** [scoute-dich/browser#670]
8.2 on LG G6 running Android 8.0.0:

![Capture+_2021-09-06-16-36-39](https://user-images.githubusercontent.com/13827055/132261847-b8a4a403-5137-45e7-b014-bc6e01d83c8f.png)

The chainlink icon here does nothing when I tap on it. Shouldn't it copy the link to its left or do something?

By the way, I keep having to go to F-Droid to remind myself of what version of FOSS Browser I'm using. I can't seem to find it anywhere in the app itself. I would imagine that this would be put into the circled "i" in the upper-right corner of the settings.

**Comment by woheller69** [comment]
the icon has no function. You can use share link and copy afterwards
