### ISSUE TITLE
Website table is cut off (in desktop and mobile views)

### ISSUE THREAD

**Issue by KeronCyst** [scoute-dich/browser#671]
8.2 on LG G6 running Android 8.0.0:

On this page: https://dictanote.co/pricing

I see the following in either mobile or desktop view (I can't pan any more to the left so I can't read the cutoff text):

![Capture+_2021-09-08-10-58-47](https://user-images.githubusercontent.com/13827055/132543936-be8dad62-4ed7-431a-bae9-de1214d45fc9.png)

**Comment by woheller69** [comment]
for me it works with desktop mode

**Comment by scoute-dich** [comment]
For me also. Does this also happen on other sites?

**Comment by tusch001** [comment]
Works also for me
@KeronCyst: Is your Android webview app up to date? On which version are you?

**Comment by KeronCyst** [comment]
The latest, 93.0.4577.62. Does it have something to do with Android 8.0.0?

**Comment by woheller69** [comment]
that is ok, have the same on Android 11

**Comment by tusch001** [comment]
I played around with the website:  

enabling and disabling desktop mode and zooming in. Guess what: Now I have the same problem as @KeronCyst and can't go back to view the full width in mobile mode. The only way to see the full panel is first in mobile mode to zoom out (very small font) and then switch to desktop mode.   
  
And: The same happens in Firefox for Linux Desktop when resizing the window to a small width!

---

There is lots of CSS3 `display:flex` property in the code with fixed and flexible widths and max-widths set for child elements. The outer container is set to 100% but marked by firefox as `overflow`. From personal experience I would guess that somewhere is a problem there that triggers the browser's behaviour.

**Comment by scoute-dich** [comment]
As it seems website related, I'll close this issue.
