### ISSUE TITLE
Website non-text content not rendering

### ISSUE THREAD

**Issue by KeronCyst** [scoute-dich/browser#672]
8.2 on LG G6 running Android 8.0.0:

On this page: https://money.cnn.com/data/fear-and-greed

None of the charts show up, even with JS enabled and filters set to only block UH. I'm not sure of what else I could try to get them to appear.

![Capture+_2021-09-08-14-34-40](https://user-images.githubusercontent.com/13827055/132574174-45e133d8-1cab-483d-8889-62b024f259e1.png)

**Comment by woheller69** [comment]
does not work for me either. I switched everything off including Adblock and Fingerprint protection. No idea.
It works with DuckDuckGo but not with Jelly - both are based on Webview

**Comment by tusch001** [comment]
The missing images are loaded with inline css as background images. Unfortunately it is only a http address (no https). So I thibk they are rightly blocked by the browser.

**Comment by tusch001** [comment]
@dev
Don't waste your time fixing this. We want a secure browser. It's 2021.

**Comment by KeronCyst** [comment]
Wow, how dumb of them to not use HTTP. We can't force the browser to add an S, huh? lol. Thanks for the catch.
