### ISSUE TITLE
Cannot collapse keyboard while viewing history

### ISSUE THREAD

**Issue by KeronCyst** [scoute-dich/browser#675]
8.2 on an LG G6 running Android 8 0.0:

1. Start typing in the address bar to bring up historical links
2. Try to retract the keyboard with the Back button, to see more historical links at a time
3. The keyboard stays visible and the history disappears instead

**Comment by scoute-dich** [comment]
That seems to be the normal behavior of autocompletetextview. I found no way to disable or override this behavior.

**Comment by tusch001** [comment]
sorry for asking:
On my keyboard there is a `hide` key to minimize the keyboard. Works great. But only here it not ony hides the keyboard but also closes history (without me hitting the physical `back` button).  
Should that not be two different functions?

**Comment by scoute-dich** [comment]
I'm also annoyed of this behavior. But at the moment I found no solution. But the good thing to report is that @woheller69 fixed a big in the "history view" which caused some forever closes.

**Comment by woheller69** [comment]
maybe with a custom AutoCompleteTextView

https://stackoverflow.com/questions/27086538/autocompletetextview-remove-soft-keyboard-on-back-press-instead-of-suggestions#27087677

**Comment by woheller69** [comment]
CustomAutoCompleteTextView does not work either, at least not as in the above example.
It collapses the keyboard but unfortunately also the history.

**Comment by scoute-dich** [comment]
This is fixed with the latest commit.
