### ISSUE TITLE
8.3

### ISSUE THREAD

**Issue by franco27** [scoute-dich/browser#676]
Hello. 
Where can I download and install the update or version 8.3?
On F-Droid, it's still version 8.2. 
And on the Playstore, you stopped offering updates.

thank you

**Comment by woheller69** [comment]
F-Droid needs a few days...

**Comment by woheller69** [comment]
something went wrong when they tried building the app.

https://monitor.f-droid.org/builds/log/de.baumann.browser/118

**Comment by woheller69** [comment]
Probably caused by this change:

 dependencies {
    -    classpath 'com.android.tools.build:gradle:4.2.2'
    +    classpath 'com.android.tools.build:gradle:7.0.2'

**Comment by franco27** [comment]
ok thank

**Comment by woheller69** [comment]
Failed again this night. 

https://f-droid.org/wiki/page/de.baumann.browser/lastbuild_118

**Comment by woheller69** [comment]
we probably need to change build.gradle to Java 11

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
       }

**Comment by woheller69** [comment]
seems to work now. Issue can be closed
