### ISSUE TITLE
Allow encrypted backups (for Seedvault, etc.)

### ISSUE THREAD

**Issue by graphonymous** [scoute-dich/browser#679]
## Allow encrypted backups
[Seedvault](https://github.com/seedvault-app/seedvault) and other backup apps can't backup app data.
Please implement this [example](https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71) provided by the Seedvault wiki.
Thanks

**Comment by woheller69** [comment]
[app-debug.zip](https://github.com/scoute-dich/browser/files/7274419/app-debug.zip)

Rename the file to .apk and install. Does encrypted backup work with it?

**Comment by graphonymous** [comment]
I can't install the renamed file. It just says 'App not installed.' (It shows the Icon and Name but then doesn't recognize the file as an APK). I'm on LineageOS 18.1 (Android 11).

**Comment by woheller69** [comment]
[app-debug.zip](https://github.com/scoute-dich/browser/files/7274473/app-debug.zip)

another try

**Comment by graphonymous** [comment]
Backing up and restoring works now. Thanks.
![IMG_20211003_225226](https://user-images.githubusercontent.com/89678894/135771173-b1daaeb1-5a9d-459e-8a0b-698861df918c.jpg)
