### ISSUE TITLE
changing font size doesn't seem to work 

### ISSUE THREAD

**Issue by iynere** [scoute-dich/browser#68]
I can see no noticeable difference between 70% & 130% zoom. would be great to have more options than just 3 discrete zoom levels- maybe a slider ? or honestly a reader mode would be fantastic, that's all I would change font size for anyway

**Comment by scoute-dich** [comment]
I think you're at version 4.+. The current version is 5.1. Since version 5 I use Ninja Browser as the base for Browser. Changing font size isn't implemented anymore. If you like the feature a lot, I can add it again in the next version.

**Comment by scoute-dich** [comment]
Will be added again in next version. Only increasing text size will be possible.
