### ISSUE TITLE
Add option for displaying navigation bar on top

### ISSUE THREAD

**Issue by vatonbero** [scoute-dich/browser#681]
Hi,

Is there a chance to get option to show navigation bar on top? Right now it is fixed at the bottom and while that is better for usability, i find it easier to navigate using top bit of the screen (it is a habit).

Thank you

**Comment by woheller69** [comment]
I was used to it as well but now I like the bottom navigation a lot more.
I guess you should not expect that this is going to be changed - it would break too many things

**Comment by scoute-dich** [comment]
At the moment I will not implement new features.

**Comment by pc00per** [comment]
> I was used to it as well but now I like the bottom navigation a lot more. I guess you should not expect that this is going to be changed - it would break too many things

But isn't "I like" a personal preference. The same goes for being the toolbar on top right?
There are people who come from chrome, who expect that url bar to be on top.
