### ISSUE TITLE
Add option to honor html meta tag "theme-color"

### ISSUE THREAD

**Issue by vatonbero** [scoute-dich/browser#682]
Hi there,

There is a meta tag which allows you to change color of navigation bar, if you set it up during web development. The HTML meta tag used for this is:

```
<meta name="theme-color" content="#MyColorInHexFormat">
```

This will color application nav bar into deveoper desired color, to create better UX. This is supported by Firefox and Google chrome (thus, all Blink forks, unsure about webkit ones). One note here: Google Chrome supports this option only if you have a valid certificate and website uses https.

More details can be found here: https://developers.google.com/web/fundamentals/design-and-ux/browser-customization/#color_browser_elements

**Comment by scoute-dich** [comment]
At the moment I will not implement new features.
