### ISSUE TITLE
Implement Super Cache to prevent FOSS Browser from reloading the previously viewed webpage

### ISSUE THREAD

**Issue by nucleone** [scoute-dich/browser#683]
A suggestion to implement super cache to prevent FOSS Browser from reloading the previously viewed webpage.

Without an implementation of super cache, after viewing a webpage and tapping on the phone's back button to return to the previously viewed webpage, the experience is jittery and data consuming as the previous page reloads upon return.

**Comment by woheller69** [comment]
"The replacement technology for AppCache is the Cache API, which requires a service worker. "

Seems to be a lot more than a one-liner...

**Comment by woheller69** [comment]
I hope @scoute-dich will accept all the changes I made :-)
