### ISSUE TITLE
Websites gets cleared after inactivity

### ISSUE THREAD

**Issue by Hund** [scoute-dich/browser#686]
If I open any website(s) and then leave them open, they're then closed when I open the web browser some time later. I don't have this issue work other clients.

I'm running Android 11 on a Pixel 3a. Current version of Foss browser is 8.3 from F-Droid.

**Comment by comamondo** [comment]
Same Problem for me. When FOSS Browser gets killed by system after a while in background, all opened tabs are gone. Tried everything in (cache)settings, but nothing helps to avoid it. Android 11 on Xiaomi device with Miui-EU rom.

**Comment by woheller69** [comment]
Maybe a vendor specific problem. The app should better not be killed in background...

     https://dontkillmyapp.com/

**Comment by comamondo** [comment]
> Maybe a vendor specific problem. The app should better not be killed in background...
> 
> ```
>  https://dontkillmyapp.com/
> ```

Okay, but other browsers keep their tabs nevertheless.

**Comment by woheller69** [comment]
The question is why the other apps do not get killed and ours is.
If an app gets killed I think it is quite normal that it starts from scratch.

**Comment by comamondo** [comment]
Also with no restrictions for "background activities" and "autostart" allowed I switch to other apps and after 5 minutes go back to FOSS Browser. All tabs are closed and I'm back to the github page. For sure any other browser (NB pro, Vivaldi, ungoogled chromium, brave) gets also killed by the system but keeps cached the info about opened tabs somewhere... Just telling because I really like the design and functions of this FOSS browser. unfortunately I'm not a good coder, so this "complaining mode" is my only contribution... sorry ;)

**Comment by woheller69** [comment]
can you try what happens with the other browsers if you kill them with a task manager or swipe them away in the overview of open apps? Do they still start with the old open tabs?

**Comment by comamondo** [comment]
yes they do. In any way you kill them: long press back button: "force closed Vivaldi" or whatever. Or killing by swiping or "X kill-all-button" in the the "recent" overview. They all keep their tabs on next time  open.

**Comment by woheller69** [comment]
Can you please try if this works? Rename from .zip to .apk
(Export your bookmarks before...)
This saves the open tabs when the app is paused and restores them if the app gets killed.

[app-release.zip](https://github.com/scoute-dich/browser/files/7479180/app-release.zip)

**Comment by comamondo** [comment]
nope, same behavior. didn't kill actively, just switched through some other apps.

**Comment by woheller69** [comment]
Then I do not have an idea... For me it works if I kill the app with a taskmanager.
It does not work if I kill it brute force by swiping it away in the list of open apps.

**Comment by woheller69** [comment]
Another try

[app-release.zip](https://github.com/scoute-dich/browser/files/7481078/app-release.zip)

**Comment by woheller69** [comment]
this should even survive a reboot

**Comment by comamondo** [comment]
yes, a difference is now, when I use the home button and don't kill it actively. At least last half hour or so it keeps the tabs open now. I'm gonna report long-term behavior...
(I'm afraid a little that it will drain battery then, but we will see)

**Comment by scoute-dich** [comment]
Hi, here I'm back again.

At the moment FOSS Browser does not restore previous opened tabs, when getting reopened. Also that FOSS Browser gets killed in there background when the resources are needed is the normal behavior. In most scenarios it's not a good idea to overwrite this.

To restore tabs at restart is a feature often requested. I only want to implement new features if they really work. And I do not have the time to do this.

With current changes I switched to a profile based settings behavior. Much code got changed, so I believe @woheller69 code improvements are obsolete. The reason why I switched to profiles are such features which messed up the logic of the settings: normal settings, whitlists, saved settings in the bookmark.

Sorry for answering so late and for any argue with latest code changes.

**Comment by woheller69** [comment]
I think the changes I made can still be applied and I am quite sure they work.

But first @comamondo should report if this fixes the problems.

**Comment by comamondo** [comment]
It works good now. Even if I kill it with "long press back button" or from the "recent" screen the tabs come back. Only when I **quit** the browser from its **own menue**, then the tabs disappear \o/
 I do not see an extraordinary battery drain, yet and I let the battery settings (in Xiaomi smth. special) to default.

I appreciate very much the idea of different profiles! But actually there should also implemented the restoring of tabs anyways IMHO.
