### ISSUE TITLE
All files get downloaded with .bin file extension

### ISSUE THREAD

**Issue by Lucas32578** [scoute-dich/browser#690]
Whenever i download a file, it gets saved with the .bin file exrension instead of its actual file extension. I havent tested this in many different places yet, but its happened with every file ive downloaded so far. I am on android 10, i installed FOSS browser from fdroid, and my phone model is an LG G8X ThinQ running the default install of android. Changing the file extension back to what it should be fixes the file, but its a bit annoying especially if you download lots of files.

**Comment by woheller69** [comment]
see #459
