### ISSUE TITLE
Can we get back to chips with images instead of text?

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#696]
![192_168_2_154_2021-11-07_19-12-37](https://user-images.githubusercontent.com/68678880/140656766-dde29e3b-f45d-4dc8-9a66-15ca445d191b.png)

I liked the small icons for adblock, fingerprint protection, etc which we had some months ago a lot more...

Instead of the domain name, e.g "heise.de" we could show the Favicon

What is the function of the crossed out shield at the bottom left?

If I can help, let me know.

**Comment by woheller69** [comment]
as a kind of tutorial what each icon means we could show a toast, e.g. "Adblock on", "Fingerprint protection off" when someone clicks on the icon.

**Comment by scoute-dich** [comment]
I think this would be ok. If we use the same icons in the settings for the profiles we don't even need a toast.

I use icons from material design icons. So first we must check, if there are matching icons for all settings. But there are many ...

**Comment by woheller69** [comment]
But a Toast with LENGTH_SHORT would not hurt and the strings are already there. When I started using the browser I did not know what the icons were for and a Toast would have helped...

**Comment by woheller69** [comment]
![Screenshot_20211109-190647_FOSS_Browser](https://user-images.githubusercontent.com/68678880/140980084-ac3183ee-b04e-4f56-8314-ea2f66d629ae.png)

I noticed you brought back the icons :-) 
But a Toast instead of the text is now even more necessary...

**Comment by woheller69** [comment]
Unfortunately on small devices this still does not look nice. With the toasts it is understandable now but I think round buttons (like profiles) with icon only would look much better than an icon and the first 2 letters of a word...
Other ideas?

**Comment by woheller69** [comment]
the DOM storage icon might be misunderstood as storage permission on SD card

**Comment by scoute-dich** [comment]
Here you can choose from:
https://materialdesignicons.com/

**Comment by woheller69** [comment]
I would suggest:
DOM
![database](https://user-images.githubusercontent.com/68678880/141186948-f1e4d00d-8e72-4965-bdbb-8c514e1ca8a2.png)

Popup
![tooltip-text](https://user-images.githubusercontent.com/68678880/141186987-f8d5ce9b-a9d9-44df-9761-394498b1e344.png)

Adblock
![block-helper](https://user-images.githubusercontent.com/68678880/141187000-33bc3dde-3bb4-43e7-803c-81c87e6ed8a9.png)

**Comment by woheller69** [comment]
And maybe for request save data (?):
![leaf-circle-outline](https://user-images.githubusercontent.com/68678880/141187918-feb2b310-60f7-44a5-8d86-4ca8cb28edb6.png)
![car-cruise-control](https://user-images.githubusercontent.com/68678880/141187938-40888cf5-7c48-444b-89bc-214882f8fcfc.png)

**Comment by scoute-dich** [comment]
Done (but not pushed):

**Comment by hurzl** [comment]
Can we get the descriptions back? I don't have the time to learn all these option symbols.

**Comment by scoute-dich** [comment]
Just long press an icon and the description will appear.

**Comment by hurzl** [comment]
Yes this is the first part of the time I don't have ...

**Comment by woheller69** [comment]
I think it is a lot better than the  cut off descriptions, which did not help either. 
This would only work on screens with at least 1000dp width

**Comment by hurzl** [comment]
I can't remember the descriptions being cut off on a tablet. Why not add a simple switch?
