### ISSUE TITLE
Link not opening

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#708]
When clicking on one of the images at

https://www.vivara.de/vogelfutter/energieblocke

the links are not opening. Only works with long click -> open in new tab

**Comment by scoute-dich** [comment]
It seems website related. This seems not even with firefox working on my laptop. SO I don't think, that we can do anything.

**Comment by woheller69** [comment]
With Firefox it works on my PC

**Comment by scoute-dich** [comment]
Perhaps some Fedora things missing on my machine ...

**Comment by woheller69** [comment]
also works with Android DuckDuckGo Browser which is also based on webview

**Comment by woheller69** [comment]
With Chrome on Android working, with Jelly browser not

**Comment by woheller69** [comment]
Maybe a redirect issue: If I capture the url in shouldInterceptRequest it looks like 


    https://www.vivara.de/googledatalayer/product/get/id/1222?_=1636558858058

instead of 

    https://www.vivara.de/energieblock-mit-mehlwurmern

**Comment by tusch001** [comment]
The html behind the "link" is not an `<a>` tag but a `<button>` element which originally was supposed to make fields in forms better stylable and accessible (compared to `<input>` fields). I even remember vaguely that in the beginning in some browsers they were (are?) not clickable, only accessible via keyboard. Touch support and browser compatibility varies. Not sure if you can do something about this.

**Comment by woheller69** [comment]
as DuckDuckGo is also based on webview it can be done for sure.
The question is how they do it and if it makes sense. I don't think it makes sense to fix if the website is buggy

**Comment by woheller69** [comment]
It is an AdBlock issue. It works with the old browser version ( before the new profiles ) if I switch off AdBlock and reload the page.

It does not work with the latest source code with profiles...

**Comment by woheller69** [comment]
Found the problem. On the device where it is not working I have AdAway installed. If I disable it, everything is fine :-)
