### ISSUE TITLE
make baidu as the default search engine for chinase

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#71]
hi ,in china we can‘t access google .
so if it is first time user open browser after an all new install.  AND the system language is chinese.
please use baidu as the  default search engine。

**Comment by scoute-dich** [comment]
I didn't know that. Of course I'll do that. I think of bottomdialog, from where the user has the choice to set baidu as default search engine or not.

**Comment by scoute-dich** [comment]
`Locale.getDefault().getLanguage().equals("zh")`

Is "zh" the right for Chinese?

**Comment by lishoujun** [comment]
@scoute-dich   
works fine for me。

in first install  my search engine is baidu.   
then i change search engine to bing. and reinstall browser. it is still bing.
so I think it is fine and no bug .

thanks!
