### ISSUE TITLE
[Feature Request] Add gesture option for page refresh/reload

### ISSUE THREAD

**Issue by fingerpad** [scoute-dich/browser#719]
A new gesture option to refresh the page would be very useful. In my case i would like to use the Swipe down gesture for the Toolbar to reload the page.

**Comment by woheller69** [comment]
why don't you use the "normal" swipe down to reload which is implemented?

**Comment by fingerpad** [comment]
That requires scrolling to the top of the page, and losing my place on particularly long pages.

**Comment by scoute-dich** [comment]
I think this is a good idea and not much work. Even, if we need a new string, which I don't like because of the translations.

I don't use the swipe down function, because I have some websites where you can move the content and every time i move it up, the site reloads.

**Comment by scoute-dich** [comment]
Will be there with next update.
