### ISSUE TITLE
I think  The goal and  The aim are too alike

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#72]
In readme :
 The goal is to provide a lightweight but power full browser. The base is "Ninja" (https://github.com/mthli/Ninja). The aim of the project is to provide a simple and light wight but powerful browser with a nice looking user interface.

it is not clean. I don't like. just leave  a goal or an aim will be better.

**Comment by scoute-dich** [comment]
Yes. I didn't see that while writing. I will change this.

**Comment by scoute-dich** [comment]
Changed it.
