### ISSUE TITLE
paste & go

### ISSUE THREAD

**Issue by pawel-em** [scoute-dich/browser#723]
would be very useful to have 'paste & go' context option on address bar

**Comment by scoute-dich** [comment]
Would it be also helpful to have an explicit "FOSS Browser entry" in the context menu of marked text to open this text in a new tab with one click? This would be much easier for me.

**Comment by pawel-em** [comment]
If it is much easier, then let's do it that way :)

**Comment by scoute-dich** [comment]
Will be there with next update.
