### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by JM480** [scoute-dich/browser#726]
Can you add Material You support so the browser follows the system colors and matches the new ui design?
https://m3.material.io/ This link contains information on Material You.

**Comment by scoute-dich** [comment]
I tried it, but since it is still in alpha, I would wait. But yes if it's ready, I'll implement it.

**Comment by scoute-dich** [comment]
If you have a link to a documentation or tutorial how to implement, you can share it here.

**Comment by scoute-dich** [comment]
Will be in next update. Just needs some more improvements.
