### ISSUE TITLE
dhl paypal 

### ISSUE THREAD

**Issue by BrunoKatz** [scoute-dich/browser#727]
I very much like this app and use it as my daily broswer on several lineageos devices with microg

Even though I generally avoid using paypal, I sometimes want to use it to pay dhl-shippments.
This used to work with foss browser, but doesn't anymore (even though I enable cookies, javascript etc.)

On desktop/firefox I had similar problems and had to change a setting concerning firstparty-isolation, maybe this is somehow similar?
https://support.mozilla.org/ha/questions/1277038

Thanks for helping !!

**Comment by woheller69** [comment]
I never had a problem. Which version do you have? 
Maybe an issue with microg?
What is happening? Does opening Paypal not work at all?

**Comment by BrunoKatz** [comment]
Version is 8.3 (installed through fdroid)

Sometimes In the past it worked, not sure when this was, though.

Problems occurred this week.
I'm not 100% sure about the details, if I remember correctly this is what happend:
1. paypal opened
2. I entered my username/email 
3. and then it loaded without end.

Will make screenhots next time I have occasion to try this.

**Comment by scoute-dich** [comment]
Perhaps you can try it again after updating to latest version (8.4.1).

**Comment by scoute-dich** [comment]
Does this still happen?

**Comment by BrunoKatz** [comment]
sorry, I didn't have occasion to test it yet again, but promise to do so as soon as possible :)

**Comment by BrunoKatz** [comment]
working! Thank you !
