### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#728]
I just installed the latest version 8.4 from F-Droid on my tablet.
I am not sure if profiles are working correctly.
E.g. I have welt.de in "Protected".
When I open welt.de I would expect the icon at the bottom left to change from "Standard" to "Protected".
Also I would expect the overflow menu after long click to reflect the settings of the currently opened page.
In an older development step at least the icon at the bottom left changed.
Is that intended? Do the icon and overflow menu always show the status of the current tab and not of the settings currently being used for the opened page? I think that is what most people would expect...

**Comment by woheller69** [comment]
If I set the profile of the tab to "custom profile" at least the icon at the bottom reflects the profile of the page (protected for welt.de)
But if the tab profile is set "standard" this is not the case.

**Comment by scoute-dich** [comment]
> If I set the profile of the tab to "custom profile" at least the icon at the bottom reflects the profile of the page (protected for welt.de)
But if the tab profile is set "standard" this is not the case.

I found the issue. Will be pushed soon.

> Also I would expect the overflow menu after long click to reflect the settings of the currently opened page.
In an older development step at least the icon at the bottom left changed.
Is that intended? Do the icon and overflow menu always show the status of the current tab and not of the settings currently being used for the opened page? I think that is what most people would expect...

Yes, that's intended. The upper section in the fastToggle dialog shows the current settings of the current profile. The next section shows, if the active profile is overwritten by the settings of the domain. Perhaps there should be a headline like "overwritten by ...".

**Comment by woheller69** [comment]
I think "overwritten by" is important...

**Comment by woheller69** [comment]
I still think most people will not understand that settings shown for the current profile are not the ones being applied if the settings are overwritten by the domain.
What about showing the settings for the current profile in a  disabled state while they are overwritten? Maybe a transparent grey overlay on top or a different color scheme for the buttons?

**Comment by scoute-dich** [comment]
Done. The buttons are now completely disabled, when overwritten.
