### ISSUE TITLE
after fullscreen video navigation bar is partly hidden

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#737]
Android 6
Browser: 6+ up to 6.4

I don't know what's triggering it: Coming back after video playback in fullscreen sometimes the lower 30% of the navigation bar is below the visible screen. Not always, don't know the trigger (livestream?). Opening a new site or a new tab doesn't make the navigation bar fully visible. If I then hit the back button I can shortly see the full navigation bar until it partly hides again. Closing the app and the problem is gone.

Maybe you can reproduce it  
(The website needs JS activated because they can't make proper css for small screens):  

[this Tagesschau-Livestream - any tagesschau.de livestream will do](https://www.tagesschau.de/inland/wieler-spahn-135.html), full screen, back button to normal website view. Now nav bar is patially hidden.

It's been a while around, I just don't watch many videos.

Thanks

**Comment by scoute-dich** [comment]
Since I drop support for Android 6, I'll close this issue. Sorry.

**Comment by JM480** [comment]
I have a similar issue on version 8.8 on my tablet running Android 10 and my phone running LineageOS 18.1. The navigation bar is never hidden even for fullscreen videos. Here is a video on BitChute to test to see if anyone else has the same issue. https://www.bitchute.com/video/R4WZvw51QE8I/
