### ISSUE TITLE
Feature request: import old whitelist as trusted sites list

### ISSUE THREAD

**Issue by danielhatton** [scoute-dich/browser#738]
Since the replacement of whitelists with profiles in release 8.4, it would be really useful to be able to import (e.g.) the cookie whitelist from a pre-8.4 settings backup as the trusted sites list in a post-8.4 version, please.

**Comment by scoute-dich** [comment]
That should be possible, if you rename the list to import to "list_protected", "list_standard" or "list_trusted".

**Comment by danielhatton** [comment]
Thanks, @scoute-dich .  Can I do that by editing in a text editor the bit of the backup file that says `WtableWHITELISTWHITELISTCREATE TABLE WHITELIST`, or do I need to install sqlitebrowser?

**Comment by scoute-dich** [comment]
A text editor should work. You can also add domains manually in the lists. If the lists are ready just put them on your sd-card in the directory "Documents/browser_backup/" and restore them.

**Comment by danielhatton** [comment]
@scoute-dich We seem to be talking about backups in different formats.  My most recent backup consists only of a file called `Ninja4.db`, although it does contain the URLs from my cookie whitelist.

**Comment by tusch001** [comment]
No additional installation. Just make backup and rename (or add content of) `export_cookie_list.txt` to `list_trusted.txt`. Restore. Worked for me.

**Comment by danielhatton** [comment]
@tusch001 Yeah, that's the file that doesn't exist in my latest backup, but I've probably got enough information to reconstruct it by copying and pasting from the `Ninja4.db` file.  Thanks.

**Comment by danielhatton** [comment]
Success, by the following sequence of steps:
- copied and pasted the cookie whitelist URLs from the backup `Ninja4.db` into a new file `list_trusted.txt`
- replaced the separator character sequences between the URLs in the new `list_trusted.txt` with newlines
- placed this new `list_trusted.txt` in the `Documents/browser_backup/` directory on the Android device where I run FOSS Browser (I don't have an SD card: the full pathname was `/storage/emulated/0/Documents/browser_backup/list_trusted.txt`);
- through the FOSS browser settings menu, restored the trusted sites list from backup.
