### ISSUE TITLE
Please add incognito

### ISSUE THREAD

**Issue by enwokoma** [scoute-dich/browser#74]
Most browsers today have incognito (even Firefox and Chrome) where a user is able to turn on incognito and browse privately without the browser saving history or any other thing from that session!

**Comment by scoute-dich** [comment]
Since not saving the history would be the inker advantage, I could immurement a toggle for saving history...

**Comment by enwokoma** [comment]
Well, this doesn't sound bad actually!

**Comment by scoute-dich** [comment]
Will be in the next update, also an option to decide the position of the button.
