### ISSUE TITLE
Is it really save data?

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#740]
1- set settings :
<a href="https://ibb.co/d6Pmfmc"><img src="https://i.ibb.co/HYthKh2/Screenshot-de-baumann-browser.png" alt="Screenshot-de-baumann-browser" border="0"></a>

2- set home page :
Google.com

3- make shore that you didn't open the app at the day of test .

4- open the app.

5- open this site as ex. and browsing it:
https://m.facebook.com/GCWCeg/

6- see how many MB is used .

**Comment by woheller69** [comment]
in save data videos should not play automatically without user action. Other than that you can consume lots of data....

**Comment by woheller69** [comment]
and "save-Data" is sent in request headers. But if this is respected is decided on the other end.

**Comment by islam2hamy** [comment]
In the example Above , the app use more than 3MB , is that expected?

"save-Data" enable
"Show images" disable

**Comment by woheller69** [comment]
does the page show a video?

**Comment by islam2hamy** [comment]
No

**Comment by woheller69** [comment]
maybe Facebook needs to download a lot of data from your phone ;-)

**Comment by islam2hamy** [comment]
:-)

**Comment by scoute-dich** [comment]
I also think this is Facebooks fault.
