### ISSUE TITLE
Folders for bookmarks?

### ISSUE THREAD

**Issue by nucleone** [scoute-dich/browser#750]
Any chance you can re-visit the idea of implementing folders for bookmarks? 
I understand that colours are a sort of a sorting feature, but I believe that, in addition to grouping similar bookmarks, folders are perhaps more needed as a means of grouping non-similar bookmarks in order to avoid clutter in the bookmarks/home list, i.e. for bookmarks that are not often used. Or any other use case. Folders are great. :)

**Comment by scoute-dich** [comment]
By long pressing the bookmark icon on the toolbar you can open the filter dialog an the choose a color. Since you can edit the colors (enable/disable, give them custom names), what's the difference to folders? Isn't that just an other name for a category?

So the question is: What folder feature are you missing? Perhaps I can implement it.

**Comment by nucleone** [comment]
You're right, those are typical folder features, and they work great. 
Honestly I didn't know that colors could be renamed, and that is the feature that changes everything for me. I can't believe I didn't figure it out earlier.

Ok, if we consider a color as a folder containing bookmarks, then the only thing missing is the ability to sort the bookmarks in a custom way, i.e. to order them by drag&drop vertically. But that needs to raised under a new issue. Or is that another thing I missed? :)

Anyway, thanks for the fantastic work so far.



On December 7, 2021 8:46:08 PM GMT+01:00, Gaukler Faun ***@***.***> wrote:
>By long pressing the bookmark icon on the toolbar you can open the filter dialog an the choose a color. Since you can edit the colors (enable/disable, give them custom names), what's the difference to folders? Isn't that just an other name for a category?
>
>So the question is: What folder feature are you missing? Perhaps I can implement it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scoute-dich/browser/issues/750#issuecomment-988216674
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by franco27** [comment]
I saw that you can't add colors

**Comment by scoute-dich** [comment]
Yes, that's right. Perhaps in the future, when I've more time, I'll make a better folder implementation. But at the moment we have to live with it, as it is.
