### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by JM480** [scoute-dich/browser#751]
There should be an option to allow websites to show notifications. This would be useful for email and messaging websites.

**Comment by pc00per** [comment]
The broswer is just a chromium web frontend. So, it won't gonna have push notifications service.

**Comment by scoute-dich** [comment]
@pc00per is right. I don't know a way to show notifications of a website. If anyone knows a solution, feel free to reopen the issue and post the solution as a comment.

**Comment by pc00per** [comment]
> @pc00per is right. I don't know a way to show notifications of a website. If anyone knows a solution, feel free to reopen the issue and post the solution as a comment.

Not possible, unless trichrome library implemented, which itself has 30megs of proprietary libraries (which is anti-foss)
