### ISSUE TITLE
Tab manager button too small & oddly placed

### ISSUE THREAD

**Issue by pc00per** [scoute-dich/browser#758]
My smartphone's rounded padding is too much that the tabs button (which is located on the bottom left) cuts out, which I have 'hit & miss' difficulty triggering the tabs menu.
I'd like to have "swipe up toolbar to open tab manager" just like chrome, instead of the existing whatever quick menus.

**Comment by pc00per** [comment]
> Just open the gesture settings there you have much possibilities for setting custom actions, for example open tab preview.

Ah thankyou. Got it.

**Comment by scoute-dich** [comment]
![Screenshot_20211209-213103_FOSS Browser](https://user-images.githubusercontent.com/3949944/145471581-e8f344c7-4cd4-49b8-8f26-3188207d137f.png)
What about this? I think all buttons on the right would be better...

**Comment by pc00per** [comment]
> ![Screenshot_20211209-213103_FOSS Browser](https://user-images.githubusercontent.com/3949944/145471581-e8f344c7-4cd4-49b8-8f26-3188207d137f.png) What about this? I think all buttons on the right would be better...

Ya. That's lil better. Also I'm thinking, that bookmark icon is not necessary, caz you can access it from menu, or just keep a gesture for that.
