### ISSUE TITLE
darksky.net doesn't zoom or scroll

### ISSUE THREAD

**Issue by StickyDigit** [scoute-dich/browser#763]
On LOS 18.1, both unofficial on a Samsung S4 mini, and official on a Nexus 7 2013 (flox).

When I load up darksky.net, the page loads, complete with slippy map.

On the Samsung I've not had it scroll or zoom at all, in either desktop or mobile view.

On the Nexus, in mobile view, it scrolled at first load, and the slippy rain radar map worked momentarily, but immediately after that neither the page nor map would move. Subsequent loads failed to scroll at all.

Switching to Desktop view on either device, the slippy map seems ok and all elements appear to work, but the page cannot be zoomed or scrolled.

**Comment by StickyDigit** [comment]
Forgot to say. That's with today's F-Droid build. 8.5.2

**Comment by scoute-dich** [comment]
After loading the website in desktop mode, it seems that zooming works fine. After zooming in or out in the map, it stops to work.

Until now I did not found a problem in FOSS Browsers code. Does the site work correctly with other browsers?

**Comment by StickyDigit** [comment]
Yes it works in others, in both mobile and desktop modes.
-- 
Sent from a phone. Please excuse my brevity.

**Comment by scoute-dich** [comment]
:-(

**Comment by pc00per** [comment]
Yes. I can confirm this. The site's map does behave strange. Not in other web based broswers.

**Comment by cauerego** [comment]
sadly, foss browser have many related zoom and styling issues. going through duck.com image search also features those issues very distinctly.

**Comment by cauerego** [comment]
oddly i couldn't edit in this image in my previous post.

![Screenshot_20220221-112957](https://user-images.githubusercontent.com/560418/154947221-e1e953bd-b654-4915-a526-9f0472382ab1.png)

https://duckduckgo.com/?q=ncase.me&t=h_&iar=images&iax=images&ia=images&iai=https%3A%2F%2Fdomain.me%2Fwp-content%2Fuploads%2F2019%2F08%2Fnc5-1024x506.jpg

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue. With the next update, there will come a lot of layout changes and improvements.
