### ISSUE TITLE
Auto complete URL or URL suggestions

### ISSUE THREAD

**Issue by jerryn70** [scoute-dich/browser#78]
It will be great if we have a feature of url suggestions. Example if I type the starting letter of the url "f" the browser will suggest some most popular URLs like facebook.com etc etc .

Firefox focus has that feature. Its great and time saving . And we can also add our personal list  for quick access.

**Comment by scoute-dich** [comment]
As discussed in #19 this will not be implemented. It would be to much trouble. Workarounds:

- enable search suggestions on your preffered search engine
- pin often used websites on the startpage

Sorry.
