### ISSUE TITLE
suggestion: link to clipboard

### ISSUE THREAD

**Issue by franco27** [scoute-dich/browser#782]
hello

Maybe a bug when I try to delete (erase) the link in the address bar, it reappears immediately.

However I select all the link and this problem occurs every time. (When I select the link entirely).
Usually the second time the link is removed from the address bar.

Could you include a function that would allow the opening of the internet browser to open the link that is in the clipboard. A window that would prompt the user to do so or add a "paste and go" menu.

Thank you in advance for considering the suggestion.

Translated with www.DeepL.com

**Comment by scoute-dich** [comment]
I do not really understand. Can you attach screenshots? Also, which FOSS Browser Version are you using? Which Android version?

**Comment by franco27** [comment]
thank you for answering. yes, Android version
8.5.2 , F-Droid

1. I select the whole URL in the address bar and click to delete 
2. The URL is displayed again, after deleting
3. I repeat the deletion operation, selecting the URL again, in the address bar.
4. Usually the second time, the URL is completely deleted. 

I use on the keyboard, the button to select everything. And each time, I am obliged to repeat the operation.

**Comment by franco27** [comment]
I give you a screenshot
![GridArt_20211214_183614320](https://user-images.githubusercontent.com/31793920/146050614-d8ca4de6-1f54-414a-857c-f349b899b42a.jpg)

**Comment by scoute-dich** [comment]
Perhaps it's a issue with you're keyboard. I do not have the problem. You mustn't delete the text. Just start typing.

**Comment by franco27** [comment]
yes , if i write a letter and then delete it. and i paste the website address that's in the clipboard.
i don't have that problem anymore.

Even going through the Android menu , I have this problem. thank

**Comment by scoute-dich** [comment]
SO I can close this issue? If not please reopen.

**Comment by franco27** [comment]
some internet browsers offer to open, through a window, the link of a web page that is in the clipboard.
it is not in your plans to include this very practical feature.
 
or add a "paste and go" menu

thank you very much for your web browser
