### ISSUE TITLE
Feature request: install PWA

### ISSUE THREAD

**Issue by aprilmay** [scoute-dich/browser#787]
It would be great to be able to install Progressive Web Apps (PWA)

**Comment by scoute-dich** [comment]
Of think PWAs can't be installed inside a browser. They can be opened. For example: https://pwa.zdf.de/

This site works as described here: https://web.dev/zdf/

**Comment by aprilmay** [comment]
I think there's a misunderstanding about PWA and service workers. The idea is to be able to use a web page as a standalone app, while still running in the browser but it's quite transparent to the end user.

See here: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs .
This was added in Fennec here: https://bugzilla.mozilla.org/show_bug.cgi?id=1212648
