### ISSUE TITLE
Nightview doesn't stick

### ISSUE THREAD

**Issue by cbiere** [scoute-dich/browser#789]
Using FOSS Browser 8.5.2 nightview doesn't stick. New tabs are opened in dayview. This used to work perfectly in the past. It seems I missed few updates as I had used FOSS Browser from Google Playstore, so I cannot pinpoint which release broke it. I've also reset the app completely but this didn't fix it. My phone is set to permanent dark mode and I use dark mode in every app that supports it.

OS: LineageOS 18.1
Device: Xiaomi Mi A1

**Comment by scoute-dich** [comment]
At the moment I'm testing there next release which fixes this.

**Comment by scoute-dich** [comment]
I removed Play Store support because of Goggles strict policy what developers should do and what they should not do.

F-Droid, of course, is still supported.

**Comment by Golbinex** [comment]
Nightview is still broken. In 8.4 version, nightview was still enabled after restarting the app.
In 8.6 version, nightview gets disabled after restart.

**Comment by hurzl** [comment]
It's still there. Tabs are saved, but not their settings including dark mode.

**Comment by scoute-dich** [comment]
Also in v8.7?

**Comment by hurzl** [comment]
Yes, even if yesterday 8.6 was the latest I got via F-Droid.
