### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by CaptainFrosty** [scoute-dich/browser#792]
I was wondering if it's possible to either get the browser to trust certificates in the Android store, or upload one to its own store? I'd like to be able to filter its HTTPS traffic with my system-wide proxy. I know it's possible on pretty much all of the Firefox-based forks using a hidden menu, but this browser uses WebView, correct? I'm not as familiar with Chromium stuff.

**Comment by scoute-dich** [comment]
This feature will not be implemented.
