### ISSUE TITLE
Desktop view

### ISSUE THREAD

**Issue by shmueldabomb441** [scoute-dich/browser#794]
Is it possible to force desktop view of a site? A video streaming site doesn't let me stream if I have a mobile ( _must_ get the app).

**Comment by scoute-dich** [comment]
If you save it as bookmark or start-site-entry, you can save desktop settings. Just long press an entry in the list and click "Edit".

**Comment by shmueldabomb441** [comment]
When I click edit it only brings up a bottom sheet to change the title.

**Comment by shmueldabomb441** [comment]
Nevermind, I was using an outdated version
