### ISSUE TITLE
Bitwarden login completion wrong

### ISSUE THREAD

**Issue by juxuanu** [scoute-dich/browser#799]
When trying to get my passwords filled in by Bitwarden, it detects the app name and not the site URL. This means that it never automatically finds the credentials for any web page, as it always tries to find login credentials for "de.baumann.browser".

**Comment by scoute-dich** [comment]
That's strange. I suppose you've enabled autofill feature in the settings? For me with keePassDX all URLs get recognized properly.

**Comment by juxuanu** [comment]
![Screenshot_20211221-093950_FOSS_Browser.png](https://user-images.githubusercontent.com/24759034/146898838-acdc6d26-21c6-4cbf-87cc-7591f88f2d7d.png)

![Screenshot_20211221-093903_FOSS_Browser.png](https://user-images.githubusercontent.com/24759034/146898860-87ff038f-c2b9-46e7-a342-b79831ce9f61.png)

When clicked on the Bitwarden option, it shows "No items found for de.baumann.browser".

**Comment by pfrogond** [comment]
Happens to me as well, I guess its because bitwarden thinks the browser is just a webview for some app, rather than standalone browser.

**Comment by scoute-dich** [comment]
The webview itself is register as important for autofill. So all login fields should be recognized by a password manager. This works well with my password manager.

Does this also happen on other WebView based browsers?

But I'll look into this in the next days.

**Comment by pfrogond** [comment]
Unfortunately, I don't know any other webview based browsers nor could I find one (except this one of course).

**Comment by pc00per** [comment]
> The webview itself is register as important for autofill. So all login fields should be recognized by a password manager. This works well with my password manager.
> 
> Does this also happen on other WebView based browsers?
> 
> But I'll look into this in the next days.

Yes. All webview based broswers should support autofill services bydefault.

> Unfortunately, I don't know any other webview based browsers nor could I find one (except this one of course).

There are some. Duckduckgo, Via (proprietary), are two popular ones.

**Comment by pfrogond** [comment]
> There are some. Duckduckgo, Via (proprietary), are two popular ones.

Thanks, DDG is not working at all with bitwarden and Via the opposite (without a problem). The thing is, bitwarden works with FOSS browser, it just registers the app for autofill and not the actual webpage.

**Comment by Morphior** [comment]
I have the same problem, Bitwarden still recognizes any website as "de.baumann.browser". I would really appreciate if this got fixed, this browser is amazing!

**Comment by pc00per** [comment]
The only current workaround, is to either search the website manually from bitwarden search I guess.

**Comment by Tealk** [comment]
Just encountered the same problem, hope there will be a solution at some point.

**Comment by pc00per** [comment]
This will never get fixed, unless @scoute-dich starts testing with Bitwarden

**Comment by panbroggi** [comment]
Hi, as far as I understood, the browser needs to be added to the list of browsers to let Bitwarden parse the URL. For example, Lightning Browser is supported (se the related issue+commit https://github.com/bitwarden/mobile/issues/110).

**Comment by mapperr** [comment]
Hi everyone, just to add my case:
with Password Store as the autofill service I always get "FOSS Browser" as the autofill search term, instead of the website domain name.
Autofill works fine with Fennec.

**Comment by juxuanu** [comment]
I think you need to ask Bitwarden (and other password managers) to add this browser to the allow list.

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues which I will not work on for the time.
