### ISSUE TITLE
Background audio playback stutters

### ISSUE THREAD

**Issue by cbiere** [scoute-dich/browser#800]
When FOSS Browser plays audio in the background, the sound starts to stutter immediately. Changing the performance profile of the smartphone doesn't seem to make any difference. Other audio playing apps don't have this issue. In contrast to Chrome which buffers a couple of seconds before it starts playing, FOSS Browser starts playing instanteously. So I suspect, allocating a larger buffer would fix this. BTW, showing playback controls in the notification area would also be helpful.

Example streams: https://www.deutschlandfunk.de/livestream-100.html

Device: Xiaomi Mi A1
OS:LineageOs 18.1

**Comment by cbiere** [comment]
After updating to 8.6 today, all streaming links are unusable with FOSS browser. They don't show a rudimentary player at least not in a way that's recognizable and usable. I've tried multiple Webview implementations (system, beta, canary) but it didn't make a difference. It's still okay in Chrome.

Playback still works on various podcast websites. 

Also the new background audio playback button doesn't seem to have any effect.

**Comment by scoute-dich** [comment]
1. There's nothing I can do against the stuttering.
2. The button in the fast rifle dialog should work in v8.7.
3. Thre is no way to show media controls in a notification. The only thing I could do would be a notification to open FOSS Browser.

**Comment by cbiere** [comment]
Ok, I see. Other browsers based on Webview behave the same.

**Comment by scoute-dich** [comment]
Notification will be there with next update (just to open FOSS Browser fast).
