### ISSUE TITLE
Rotating display acts like a restart

### ISSUE THREAD

**Issue by cbiere** [scoute-dich/browser#801]
When I rotate the display using the hovering button in Android 11, FOSS Browser acts as if the app had just quit and restarted. Unless Reload Tabs is activated, you're back to the homepage. Reload tabs however seems to win over "clear data on exit". When I quit the browser I really want it to forget all tabs, history and come cookies. Rotation shouldn't interfere with this.

**Comment by scoute-dich** [comment]
Does this also happen on v8.7 (which was released today on F-Droid)? Because I can't reproduce it.

**Comment by cbiere** [comment]
I've updated to 8.6 — not 8.7 — from F-Droid today. The behavior is unchanged. I've reset the app to default settings, too. When I'm on any site, rotation causes loading of the browser's homepage.

**Comment by franco27** [comment]
I also confirm that there is no version 8.7 on the F-Droid site. It's the 8.6 that was released today.

**Comment by nucleone** [comment]
I can also confirm that version 8.7 is not on F-droid. Instead, I received an update to version 8.6.

**Comment by scoute-dich** [comment]
Now the update arrived. Actually I wanted F-Droid to skip 8.6 ... I'd the issue solved?

**Comment by cbiere** [comment]
No difference. Same behavior as before.

**Comment by woheller69** [comment]
what is the hovering button in Android11? Does it also happen when rotating the whole device?

**Comment by woheller69** [comment]
maybe "screenLayout" needs to be added to configChanges in manifest?

**Comment by cbiere** [comment]
The rotate button is shown and explained here:
https://www.bestusefultips.com/how-to-enable-auto-rotate-screen-in-android-11/

The issue occurs with automatic rotation enabled, too.

**Comment by scoute-dich** [comment]
> maybe "screenLayout" needs to be added to configChanges in manifest?

I'll test this and provide a test apk here later today.

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/7809135/app-debug.apk.zip)

Here to test. Just delete ".zip" from the file name.

**Comment by cbiere** [comment]
Yes, this works.

**Comment by pc00per** [comment]
> When I rotate the display using the hovering button in Android 11, FOSS Browser acts as if the app had just quit and restarted. Unless Reload Tabs is activated, you're back to the homepage. Reload tabs however seems to win over "clear data on exit". When I quit the browser I really want it to forget all tabs, history and come cookies. Rotation shouldn't interfere with this.

Welp, I can't reproduce it too. OP is right. Your device or android has something to do with it.
