### ISSUE TITLE
[Bug]: app-link (market://) is not trigerred on click.

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#806]
Go to https://m.okcashbag.com/frontTemplate/frontTemplateMobileGate.mocb?tplSeq=f8a9c6e319e089598f023e9d07a7dfe0
Click on
![image](https://user-images.githubusercontent.com/87817690/147374097-fe16e3b5-f6d6-4278-9e94-ae3aa1066a1f.png)

**Comment by scoute-dich** [comment]
Should be solved with next update. If not, feel free to reopen the issue.
