### ISSUE TITLE
non-http fallback URL not handling

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#807]
Visit: https://studio.click.godaddy.com/FVXM/f2c4755d
Dialog open in another app is not shown.

**Comment by pc00per** [comment]
Yes. Link redirections are not yet supported.
![Screenshot_20220110-014632_Settings](https://user-images.githubusercontent.com/83843264/148699207-80498a5d-5c87-4e3e-a1bb-fb4c24df745d.png)

**Comment by scoute-dich** [comment]
I'll close this issue. PLease follow #874 . At the moment I have no idea how to solve this problem.
