### ISSUE TITLE
Back/forward cache _info

### ISSUE THREAD

**Issue by nucleone** [scoute-dich/browser#811]
This is just to let you know what I meant by '_super cache_' in my earlier communication.
It's actually called back/forward cache (**bfcache**) and here's a link describing it, along with detailed explanations of how to implement it, what to observe, and what to watch out for, in case you ever decide to implement it.

https://web.dev/bfcache/ 

The biggest advantage of bfcache, in addition to smooth page transitions and a seamless browsing experience, is the fact that a lot of data is saved, as previously viewed pages don't need to be reloaded each time you go back/forward.

P.S. Thanks for the excellent **v8.7**.

**Comment by scoute-dich** [comment]
I'll not implement this. This feature interferes with the way FOSS Browser initializes the profiler settings.

**Comment by nucleone** [comment]
I regret this, it's probably the only major thing missing in the browser, one that would make make it complete.
But of course, it's your decision and I respect that.
Great work so far.



On December 27, 2021 6:22:35 PM GMT+01:00, Gaukler Faun ***@***.***> wrote:
>I'll not implement this. This feature interferes with the way FOSS Browser initializes the profiler settings.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/scoute-dich/browser/issues/811#issuecomment-1001666308
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
