### ISSUE TITLE
Click to call, email and live TV not working 

### ISSUE THREAD

**Issue by shaikhsadi2** [scoute-dich/browser#812]
When Clicking on the phone number and email number on my website is not working

https://adsmos.com/essential/computers-hardware/4k-dell-xps-15-core-i7-8th-generation-ram-16gb-ssd-1tb-graphics-12gb_i67

![IMG_20211227_232544_183](https://user-images.githubusercontent.com/94756026/147494177-351f3192-1fb9-4d53-82f2-20dfcb1ebe75.jpg)

TV channels are not playing

http://gp.bioscopelive.com/en/channel/zee-tv

![IMG_20211227_232550_581](https://user-images.githubusercontent.com/94756026/147494327-11a5a870-0e2a-4cd8-86b5-bc40020ae8d3.jpg)

I have made margins in the pictures to understand the problems.

Please Reputable developers please fix these issues

**Comment by scoute-dich** [comment]
Hi. Thanks for reporting. This will be solved with next update.
