### ISSUE TITLE
Some webpages show half the screen

### ISSUE THREAD

**Issue by ksapp-dell** [scoute-dich/browser#817]
Hi, this issue was there some time ago. With the latest update it is back again. 
![Screenshot_20211230-085218_FOSS Browser](https://user-images.githubusercontent.com/62463497/147732637-01b4286b-86cd-47fa-a470-053ec400a580.jpg)
![Screenshot_20211230-085246_FOSS Browser](https://user-images.githubusercontent.com/62463497/147732647-5560f87c-0ada-40e9-bda1-2a332cd36c51.jpg)
I open this web page via a shortcut from the start screen of my phone.  I am doing this since some time and it was working fine since latest update.

P.S. this was the old bug I have reported on an earlier version
https://github.com/scoute-dich/browser/issues/558

**Comment by scoute-dich** [comment]
I just released version 8.8 which should solve this  issue. Please report back after updating.

**Comment by ndr1224** [comment]
@scoute-dich Twitter mobile view is not good also. I cannot remove side bar. It is working normal on Chrome or Firefox app.

![Screenshot_20220104-180439_FOSS_Tarayıcı](https://user-images.githubusercontent.com/94392428/148079525-d131cc05-d660-436b-a645-cea737153f9d.png)

**Comment by scoute-dich** [comment]
Is this gone with v 8.8?

**Comment by ndr1224** [comment]
problem persist @scoute-dich

**Comment by ksapp-dell** [comment]
Mixed results with 8.8 - one website that was distubed befor is working fine - Wetteronline.de stopped responding to tap on buttons (other browser is working fine).

**Comment by ndr1224** [comment]
@scoute-dich I disabled fingerprint protection and twitter works fine.

**Comment by ndr1224** [comment]
@scoute-dich I can't switch between pictures on any website like Twitter.  I have to click one by one.

**Comment by scoute-dich** [comment]
> @scoute-dich I disabled fingerprint protection and twitter works fine.

So I can close this issue, since the original problem seems to be solved?

**Comment by Helaxious** [comment]
I was having this issue too, I disabled the fingerprint protection, and it seems to fix the issue

**Comment by ksapp-dell** [comment]
Hi, the issue seems to be back. 
![Screenshot_20220202-174616_FOSS Browser](https://user-images.githubusercontent.com/62463497/152198895-74f2d59b-4f62-4242-bd65-8b8118168881.jpg)
I have updated to latest version from F-droid some days ago.
