### ISSUE TITLE
cannot connect to mailo webmail

### ISSUE THREAD

**Issue by zorzibaffo** [scoute-dich/browser#818]
Hello,
Since a few versions, I cannot access to my webmail.
I'm using Mailo
https://www.mailo.com/fr/
After login and type my password, I'm immediately disconnected, as If I had closed my session.
Thanks for your help.

**Comment by scoute-dich** [comment]
I assume that you've enabled JavaScript, cookies and DOM-storage?

**Comment by zorzibaffo** [comment]
Yes. Javascript was enabled by default. I activated cookies. Neglected Dom Storage.

**Comment by DemOrex** [comment]
I have the same problem with gmail.

**Comment by scoute-dich** [comment]
What about enabling DOM-storage. Some websites use this to store user information, as for example login data.

**Comment by DemOrex** [comment]
It didn't help.

**Comment by DemOrex** [comment]
My problem is probably in the old build. 
 versionCode 126
        versionName "8.7"

**Comment by scoute-dich** [comment]
Then please update and report back. ;-)

**Comment by DemOrex** [comment]
The build that I use with githab.Build with F-droid, looks the same, gmail is a white sheet on them.Builds from Yandex market,looks different,gmail works fine.(if you enable or disable gmail DOM storage, it works fine).What is the difference between these duilds, other than the appearance?Where to look for the problem?

**Comment by DemOrex** [comment]
Thanks, I solved the problem.
