### ISSUE TITLE
[Feature Request] Allow modification of long press behavior for 3 dots

### ISSUE THREAD

**Issue by Anskrevy** [scoute-dich/browser#819]
Right now long pressing the three dots does the same thing as long pressing the shield. It can be long pressed so it seems logical a user would be able to change result of a long press. Maybe there is something preventing this, but if I can be added that would be nice.

**Comment by scoute-dich** [comment]
Long press gestures will be there in v 8.8.

**Comment by scoute-dich** [comment]
But long pressing the tab-button and pressing the menu-button will still trigger the same event.
