### ISSUE TITLE
Settings button does not open settings

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#823]
Instead profile settings are opened. Or is this intended?
(3 dots -> Settings button at top right)
Only settings button at the bottom in profiles works.

**Comment by scoute-dich** [comment]
Thre question is: do we really need this button? I want to remove it. There would be more space for the website title.

What do you think about that?

But if it remains, you're right and it should kitten settings.

**Comment by woheller69** [comment]
I usually use swipe to reload, but others may want to use it.
If the corners were a little less rounded it would work

**Comment by woheller69** [comment]
sorry, I mixed it with the reload button issue

**Comment by scoute-dich** [comment]
Done.
