### ISSUE TITLE
Crash when opening the app

### ISSUE THREAD

**Issue by mrflamist** [scoute-dich/browser#829]
The app crashes immediately upon opening. It doesn't give an error message, it's just black screen and then it closes.

I'm on Xiaomi Redmi 8, Android 10, API 29. Tried both GitHub and F-Droid, both act the same.
I'm not aware of crash logs being made anywhere.
I can try to provide more info if needed.

**Comment by scoute-dich** [comment]
Will be fixed with next update. If not, please reopen. Thanks for reporting.

**Comment by scoute-dich** [comment]
Meanwhile just open the app a second or third time. It should open then

**Comment by mrflamist** [comment]
It doesn't. I tried it additional 20 times just to be absolutely sure, but I'm afraid the problem persists.

**Comment by mrflamist** [comment]
I can confirm, the issue is now fixed with the latest release and the app works just fine. Thanks man!
