### ISSUE TITLE
Shortcut on the home screen

### ISSUE THREAD

**Issue by DemOrex** [scoute-dich/browser#830]
When you save the site shortcut, the Foss Browser icon is saved, not the site icon.Android 10.

**Comment by DemOrex** [comment]
To solve the problem, I changed the code.

**Comment by DemOrex** [comment]
HelperUnit.
public static void createShortcut (Context context, String title, String url, Bitmap bitmap) {
        Icon icon = null;
        try {
            Intent i = new Intent();
            i.setAction(Intent.ACTION_VIEW);
            i.setData(Uri.parse(url));
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) { // code for adding shortcut on pre oreo device
                Intent installer = new Intent();
                installer.putExtra("android.intent.extra.shortcut.INTENT", i);
                installer.putExtra("android.intent.extra.shortcut.NAME", title);
                installer.putExtra(Intent.EXTRA_SHORTCUT_ICON_RESOURCE, Intent.ShortcutIconResource.fromContext(context.getApplicationContext(), R.drawable.icon_bookmark));
                installer.setAction("com.android.launcher.action.INSTALL_SHORTCUT");
                context.sendBroadcast(installer);
            } else {
                ShortcutManager shortcutManager = context.getSystemService(ShortcutManager.class);
                assert shortcutManager != null;
                if (bitmap != null){
                  icon=createWithBitmap(bitmap);
                }else{
                    icon=createWithResource(context, R.drawable.icon_bookmark);
                }
                    if (shortcutManager.isRequestPinShortcutSupported()) {
                    ShortcutInfo pinShortcutInfo =
                            new ShortcutInfo.Builder(context, url)
                                    .setShortLabel(title)
                                    .setLongLabel(title)
                                    //.setIcon(Icon.createWithResource(context, R.mipmap.ic_launcher))
                                    .setIcon(icon)
                                    .setIntent(new Intent(Intent.ACTION_VIEW, Uri.parse(url)))
                                    .build();
                    shortcutManager.requestPinShortcut(pinShortcutInfo, null);
                } else {
                    System.out.println("failed_to_add");
                }
            }
        } catch (Exception e) {
            System.out.println("failed_to_add");
        }
    }

**Comment by DemOrex** [comment]
BrowserActivity
  HelperUnit.createShortcut(context, ninjaWebView.getTitle(), ninjaWebView.getOriginalUrl(),ninjaWebView.getFavicon());

**Comment by DemOrex** [comment]
Thanks!

**Comment by scoute-dich** [comment]
Thanks also!
