### ISSUE TITLE
Can't switch between pictures / unable to refresh page on Twitter mobile

### ISSUE THREAD

**Issue by ndr1224** [scoute-dich/browser#831]
@scoute-dich I can't switch between pictures on Twitter. I have to click one by one each picture. Unable to refresh page also

Thanks

https://user-images.githubusercontent.com/94392428/148652023-a38f21ab-8185-4f58-96aa-37eb2ba2fee1.mp4

https://user-images.githubusercontent.com/94392428/148696697-b3a0954b-b96d-42e2-932c-943ac747a391.mp4

**Comment by ndr1224** [comment]
Problem persist on v8.9.1

**Comment by ndr1224** [comment]
@scoute-dich unable to install v9.0 to test again.
My phone is arm64

**Comment by comamondo** [comment]
and still in v9.0

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue. With the next update, there will come a lot of layout changes and improvements.

_Also be care of enabling all features you need in the profile settings (JavaScript, disable fingerprinting, cookies, ...)._
