### ISSUE TITLE
Feature request: Downloads window and progress bar in browser

### ISSUE THREAD

**Issue by ndr1224** [scoute-dich/browser#832]

**Comment by pc00per** [comment]
I know Downloads management is a useful feature. But these days all Android devices come with default download manager, managed by "Files", which works fine. You can use ADM too.

**Comment by ndr1224** [comment]
Thanks @pc00per

**Comment by scoute-dich** [comment]
There should also be the default notifications of the default download manager. One aim of FOSS Browser is to use as many native Android features as possible. This helps to keep the app small.
