### ISSUE TITLE
Websiteview is changed

### ISSUE THREAD

**Issue by WST1811** [scoute-dich/browser#833]
Hi,

i'm using FOSS Browser since  couple of months. Since last Update up to 8.8 i see a change. Pls open this website: https://download.lineageos.org/klte/changes/ Before 8.8 i can see only the part in the middle: Changes for klte, left part was not visible. Now i only see the left part Devices and i find no way to disable the devices.

Can anyone help me?

Thanks and Regards

**Comment by scoute-dich** [comment]
It seems that you must enable cookies, JavaScript and probably DOM-storage. Then the website should work.

**Comment by WST1811** [comment]
Thanks for answer, after testing a couple of minutes, now its working, thanks for help.
![Screenshot_20220108-112540_FOSS_Browser_1](https://user-images.githubusercontent.com/56893754/148641653-76759ea7-c9c0-4fd0-b7a5-a610f7732ddd.png)
.
