### ISSUE TITLE
Not possible to enter an ip-address on a specific start page

### ISSUE THREAD

**Issue by ZeldosID** [scoute-dich/browser#834]
If a specific startpage (Favorite in version 7.x)  is alredy loaded; I my case Qwant Lite (https://lite.qwant.com/?!=de), then it's not possible to load another page after entering the ip-address in the adress bar (e.g. tagesschau.de or anything else). Nothing happens. But if another site is alreaday loaded except Qwant Lite, then it works fine. Strange??!!

**Comment by scoute-dich** [comment]
If this is still from relevance after update to version 9.2. Please open a new issue.

**Comment by scoute-dich** [comment]
If this is still from relevance after update to version 9.5. Please open a new issue.
