### ISSUE TITLE
Gesture to hide Toolbar

### ISSUE THREAD

**Issue by JM480** [scoute-dich/browser#835]
There should be a gesture which can be used to show and hide the toolbar because the toolbar doesn't automatically hide on map websites.

**Comment by scoute-dich** [comment]
If the website can't scroll, the swiping up and down on the webview should show/hide the toolbar. I have the problem to on a website with a map. You must find a place (the menu, the footer, website title, ...), where you con swipe up or down.

**Comment by pc00per** [comment]
> If the website can't scroll, the swiping up and down on the webview should show/hide the toolbar. I have the problem to on a website with a map. You must find a place (the menu, the footer, website title, ...), where you con swipe up or down.

Can it be possible to open a website in its own window? Like a PWA instance without a toolbar, that can be switchable from recents?

**Comment by scoute-dich** [comment]
SO I think this is possible.

But I will not implement it. The simple reason is: I don't plan to add any new features in the future. I do not have much time. Every new feature means, that I have one more thing to consider in the whole app. So maintaining FOSS Browser would become more work with every new feature. Also, I should create new strings to translate. That means that all translations must be updated...
