### ISSUE TITLE
foss browser steals the audio

### ISSUE THREAD

**Issue by cmdtstof** [scoute-dich/browser#838]
foss browser (fb) is my standard browser on my mobile.
since last update (8.8),
when opening a site,
fb STEALS THE AUDIO!
playing music will be interrupted (silent).

???where to turn of this function???

sorry, since i like to listen to my music, i'm not able to start fb and go throught the settings, finding where i could turn of this mis-behavior. sorry.

ps: pls, add (not to much!) new features. but do not change user configurations when updating! pls! thanks (for yur greath work)

**Comment by cmdtstof** [comment]
maybe it has to do with [#800](https://github.com/scoute-dich/browser/issues/800) ???

**Comment by scoute-dich** [comment]
You must disable "Play audio in background".

**Comment by cmdtstof** [comment]
> You must disable "Play audio in background".

it is disabled (no thick).
but enabled or disabled, my playing music from an other source (RadioDroid = internet streaming) turns off playing as soon foss browser is started and plays again, when i killed it. 
daniavad (thanks)

**Comment by jer194** [comment]
> You must disable "Play audio in background".

I had the same problem, while "Play audio in background" was disabled (quite annoying, when listening to RadiDroid eg ...).
After enabling "Play audio in background", the problem seems to be gone.
