### ISSUE TITLE
Back / forward navigation

### ISSUE THREAD

**Issue by ildar** [scoute-dich/browser#84]
Buttons to bring a user back and forward in history (per tab) is highly desirable.

**Comment by scoute-dich** [comment]
This is implemented in the navigation button, which you can see in fullscreen mode. But perhaps I will give you an option to always show the navigation button.

**Comment by ildar** [comment]
I am sorry for my dumbness:
1. I don't see the navigation button, only "Overflow button" aka FAB in
right bottom
2. I don't see no Back/Forward in the FAB menu and also on [screenshots](
https://github.com/scoute-dich/browser/blob/master/SCREENSHOTS.md)
Please help me finding it. Thanks!
Just in case: I have the latest version from F-Droid.

**Comment by scoute-dich** [comment]
You can swipe left/right on the fab-button to navigate. Please read the help dialog. In the next release there will be also options to show the button always and to decide on which position (left, right, center) the button will be displayed.

**Comment by ildar** [comment]
Yes, indeed. Help may be helpful. Though usually nobody reads it 😏 Maybe
showing start tips could be more effective?
Indeed swipe to the right almost impossible.
And BTW is the FAB button named both Overflow and Nav button in different
places of the app?

**Comment by scoute-dich** [comment]
In the toolbar it's called overflow be default. And the fab needs a name... But perhaps it would be easier of both had the same name ...?

I also tried start tips in an other app. That's the same. Nobody reads it...

**Comment by ildar** [comment]
>
> I tested the latest version.
The variant with FAB in center is... fabulous 🙂 I cannot accept this way,
sorry.
As swiping to the right from the right-aligned Fab is incredibly difficult,
may I ask: either move Fab a little to the left so swiping is possible? or
give alternative way to move in the tab history (hence
https://github.com/scoute-dich/browser/issues/88) ?
Thanks for the open discussion!

**Comment by scoute-dich** [comment]
I will also implement back/forward navigation in the main menu (mainly for guys who disable the navigation button.
