### ISSUE TITLE
[Cloudflare] HTTP 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#841]
Link
https://download.fastgit.org/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0.tar.xz

**Comment by scoute-dich** [comment]
Works for me with trusted profile (JavaScript, cookies, dom-storage: enabled, fingerprint protection: disabled.

**Comment by scoute-dich** [comment]
Than a download starts.

**Comment by scoute-dich** [comment]
Any news from here?

**Comment by scoute-dich** [comment]
If not, please reopen.
