### ISSUE TITLE
Immersive Mode

### ISSUE THREAD

**Issue by JM480** [scoute-dich/browser#842]
Can you add an option to enable Immersive Mode in the browser? And can you make sure that it works properly with phones with notches?

**Comment by pc00per** [comment]
Define immersive. Overscan (that provided systemwide immersive mode) is discontinued right from Android 11 itself. If you wanna hide toolbar, enable it from behaviour settings. You can't hide status bar though.

**Comment by scoute-dich** [comment]
I think immersive mode could be done:
https://developer.android.com/training/system-ui/immersive

But I will not implement it. The simple reason is: I don't plan to add any new features in the future. I do not have much time. Every new feature means, that I have one more thing to consider in the whole app. So maintaining FOSS Browser would become more work with every new feature. Also, I should create new strings to translate. That means that all translations must be updated...
