### ISSUE TITLE
Google images streched out

### ISSUE THREAD

**Issue by pc00per** [scoute-dich/browser#843]
I think this is User agent issue. Isn't the default agent "Android" ?
![Screenshot_20220113-102612_crDroid_Home](https://user-images.githubusercontent.com/83843264/149269360-a845331a-98bf-406c-8465-5fe8ce2f83ed.png)

**Comment by scoute-dich** [comment]
It could also be, because you enabled fingerprint protection, or disabled javascript/dom-storage, or something like that.

Anyway, I will proof the userAgent thing.

**Comment by scoute-dich** [comment]
Any news here? User Agent is mainly the used Android version.

**Comment by pc00per** [comment]
> Any news here? User Agent is mainly the used Android version.

It's not yet fixed yet.
Something's giving google a page rendering problem.
I've tried other webview browsers like Duckduckgo & Via. They didn't had this issue.

**Comment by pc00per** [comment]
It fixes when I enable "Custom User Agent" & set "Android" manually.
That means the default whatever user agent that comes out of the box have this issue.
![Screenshot_20220421-182604_FOSS_Browser](https://user-images.githubusercontent.com/83843264/164462730-864493da-3c86-477c-8ae8-da9da42292d4.png)

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue. With the next update, there will come a lot of layout changes and improvements.

_Also be care of enabling all features you need in the profile settings (JavaScript, disable fingerprinting, cookies, ...)._
