### ISSUE TITLE
Sort bookmarks to be the last result

### ISSUE THREAD

**Issue by pc00per** [scoute-dich/browser#844]
A weird scenario. When you search a bookmark, but "search" results keep bookmarks on top & history results after bookmarks, which I, then always have to scroll to the top, which is kinda bummer.
![Screenshot_20220113_104942](https://user-images.githubusercontent.com/83843264/149270370-8a2f5350-81cf-4c00-aa25-8cb706da4bfc.png)

**Comment by scoute-dich** [comment]
I will not implement this. The simple reason is: I don't plan to add any new features in the future. I do not have much time. Every new feature means, that I have one more thing to consider in the whole app. So maintaining FOSS Browser would become more work with every new feature. Also, I should create new strings to translate. That means that all translations must be updated...

**_A workaround (which I also use): Edit the name of the bookmark. Use a special character ("*@-|...), number, an emoji or something other unique in the name. That makes it very easy to open a special entry from startsite or bookmarks._**

**Comment by woheller69** [comment]
would listView.setStackFromBottom(true) do the job?

**Comment by scoute-dich** [comment]
If I remember this is already defined in the layout xml-file.
