### ISSUE TITLE
crash on every start Android oppo A9

### ISSUE THREAD

**Issue by shaikhsadi2** [scoute-dich/browser#848]
After download v8.8 and i have installed but
crash on every start Android oppo A9

https://user-images.githubusercontent.com/94756026/150481220-dd1362b2-3b15-40c1-8e6e-6ba467f7ba03.mp4

**Comment by scoute-dich** [comment]
Sorry, I was offline a time. I'll release an update this weekend. Then this should be fixed. 😉
