### ISSUE TITLE
add a backup for home

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#85]
there is a backup for bookmarks  but I rarely  use bookmark. 
I prefer store link in home.

**Comment by scoute-dich** [comment]
In the next release it is possible to backup the whole database. But the preview pictures will not get restored. There will be an option in the context menu of restored entries to easily delete and save them again with preview. However, if you want the preview you must do this for every single entry.

**Comment by lishoujun** [comment]
ok  got

**Comment by scoute-dich** [comment]
Finally found a way to backup all settinggs and the whole app data. So with the net release backup of home is possible with previews. ;-)
