### ISSUE TITLE
Favorites & Homepage section appears transparent sometimes

### ISSUE THREAD

**Issue by ndr1224** [scoute-dich/browser#851]
Version: v8.9.1

https://user-images.githubusercontent.com/94392428/150668115-e27861c8-bf96-44c7-bf1c-20f11d0c2a67.mp4

**Comment by scoute-dich** [comment]
I can not reproduce this.

I assume you use the OLED theme? Which Android version are you using? Other themes are displayed in the right way? Are you using any theming apps or something like that?

**Comment by ndr1224** [comment]
Android 11. I did not try other themes. Not using any extension

**Comment by ndr1224** [comment]
You can test on twitter or telegram with OLED theme.

**Comment by scoute-dich** [comment]
Twitter works well on my phone. Are the themes displayed correct? I only have a phone running Android 12, but perhaps I can find an older device in the family to test.

**Comment by scoute-dich** [comment]
Any news here?

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue. With the next update, there will come a lot of layout changes and improvements.

_Also be care of enabling all features you need in the profile settings (JavaScript, disable fingerprinting, cookies, ...)._
