### ISSUE TITLE
Pressing the back button in the search bar deletes my search text

### ISSUE THREAD

**Issue by Anskrevy** [scoute-dich/browser#852]
If I decide not to search for whatever I was typing it's usually because I want to return to the web page I was on before I started typing. Instead when I hit the back button on my phone my keyboard closes, hitting it again deletes the text that was typed, and then hitting it again returns me to the web page I was on. I'm not sure if this is intended but it seems weird to say the least.

**Comment by scoute-dich** [comment]
Fixed with next update.
