### ISSUE TITLE
lesezeichen bearbeiten/edit favorites

### ISSUE THREAD

**Issue by otto22otto** [scoute-dich/browser#854]
this window dosnt scroll to bottom nor jumps via tab to next field  to accept/save changes if content not completly fits on screen.
version 8.8 / android 8.1.0 / 1920*1080px

**Comment by scoute-dich** [comment]
Fixed with next update.

**Comment by otto22otto** [comment]
Thanks, now scrollable.
But still a Lot of Problems. Most of the time there ist no "save" Button. 
![Screenshot_2022-02-03_13-40-29](https://user-images.githubusercontent.com/98341864/152371992-f141d127-e960-4006-b820-c82d4b5df93f.jpg)
![Screenshot_2022-02-03_14-02-23](https://user-images.githubusercontent.com/98341864/152372119-589a6f7e-2dfa-49f6-aafc-e6d76a99cdf2.jpg)
![Screenshot_2022-02-03_16-06-39](https://user-images.githubusercontent.com/98341864/152372214-e64a45dd-3f4d-4207-92d2-2ae623c131bb.jpg)

**Comment by otto22otto** [comment]
With "save Button" I meant the "OK" See Screenshot.
![Screenshot_20220206_1](https://user-images.githubusercontent.com/98341864/152683083-89035952-66fe-414d-ba4b-04cb96d23c5a.jpg)
![Screenshot_20220206_1](https://user-images.githubusercontent.com/98341864/152683097-ea8cc456-3a82-455c-843a-b88793c3d0e7.jpg)
