### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by DemOrex** [scoute-dich/browser#855]
The browser gets permissions during operation, then a reboot is required.I suggest at the first start, to offer the user a choice, to grant permissions immediately or later.

**Comment by DemOrex** [comment]
BrowserActivity

private ValueCallback<Uri[]> mFilePathCallback;

    private static final String TAG;
    private static String[] PERMISSIONS_STORAGE;

    private SharedPreferences mFirstPrefs = null;

    // permission
    static {
        TAG = BrowserActivity.class.getSimpleName();
        PERMISSIONS_STORAGE = new String[]{
                "android.permission.READ_EXTERNAL_STORAGE",
                "android.permission.WRITE_EXTERNAL_STORAGE",
                "android.permission.CAMERA",
                "android.permission.ACCESS_COARSE_LOCATION",
                "android.permission.ACCESS_BACKGROUND_LOCATION",
                "android.permission.ACCESS_FINE_LOCATION",
                "android.permission.ACCESS_GPS",
                "android.permission.ACCESS_ASSISTED_GPS",
                "android.permission.RECORD_AUDIO",
                "android.permission.RECORD_VIDEO",
                "android.permission.MODIFY_AUDIO_SETTINGS"};
    }

    // permission
    public static void verifyStoragePermissions(Activity activity) {
        int n = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.WRITE_EXTERNAL_STORAGE");
        int n2 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.READ_EXTERNAL_STORAGE");
        int n3 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.CAMERA");
        int n4 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.ACCESS_COARSE_LOCATION");
        int n5 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.ACCESS_BACKGROUND_LOCATION");
        int n6 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.ACCESS_FINE_LOCATION");
        int n7 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.ACCESS_GPS");
        int n8 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.ACCESS_ASSISTED_GPS");
        int n9 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.RECORD_AUDIO");
        int n10 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.RECORD_VIDEO");
        int n11 = ActivityCompat.checkSelfPermission((Context) activity, (String) "android.permission.MODIFY_AUDIO_SETTINGS");
        if (n != 0 || n2 != 0 || n3 != 0 || n4 != 0 || n5 != 0 || n6 != 0 || n7 != 0 || n8 != 0 || n9 != 0 || n10 != 0 || n11 != 0) {
            ActivityCompat.requestPermissions((Activity) activity, (String[]) PERMISSIONS_STORAGE, (int) 1);
        }
    }

    // Classes

**Comment by DemOrex** [comment]
BrowserActivity

 public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
 mFirstPrefs = getSharedPreferences("de.baumann.browser", MODE_PRIVATE);
        if (mFirstPrefs.getBoolean("firstborn", true)) {
            MaterialAlertDialogBuilder builder = new MaterialAlertDialogBuilder(context);
            builder.setTitle(R.string.app_first_run);
            builder.setIcon(R.drawable.icon_alert);
            builder.setMessage(R.string.app_first_run_text);
            builder.setPositiveButton(R.string.app_ok, (dialog, whichButton) -> verifyStoragePermissions(activity));
            builder.setNegativeButton(R.string.app_cancel, (dialog, whichButton) -> dialog.cancel());
            Dialog dialog = builder.create();
            dialog.show();

            mFirstPrefs.edit().putBoolean("firstborn", false).commit();
        }

**Comment by DemOrex** [comment]
<string name="app_first_run">First run</string>
    <string name="app_first_run_text">For full operation, the browser needs permissions.Provide them now?</string>

**Comment by DemOrex** [comment]
sting.xml
string name="app_first_run">First run</string>
string name="app_first_run_text">For full operation, the browser needs permissions.Provide them now?</string>

**Comment by DemOrex** [comment]
Thanks

**Comment by scoute-dich** [comment]
No more features at the moment. I think it is ok to ask for permission during runtime.
