### ISSUE TITLE
 [Feature request] It goes back to your bookmarks folder

### ISSUE THREAD

**Issue by Pantyhose-X** [scoute-dich/browser#857]
It goes back to your bookmarks folder. Both in the bookmarks tab and panel.
People who have a lot of Bookmarks are very useful.

**Describe the solution you'd like**

- Bookmarks directory, after the first time open the website, click the Back key to return to the Bookmarks directory.

**Additional context**

https://user-images.githubusercontent.com/42504385/148888901-46bfb31e-988a-41d2-8105-a0a14cd6de18.mp4

**Comment by scoute-dich** [comment]
This can not be implemented, since the overview is not a separate tab. It is placed in a view which will be displayed or not. Anyway: Opening the bookmarks is just one click in the toolbar away ... just the same as pressing back one time.
