### ISSUE TITLE
Opening a link from another app goes to Bookmarks

### ISSUE THREAD

**Issue by nucleone** [scoute-dich/browser#858]
In v8.9.1, after tapping on a link in another app (e.g. WhatsApp, Viber, etc.) to open it in FOSS Browser, it shows the _Bookmarks_ page (_probably because I set it as my default page in FOSS Browser_) while the link is opened in the background.
I need to tap on the _Opened Tabs_ icon in the toolbar to see the opened link as a tab, and then tap on the tab to actually view the opened link.
Too many steps for an otherwise simple action. Wasn't the case in the previous version.

**Comment by scoute-dich** [comment]
Perhaps you have enabled "opening Overview on start" in the behavior/UI settings. Normally that should not happen.

**Comment by nucleone** [comment]
> Perhaps you have enabled "opening Overview on start" in the behavior/UI settings. Normally that should not happen.

Under Behaviour/UI / 'Show on start' I set it to open Bookmarks. But regardless, if I'm opening a link from another app, FOSS Browser should show me the link's page and not what I set to open on start.

Please try to replicate the issue, and see what you can do. This was not present in the previous version, so it has to be something that was introduced in v.8.9.1.

**Comment by scoute-dich** [comment]
Does the overview also show up on a regular app start? Without an intent from another app?

**Comment by nucleone** [comment]
> Does the overview also show up on a regular app start? Without an intent from another app?

Yes, it does. The browser works as it should, except for the issue I described.

**Comment by nucleone** [comment]
I closed it by accident, here is a re-open.

**Comment by scoute-dich** [comment]
So the only explanation is that you have enabled "Show on start" in Behavior/UI settings. Uncheck that and FOSS Browser will not the overview on the first start. The chosen tab (Startsite/Bookmarks/History) will show, when you open the overview manually.

**Comment by nucleone** [comment]
Yes, that's the explanation, but this should be about adjusting a behaviour that is not user-friendly.

Isn't it logical to have the overview (_Bookmarks, in my case_) show when normally (manually) tapping on the FOSS browser icon and opening the browser with the intention to browse the internet and **NOT** show the overview when using the browser to simply open a link from another app (just to see what the link contains)?

In short, **the overview should show on first start when manually opening FOSS browser** and **the overview should _not_ show when I open a link from another app**. 
This is possible in literally every other browser in the world.

No one should have to disable their preferred start page (Startsite/Bookmarks/History) in 'Show on start' just to be able to directly open a link from another app. 

I have no other words to explain what I mean. If you think this behaviour should remain as is, please close the issue.

**Comment by scoute-dich** [comment]
I know what you mean. At the moment I don't have much time. But I will change it.

**Comment by scoute-dich** [comment]
Done. Will be fixed with next update!

**Comment by cauerego** [comment]
i noticed this bug and couldn't bother about fixing it as much as both of you.

what's more, perhaps this whole "choose where to start" feature should be removed if it ever bugs again.

so the dev can focus on the essential issues always!

if everything was minimalistic, i'm sure there could be a summons gesture for all actions needed, so whenever you want, you quickly go straight to where you want to go.

**Comment by nucleone** [comment]
@cauerego  I agree, keeping it minimal and minimalistic is the best way forward. Though there must be a start page always, whatever that is.

I believe that, currently, FOSS Browser is at a stage where it has reached its maturity and its development should now be focused on ironing out any bugs and issues, such as the one I reported here. No need for introducing any other major features. 
The dev knows where the weak spots are, and I'm sure he'll take care of them in due time.

FOSS Browser is at a level where most people would be very happy with its performance, and even use it as their default browser.
I will forever regret that it doesn't have back/forward cache, but its other features and its overall philosophy are excellent and better than most of the paid or ad-infested browsers out there, and this should always be acknowledged. 

In my opinion, this is one of the best projects in the entire GitHub.

**Comment by cauerego** [comment]
i suggest we take this offtopic discussion to the fediverse talk.ahoxus.org
