### ISSUE TITLE
the world needs agpl

### ISSUE THREAD

**Issue by cauerego** [scoute-dich/browser#860]
thanks for sharing this beautiful piece of app!! 🤗

however...

here's how you can easily make it much better with no need to touch the code!

https://banana.dog/@cregox/107140241290340311#agpl#license

as i just said [elsewhere](https://t.me/ofvolla/52)

> (agpl is) not the final solution for everything software... just a good start.

**Comment by scoute-dich** [comment]
Done!

**Comment by cauerego** [comment]
amazing! https://github.com/scoute-dich/browser/commit/17a00923478f5c777753a563111d15daf79ad181

why so fast and efficient?! 🤣

hope you don't mind a ping back: https://talk.ahoxus.org/notice/AG5YoLmLZsAPfG16v2

**Comment by kcubeterm** [comment]
nice.
