### ISSUE TITLE
Some webpages show half the screen (817 seems back)

### ISSUE THREAD

**Issue by ksapp-dell** [scoute-dich/browser#862]
Hi, the issue when webpages are showing half screen seems back again. I have updated some days ago to latest f droid version.
![Screenshot_20220202-174616_FOSS Browser](https://user-images.githubusercontent.com/62463497/152209856-1176c0e5-f0a8-45ad-a8f2-bb809cd74614.jpg)

Additionally the status bar is unreadable as the browser show transparent on the top.

**Comment by ksapp-dell** [comment]
Good morning, here is another example. Now it shows bookmarks at the bottom. You scroll through the bookmarks.
![Screenshot_20220204-071911_FOSS Browser_1](https://user-images.githubusercontent.com/62463497/152482260-ec397af8-0cf9-4da4-8ffa-4a1f83454ef5.jpg)

**Comment by scoute-dich** [comment]
I am aware of it, but can not reproduce it reliable at the moment. If you have any further hints how to reproduce, just let me know.

**Comment by ksapp-dell** [comment]
Hi, sometimes this happens after the phone is in landscape mode and turns back to portrait mode.
May be this helps to identify the problem ?

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue. With the next update, there will come a lot of layout changes and improvements.

_Also be care of enabling all features you need in the profile settings (JavaScript, disable fingerprinting, cookies, ...)._
