### ISSUE TITLE
https warning

### ISSUE THREAD

**Issue by cauerego** [scoute-dich/browser#863]
ahoxus.org my own website promotes http usage for very good reasons.

i understand perhaps most http sites today are either still lazy or dangerous.

but i think the warning should still get fixed:

+ it should never show under the "list of tabs" button. makes no sense. (and it annoys the hell out of me to "cancel" the warning every time! even if i set the website as trusted!! i understand they're different concepts of trust, but still...) how about moving the tabs button to the right? i never use home, favourites and history anyway.

+ the message should read something like "this site uses an insecure connection (http)" and offer buttons "switch to https" and "stay on http".

when you say "secure" without combining it with "connection" it will become very misleading.

and words program our brains nearly as much as commands do to computers...

**Comment by cdhub** [comment]
https warning should exclude about:blank

**Comment by cauerego** [comment]
on a second thought, even "insecure connection" gets it wrong.

the S in http surely stands for "secure", but it doesn't mean http will be insecure, only that it doesn't use the secure protocol.

we can have an http site way more secure than a https one, just like we can have an unlocked room way more secure than a locked one. locking doors and using cryptography can only go so far too offer security...

perhaps you want to read an old article around all of it https://arstechnica.com/civis/viewtopic.php?f=2&t=1321817&sid=dca4eab01d7aa2fc8bb56996bc9ce8ac

and then ahoxus.org/secure might make better sense...

that's all that https should ever be used for, if it wasn't for stupid google pushing their agenda.

even the identity issue gets it wrong, as it can also be tampered with on https.

too long; didn't read?

thanks for all the improvement done here. i guess (from looking at both commits) we might just miss a better warning message...

brave got a decent warning, on the first alert screen only:

> Connection is not secure
> You should not enter any sensitive passwords or credit cards, because it could be stolen by attackers.

**Comment by alicaccs** [comment]
> https warning should exclude about:blank

https warning should also exclude plain private ip address (like http://192.168.x.x/) , since it should be impossible to acquire proper signed certificate for host using private ip address (without first wrap it with domain). Upgrading to https will cause more trouble (connection refused, cert error) in plain private ip address.
