### ISSUE TITLE
can't properly swipe on olx gallery

### ISSUE THREAD

**Issue by cauerego** [scoute-dich/browser#867]
simply get any item on olx.pt and try to swipe on the gallery. 

for instance https://m.olx.pt/d/anuncio/troco-hyundai-ioniq-28kwh-full-eletric-por-xbus-IDGrlQ1.htm

work around: swipe left enough so the image goes past the middle and tap on the right image.

**Comment by nucleone** [comment]
The page you linked to no longer exists, but yes, you're right, swiping on pictures in problematic on most websites. 

Here's another example of this issue: https://nultatacka.rs/ 

I hope something can be done about it.

**Comment by cauerego** [comment]
it shall come back. on another point, this is how galleries should be done...

ahoxus.org/ioniq

so i would like to say it's certainly a double bug with those websites: doing poor javascript and non-failure-resistant ux.

but i bet there's something that can be done on foss as well to get around it. even if it would be, if that's the case, stripping out the javascript when it's poorly done and warning the user, giving a link to send an automatic message to the postmaster of that domain pointing out their error!! 🤣

**Comment by scoute-dich** [comment]
> but i bet there's something that can be done on foss as well to get around it. even if it would be, if that's the case, stripping out the javascript when it's poorly done and warning the user, giving a link to send an automatic message to the postmaster of that domain pointing out their error!!

This is not possible from my point of view. If there are no other hints, I#ll assume that this are website errors and I can do nothing.

**Comment by cauerego** [comment]
well, i can "brainstorm" until you find something possible, if you will.

but i rather do 1 idea per time.

how about adding custom javascript per domain?

**Comment by scoute-dich** [comment]
You can add (not per domain) custom JavaScript in the settings.

**Comment by cauerego** [comment]
even a general custom javascript could work for me and lots of folks!

but i searched for it again and still couldn't find it. can you shed some light?
