### ISSUE TITLE
"Blob" downloads

### ISSUE THREAD

**Issue by CaptainFrosty** [scoute-dich/browser#875]
`blob:/tps://mullvad.net/bc942375-6f03-46ce-bbed-f9582cd6092a` 

Just a quick question, why do open source browsers have such a hard time downloading these? I had to use Samsung Internet for pete's sake, which is stuck on my phone permanently and I don't like to even launch if I can help it.

**Comment by scoute-dich** [comment]
This would be complicated. I do not really know how to achieve this.

**Comment by CaptainFrosty** [comment]
@scoute-dich Clearly the problem isn't unique to you, because I couldn't download it with three different open source browsers. I don't understand the need for a non-standard proprietary download mechanism. Is it a security thing? I was downloading VPN keys after all.
