### ISSUE TITLE
weird crash on opening a link

### ISSUE THREAD

**Issue by cauerego** [scoute-dich/browser#876]
http://ahoxus.org/visit

when i go to "play games" it just crashes.

edit: in fact, i just noticed that even going straight to https://talk.ahoxus.org/notice/AGhOzl1NL1W1aYJ36u#arthur#challenge the browser crashes! 😳

**Comment by scoute-dich** [comment]
You can test this:
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/8162901/app-debug.apk.zip)

**Comment by woheller69** [comment]
just remove .zip from file name and install

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue.
