### ISSUE TITLE
how to copy link without open it

### ISSUE THREAD

**Issue by cdhub** [scoute-dich/browser#878]
for some url will redirect vary device

**Comment by scoute-dich** [comment]
Just long press the link and than you can share it to the clipboard via the context menu.

**Comment by cdhub** [comment]
> Just long press the link and than you can share it to the clipboard via the context menu.

thank you, here the problem is the device have no clipboard option for share to ,so i have to share it to some editor and then select all text and press copy

**Comment by scoute-dich** [comment]
Will be in context menu with next update.
