### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by xandro0777** [scoute-dich/browser#881]
When viewing https://www.skiforum.it/board/index.php?threads/90441/ the images are not displayed. I tried to change the settings and protection level but did not manage to have them displayed.

**Comment by scoute-dich** [comment]
Perhaps it is a website issue. By long pressing the link, you can open the images in a new tab. So the pictures are there. I don't know why the pictures aren't displayed in the thread.

**Comment by xandro0777** [comment]
It might be they are not displayed because the links are "http" as
opposed "https" ?

Displaying them in a separate page is not that great, I wanted to save
the page including images for offline use.

**Comment by scoute-dich** [comment]
So at the moment I have no hint to solve the problem. But perhaps I'll look into it, when I have more time.

**Comment by xandro0777** [comment]
Apparently the images load in Chrome and Firefox because those browsers do rewrite the HTTP into HTTPS.

**Comment by xandro0777** [comment]
I looked around how to enable mixed content loading: https://stackoverflow.com/questions/32155634/android-webview-not-loading-mixed-content

It would be preferable to try if the resource could be loaded over https before enabling mixed content. Rewriting URLs apparently can be done with  shouldInterceptRequest

**Comment by scoute-dich** [comment]
Thanks for the hint. Will be fixed with next update.
