### ISSUE TITLE
[Feature Request] support search engine instances

### ISSUE THREAD

**Issue by NSTAdventure** [scoute-dich/browser#886]
issues:
sometime search engine have many instances for example:
[Searx the meta search engine](https://searx.space/) 
and FOSS browser isn't support it ik searx is already available in setting BUT what i want is i want to use other instance on same search engine

solution:
add support for custom instance for search engine

**Comment by scoute-dich** [comment]
You can already set a custom search engine in the (advanced) settings.

**Comment by 5lttrz** [comment]
@NSTAdventure you have to add 

"/search?q=" at the end of the search engine url for it to work.

Example:
"https://searx.be/search?q="
