### ISSUE TITLE
Splitscreen again

### ISSUE THREAD

**Issue by Noitarud** [scoute-dich/browser#887]
In a previous issue you offered a debug apk but I downloaded this and it was not able.

One alternative is to put the option for split screen (disabled) in Behaviour/UI with warning that crash occurs when user does (something) in the description. (perhaps make user enable in each session/day so user does not forget there is a problem and create a new issue on here).

**Comment by scoute-dich** [comment]
Sorry, no new features at the moment.

**Comment by Noitarud** [comment]
Cannot find version of app the person who wrote the 2021/5/31 comment could have used, so cannot test for Android Ten (I have an app that warns about split but no issue, so perhaps was a Google problem, yours may work now).

**Comment by Noitarud** [comment]
Instead of what I wrote above, I notice APV PDF viewer puts up a warning when the user tries to splitscreen, so copy their code.
