### ISSUE TITLE
Browse local html files

### ISSUE THREAD

**Issue by xandro0777** [scoute-dich/browser#888]
Hi, would you consider supporting the "file://" URI scheme? I keep documentation files as local html files with hyperlinks etc. 

Would not like to run a local http server just for that.

**Comment by Noitarud** [comment]
there were other apps that would create the address of local files so you could open it, but new android disabled it. As you see, the green android bot when the page is not available, android is processing pages, if you now want it, the author of this app will have to make an external version of the page processor including JavaScript. I do not think he will do it.

I notice Ghost commander uses content://com.android.externalstorage.documents/tree/####-####%3A/document/####-####%3A for memory cards only (saf:), not sure if helpful.

**Comment by scoute-dich** [comment]
I plan to implement this some day. Since some custom roms doesn't have a html-viewer or even a text-viwer, this is on my todo list. But it has low priority at the moment.

**Comment by xandro0777** [comment]
Might be sufficient to set setAllowFileAccess?
https://developer.android.com/reference/android/webkit/WebSettings#setAllowFileAccess(boolean)

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues concerning feature requests which I will not work on for the time.
