### ISSUE TITLE
Not all colors are updated in day-night-mode switch

### ISSUE THREAD

**Issue by thetwom** [scoute-dich/browser#893]
Thanks a lot for developing this app!

There is a small issue I am observing when the android system switches from day-to-night mode.

Steps to reproduce:
1. Start FossBrowser and keep it active (it can be in background though)
2. Wait until the phone automatically changes from day-to-night mode (or via verse)
3.  Open bookmarks or history: The font color has switched color, but not the background color. Expected: background would also switch color.

The issue can be temporarily fixed by fully closing the app and starting it again.

Here a screenshot of the issue:
![Screenshot_20220308-182842_FOSS_Browser](https://user-images.githubusercontent.com/29151788/161299647-04942b84-8a11-4082-933c-c0c6021bdb62.png)
This is how it looks after restarting the app:
![Screenshot_20220308-182903_FOSS_Browser](https://user-images.githubusercontent.com/29151788/161300830-24310c45-d55c-446d-aea2-9dcceed983f4.png)

The issue was observed at version 9.0 (but I guess it stays in 9.1). My system is Lineage 18.1.

**Comment by scoute-dich** [comment]
I can not change that, because some views can not change their color on runtime. Instead of closing and reopening FOSS Browser, you can open the menu. On the rightest section (with the three dots), you can click "Restart and open tabs again".
