### ISSUE TITLE
Scrolling randomly stops working

### ISSUE THREAD

**Issue by JM480** [scoute-dich/browser#894]
Sometimes when I'm using the browser the scrolling will suddenly stop working and I have to restart the browser to fix it. I'm running version 9.1 on Oxygen OS 11 (Android 11) on a Oneplus Nord N10 5G.

**Comment by JM480** [comment]
This issue seems to happen most often in articles on www.thegatewaypundit.com.

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue. With the next update, there will come a lot of layout changes and improvements.

_Also be care of enabling all features you need in the profile settings (JavaScript, disable fingerprinting, cookies, ...)._
