### ISSUE TITLE
[anysoft] keyboard on Github, prevents use

### ISSUE THREAD

**Issue by Noitarud** [scoute-dich/browser#895]
I am not sure if issue lies with your browser or keyboard (suspect browser), repeat these actions on a github page that you can scroll on (not this one while it has few posts).

Scroll to bottom
Press on bottom comment box as if to add comment (opens keyboard)
Scroll down [to move into view] (closes keyboard)
Press on comment box as if to add comment (problem)

Result should be a flash of keyboard (shows briefly then closes), cannot enter text. Browser may scroll itself and that closes it.

B)It may do it in one step also, just press on comment box

Low priority

**Comment by Noitarud** [comment]
Can hold-press as if to select.

**Comment by scoute-dich** [comment]
Can you test default keyboard. I have no problems on my device.

**Comment by scoute-dich** [comment]
Since I did a lot of layout changes. Please open a new issue, if this is still from relevance after updating to version 9.2.

**Comment by Noitarud** [comment]
[Additional detail discovered, adding here for reference sake: while the description entry has focus (blue boarder on it) of page to create new issue on GitHub (described problem already triggered), if I then try to change the URL, the same thing occurs. No issue when title entry has focus. ]

**Comment by Noitarud** [comment]
I got new one, added GitHub.com to trusted, restarted, still says cookies required.

I will have to end here, what I probably did was prefer an older version and was using that. I did not remember because that one nor that new version does not advertise its version number (in the older one you used to have an 'about' page in settings, but version was not in the message - and that new version does not have an 'about' page to introduce you at all)
