### ISSUE TITLE
Restore the option to show non-mobile version of site

### ISSUE THREAD

**Issue by dkavlakov** [scoute-dich/browser#9]
Being able to switch to non-mobile version of a site is the only usable feature of Android stock browser (some mobile sites have limited usability or are just to intuitive to be used by humans). Unfortunately it's latest versions require unacceptable set of permissions, so it is no longer usable as failback and i was glad to find this feature in your browser. Seeing it gone now is great dissapointment. Is it possible restore it? This feature was the reason i installed it.

**Comment by scoute-dich** [comment]
The problem is, that I found no way to implement switching the user agent in a reliable way (that's the reason why I removed it). In which version it was implemented? Perhaps I can try it again.

**Comment by scoute-dich** [comment]
It is now again implemented. But works not always. Will be available in next update.
