### ISSUE TITLE
[BUG] Pressing Menu button opens menu but also closes the current tab.

### ISSUE THREAD

**Issue by Metamoran** [scoute-dich/browser#903]
As said above, on pressing the device's menu button the browser's menu will open as intended, but also the current tab will be closed outright if the "Confirm tab close" setting is disabled. If the "Confirm tab close" setting is enabled, the browser will instead ask for confirmation to close the tab. If there's a single tab open, then the browser will either be closed outright if the "Confirm browser exit" setting is disabled, or ask for confirmation to close the browser if enabled.

**Steps to reproduce:** Simply press the device's menu button. 
**FOSS Browser Version:** 9.1 (I tried both the F-Droid and Github versions)
**Android version/device:** Android 11 (MIUI , yes I know it's trash and I should replace it), Xiaomi

Thanks.

**Comment by scoute-dich** [comment]
Hi,

since I have no on-screen buttons, I can not reproduce this. Pressing the menu button should simply open the menu. Perhaps a Miui issue? Or have you remapped the actions, triggered when pressing hardware buttons?

**Comment by scoute-dich** [comment]
Since I did a lot of layout changes. Please open a new issue, if this is still from relevance after updating to version 9.2.
