### ISSUE TITLE
Home-screen links improvment

### ISSUE THREAD

**Issue by Noitarud** [scoute-dich/browser#906]
Registering interest feature improvment.
I see on desktop computers the web sites have icons (and in DDG), I ask for the icon to be used in the shortcut placed on the Home-screen. It is doable because the app Contacts will place image of contact (when you select 'create shortcut') if one was added to the contact, maybe you can copy how they did it.
The idea was to run what are called HTML or Web applications, or are called PWAs...

Issue#2: the bookmarks sent to home open with DDG even though it has your icon in the corner … probably an android issue.

Incidentally, DDG does use site icons for its home-screen links.

**Comment by scoute-dich** [comment]
This will is fixed with next update. Also, Favicons as icons!
