### ISSUE TITLE
Link opens in OTHER browser

### ISSUE THREAD

**Issue by Noitarud** [scoute-dich/browser#907]
I  might have DDG set as the default browser, you use 'startpage' as your search engine. Pressing on a search result opens in DDG. Can this be stopped? I can use long press to continue with Scoute.
Low priority

**Comment by scoute-dich** [comment]
You can set FOSS Browser as your default browser in system settings.

**Comment by scoute-dich** [comment]
For shortcuts on the home screen, this is solved.
