### ISSUE TITLE
[Enhancement] Add subsection  section to the profile private  options

### ISSUE THREAD

**Issue by skyerjoe** [scoute-dich/browser#909]
Hello

In the actual state there are only one section ( enable/disable) in the data privacy setting in the profile.

This suggests that the option when it's disabled, regardless if it's an tracking or an option which enhance privacy, leads to an disadvantage. 

Solution:

Add an extra section. 

1. Enable/disable 
2. Allow/disallow 

Best regards

**Comment by scoute-dich** [comment]
I resorted the entries in the "edit profile settings". So I think things should be clearer in the future. Thanks for the hint.
