### ISSUE TITLE
Background links changed

### ISSUE THREAD

**Issue by cavemandaveman** [scoute-dich/browser#91]
Before, when you opened a link from a different app, Browser created a separate notification for each link. Now they are all grouped into one notification.

Also, when you click this notification to go to open the link, it takes you to the original first tab you were on previously. You have to show your tabs to see the links that were opened.

It would be nice if each link you click creates a separate notification, then when you click that notification, Browser will take you to that tab.

**Comment by scoute-dich** [comment]
SInce I switched to Ninja Browser as base for my app this isn't possible anymore. The in the background opened tabs are all stored in an "Holder". When you open Browser all links are already fully loaded and you can switch between them easily.
