### ISSUE TITLE
Black screen in the middle of the screen

### ISSUE THREAD

**Issue by GasenGH** [scoute-dich/browser#910]
Hello Everyone!

I have a problem with FOSS. Sometimes when I go to my search and I want to find something. When I clic search the browser finds my search but I see half screen black or my favorites webs pages.

![Screenshot_20220505-084353_Navegador_FOSS](https://user-images.githubusercontent.com/104969125/166876303-9bcabf76-a7fe-4920-81d9-db4d02cbf709.png)

![Screenshot_20220505-085739_Navegador_FOSS_1](https://user-images.githubusercontent.com/104969125/166876835-fd7bf67a-b900-45f9-aef5-f26c9262ec79.png)

 
I can change some configuration in app or It's a bug? I attached a screenshots.

Thank you in adavance.

**Comment by scoute-dich** [comment]
I'm aware of it. But I can not reliably reproduce this. It seems to happen randomly, when lists change their visibility (p.a. the search list ...).

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue. With the next update, there will come a lot of layout changes and improvements.

Also be care of enabling all features you need in the profile settings (JavaScript, disable fingerprinting, cookies, ...).
