### ISSUE TITLE
File name is not shown in the download prompt at southmp3.org

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#916]
Steps to reproduce
Navigate to: https://southmp3.org/kanchana/.
Download a file.
Observe the download prompt.
Expected behaviour
The file name is shown.

Actual behaviour
The file name is blank.

**Comment by scoute-dich** [comment]
Perhaps the same issue than #917 ?

**Comment by scoute-dich** [comment]
There's a method in the code which is called "GuessFilename". I improved it a bit, but it is not possible, that the right filename is always shown.
