### ISSUE TITLE
Download dialog does not decode multibyte file name 

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#917]
Steps to reproduce
Download the test file here: https://wwa.lanzoui.com/iz4favlcrne

Expected behaviour
Decoded as: 中文文件名测试.txt

Actual behaviour
File name could not be decoded: %E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E5%90%8D%E6%B5%8B%E8%AF%95.txt

**Comment by scoute-dich** [comment]
There's a method in the code which is called "GuessFilename". I improved it a bit, but it is not possible, that the right filename is always shown.
