### ISSUE TITLE
what's this

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#918]
![Screenshot_20220510220336~2](https://user-images.githubusercontent.com/87817690/167661331-ca98464a-053f-4d93-bc7f-447df7c6e96f.jpg)

**Comment by scoute-dich** [comment]
Just a to late Easter egg.

**Comment by scoute-dich** [comment]
I'll make a hint when long pressing. I had the idea around Easter this year. And now a had new string and didn't want to as a new one, because of the translations. Should I remove it?
