### ISSUE TITLE
Can not play music in this url

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#92]
It was a music play page.I can play music in other browser 
But can not play in 'browser'
 http://m.kugou.com/share/?chain=3TE6c4ct4V3&id=3TE6c4ct4V3

**Comment by scoute-dich** [comment]
Yes, I can confirm. But at the moment I don't know what to do....

**Comment by lishoujun** [comment]
I guess this site has some browser limit。

**Comment by scoute-dich** [comment]
Ok. I looked in it but found also no reason... Perhaps you need a special plugin (flashplyer or something like that).
