### ISSUE TITLE
Image download fails on meteoprades.net 

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#920]
Steps to reproduce
Navigate to https://www.meteoprades.net/webcams/webcam-castell-de-siurana/
Long press an image and select "Save as" option.
Observe behavior.
Expected behaviour
The image is downloaded and available on the mobile device.

Actual behaviour
Download fails.

Android version
Android 9

**Comment by scoute-dich** [comment]
> Just guessing: not something that can be fixed in the browser?
