### ISSUE TITLE
Unrelated: K9-Material-mods

### ISSUE THREAD

**Issue by spmp** [scoute-dich/browser#922]
UNRELATED TO `browser`, sorry, this is the only way I could find to get hold of you @scoute-dich.

I am still using your old fork of K9-Material as it seems to have a modification from K9 (vanilla) that allows a threaded view of incoming and sent mail at the same time in Universal view.
Are you able to point to the changes you made (diff/whatever) such that these changes can be incorporated upstream. I have tried and failed to find the source code of your fork. 
 There is a ticket from 2015 in K9 on this, maybe time it's closed 🤗

Cheers 8)

**Comment by scoute-dich** [comment]
I think I can not help you. It is too long in the past. Also, it seems that I deleted the repo ... Sorry.
