### ISSUE TITLE
browser GUI forward/back pages navigation

### ISSUE THREAD

**Issue by Strats8** [scoute-dich/browser#923]
Hi,

Just downloaded FOSS browser from F-Droid and it has become my default android browser.

I was wondering if a GUI page navigation system could be added to the browser i.e. going to page 1 and tapping link to page 2 then tapping page 2 link to page 3 all within the same profile tab and navigating forward/back to these pages.

As it stands, I can go back to page 2 from page 3 through OS back button but from page 2 I cannot go forward to page 3.

Could a browser GUI option be added to navigate forward/back through different links from same profile tab with the added option to explicitly define the number of allowed pages to navigate to/back from? e.g. 10 pages total can be saved in cache to navigate to/back from, etc.

Thanks

**Comment by tusch001** [comment]
You could use guestures in settings and define forward / backward guestures (e.g swiping left / right on navigation bar) to move through pages.

**Comment by Strats8** [comment]
> You could use guestures in settings and define forward / backward guestures (e.g swiping left / right on navigation bar) to move through pages.

Hi tusch,

Never thought of using this, great advice.

Not a coder, did come here for a request but as feedback goes, swiping to move forwards/backwards is great but can cause the browser to be dismissised when correcting a url on first page and swiping backwards on accident.

Pushing it but I believe a customizable page cache could be useful too if relevant at all.

**Comment by scoute-dich** [comment]
As @tusch001 said, there are gestures to navigate back and forward in history. If you do not want to accidentally close FOSS Browser there's also a setting to give a warning, if FOSS Browser closes.
