### ISSUE TITLE
Persistent swipe issues

### ISSUE THREAD

**Issue by Strats8** [scoute-dich/browser#924]
Hi scoute,

Thanks for FOSS Browser.

Had to downgrade 9.2 to 9.1 as history gestures i.e. swiping either way to navigate history from the toolbar no longer works but only selects url textfield.

**Comment by Strats8** [comment]
> I changed the gesture settings for more consistence for new users. Just update and go to the gesture settings. Sorry for the trouble.

No worries.

Can confirm persistent issue on fresh F-Droid FOSS Browser 9.2 android v. 9

**Comment by Strats8** [comment]
Same problem with GitHub v. 9.3 android 9

**Comment by scoute-dich** [comment]
I'll release 9.3.1 today. Sorry for the trouble.

**Comment by SantjagoCorkez** [comment]
Swiping down (scroll up) reloads current page no matter was if it was a long swipe at the very top of the page or somewhere in the middle of even the bottom.

Was not an issue before the last update.

**Comment by Strats8** [comment]
> Swiping down (scroll up) reloads current page no matter if it was a long swipe at the very top of the page or somewhere in the middle of even the bottom.
> 
> Was not an issue before the last update.

There are multiple settings for swipe down/reload.

Make sure either reload set in Behavior/UI or Gestures.

**Comment by SantjagoCorkez** [comment]
> Make sure either reload set in Behavior/UI or Gestures.

Neither.

Swipe up -> scroll up
Swipe down -> scroll down

**Comment by Strats8** [comment]
> 
> > Make sure either reload set in Behavior/UI or Gestures.
> 
> Neither.
> 
> Swipe up -> scroll up
> Swipe down -> scroll down

You can find this in the settings.

**Comment by scoute-dich** [comment]
With the next update, I'll  remove the "swipe down to reload" - setting, since it can be handled with gesture settings.

**Comment by Lakjdf** [comment]
Just a note: Swipe down to reload works just fine for me with 9.3.1.
Also: you may want to consider applying such a workaround for the gestures: https://github.com/Lakjdf/browser/commit/0cf8bf72f96b76e15cf82d2186bbe84cc78ad40c
Currently, the onFocusChangeListener sometimes prevents the gestures to be detected. This workaround only sets it when you are editing the url.

**Comment by tusch001** [comment]
> I'll remove the "swipe down to reload" - setting, since it can be handled with gesture settings.

---

Just a remark:
For me the swipe down guesture on the navigation bar is often not usable (too near at the bottom to be detected, both on my older phones as well as my new one). Swipe left / right I use for backwards / forward, swipe up for tab overview and long press for the individual domain security settings.

---

In my personal setup I would not have any guesture left to reload a page. This would not be a problem if there were still a reload icon in the 3 dot menu as it was in older versions of FOSS browser. Or if I could assign a long press event to the the three dot menu as it used to be to open the security settings.

I'm not sure if you would want to bring back the reload icon?

---

Don't get me wrong: 
I still think it is a good idea to let the user customize the swipe gustures. There are just too many options for a limited number of guestures. And the more options I have ... I want them all :-)

---

Thanks anyway for your browser. You might be interested to hear that I love it so much that it is even my main browser on a mobile phone with Ubuntu Touch OS (+ waydroid container with lineage OS 17).

**Comment by tusch001** [comment]
something else:
if you have the history icon instead of the bookmark icon next to the tab overview in the navigation bar the second set of guesrures (in settings) are not applied. Instead you get a toast with "error". Correct behaviour because the guestures fir history are not set. But not something a user would expect.

**Comment by Kamul-PL** [comment]
> With the next update, I'll remove the "swipe down to reload" - setting, since it can be handled with gesture settings.

Could you revert this option, please? I used it a lot and it was very comfortable for me. I know it could be set as a gesture for one of the two toolbar buttons. But I have used whole gestures - no on free for site reload. ;)
Besides, if *swipe down to reload* is as an option, it could be simple disabled by everyone who doesn't like it. Or maybe there is some other good reason it was removed?

**Comment by scoute-dich** [comment]
Since opening this issue, I changed a lot of code. So I'll close this issue. If the issue also exists after the update in Version 9.6, please open a new issue.

**Comment by Strats8** [comment]
Will be checking as soon as 9.6 hits F-Droid.
