### ISSUE TITLE
Browser crashes when switching embedded video to full screen

### ISSUE THREAD

**Issue by nucleone** [scoute-dich/browser#925]
The issue is that whenever there's an **embedded video** in a webpage (e.g. https://www.nezavisne.com/novosti/drustvo/Milica-Pavlovic-s-maturantima-defile-Katolickog-skolskog-centra-i-Elektrotehnicke-skole/719085 ), if I tap on the video's **square button** to make it go full screen, the browser crashes (see the attached screenshot).
It wasn't happening before at least the latest update (v9.3), as I hadn't tried v9.2 before it. 
Can anyone else confirm it? 

![Screenshot_2022-05-19-08-22-53-126_de baumann browser](https://user-images.githubusercontent.com/92372373/169225182-b0eaf085-fefe-4550-ad43-871aad17c759.jpg)

**Comment by JM480** [comment]
I have the same problem with [BitChute.](https://www.bitchute.com/)

**Comment by scoute-dich** [comment]
Will release 9.3.1 today. Thanks for reporting!
