### ISSUE TITLE
Pull-to-refresh Interfering with Scrolling

### ISSUE THREAD

**Issue by runninghamster0** [scoute-dich/browser#926]
I've just updated to the latest GitHub 9.3 release, and I'm facing issues trying to scroll through pages.

It seems the pull-to-refresh is too sensitive, registering a relatively normal swipe as a long/fast swipe for activating pull-to-refresh.

![record.gif](https://user-images.githubusercontent.com/52240313/169260669-9924ebcd-dc2d-44b7-961e-30afc58f650f.gif)

**Comment by scoute-dich** [comment]
I noticed. Just working on it. Will release 9.3.1 today.
