### ISSUE TITLE
Crash when switching embedded Video to fullscreen

### ISSUE THREAD

**Issue by ksapp-dell** [scoute-dich/browser#928]
Hi,

the latest version can play videos from Twitter through their website. But when you try to switch the video to full screen,  the browser crashes.
This is repeatable for example here

https://mobile.twitter.com/home

**Comment by scoute-dich** [comment]
Next update will fix this. Sorry for the trouble and thanks for reporting the issue.

**Comment by JM480** [comment]
This issue is fixed in the latest version.
