### ISSUE TITLE
Redirection feature doesn't seem to work

### ISSUE THREAD

**Issue by cbiere** [scoute-dich/browser#935]
version: 9.3.1
source: F-Droid

In the privacy settings the feature Redirect is enabled for Twitter and Instagram. 

Expected behavior: When I click on a Twitter link, I want to be redirected to the equivalent nitter link . Ditto for Instagram.

Actual behavior: When I click on a Twitter link, the original Twitter website is loaded. Ditto for Instagram.

**Comment by cbiere** [comment]
It does work, if I copy the link or long-press the link to open it in a new tab. Is this intended behavior?

**Comment by cbiere** [comment]
By the way, the replacement is implemented too simplistic. thisisnottwitter.com and thisisnottwitter.com.nyud.net get redirected to nitter.net as well. The same applies to the other two refirect options (YouTube and Instagram).

**Comment by scoute-dich** [comment]
Thanks for reporting. I think for the first problem (opening twitter in the same tab) I found a solution. On the second thing, I'm working.

**Comment by scoute-dich** [comment]
So I think this is solved, as good as I can. For the second part of your issue, there will be a button in the FastToggleDialog to enable/disable redirections on the fly.
