### ISSUE TITLE
Translate option in context menu

### ISSUE THREAD

**Issue by Kamul-PL** [scoute-dich/browser#936]
Hello!

In context menu in browser I used to use was an option to translate selected text (via Google Translate). It was very convenient in case of reading sites in foreign languages. Unfortunately I can't find such a thing in FOSS Browser.

Could you add this feature, please? It seems it's not a lot of work. But it's a great facilitation in case when someone needs to translate some words frequently.

**Comment by scoute-dich** [comment]
That would be too much work. Just think of the new strings ... . I learned to code by myself in my free time. Since I have also a job and family, I want to keep it simple. So I will not implement this.

You can share the text to preferred translation app.

**Comment by Kamul-PL** [comment]
That's OK. It was just a suggestion. I used to use Naked Browser Pro (lightweight web browser). There was such an option implemented and it was really comfortable. And I thought it's a really simple thing to add. I thought it's simple a matter of sending marked text to external app (Google Translate) after choosing such an option in context menu. It looked for me like "a few" lines of code. But it seems I was wrong.

*Just think of the new strings ... .*
By the way, what do you mean by that?
