### ISSUE TITLE
Custom hosts file

### ISSUE THREAD

**Issue by amir28** [scoute-dich/browser#939]
The default block hosts.txt does not block some advertising domains. I think It's better to allow user to choose hosts file alongside default ones so user can edit it and add some domains or delete some.

**Comment by scoute-dich** [comment]
That's something I'm thinking about, and it is set to the todo list. At least to add custom domains to the hosts. But that could take time, since I have work and family.

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues concerning feature requests which I will not work on for the time.
