### ISSUE TITLE
Put the backup in android/data/de...

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#94]
Current  the backup are put in the root of sdcard.
I think it is not fit the android suggestion.
It should be put in android/data/de...browser/

**Comment by scoute-dich** [comment]
If I make this, the suggested folder will be deleted when uninstalling Browser.

**Comment by ildar** [comment]
right. AFAIK there's no standard place for such things. But creating just
another folder in /SDCARD root is a mess. The most appropriate way I've
seen apps using /sdcard/Documents/app/

**Comment by scoute-dich** [comment]
With next update backup folder will be /Documents/browser_backup.

Thanks for the hint. So it'll be much better.

**Comment by lishoujun** [comment]
OK
