### ISSUE TITLE
Force HTTPS protocol

### ISSUE THREAD

**Issue by newbiedroid** [scoute-dich/browser#940]

**Comment by tusch001** [comment]
I second this, especially in mixed content pages (images with http in https sites).
In my opinion support for the http protocol should be dropped completely. Urls can be rewritten to https by the browser if necessary.


You can expect webhosters to configure their server for https correctly. And even private people running their own server can find out how to configure ssl in 5 minutes for apache / nginx server and use let's encrypt for certifcates.

If a page is still not viewable it most likely has not been maintained for 20+ years.

**Comment by alicaccs** [comment]
> I second this, especially in mixed content pages (images with http in https sites).
> In my opinion support for the http protocol should be dropped completely. Urls can be rewritten to https by the browser if necessary.
> 
> 
> You can expect webhosters to configure their server for https correctly. And even private people running their own server can find out how to configure ssl in 5 minutes for apache / nginx server and use let's encrypt for certifcates.
> 
> If a page is still not viewable it most likely has not been maintained for 20+ years.

Then you must forget the admin interface found on ordinary home routers. One cannot easily upgrade the interface to HTTPS without detailed knowledge.

**Comment by tusch001** [comment]
@alicaccs 
You are right.
Until yesterday I could have sworn that any router / switch / IP phone bought in the last 10 years should be able to use https (with an unknown CA certificate). Today I ran into a recently bought DECT station that only supports http.

Maybe at least for mixed content pages (= no user input or https demand by the user in the url) we should force https for all content on the page. And only when explicitly a http page is requested there could be an exeption.

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues concerning feature requests which I will not work on for the time.
