### ISSUE TITLE
Settings are lost again

### ISSUE THREAD

**Issue by hurzl** [scoute-dich/browser#943]
Since the latest version(?) the dark mode is disabled on every tab every time the app is restarted. I thought this was solved some time ago ...

**Comment by scoute-dich** [comment]
Just check the settings. I added a new option: "Follow system". Perhaps this caused the trouble.

**Comment by scoute-dich** [comment]
Since opening this issue, I changed a lot of code. So I'll close this issue. If the issue also exists after the update in Version 9.6, please open a new issue.
