### ISSUE TITLE
HttpAuth no password field

### ISSUE THREAD

**Issue by ralfi** [scoute-dich/browser#945]
Hi, using httpauth with user/password do not show the pwd field using apache mod_auth.

**Comment by scoute-dich** [comment]
Can you give ma link to test?

**Comment by scoute-dich** [comment]
Only to show the dialog.

**Comment by ralfi** [comment]
Yes of course, I am on short vacancy trip last weekend, give you asap ...

**Comment by scoute-dich** [comment]
I just need a link to a website where such a "HttpAuth-popup-dialog" is shown. I do not need a config file or something like that. You can send me a link to baumann.juergen@posteo.de, if you want.

**Comment by ralfi** [comment]
Hi, i send you this asap...

**Comment by ralfi** [comment]
Done...

**Comment by ralfi** [comment]
A little bit confusion...

![ksnip_20220715-133456_v1](https://user-images.githubusercontent.com/294423/179216500-b6d0a97a-7449-47b6-a809-67dbae2360e5.jpg)

**Comment by scoute-dich** [comment]
Since opening this issue, I changed a lot of code. So I'll close this issue. If the issue also exists after the update in Version 9.6, please open a new issue.
