### ISSUE TITLE
feature request: fine tuning of javascript permission / cookies for third party domains

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#946]
Nowadays a lot of sites are not usable without javascript. Most times JS is not strictly necessary if you just want to view the page without eg buying something. 

- menus can't be opened (a lot of smaller shopping sites)
- annoying GDPR consent boxes on top of everything, that can't be discarded (amazon, also issue 933)
- images are not visible and loaded with js (amazon again)
- incorrect css for wide screens that is corrected with JS (tagesschau.de)
- google recaptcha necessary for access (login ebay-kleinanzeigen.de)
- if you need JS for the service you also get the tracking (even without consent - bahn.de)
- also most likely some of the download failures are related to JS (issues 920 / 921?)

But when you give javascript permission you also allow all third party domain connections (and all the tracking).

I wish I had something like the noscript addon for firefox where I could allow for a site on `example.com` access to the domains

```
example.com
example-pictures.com
```

but prevent access to

```
google-analytics.com
google.com
i-sell-your-data.com
```

This needs most likely to be individually toggled for each domain. Maybe even only temporary.

I know it might be complicated to implement in the UI with a small screen but if you will ever find the time ...

**Comment by scoute-dich** [comment]
I'm not knowing, how to implement such things. I learned to code by myself in my free time. Since I have also a job and family, I want to keep it simple. So I will not implement this. Not in the near future.
