### ISSUE TITLE
Can't move toolbar to top

### ISSUE THREAD

**Issue by Taxit0m** [scoute-dich/browser#947]
Please add this or clear instruction for process if existing.  No option to open url with native app, no option to edit custom profile level

**Comment by tusch001** [comment]
please read #681

**Comment by tusch001** [comment]
This feature was repeatedly requested (last time 6 weeks ago) but the changes to the UI would be a too huge project for a privately maintained app from 1 author.

The upside:
Once you get used to the bottom navigation bar you will miss it in other browsers. 
Less movement = faster input :-)

**Comment by tusch001** [comment]
> no option to edit custom profile level

In the three dot menu - advanced settings (the three horizontal dots) - settings - privacy you can edit the different security profiles and choose your default profile.

To change the security settings for an individual domain you need to assign "fast settings" (rough translation) to a guesture to open a menu with this guesture in an open tab.

Unfortunately at the moment there are some issues with guesture input in version (9.2?,) 9.3 and 9.3.1 which will hopefully be fixed soon. But eg a long press event on the tab icon in the navigation bar (after assigning the guesture) works well to open security settings.

**Comment by tusch001** [comment]
> No option to open url with native app

Three dot menu - share icon (second left in ltr languages) you have the options to do something with an url

- share to app
- share to clipboard
- open with ...

**Comment by Taxit0m** [comment]
> This feature was repeatedly requested (last time 6 weeks ago) but the changes to the UI would be a too huge project for a privately maintained app from 1 author.
> 
> The upside:
> Once you get used to the bottom navigation bar you will miss it in other browsers. 
> Less movement = faster input :-)

While it may give _you_ faster movements and in your opinion be missed in other applications/readers/browsers, my device has quite a large screen and a very high screen to body ratio, and I'm not double jointed in the thumbs, or any other finger, so this not only cramps the part of the display where my eyes focus clouding the speed in which my brain processes input but also cramps my hands.  I do like the FOSS community and applications a ton and do realize the amount of effort they contain, especially maintained by 1 person, but if it's been requested numerous times and your answer is tough sh*t, change your preference in application usability,  I find it easier and more suitable to use the uninstall feature and leave this application to the section of double jointed users with Fisher Price devices.

**Comment by Taxit0m** [comment]
> > No option to open url with native app
> 
> In the three dot menu - share icon (second left in ltr languages) you have three options to do something with an url
> 
> - share to app
> - copy to clipboard
> - open with ...

Ok so they're is an option but takes 4 extra steps and movements for each individual link every time you come across one...but refusing the toolbar at the top for...... Faster movements?

**Comment by Taxit0m** [comment]
> > no option to edit custom profile level
> 
> In the three dot menu - advanced settings (the three horizontal dots) - settings - privacy you can edit the different security profiles and choose your default profile.
> 
> To change the security settings for an individual domain you need to assign "fast settings" (rough translation) to a guesture to open a menu with this guesture in an open tab.
> 
> Unfortunately at the moment there are some issues with guesture input in version (9.2?,) 9.3 and 9.3.1 which will hopefully be fixed soon. But eg a long press event on the tab icon in the navigation bar (after assigning the guesture) works well to open security settings.

Ahhh, ok I see now.  There isn't an option to modify the custom profile level, and I just manually add each domain any time I come across a website using cookies (99.9% of them these days) or I have to trust every site?  No way to specify 3rd party cookies separately from other cookie types?  Seems like a lot just for functionality.... Didn't you say something about faster when asked about toolbar at the top?

**Comment by tusch001** [comment]
Sorry, I am NOT the maintainer of the app.
I was just trying to help, because you couldn't find some settings. 

And concerning the toolbar:
That is up to @scoute-dich. I'm just following here for a long time and he has repeatedly said that he has no time for this. The reason that the nav bar is at the bottom is bc he likes it this way, as I do. It is from a time when phones were small and usable with one hand. So if you are lucky he may reconsider.

Perhaps he can give his input. (It might be some days, Pentcost in Germany are important holidays)

Have a nice weekend.

**Comment by Taxit0m** [comment]
>  It is from a time when phones were small and usable with one hand.  
   
8 44 2 8 7777 _ 222 88 8 33 _ 222 2 555 555 _ 6 33 _ 2 333 8 33 777 _ _ 9 44 33 66 _ 6 444 66 88 8 33 7777 _ 2 777 33 _ 333 777 33 33


My fist cell phone held a charge for 4 days with heavy use.  This is a moot point.  
   
Since your are not creating a fork and not able to alter the original source in this repository, it would make you intelligible to respond with such an answer and would advise you in the future to refrain from adding input of this sort and leave these issues for the developer.

**Comment by pc00per** [comment]
> Since your are not creating a fork and not able to alter the original source in this repository, it would make you ineligible to respond with such an answer

That is purely his pov. Everyone can give their own opinions, and that doesn't mean one isn't eligible to state their own pov. This isn't some eligibility competition (as long as the comments adher to GitHub's guidelines).
