### ISSUE TITLE
Change browser default settings

### ISSUE THREAD

**Issue by leopedro95** [scoute-dich/browser#949]
I am newbie in this branch of android app development and I am using this script to learn how to modify.

However, I would like to change the default settings of the "normal" profile, in which file/path can I do this? I saw xml of the other profiles, but the default I don't think. Anyone who can help me, I appreciate it.

**Comment by tusch001** [comment]
You don't need to edit files just for changing most of the profile settings. 
You can change the settings of the individual profiles in the menu: tab the `three vertical dots` in the nav bar, then the `three horizontal dots` in the menu, then goto `settings`. In `privacy` you can set your prefered `profile at app start`, the button `edit profile` let's you toggle data, privacy and security settings for the three different profiles (trusted, default, protected). 

(menu entrys might be different, I just translated back to English).

**Comment by leopedro95** [comment]
> Você não precisa editar arquivos apenas para alterar a maioria das configurações de perfil. Você pode alterar as configurações dos perfis individuais no menu: guia `three vertical dots`na barra de navegação, depois `three horizontal dots`no menu e depois em `settings`. Em `privacy`você pode definir sua preferência `profile at app start`, o botão `edit profile`permite alternar as configurações de dados, privacidade e segurança para os três perfis diferentes (confiável, padrão, protegido).
> 
> (as entradas do menu podem ser diferentes, acabei de traduzir de volta para o inglês).
Yes I understand, but I would like to edit the default settings, because I will be using this browser for a purpose.  The fact that the browser does not accept cookies by default already interferes with my purpose with the application.  Teaching my users to configure this way right in the app would be too much work.  If you can help me I would be grateful.

**Comment by scoute-dich** [comment]
The default values are defined in the "res/xml/..." files. But also, when you call a setting the first time, you must configure the default value. Also, some settings are written, when the app first starts. So you have to search this callings and also configure them.
