### ISSUE TITLE
Bug: "Save at Home" option not work correctly 

### ISSUE THREAD

**Issue by rockstar96969696** [scoute-dich/browser#95]
#### Expected behavior
If we select the option "Save to Home" then it must save the specific page to Home screen or in the Home of the Browser but it done Nothing. No any action actually found on Home Screen or Home of the Browser.
#### Actual behavior
When i click on the option "Save to Home" then it shows the Message that it successfully added to Home. But actually it does nothing i didn't  find my page in Home.
#### How to reproduce
Download and install the Browser Version 5.1.1 [Download Link](https://f-droid.org/packages/de.baumann.browser/)
Visit any website and click on option button as shown in this screenshot
![IMG-20180216-WA0001.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518768711/flv4lprejh4dpqkw1swr.jpg)

Now click in save

![IMG-20180216-WA0002.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518768771/mx8jwc1idqjrrgzxzcpm.jpg)

Now click on Save to Home option

![IMG-20180216-WA0003.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518768890/nngggsfbycjpw7mrv1fu.jpg)

Nothing Inserted on Home. 

* Browser: Browser Version 5.1.1 [Download link](https://f-droid.org/packages/de.baumann.browser/)
* Operating system: Android Nougat 7.0
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@faisalamin/bug-save-at-home-option-not-work-correctly">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by scoute-dich** [comment]
Please update to latest version (v5.2) via F-Droid or PLayStore and report if the bug still exists. Tere are no problems on my side.

**Comment by scoute-dich** [comment]
Please reopen, when still persists on latest version. Thanks.

**Comment by rraallvv** [comment]
I'm having this issue too. I've cloned the repository and I'm currently at 2104314.
The problem is that when I go to google.com and save it as the home page, apparently it's saved but then if I close and re-open the browser it stills open the repository page. Trying to open a new tab opens the repository page too, and if I try to save google.com again as the home page it says the page is already saved. I have Android 5.0.1.

**Comment by rraallvv** [comment]
I'm skimming through the source code and it looks as if the home page is some kind of grid, maybe something like Chrome when a new tab is open, but that's not what I see. When I open a new tab I always get the repository page, and can't find anything on the settings or tabs menus to show the home page that I've save at home.

**Comment by Tobiplayer3** [comment]
@rraallvv The home page is not the new tab page. You can access the home page by clicking on the bottom left and then selecting the icon that looks like a globe. The page for a new tab can be set by saving a webpage as a bookmark and then doing a long click on the new item in the bookmark category (again the bottom left icon but this time the icon that looks like a bookmark).

**Comment by rraallvv** [comment]
@Tobiplayer3 Thanks for looking into this. I saved the page as a bookmark and went to the bookmarks page, then with a long press I get the options for "New tab (foreground)", "New tab (background)", and also "Set as start site". I tried the set as a start site but it creates a new icon on the launcher, is that what you are referring to?

**Comment by rraallvv** [comment]
Never mind, the option "New tab (foreground)" seems to set the home page to the one I've selected from the bookmarks. Thanks a lot.

**Comment by scoute-dich** [comment]
In the next release you will be able to set every website which is saved in the overview (startsite, bookmarks, history) as the website which will open on first start, or when you open a new tab. It will be also possible to sweet an empty startsite via the overview menu. This works at the moment only from the bookmark page.
![](https://i.imgur.com/UCLdwuf.png)

![](https://i.imgur.com/sS4h7mr.png)

**Comment by rraallvv** [comment]
Pretty cool stuff! Can't wait.
