### ISSUE TITLE
Proxy option and built in download

### ISSUE THREAD

**Issue by andmailconta** [scoute-dich/browser#952]
As I mentioned in the previous request "force https always" for better security, in this one my dears I ask to add a proxy configuration and for the browser to download internally, without the need to forward it to the "Downloads" application of the device.

Who agrees with me?

**Comment by scoute-dich** [comment]
I'm not knowing, how to implement such things. I learned to code by myself in my free time. Since I have also a job and family, I want to keep it simple. So I will not implement this.
