### ISSUE TITLE
`&` not escaped in search URL

### ISSUE THREAD

**Issue by BrendonIrwan** [scoute-dich/browser#959]
On the release version 9.3.1,  search for `dragon quest i & ii` and be returned the results for `dragon quest i`. Look at the URL, and the `&` is not escaped to `%26`. So the string following the `&` may have been parsed as a URL argument.

You can also try to search for `&` and get the landing page.

Just in case, my search engine is:
```
https://html.duckduckgo.com/html?q=
```
But it also affects the built-in DuckDuckGo option.

**Comment by scoute-dich** [comment]
Is this still from relevance in v 9.5? I tested it and it works on my side.

**Comment by BrendonIrwan** [comment]
I installed release version 9.5. Searched for `dragon quest i & ii`, and got Startpage results for `dragon quest i`.

So no. Not sure how it worked on your side though.

**Comment by scoute-dich** [comment]
Will be fixed in v 9.6.
