### ISSUE TITLE
please add home page url or any 5 site url ex. facebook, youtube, amezon, etc. , and instragram not open in this browser please show this , and Add downloder because download etc. download file is retry and push button and show progressbar download file in browser 

### ISSUE THREAD

**Issue by niksooo7** [scoute-dich/browser#96]

**Comment by scoute-dich** [comment]
You mean links on your start page to your favorite websites?

**Comment by niksooo7** [comment]
Yes and add Download manager because Download file video,mp3,image   etc.
Pause and resume add
On 20-Feb-2018 7:32 PM, "Gaukler Faun" <notifications@github.com> wrote:

You mean links on your start page to your favorite websites?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scoute-dich/browser/issues/96#issuecomment-366986266>,
or mute the thread

**Comment by niksooo7** [comment]
add in browser open this browser and show links 
ex
(1) www.facebook.com
(2)www.youtube.co.in
etc.

**Comment by scoute-dich** [comment]
You can save every website you want via the menu: save -> on start page.

For downloading the system download manager is implemented. As I want it simple and lightweight I won't change this.
