### ISSUE TITLE
Add Brave Search as part of the Search Engine options

### ISSUE THREAD

**Issue by ghost** [scoute-dich/browser#960]
It would be nice if brave search was added alongside the other defaults in Browser Settings -> Search Engine  for convenience (easier than manually setting it).

`https://search.brave.com/search?q=`

(edit: remove %s)

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues concerning feature requests which I will not work on for the time.

Please use custom search settings.
