### ISSUE TITLE
Update app in the PlayStore

### ISSUE THREAD

**Issue by n-ce** [scoute-dich/browser#963]
There is an outdated version of FOSS Browser available in the store.
https://play.google.com/store/apps/details?id=de.baumann.browser1
The link in the description for a new version doesn't work as it keeps loading.

**Comment by tusch001** [comment]
Please read issue [#927](https://github.com/scoute-dich/browser/issues/927) halfway down. @Scoute-dich is the developer here.
Sorry.

Be aware: Before you install the newer versions from github or fdroid make a backup and copy the folder in sdcard - documents - browser_backup somewhere else. You need to uninstall google foss browser (which deletes all settings) before installing foss browser from other sources. Afterwards copy saved folder back to documents and restore your settings.

**Comment by n-ce** [comment]
Closing this as a result of https://github.com/scoute-dich/browser/issues/927#issuecomment-1133123829.
