### ISSUE TITLE
Change search engines from search bar in browser

### ISSUE THREAD

**Issue by luke-2136** [scoute-dich/browser#965]
Greetings. New user - this a 2nd feature request. When wanting to use a different search engine now you have to go into settings. It would be real handy to be able to change search engines from the search bar itself. A little seach engine changer/button on the search bar itself would be great. Thanks again.

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues concerning feature requests which I will not work on for the time.
