### ISSUE TITLE
FOSS Browser search bar widget for home screen

### ISSUE THREAD

**Issue by luke-2136** [scoute-dich/browser#966]
New user - nice work on this browser. This would be a feature request. Would be nice to have a FOSS Browser search bar widget that could be put on the home screen - that would open in the browser (like the standard google one). Type in the bar - hit enter - open up right in FOSS on the search result page. Be very useful. Thanks

**Comment by tusch001** [comment]
For now you could use a search bar widget app for the homescreen. I use https://play.google.com/store/apps/details?id=de.j4velin.searchwidget
It is very old but it is still working on Android 10 and only very few kB big. Doesn't need GSF, no advertisement.
You can use the search engine of your choice by configuring the search link, eg:
- Google https://www.google.com/search?q=
- Startpage https://www.startpage.com/do/search?query=
- Qwant lite which can be configured in detail (language, search type, ...) by adjusting parameters - here for German, no News, no social links, open in new tab, light theme: https://lite.qwant.com/?r=DE&sr=de&l=de_de&h=0&s=2&a=1&b=1&vt=0&hc=0&smartNews=0&smartSocial=0&theme=0&i=1&donation=0&qoz=0&shb=0&shl=0&q=

**Comment by luke-2136** [comment]
> For now you could use a search bar widget app for the homescreen. I use https://play.google.com/store/apps/details?id=de.j4velin.searchwidget It is very old but it is still working on Android 10 and only very few kB big. Doesn't need GSF, no advertisement. You can use the search engine of your choice by configuring the search link, eg:
> 
>     * Google https://www.google.com/search?q=
> 
>     * Startpage https://www.startpage.com/do/search?query=
> 
>     * Qwant lite which can be configured in detail (language, search type, ...) by adjusting parameters - here for German, no News, no social links, open in new tab, light theme: https://lite.qwant.com/?r=DE&sr=de&l=de_de&h=0&s=2&a=1&b=1&vt=0&hc=0&smartNews=0&smartSocial=0&theme=0&i=1&donation=0&qoz=0&shb=0&shl=0&q=

Thanks

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues concerning feature requests which I will not work on for the time.
