### ISSUE TITLE
'New Tab (background)' issue - when enabled FOSS opens in background from external link 

### ISSUE THREAD

**Issue by luke-2136** [scoute-dich/browser#969]
1. With 'New Tab (background)' enabled in settings there is a strange behavior: opening from an external link, with browser closed, FOSS opens in the background. For instance, from F-Droid app (or any web page), click a link to open with FOSS - it pops up for an instant - but immediately goes to background and the F-Droid app page comes back on screen.

- swiping back to FOSS the link will then load .. (*sometimes comes up blank though - have to then do it twice - similar to #874)

2. With 'New Tab (background)' not enabled everything seems to work fine. 

- took some time to figure out what was going on but this seems to be the issue - thanks; fyi

(phone is Android 11)

**Comment by scoute-dich** [comment]
This should be fixed with next update.
