### ISSUE TITLE
[Feature Request] Add Action item on links

### ISSUE THREAD

**Issue by cavemandaveman** [scoute-dich/browser#97]
Sometimes I want the links I click to open in other apps. In other browsers for example if I long press on a Youtube link I can choose to "Open with another app" and choose the Youtube app. Is it possible to include this functionality?

**Comment by ildar** [comment]
Yes, with Easy Open Link (Open URLs via select and share) -
https://f-droid.org/app/de.audioattack.openlink

**Comment by scoute-dich** [comment]
Will be there in next update. In the context menu (long pressing) of links and in the share menu.
