### ISSUE TITLE
Web site loads then shows image data URL 

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#971]
Open the following URL and see what happens:
https://www.sky.de/sport/fussball/premier-league/sendeplan

**Comment by tusch001** [comment]
I had a look at the site. Although there is a bit of white space I don't see visible data image URLs. I'm not sure what you are referencing. Can you post a screenshot and mark the area so I can have a look at the source code?

**Comment by tusch001** [comment]
Are you logged in while viewing the page? I don't use sky.

**Comment by Kita2345** [comment]
![Screenshot_20220807-132921](https://user-images.githubusercontent.com/87817690/183278442-37610a6b-cd6e-4ea7-8d9e-8b39c0b0d5c4.png)

**Comment by Kita2345** [comment]
Worked fine with browservio

**Comment by tusch001** [comment]
Ok. I will have a look this evening (after going swimming). I'm not so good with Java (the browser side), but 95 % of image problems are on the server side (Javascript, css, ...).

**Comment by scoute-dich** [comment]
Since opening this issue, I changed a lot of code. So I'll close this issue. If the issue also exists after the update in Version 9.6, please open a new issue.
