### ISSUE TITLE
Ufile doesn't download and results in a html file instead of the download 

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#974]
When I press download, it downloads a HTML file instead of the actual file that I want
I have some sample links here.

https://macapps.ufile.io/pfjlbgd5
https://macapps.ufile.io/w6apnkkl
https://macapps.ufile.io/4rl7pt16
https://macapps.ufile.io/bti1wgqe
https://macapps.ufile.io/wlfa9q5c

**Comment by Ilav1** [comment]
I also can't download files with foss browser.

When I want to download NetGuard 

https://github.com/M66B/NetGuard/releases/download/2.303/NetGuard-v2.303-release.apk

The browser wants to download a .bin file with compleate wrong name when click on "save as".

![Screenshot_20221114_204042_de baumann browser](https://user-images.githubusercontent.com/102852954/201751151-e66a080b-d2fc-4a87-a976-4ab817ce7b74.jpg)


When I click on "OK" the Browser download a crypticle Name as .bin


![Screenshot_20221114_204401_de baumann browser](https://user-images.githubusercontent.com/102852954/201751329-dbe3dd79-fb3b-4f1b-aea3-6b185d8f8461.jpg)

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues concerning feature requests which I will not work on for the time.
