### ISSUE TITLE
portrait-landscape-mode

### ISSUE THREAD

**Issue by otto22otto** [scoute-dich/browser#976]
- text of buttons are abbreviated. button action hard to guess. icons at former versions were more meaningful.
- vertical 3-dot window has no menue at the bottom in portrait mode. see pipictures
![Screenshot_2022-08-11_17-58-55](https://user-images.githubusercontent.com/98341864/184184100-61fef1e7-78ea-4bbd-bf55-6eb4e443fc60.jpg)
![Screenshot_2022-08-11_17-59-20](https://user-images.githubusercontent.com/98341864/184184227-3128cd8d-0245-4a18-9cdf-e20d988eed0a.jpg)

**Comment by scoute-dich** [comment]
For me, there are no problems. But since the last update, I changed a lot of code. So I'll close this issue. If the issue also exists after the update in Version 9.6, please open a new issue.
