### ISSUE TITLE
crash on start because I import nothing

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#98]
uninstall the old browser
install new browser
import database (when there are no files in backup folder)
choose restart

can't start in restart,then i start it manual crash.
then i start it again  it work now.

`02-21 13:43:10.515 19240-19240/? I/art: Late-enabling -Xcheck:jni
02-21 13:43:10.515 19240-19240/? I/art: Reinit property: dalvik.vm.checkjni= false
02-21 13:43:10.558 19240-19240/? W/System: ClassLoader referenced unknown path: /data/app/de.baumann.browser-1/lib/arm64
02-21 13:43:10.598 19240-19240/de.baumann.browser I/HwCust: Constructor found for class android.app.HwCustActivityImpl
02-21 13:43:10.601 19240-19240/de.baumann.browser I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
02-21 13:43:10.610 19240-19240/de.baumann.browser I/WebViewFactory: Loading com.google.android.webview version 64.0.3282.137 (code 328213750)
02-21 13:43:10.630 19240-19240/de.baumann.browser I/cr_LibraryLoader: Time to load native libraries: 1 ms (timestamps 4881-4882)
02-21 13:43:10.633 19240-19240/de.baumann.browser I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
02-21 13:43:10.633 19240-19240/de.baumann.browser I/cr_LibraryLoader: Expected native library version number "64.0.3282.137", actual native library version number "64.0.3282.137"
02-21 13:43:10.650 19240-19240/de.baumann.browser I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
02-21 13:43:10.651 19240-19240/de.baumann.browser I/cr_base: Android Locale: zh_CN requires .pak files: []
02-21 13:43:10.681 19240-19282/de.baumann.browser E/chromium: [ERROR:instance.cc(49)] Unable to locate service manifest for metrics
02-21 13:43:10.681 19240-19282/de.baumann.browser E/chromium: [ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
02-21 13:43:10.728 19240-19240/de.baumann.browser W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-21 13:43:10.772 19240-19294/de.baumann.browser W/Browser: Error loading hosts
02-21 13:43:10.775 19240-19295/de.baumann.browser W/Browser: Error loading hosts
02-21 13:43:10.778 19240-19240/de.baumann.browser E/SQLiteLog: (1) 
02-21 13:43:10.778 19240-19240/de.baumann.browser W/System.err: android.database.sqlite.SQLiteException: no such table: COOKIE (Sqlite code 1): , while compiling: SELECT DOMAIN FROM COOKIE ORDER BY DOMAIN, (OS error - 2:No such file or directory)
02-21 13:43:10.778 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
02-21 13:43:10.778 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:910)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:521)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:603)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1397)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1239)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1110)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1278)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at de.baumann.browser.Database.RecordAction.listDomainsCookie(RecordAction.java:541)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at de.baumann.browser.Browser.Cookie.loadDomains(Cookie.java:47)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at de.baumann.browser.Browser.Cookie.<init>(Cookie.java:59)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at de.baumann.browser.Activity.BrowserActivity.onCreate(BrowserActivity.java:445)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.app.Activity.performCreate(Activity.java:6915)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.os.Looper.loop(Looper.java:156)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6523)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
02-21 13:43:10.779 19240-19240/de.baumann.browser W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$7>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.View.NinjaWebView.<init>(android.content.Context) (NinjaWebView.java:108)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.pinAlbums(java.lang.String) (BrowserActivity.java:2650)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.dispatchIntent(android.content.Intent) (BrowserActivity.java:1230)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.onCreate(android.os.Bundle) (BrowserActivity.java:453)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6915)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1123)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2746)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.os.Looper.loop() (Looper.java:156)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.RenderProcessGoneDetail" on path: DexPathList[[zip file "/data/app/com.google.android.webview-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.webview-2/lib/arm64, /data/app/com.google.android.webview-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.View.NinjaWebView.<init>(android.content.Context) (NinjaWebView.java:108)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.pinAlbums(java.lang.String) (BrowserActivity.java:2650)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.dispatchIntent(android.content.Intent) (BrowserActivity.java:1230)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.onCreate(android.os.Bundle) (BrowserActivity.java:453)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6915)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1123)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2746)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.os.Looper.loop() (Looper.java:156)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
02-21 13:43:10.788 19240-19240/de.baumann.browser I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$3>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/SafeBrowsingResponse;
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.View.NinjaWebView.<init>(android.content.Context) (NinjaWebView.java:108)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.pinAlbums(java.lang.String) (BrowserActivity.java:2650)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.dispatchIntent(android.content.Intent) (BrowserActivity.java:1230)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.onCreate(android.os.Bundle) (BrowserActivity.java:453)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6915)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1123)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2746)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.os.Looper.loop() (Looper.java:156)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.SafeBrowsingResponse" on path: DexPathList[[zip file "/data/app/com.google.android.webview-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.webview-2/lib/arm64, /data/app/com.google.android.webview-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.View.NinjaWebView.<init>(android.content.Context) (NinjaWebView.java:108)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.pinAlbums(java.lang.String) (BrowserActivity.java:2650)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.dispatchIntent(android.content.Intent) (BrowserActivity.java:1230)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void de.baumann.browser.Activity.BrowserActivity.onCreate(android.os.Bundle) (BrowserActivity.java:453)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6915)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1123)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2746)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.os.Looper.loop() (Looper.java:156)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
02-21 13:43:10.789 19240-19240/de.baumann.browser I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
02-21 13:43:10.825 19240-19298/de.baumann.browser W/Browser: Error loading hosts
02-21 13:43:10.828 19240-19299/de.baumann.browser W/Browser: Error loading hosts
02-21 13:43:10.861 19240-19240/de.baumann.browser I/HwPointEventFilter: do not support AFT because of no config
02-21 13:43:10.880 19240-19240/de.baumann.browser I/art: System.exit called, status: 0
02-21 13:43:10.880 19240-19240/de.baumann.browser I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
`

**Comment by scoute-dich** [comment]
That's because of the implementation of cookie whitelist. I had to change the database model. The update will delete the database (that's the crash) and recreate a new (that's why it works after restart. I will do nothing more. Once the app restarted, it will work properly.
