### ISSUE TITLE
Filenames of downloads are wrong

### ISSUE THREAD

**Issue by ksapp-dell** [scoute-dich/browser#980]
When klicking on a link to download a file a very long filename will be given. Also the extension is very often wrong - e.g. '.bin' instead of PDF.
![Screenshot_20220826-084041_FOSS Browser](https://user-images.githubusercontent.com/62463497/186839806-0f4b3c49-8fb3-4d92-b98b-6ddbe380e6ea.jpg)
![Screenshot_20220826-084037_FOSS Browser](https://user-images.githubusercontent.com/62463497/186839865-c092b521-9e78-4844-a112-ad1b7df0effa.jpg)

**Comment by pipip** [comment]
same problem here

**Comment by Ilav1** [comment]
Ibalso habe these Problem :(
