### ISSUE TITLE
Support U2F/WebAuthn

### ISSUE THREAD

**Issue by jplitza** [scoute-dich/browser#981]
It would be great to habe support for U2F/WebAuthn. In my case I'd love to usw my Yubikey via NFC or USB for that, but using the secure enclave of the phone would be a great option too!

I'm not aware of support for this outside of Chrome, which uses the GMS Core for everything, so its code is useless to free browsers.

**Comment by scoute-dich** [comment]
I don't know if this is possible using webview. Also, I don't even have the knowledge to implement such things. So I cannot add this feature. So I will not add this feature.
