### ISSUE TITLE
IPv6 literal addresses

### ISSUE THREAD

**Issue by xerz-one** [scoute-dich/browser#982]
[According to RFC3986](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.2), and in order to allow parsing while avoiding conflicts with ports, IPv6 URIs are defined like the following:

> A host identified by an Internet Protocol literal address, version 6
   [[RFC3513](https://www.rfc-editor.org/rfc/rfc3513)] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").

> `IP-literal = "[" ( IPv6address / IPvFuture  ) "]"`

However, when introducing an IPv6 literal URI, FOSS Browser fails to parse it correctly, and instead attempts a web search. This is obviously wrong and should be trivial to fix as well, although if you use `android.net.Uri`, you might want to be careful due to incompatibilities prior to API 29: https://issuetracker.google.com/issues/37069493

**Comment by xerz-one** [comment]
P.S.: You might also be interested in [RFC6874](https://www.rfc-editor.org/rfc/rfc6874.html), which extends IPv6 literal addresses to support zone identifiers (e.g. `[2a03:4000:58:9fd::1%wlan0]`). This might require extra manual parsing and I don't know if it is supported by Android itself, though.

**Comment by scoute-dich** [comment]
Sorry to say: Since I do not have a lot of time, I'm closing issues concerning feature requests which I will not work on for the time.

If it is that easy you can help, opening a pull request.
