### ISSUE TITLE
Bring back scroll down to show navigation

### ISSUE THREAD

**Issue by jerryn70** [scoute-dich/browser#99]
Now it's hard to switch tabs . Because everytime i need to press the back button to make the navigation visible .

**Comment by scoute-dich** [comment]
For what do you need the navigation? Open tabs, switching tabs, searching?
I'm asking because I don't want to switch to the previous behavior. But perhaps there's an other solution... Since I'm also not really happy as it is.

**Comment by jerryn70** [comment]
I need it for switching tabs. That old swipe to switch tab was amazing.

**Comment by scoute-dich** [comment]
Will be back optional in the settings with next release. I also found a way to stop the stottering when scrolling slowly (that was the main reason I removed or). ;-)
