### ISSUE TITLE
Redirect error from YouTube

### ISSUE THREAD

**Issue by Wjxfi** [scoute-dich/browser#991]
YouTube redirect only works with https://yewtu.be/. With the rest of the sites an error occurs, it does not matter if you open in a browser or through share. Most likely it is because only https://yewtu.be/ finds from searx among other invidious. It's probably a bug, but https://yewtu.be/ works, and I think you need to set it as the default redirector for youtube or fix this bug

MIUI 13.0.5

**Comment by scoute-dich** [comment]
I set https://yewtu.be/ now as default value for redirecting youtube. Meanwhile, you can set it for your own in FOSS Browser privacy settings.
