### ISSUE TITLE
No ability to customize a user profile

### ISSUE THREAD

**Issue by Wjxfi** [scoute-dich/browser#993]
What? I noticed that in "open a new tab with profile" there is a function to enable custom mode, but there is no way to configure it

**Comment by scoute-dich** [comment]
Custom mode means without the three predefined profiles. If you activate “Custom profile” (it can also be activated on app start), you can edit it directly in the Quicksettings (long press the left fab-button). These settings are automatically saved as your custom profile, whenever you change it.
